databricks/cli

- libs/flags/json_flag.go
- libs/flags/json_flag_test.go
Fixed unmarshalling json input into `interface{}` type
Commands like `api post` support free form request input, so it should be unmarshaled correctly
Added regression test + E2E test pass
> Fixed unmarshalling json input into `interface{}` type

- internal/fs_mkdir_test.go
- internal/helpers.go
This test passes on normal `azure-prod` but started to fail on `azure-prod-is`, which is the isolated version of azure-prod. This PR patches the test to include the error returned from the cloud setup in `azure-prod-is`.
The test passes now on `azure-prod-is`.
> Fix `TestAccFsMkdirWhenFileExistsAtPath` in isolated Azure environments

- bundle/tests/issue_1828/databricks.yml
- bundle/tests/issue_1828_test.go
- libs/dyn/convert/normalize.go
- libs/dyn/convert/normalize_test.go
The issue reported in #1828 illustrates how using a YAML timestamp-like value (a date in this case) causes an issue during conversion to and from the typed configuration tree.
We use the `AsAny()` function on the `dyn.Value` when normalizing for the `any` type. We only use the `any` type for variable values, because they can assume every type. The `AsAny()` function returns a `time.Time` for the time value during conversion **to** the typed configuration tree. Upon conversion **from** the typed configuration tree back into the dynamic configuration tree, we cannot distinguish a `time.Time` struct from any other struct.
To address this, we use the underlying string value of the time value when we normalize for the `any` type.
Fixes #1828.
Existing unit tests pass
> Handle normalization of `dyn.KindTime` into an any type

- bundle/permissions/validate.go
- bundle/permissions/validate_test.go
- bundle/permissions/workspace_root.go
- bundle/permissions/workspace_root_test.go
- bundle/phases/initialize.go
Added a warning when incorrect permissions used for `/Workspace/Shared` bundle root
> Added a warning when incorrect permissions used for `/Workspace/Shared` bundle root

- libs/git/repository.go
This file is at `info/exclude`, and not `info/excludes`.
Also see https://git-scm.com/docs/gitignore.
Manually confirmed that these ignore patterns are now picked up. I created a repository with a pattern in this file and ran `sync` to confirm it ignores files matching the pattern.
> Fix path to repository-wide exclude file

- bundle/config/mutator/translate_paths_test.go
- bundle/libraries/local_path.go
Added support for specifying pip options such as `--extra-index-url` and etc. in environments dependencies
```
environments:
- environment_key: Default
spec:
client: "1"
dependencies:
- --extra-index-url https://foo@bar.com/packages/smth somepackage
- json==1.0.0
```
> Added support for pip options in environment dependencies

- internal/bugbash/README.md
- internal/bugbash/exec.sh
Convenience script to exec into a shell where a CLI build for a specific branch is made available.
Manually from `/tmp` with `bash <([path]) demo-dashboards`.
> Add script to make testing of code on branches easier

- libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}.pipeline.yml.tmpl
Change the default-python template to not set the `catalog` field for the pipeline for workspaces that set `hive_metastore` as the default catalog. The Pipelines service currently returns an error when that value is used for the `catalog` field.
This is the most simple fix for this issue, which was reported by a customer. As a followup, we should look at whether we want to prompt for a catalog instead, possibly just for this specific scenario.
> Fix pipeline in default-python template not working for certain workspaces

- CHANGELOG.md
CLI:
* Added JSON input validation for CLI commands ([#1771](https://github.com/databricks/cli/pull/1771)).
* Support Git worktrees for `sync` ([#1831](https://github.com/databricks/cli/pull/1831)).
Bundles:
* Add `bundle summary` to display URLs for deployed resources ([#1731](https://github.com/databricks/cli/pull/1731)).
* Added a warning when incorrect permissions used for `/Workspace/Shared` bundle root ([#1821](https://github.com/databricks/cli/pull/1821)).
* Show actionable errors for collaborative deployment scenarios ([#1386](https://github.com/databricks/cli/pull/1386)).
* Fix path to repository-wide exclude file ([#1837](https://github.com/databricks/cli/pull/1837)).
* Fixed typo in converting cluster permissions ([#1826](https://github.com/databricks/cli/pull/1826)).
* Ignore …
> [Release] Release v0.231.0

- libs/process/opts.go
Test failures indicate that both stdout and stderr are consumed, yet the content of stdout doesn't end up in the intended output. This can happen if the goroutines responsible for writing to the combined output buffer attempt to write to the same underlying buffer concurrently.
Example failure:
```
=== RUN   TestBackgroundCombinedOutput
background_test.go:65: 
Error Trace:	D:/a/cli/cli/libs/process/background_test.go:65
Error:      	elements differ
extra elements in list A:
([]interface {}) (len=1) {
(string) (len=1) "2"
}
listA:
([]string) (len=2) {
(string) (len=1) "1",
(string) (len=1) "2"
}
listB:
([]string) (len=1) {
(string) (len=1) "1"
}
Test:       	TestBackgroundCombinedOutput
```
With the test body:
https://github.com/databricks/cli/blob/ca45e53f42c5c4b26f2833554ab7118802c017cb/l …
> Attempt to reduce test flakiness on Windows

- bundle/config/validate/folder_permissions.go
- bundle/libraries/path.go
- bundle/paths/paths.go
- bundle/permissions/workspace_root.go
- bundle/permissions/workspace_root_test.go
Changed to use SetPermissions() to configure the permissions which remove other permissions on deployment folders.
> Use SetPermissions instead of UpdatePermissions when setting folder permissions based on top-level ones

- CHANGELOG.md
**New features for Databricks Asset Bundles:**
This release adds support for managing AI/BI dashboards as part of your bundle configuration. The `bundle generate` command is updated to support producing dashboard bundle configuration as well as a serialized JSON representation of the dashboard.
You can find an example configuration and walkthrough at https://github.com/databricks/bundle-examples/tree/main/knowledge_base/dashboard_nyc_taxi
CLI:
* Add privacy notice to README ([#1841](https://github.com/databricks/cli/pull/1841)).
Bundles:
* Add support for AI/BI dashboards ([#1743](https://github.com/databricks/cli/pull/1743)).
* Added validator for folder permissions ([#1824](https://github.com/databricks/cli/pull/1824)).
* Add bundle generate variant for dashboards …
> [Release] Release v0.232.0

- bundle/config/mutator/prepend_workspace_prefix.go
- bundle/config/mutator/prepend_workspace_prefix_test.go
- bundle/config/mutator/process_target_mode_test.go
- bundle/config/validate/folder_permissions.go
- bundle/paths/paths.go
- bundle/permissions/workspace_root.go
`/Workspace` prefix needs to be added to `resource_path` as well.
Fixes the issue mentioned here: https://github.com/databricks/cli/pull/1822#issuecomment-2447697498
Fixes #1867 
> Fixed adding /Workspace prefix for resource paths

- CHANGELOG.md
This patch release fixes the following error observed when deploying to /Shared root folder
"Error: Path (/Shared/.bundle/.../resources) doesn't exist"
Bundles:
* Fixed adding /Workspace prefix for resource paths ([#1866](https://github.com/databricks/cli/pull/1866)).
> [Release] Release v0.232.1

- .github/workflows/release-snapshot.yml
- .goreleaser.yaml
Deprecation of `name_template`:  https://goreleaser.com/deprecations#snapshotnametemplate
Observed in the "Run GoReleaser" step of https://github.com/databricks/cli/actions/runs/11599180656/job/32296748853.
* Run `goreleaser check`
* The snapshot build on this PR works
> Address goreleaser deprecation warning

- .github/workflows/release.yml
This fixes warnings on the jobs that create PRs after a release:
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/github-script@v6. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
Observed this here: https://github.com/databricks/cli/actions/runs/11599180656
The [release notes](https://github.com/actions/github-script/releases/tag/v7.0.0) indicate no major changes besides the upgrade to Node 20.
> Update actions/github-script to v7

- .github/workflows/push.yml
- .github/workflows/release-snapshot.yml
- .github/workflows/release.yml
- go.mod
This was released 2+ months ago so it has baked enough.
Blog post: https://go.dev/blog/go1.23.
None other than unit and integration tests.
> Use Go 1.23

- .github/workflows/external-message.yml
- .github/workflows/integration-tests.yml
Old script could not be run from master due to security restrictions and there is no reliable way to detect if a user as secrets.
Opened a PR in SDK Java from fork
https://github.com/databricks/databricks-sdk-java/pull/375
> [Internal] Always write message for manual integration test trigger

- internal/bundle/bundles/python_wheel_task_with_cluster/databricks_template_schema.json
- internal/bundle/bundles/python_wheel_task_with_cluster/template/databricks.yml.tmpl
- internal/bundle/bundles/python_wheel_task_with_cluster/template/setup.py.tmpl
- internal/bundle/bundles/python_wheel_task_with_cluster/template/{{.project_name}}/__init__.py
- internal/bundle/bundles/python_wheel_task_with_cluster/template/{{.project_name}}/__main__.py
- internal/bundle/python_wheel_test.go
Added E2E test to run python wheels on interactive cluster created in bundle.
We had a gap in testing wheel on all purpose clusters, so this PR addresses the gap
> Added E2E test to run Python wheels on interactive cluster created in bundle

- cmd/bundle/run.go
The commit where resource lookup was factored out into a separate package (#1858) didn't take into account the use of `args` further down in the code.
This change fixes that oversight by returning the tail arguments when determining which resource to run. The later call no longer has to index the `args` slice.
Manually confirmed that the command works when being prompted for the resource to run.
> Fix bundle run when run interactively

- bundle/config/mutator/translate_paths.go
- bundle/config/mutator/translate_paths_dashboards_test.go
The file presence check for dashboard files was missing a `filepath.ToSlash`.
This means it didn't work on Windows unless the dashboard was located at a path without slashes (i.e. the bundle root).
Closes #1875.
* Added a unit test to cover this case (failed before the fix).
* Manually ran a dashboard deployment on Windows.
> Fix relative path resolution for dashboards on Windows

- libs/auth/oauth.go
- libs/auth/oauth_test.go
The host URL for databricks workspaces includes the workspaceId by default as a positional arg. Eg: https://e2-dogfood.staging.cloud.databricks.com/?o=1234
Thus a user can't simply copy paste the URL today to the auth login command. They'll see a runtime error:
```
➜  cli git:(main) ✗ databricks auth login --host https://e2-dogfood.staging.cloud.databricks.com/\?o\=xxx --profile new-dg
Error: oidc: fetch .well-known: failed to unmarshal response body: invalid character '<' looking for beginning of value. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:
GET /login.html
...
```
Unit tests and manually. …
> Clean host URL in the `auth login` command

- CHANGELOG.md
CLI:
* Clean host URL in the `auth login` command ([#1879](https://github.com/databricks/cli/pull/1879)).
Bundles:
* Fix bundle run when run interactively ([#1880](https://github.com/databricks/cli/pull/1880)).
* Fix relative path resolution for dashboards on Windows ([#1881](https://github.com/databricks/cli/pull/1881)).
Internal:
* Address goreleaser deprecation warning ([#1872](https://github.com/databricks/cli/pull/1872)).
* Update actions/github-script to v7 ([#1873](https://github.com/databricks/cli/pull/1873)).
* Use Go 1.23 ([#1871](https://github.com/databricks/cli/pull/1871)).
* [Internal] Always write message for manual integration test trigger ([#1874](https://github.com/databricks/cli/pull/1874)).
* Add `cmd-exec-id` to user agent …
> [Release] Release v0.233.0

- cmd/bundle/destroy.go
There's no value in building artifacts on destroy because they are just removed from workspace as part of destroy.
> Do not execute build on bundle destroy

- CHANGELOG.md
Bundles:
* Do not execute build on bundle destroy ([#1882](https://github.com/databricks/cli/pull/1882)).
* Add support for non-Python ipynb notebooks to DABs ([#1827](https://github.com/databricks/cli/pull/1827)).
API Changes:
* Added `databricks credentials` command group.
* Changed `databricks lakeview create` command with new required argument order.
OpenAPI commit d25296d2f4aa7bd6195c816fdf82e0f960f775da (2024-11-07)
* Upgrade TF provider to 1.58.0 ([#1900](https://github.com/databricks/cli/pull/1900)).
* Bump golang.org/x/sync from 0.8.0 to 0.9.0 ([#1892](https://github.com/databricks/cli/pull/1892)).
* Bump golang.org/x/text from 0.19.0 to 0.20.0 ([#1893](https://github.com/databricks/cli/pull/1893)).
* Bump golang.org/x/mod from 0.21.0 to 0.22.0 …
> [Release] Release v0.234.0

- bundle/config/mutator/configure_wsfs.go
- bundle/config/mutator/configure_wsfs_test.go
- cmd/root/root.go
- libs/dbr/context.go
- libs/dbr/context_test.go
- libs/dbr/detect.go
- libs/dbr/detect_test.go
- libs/fakefs/fakefs.go
Whether or not the CLI is running on DBR can be detected once and stored in the command's context.
By storing it in the context, it can easily be mocked for testing.
This builds on the simpler approach and conversation in #1744. It unblocks testing of the DBR-specific paths while not compromising on the checks we can perform to test if the CLI is running on DBR.
* Unit tests for the new `dbr` package
* New unit test for the `ConfigureWSFS` mutator
> Extract functionality to detect if the CLI is running on DBR

- bundle/config/mutator/prepend_workspace_prefix.go
- bundle/config/mutator/prepend_workspace_prefix_test.go
> Do not prepend paths starting with ~ or variable reference

- cmd/bundle/init.go
- internal/bundle/helpers.go
- libs/jsonschema/schema.go
- libs/jsonschema/schema_test.go
- libs/template/builtin.go
- libs/template/builtin_test.go
- libs/template/config.go
- libs/template/config_test.go
- libs/template/file.go
- libs/template/file_test.go
- libs/template/helpers_test.go
- libs/template/materialize.go
- libs/template/materialize_test.go
- libs/template/renderer.go
- libs/template/renderer_test.go
While working on the v2 of #1744, I found that:
* Template initialization first copies built-in templates to a temporary directory before initializing them
* Reading a template's contents goes through a `filer.Filer` but is hardcoded to a local one
This change updates the interface for reading templates to be `fs.FS`. This is compatible with the `embed.FS` type for the built-in templates, so they no longer have to be copied to a temporary directory before being used.
The alternative is to use a `filer.Filer` throughout, but this would have required even more plumbing, and we don't need to _read_ templates, including notebooks, from the workspace filesystem (yet?).
As part of making `template.Materialize` take an `fs.FS` argument, the logic to match a given argument to a particular …
> Use `fs.FS` interface to read template

- libs/filer/filer.go
- libs/filer/filer_test.go
- libs/filer/local_client.go
- libs/template/config_test.go
- libs/template/file.go
- libs/template/file_test.go
- libs/template/helpers_test.go
- libs/template/materialize.go
- libs/template/renderer.go
- libs/template/renderer_test.go
Prior to this change, the output directory was part of the `renderer` type and passed down to every `file` it produced. Every file knew its absolute destination path. This is incompatible with the use of a filer, where all operations are automatically anchored to some base path.
To make this compatible, this change updates:
* the `file` type to only know its own path relative to the instantiation root,
* the `renderer` type to no longer require or pass along the output directory,
* the `persistToDisk` function to take a context and filer argument,
* the `filer.WriteMode` to represent permission bits
* Existing tests pass.
* Manually confirmed template initialization works as expected.
> Use `filer.Filer` to write template instantiation

- cmd/bundle/init.go
- internal/bundle/helpers.go
- libs/template/materialize.go
- libs/template/materialize_test.go
When running the CLI on Databricks Runtime (DBR), use the extension-aware filer to write an instantiated template if the instance path is located in the workspace filesystem. 
Notebooks cannot be written through the workspace filesystem's FUSE mount. As a result, this is the only method for initializing templates that contain notebooks when running the CLI on DBR and writing to the workspace filesystem.
Depends on #1910 and #1911.
Supersedes #1744.
* Manually confirmed I can initialize a template with notebooks when running the CLI from the web terminal.
> Fix template initialization when running on Databricks

- cmd/bundle/generate/generate_test.go
- cmd/bundle/generate/job.go
- cmd/bundle/generate/pipeline.go
- internal/bundle/bind_resource_test.go
Update filenames used by bundle generate to use '.resource-type.yml'
Similar to [Add sub-extension to resource files in built-in templates by shreyas-goenka · Pull Request #1777 · databricks/cli](https://github.com/databricks/cli/pull/1777)
> Update filenames used by bundle generate to use `.<resource-type>.yml`

- CHANGELOG.md
**Note:** the `bundle generate` command now uses the `.<resource-type>.yml`
sub-extension for the configuration files it writes. Existing configuration
files that do not use this sub-extension are renamed to include it.
Bundles:
* Make `TableName` field part of quality monitor schema ([#1903](https://github.com/databricks/cli/pull/1903)).
* Do not prepend paths starting with ~ or variable reference ([#1905](https://github.com/databricks/cli/pull/1905)).
* Fix workspace extensions filer accidentally reading notebooks ([#1891](https://github.com/databricks/cli/pull/1891)).
* Fix template initialization when running on Databricks ([#1912](https://github.com/databricks/cli/pull/1912)).
* Source-linked deployments for bundles in the workspace …
> [Release] Release v0.235.0

- bundle/config/mutator/translate_paths.go
- bundle/config/mutator/translate_paths_test.go
The full workspace path for a notebook does not contain the notebook's extension. If a user converts that file path to a relative path (like `/Workspace/bundle_root/bar/nb` -> `./bar/nb`), they can be confused as to why the new file path does not work.
The changes in this PR nudge them to add the appropriate file extension (e.g., `./bar/nb.py` or `./bar/nb.ipynb`). We
One common way users can end up in this scenario is by using the view job as YAML functionality in the Databricks UI.
Unit test and manually.
```
(.venv) ➜  bundle-playground git:(master) ✗ cli bundle validate 
Error: notebook ./foo not found. Local notebook references are expected
to contain one of the following file extensions: [.py, .r, .scala, .sql, .ipynb]
```
When we detect that a candidate file exists then the error …
> Extend "notebook not found" error to warn about missing extension

- internal/init_test.go
The ML production team modified mlops-stack to use `mode: development` for their development target here: https://github.com/databricks/mlops-stacks/pull/174
This PR makes the integration test assertion agnostic of the prefix to make it pass again. 
The test passes now
> Fix `TestAccBundleInitOnMlopsStacks`

- bundle/config/variable/lookup.go
- bundle/config/variable/resolve_notification_destination.go
- bundle/config/variable/resolve_notification_destination_test.go
Add support for notification destinations in variable lookups.
More information: https://docs.databricks.com/en/admin/workspace-settings/notification-destinations.html
Depends on #1921.
* New unit test
* Manually confirmed that the lookup works
> Support lookup by name of notification destinations

- bundle/config/validate/files_to_sync.go
- bundle/config/validate/files_to_sync_test.go
Users can configure the bundle to not synchronize any files with:
```yaml
sync:
paths: []
```
If it is explicitly configured as an empty list, the validate command must not warn about not having any files to synchronize. The warning exists to alert users who are unintentionally not synchronizing any files (they might have a `.gitignore` pattern that matches everything).
Closes #1663.
* New unit test.
> Skip sync warning if no sync paths are defined

- bundle/config/mutator/apply_presets.go
- bundle/config/mutator/apply_presets_test.go
Added path and locations to the warning which displayed when source-linked mode is used outside of the workspace
> Extended message for warning when source-linked mode is used outside of the workspace

- bundle/config/validate/single_node_cluster.go
- bundle/config/validate/single_node_cluster_test.go
- bundle/config/validate/validate.go
This PR adds a warning validating that the configuration for a single node cluster is valid for interactive, job, job-task, and pipeline clusters. 
Note: We skip the validation if a cluster policy is configured because the policy is likely to configure `spark_conf` / `custom_tags` itself. 
Note: Terrform originally only had validation for interactive, job, and job-task clusters. This PR adding the validation for pipeline clusters as well is new.
This PR follows the same logic as we used to have in Terraform. The validation was removed from Terraform because we had no way to demote the error to a warning:
https://github.com/databricks/terraform-provider-databricks/pull/4222
Single-node clusters require `spark_conf` and `custom_tags` to be correctly set in the cluster definition for them to …
> Add validation for single node clusters

- bundle/tests/python_wheel/python_wheel/bundle.yml
- bundle/tests/python_wheel/python_wheel_dbfs_lib/bundle.yml
- bundle/tests/python_wheel/python_wheel_multiple/bundle.yml
- bundle/tests/python_wheel/python_wheel_no_artifact/bundle.yml
- bundle/tests/python_wheel/python_wheel_no_artifact_no_setup/bundle.yml
- bundle/tests/python_wheel/python_wheel_no_artifact_notebook/bundle.yml
- bundle/tests/python_wheel/python_wheel_no_build/bundle.yml
- libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}.pipeline.yml.tmpl
The built-in template contains a reference to `${bundle.environment}`.
This property has been deprecated in favor of `${bundle.target}` a long time ago (#670), so we should no longer emit it. The environment field will continue to be usable until we cut a new major version in some far away future.
* Unit tests
* The test `TestInterpolationWithTarget` still covers correct interpolation of `${bundle.environment}`
> Update target references to use `${bundle.target}`

- bundle/config/resources.go
- bundle/config/resources/clusters.go
- bundle/config/resources/dashboard.go
- bundle/config/resources/job.go
- bundle/config/resources/mlflow_experiment.go
- bundle/config/resources/mlflow_model.go
- bundle/config/resources/model_serving_endpoint.go
- bundle/config/resources/pipeline.go
- bundle/config/resources/quality_monitor.go
- bundle/config/resources/registered_model.go
- bundle/config/resources/schema.go
- bundle/render/render_text_output_test.go
- bundle/resources/completion_test.go
- bundle/resources/lookup_test.go
This PR introduces use of new `isNil` method. It allows to ensure we filter out all improperly defined resources in `bundle summary` command. This includes deleted resources or resources with incorrect configuration such as only defining key of the resource and nothing else.
Fixes #1919, #1913
Added regression unit test case
> Fix segfault in bundle summary command

- bundle/config/bundle.go
- libs/template/helpers.go
- libs/template/helpers_test.go
- libs/template/testdata/bundle-uuid/template/bar.txt.tmpl
- libs/template/testdata/bundle-uuid/template/foo.txt.tmpl
This PR adds the `bundle_uuid` helper function that'll return a stable identifier for the bundle for the duration of the `bundle init` command.
This is also the UUID that'll be set in the telemetry event sent during `databricks bundle init` and would be used to correlate revenue from bundle init with resource deployments. 
Template authors should add the uuid field to their `databricks.yml` file they generate:
```
bundle:
uuid: {{ bundle_uuid }}
```
Unit test
> Add the `bundle_uuid` helper function for templates

- bundle/config/mutator/configure_volume_defaults.go
- bundle/config/mutator/configure_volume_defaults_test.go
- bundle/internal/schema/main.go
- bundle/internal/schema/testdata/fail/incorrect_volume_type.yml
- bundle/internal/schema/testdata/pass/volume.yml
- bundle/phases/initialize.go
- bundle/schema/jsonschema.json
The Unity Catalog volumes API requires a `volume_type` argument when creating volumes. In the context of DABs, it's unnecessary to require users to specify the volume type every time. We can default to "MANAGED" instead.
This PR is similar to https://github.com/databricks/cli/pull/1743 which does the same for dashboards.
Unit test
> Add default value for `volume_type` for DABs

- bundle/bundle.go
- bundle/bundle_read_only.go
- bundle/config/mutator/load_git_details.go
- bundle/config/validate/files_to_sync_test.go
- bundle/deploy/files/sync.go
- cmd/sync/sync.go
- internal/git_fetch_test.go
- libs/diag/diagnostic.go
- libs/git/fileset.go
- libs/git/fileset_test.go
- libs/git/info.go
- libs/git/repository.go
- libs/git/view.go
- libs/git/view_test.go
- libs/sync/snapshot_test.go
- libs/sync/sync.go
- libs/sync/sync_test.go
Since there is no .git directory in Workspace file system, we need to make an API call to api/2.0/workspace/get-status?return_git_info=true to fetch git the root of the repo, current branch, commit and origin.
Added new function FetchRepositoryInfo that either looks up and parses .git or calls remote API depending on env.
Refactor Repository/View/FileSet to accept repository root rather than calculate it. This helps because:
- Repository is currently created in multiple places and finding the repository root is becoming relatively expensive (API call needed).
- Repository/FileSet/View do not have access to current Bundle which is where WorkplaceClient is stored.
- Tested manually by running "bundle validate --json" inside web terminal within Databricks env.
- Added integration tests for …
> Properly read Git metadata when running inside workspace

- CHANGELOG.md
**New features for Databricks Asset Bundles:**
This release adds support for managing Unity Catalog volumes as part of your bundle configuration.
Bundles:
* Add DABs support for Unity Catalog volumes ([#1762](https://github.com/databricks/cli/pull/1762)).
* Support lookup by name of notification destinations ([#1922](https://github.com/databricks/cli/pull/1922)).
* Extend "notebook not found" error to warn about missing extension ([#1920](https://github.com/databricks/cli/pull/1920)).
* Skip sync warning if no sync paths are defined ([#1926](https://github.com/databricks/cli/pull/1926)).
* Add validation for single node clusters ([#1909](https://github.com/databricks/cli/pull/1909)).
* Fix segfault in bundle summary command ([#1937](https://github.com/databricks/cli/pull/1937)).
* Add the …
> [Release] Release v0.236.0

- .golangci.yaml
- bundle/config/root_test.go
- bundle/internal/tf/codegen/schema/generate.go
- bundle/internal/tf/schema/root.go
- bundle/render/render_text_output.go
- bundle/run/output/task.go
- bundle/tests/complex_variables_test.go
- internal/helpers.go
- internal/mocks/libs/filer/mock_filer.go
- libs/cmdgroup/command.go
- libs/cmdio/render.go
- libs/dyn/dynassert/assert.go
- libs/dyn/yamlloader/loader.go
- libs/errs/aggregate.go
- libs/jsonschema/from_type_test.go
The `any` alias for `interface{}` has been around since Go 1.18.
Now that we're using golangci-lint (#1953), we can lint on it.
Existing commits can be updated with:
```
gofmt -w -r 'interface{} -> any' .
```
n/a
> Rewrite 'interface{} -> any'

- internal/filer_test.go
I found a race where this error is nil and the subsequent assert panics on the error being nil. This change makes the test robust against this to fail immediately if the error is different from the one we expect.
n/a
> Fail filer integration test if error is nil

- .golangci.yaml
- libs/auth/oauth_test.go
Enable linter '[bodyclose](https://github.com/timakin/bodyclose)' and fix 2 cases in tests.
> Enable linter bodyclose

- internal/init_test.go
- internal/testutil/env.go
This test changes the cwd using the `testutil.Chdir` function. This causes flakiness with other integration tests, like `TestAccWorkspaceFilesExtensionsNotebooksAreNotDeletedAsFiles`, which rely on the cwd being configured correctly to read test fixtures.
The `t.Setenv` call in `testutil.Chdir` ensures that it is not run from a test whose upstream is executing in parallel.
> Do not run mlops-stacks integration test in parallel

- internal/clusters_test.go
I saw this test fail on rerun because the global wasn't set.
Fix by removing the global and using a different approach to acquire a valid cluster ID.
Integration tests.
> Remove global variable from clusters integration test

- bundle/config/mutator/override_compute.go
- bundle/config/mutator/override_compute_test.go
Allow overriding compute for non-development targets. We previously had a restriction in place where `--cluster-id` was only allowed for targets that use `mode: development`. The intention was to prevent mistakes, but this was overly restrictive.
Updated unit tests.
> Allow overriding compute for non-development mode targets

- bundle/config/mutator/expand_workspace_root.go
Extra check to avoid panic if /api/2.0/preview/scim/v2/Me returns `{}`
> Avoid panic if Config.Workspace.CurrentUser.User is not set

- Makefile
Add 'make lintcheck' to lint without fixing. Fixing is what you usually want.
No changes to github workflow since that does not call our Makefile.
> Make 'make lint' apply --fix

- bundle/config/mutator/override_compute.go
- bundle/config/mutator/override_compute_test.go
We should show a warning when using a cluster override with 'mode: production'. Right now, we inadvertently show an error for this state. This is a followup based on https://github.com/databricks/cli/pull/1899#discussion_r1877765148.
> Show an error when using a cluster override with 'mode: production'

- .git-blame-ignore-revs
This file is automatically recognized by GitHub. For git to recognized it, run:
`git config blame.ignoreRevsFile .git-blame-ignore-revs`
Run 'git blame' with and without this option.
Compare view on Github
https://github.com/databricks/cli/blame/2e018cf/libs/git/reference_test.go
https://github.com/databricks/cli/blame/denis.bilenko/ignore-linter-commits/libs/git/reference_test.go
> Add .git-blame-ignore-revs with linter-related mass change commits

- .vscode/settings.json
Verified that with this setting, VSCode reformats code on Save according to gofumpt rules.
> Enable gofumpt in vscode

- internal/acc/debug.go
- internal/acc/workspace.go
- internal/bundle/clusters_test.go
- internal/bundle/deploy_to_shared_test.go
- internal/bundle/helpers.go
- internal/bundle/python_wheel_test.go
- internal/filer_test.go
- internal/fs_cp_test.go
- internal/fs_ls_test.go
- internal/helpers.go
- internal/secrets_test.go
- internal/testutil/cloud.go
- internal/testutil/copy.go
- internal/testutil/env.go
- internal/testutil/file.go
- internal/testutil/helpers.go
- internal/testutil/interface.go
- internal/testutil/jdk.go
- internal/testutil/requirement.go
- internal/testutil/testutil_test.go
Using an interface instead of a concrete type means we can pass `*testing.T` directly or any wrapper type that implements a superset of this interface. It prepares for more broad use of `acc.WorkspaceT`, which enhances the testing object with helper functions for using a Databricks workspace.
This eliminates the need to dereference a `*testing.T` field on a wrapper type.
n/a
> Define and use `testutil.TestingT` interface

- internal/acc/fixtures.go
- internal/acc/workspace.go
- internal/bundle/artifacts_test.go
- internal/bundle/basic_test.go
- internal/bundle/bind_resource_test.go
- internal/bundle/clusters_test.go
- internal/bundle/deploy_test.go
- internal/bundle/deploy_then_remove_resources_test.go
- internal/bundle/deploy_to_shared_test.go
- internal/bundle/deployment_state_test.go
- internal/bundle/destroy_test.go
- internal/bundle/generate_job_test.go
- internal/bundle/generate_pipeline_test.go
- internal/bundle/job_metadata_test.go
- internal/bundle/local_state_staleness_test.go
- internal/bundle/python_wheel_test.go
- internal/bundle/spark_jar_test.go
- internal/dashboard_assumptions_test.go
- internal/fs_cat_test.go
- internal/helpers.go
- internal/locker_test.go
- internal/python/python_tasks_test.go
- internal/sync_test.go
- internal/tags_test.go
- internal/testutil/cloud.go
- internal/workspace_test.go
This change moves fixture helpers to `internal/acc/fixtures.go`. These helpers create an ephemeral path or resource for the duration of a test. Call sites are updated to use `acc.WorkspaceTest()` to construct a workspace-focused test wrapper as needed.
This change also moves the `GetNodeTypeID()` function to `testutil`.
n/a
> Move test helpers from internal to `acc` and `testutil`

- integration/bundle/bind_resource_test.go
- integration/bundle/deployment_state_test.go
- integration/bundle/init_test.go
- integration/bundle/spark_jar_test.go
- integration/bundle/validate_test.go
- integration/cmd/alerts/alerts_test.go
- integration/cmd/api/api_test.go
- integration/cmd/auth/describe_test.go
- integration/cmd/clusters/clusters_test.go
- integration/cmd/fs/cat_test.go
- integration/cmd/fs/cp_test.go
- integration/cmd/fs/helpers_test.go
- integration/cmd/fs/ls_test.go
- integration/cmd/jobs/jobs_test.go
- integration/cmd/repos/repos_test.go
- integration/cmd/sync/sync_test.go
- integration/cmd/workspace/workspace_test.go
- integration/libs/filer/helpers_test.go
- integration/libs/git/git_clone_test.go
- integration/libs/locker/locker_test.go
- integration/python/python_tasks_test.go
These calls are no longer necessary now that integration tests use a main function that performs this check. This change updates integration tests that call this function. Of those, the call sites that initialize a workspace client are updated to use `acc.WorkspaceTest(t)` to get one.
n/a
> Remove calls to `testutil.GetEnvOrSkipTest(t, "CLOUD_ENV")`

- .vscode/settings.json
- libs/template/templates/dbt-sql/template/{{.project_name}}/.vscode/settings.json.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/.vscode/settings.json
- libs/template/templates/default-sql/template/{{.project_name}}/.vscode/settings.json.tmpl
VSCode extension no longer uses `databricks.python.envFile ` setting. And older extension versions will use the same default value anyway.
None
> Remove unused vscode settings in the templates

- integration/bundle/artifacts_test.go
- integration/bundle/basic_test.go
- integration/bundle/bind_resource_test.go
- integration/bundle/clusters_test.go
- integration/bundle/dashboards_test.go
- integration/bundle/deploy_test.go
- integration/bundle/deploy_then_remove_resources_test.go
- integration/bundle/deploy_to_shared_test.go
- integration/bundle/deployment_state_test.go
- integration/bundle/destroy_test.go
- integration/bundle/empty_bundle_test.go
- integration/bundle/environments_test.go
- integration/bundle/generate_job_test.go
- integration/bundle/generate_pipeline_test.go
- integration/bundle/helpers_test.go
- integration/bundle/job_metadata_test.go
- integration/bundle/local_state_staleness_test.go
- integration/bundle/python_wheel_test.go
- integration/bundle/spark_jar_test.go
These test helpers were updated to handle the error internally and not return it. Since they have testing.T object, they can do so directly. On the caller side, this functions were always followed by require.NoError(t, err), that was cleaned up.
This approach helps reduce the setup/teardown boilerplate in the test cases.
> Refactor initTestTemplate/deployBundle/destroyBundle to not return errors

- internal/testutil/helpers.go
It was using first 12 chars, that does not seem intended.
> Fix testutil.RandomName to use the full character set

- internal/bugbash/exec.sh
Fixed downloading arm64 binaries
Go 1.23 changed the way built binaries are prefixed on amd64, more details here: https://tip.golang.org/doc/go1.23#arm64
> Fixed downloading arm64 binaries

- .github/workflows/push.yml
- Makefile
Remove unnecessary make command and github workflow - it's a subset of "lint" now. However, keep "mod tidy" separately, don't think the linter does that.
> Remove 'make fmt' and 'fmt' workflow

- Makefile
- integration/bundle/clusters_test.go
- integration/bundle/python_wheel_test.go
- integration/bundle/spark_jar_test.go
A small subset of tests trigger cluster creation to run jobs. These tests comprise a substantial amount of the total integration test runtime. We can skip them on PRs and only run them on the main branch.
Confirmed the short runtime is ~20 mins.
> Skip job runs during integration testing for PRs

- integration/bundle/clusters_test.go
- integration/bundle/python_wheel_test.go
- internal/testutil/cloud.go
There was only one helper for AWS and not the other clouds. Found this when looking through double calls to `acc.WorkspaceTest()` (see `TestPythonWheelTaskDeployAndRunOnInteractiveCluster`).
n/a
> Remove superfluous helper

- .codegen/service.go.tmpl
If there's required query params, it is a top-level field of request object and not a field of nested request body.
This is needed for upcoming changes from OpenAPI spec changes where such query parameters is introduced.
No changes after regenerating CLI with current spec and the fix (appears we haven't had such params before)
> Correctly handle required query params in CLI generation

- bundle/config/generate/app.go
- bundle/config/mutator/apply_presets_test.go
- bundle/config/resources.go
- cmd/bundle/generate.go
- cmd/bundle/generate/app.go
- cmd/bundle/generate/utils.go
Added support for bundle generate and bind for Apps
> Added support for bundle generate and bind for Apps

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_cluster.go
- bundle/internal/tf/schema/resource_cluster.go
- bundle/internal/tf/schema/resource_job.go
- bundle/internal/tf/schema/resource_pipeline.go
- bundle/internal/tf/schema/root.go
* Added support for `IsSingleNode`, `Kind` and `UseMlRuntime` for clusters
* Added support for `CleanRoomsNotebookTask`
* `DaysOfWeek` for pipeline restart window is now a list
> Upgrade TF provider to 1.62.0

- CHANGELOG.md
Bundles:
* Allow overriding compute for non-development mode targets ([#1899](https://github.com/databricks/cli/pull/1899)).
* Show an error when using a cluster override with 'mode: production' ([#1994](https://github.com/databricks/cli/pull/1994)).
API Changes:
* Added `databricks account federation-policy` command group.
* Added `databricks account service-principal-federation-policy` command group.
* Added `databricks aibi-dashboard-embedding-access-policy delete` command.
* Added `databricks aibi-dashboard-embedding-approved-domains delete` command.
OpenAPI commit a6a317df8327c9b1e5cb59a03a42ffa2aabeef6d (2024-12-16)
* Upgrade TF provider to 1.62.0 ([#2030](https://github.com/databricks/cli/pull/2030)).
* Upgrade Go SDK to 0.54.0 …
> [Release] Release v0.237.0

- .github/workflows/integration-approve.yml
- .github/workflows/integration-main.yml
- .github/workflows/integration-pr.yml
The existing workflow already had 2 trigger conditions, so instead of adding a third (and seeing more "skipped" jobs), I split them up into dedicated workflow files, each with their own trigger condition.
The integration test status is reported back via commit status.
We can confirm that everything works as expected as this PR moves from here to the merge group to main.
> Trigger integration tests on push to main

- libs/template/builtin_test.go
Relax the checks of `lib/template/builtin_test` so they don't fail for a local development copy that has uncommitted draft templates. Right now these tests fail because I have some git-ignored uncommitted templates in my local dev copy.
> Relax checks in builtin template tests

- Makefile
- lint.sh
First stage is to run goimports and formatter, second is full suite.
This ensures that imports and formatting are fixed even in presence of other issues. Otherwise golanci-lint refuses to fix anything https://github.com/golangci/golangci-lint/issues/5257
This helpful when running aider with config like this - aider will use that to autofix what it can after every update:
```
% cat .aider.conf.yml
lint-cmd:
- "go: ./lint.sh"
```
> Add lint.sh to run golanci-lint in 2 stages

- integration/bundle/init_default_python_test.go
- internal/testcli/golden.go
- libs/testdiff/golden.go
- libs/testdiff/golden_test.go
- Detach "golden files" assertions from testcli runner. Now any output can be compared, no matter how it is obtained. 
- Move those assertion to libs/testdiff package.
This allows using "golden files" in non-integration tests.
Existing tests
> Move bulk of "golden tests" logic to libs/testdiff

- lint.sh
As suggested here: https://github.com/databricks/cli/pull/2051#discussion_r1899641273
> lint.sh: read config for formatters; include gofmt

- bundle/artifacts/expand_globs.go
- bundle/config/mutator/resolve_resource_references.go
- bundle/config/root.go
- bundle/config/validate/folder_permissions.go
Fix cases where accumulated diagnostics are lost instead of being propagated further. In some cases it's not possible, add a comment there.
Existing tests
> Fix lost diags across different mutators

- integration/internal/acc/workspace.go
- internal/testcli/golden.go
- internal/testcli/runner.go
- internal/testutil/interface.go
- libs/testdiff/golden.go
- libs/testdiff/testdiff.go
- Add t.Helper() in testcli-related helpers, this ensures that output is attributed correctly to test case and not to the helper.
- Modify testlcli.Run() to run process in foreground. This is needed for t.Helper to work.
- Extend a few assertions with message to help attribute it to proper helper where needed.
Manually reviewed test output.
Before:
```
+ go test --timeout 3h -v -run TestDefaultPython/3.9 ./integration/bundle/
=== RUN   TestDefaultPython
=== RUN   TestDefaultPython/3.9
workspace.go:26: aws
golden.go:14: run args: [bundle, init, default-python, --config-file, config.json]
runner.go:206: [databricks stderr]:
runner.go:206: [databricks stderr]: Welcome to the default Python template for Databricks Asset Bundles!
...
testdiff.go:23:
Error Trace: …
```
> Improve test output to include correct location

- .github/workflows/push.yml
Upgrade your laptops with: brew install golangci-lint
This has a lot more autofixes, which makes it easier to adopt those linters.
https://golangci-lint.run/product/changelog/#v1630
> Upgrade golangci-lint to v1.63.1

- lint.sh
Follow up to #2051 and #2056.
Running golangci-lint twice always is measurably slower (1.5s vs 2.5s), so only run it twice in case it is necessary.
> Make lint.sh to run golangci-lint only once in the best case

- .github/workflows/push.yml
- Makefile
On main branch: ‘make test’ takes about 33s
On this branch: ‘make test’ takes about 2.7s
(all measurements are for hot cache)
What’s done (from highest impact to lowest):
- Remove -coverprofile= option - this option was disabling "go test"'s built-in cache and also it took extra time to calculate the coverage (extra 21s).
- Exclude ./integration/ folder, there are no unit tests there, but having it included adds significant time. "go test"'s caching also does not work there for me, due to TestMain() presence (extra 7.2s).
- Remove dependency on "make lint" - nice to have, but slow to re-check the whole repo and should already be done by IDE (extra 2.5s).
- Remove dependency on "make vendor" — rarely needed; on CI it is already executed separately (extra 1.1s).
The coverage option is still …
> Speed up best case for "make test" 12x

- Makefile
This is useful on CI and locally for debugging and being able to copy-paste command to tweak the options.
Removed redundant and imprecise messages like "✓ Running tests ...".
> Make "make" output the commands it runs

- .golangci.yaml
By default it stops after 3 issues of a given type, which gives false impression and also unhelpful if you fixing it with aider.
1000 is almost like unlimited but not unlimited in case there is a bug in a linter.
> lint: Raise max issues output

- integration/bundle/init_test.go
- internal/testutil/helpers.go
https://github.com/databricks/mlops-stacks/pull/187 broke mlops-stacks deployments for non-UC projects. Snoozing the test until upstream is fixed.
The test is skipped on my local machine. CI run will verify it's also skipped on Github Actions runners.
> Snooze mlops-stacks integration test

- integration/bundle/init_test.go
This test was broken due to upstream change: https://github.com/databricks/mlops-stacks/pull/187
Fixed in upstream change: https://github.com/databricks/mlops-stacks/pull/188
Test passes now
> Enable TestBundleInitOnMlopsStacks

- .github/workflows/external-message.yml
- .github/workflows/integration-pr.yml
The comment block appears on all PRs, even if the integration tests are automatically triggered. This is quite noisy. This change limits those comments to PRs from forks.
Have to try by merging...
> Limit comment about integration tests to PRs from forks

- .github/workflows/push.yml
- Makefile
This gives grouping and ability to open individual test logs.
> Set gotestsum --format to github-actions when running on github

- .github/workflows/close-stale-issues.yml
- .github/workflows/external-message.yml
- .github/workflows/integration-approve.yml
- .github/workflows/integration-main.yml
- .github/workflows/integration-pr.yml
- .github/workflows/release-snapshot.yml
- .github/workflows/release.yml
Migrate workflows to Databricks-hosted GitHub Actions runners.
The GitHub-hosted runners can no longer be used because of security hardening.
> Migrate workflows that need write access to use hosted runners

- .github/workflows/external-message.yml
- .github/workflows/integration-approve.yml
- .github/workflows/integration-main.yml
- .github/workflows/integration-pr.yml
This reverts commit 31552852ff6856a70f54454322d7407f6fdcfb06.
These workflows were disabled in #2085.
They should work again now that we're using self-hosted runners (see #2077).
(inline)
> Enable integration workflows

- bundle/config/experimental.go
- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/python/python_mutator_test.go
- bundle/internal/schema/annotations.yml
- bundle/phases/initialize.go
- bundle/schema/jsonschema.json
Add `experimental/python` section replacing `experimental/pydabs`.
Add 2 new mutators into existing pipeline:
- `ApplyPythonMutator(load_resources)` - loads resources from Python code
- `ApplyPythonMutator(apply_mutators)` - transforms existing resources defined in Python/YAML
Example:
```yaml
experimental:
python:
resources:
- "resources:load_resources"
mutators:
- "mutators:add_email_notifications"
```
Unit tests and manually
> Add 'experimental/python' support

- CHANGELOG.md
Bundles:
* Fix finding Python within virtualenv on Windows ([#2034](https://github.com/databricks/cli/pull/2034)).
* Include missing field descriptions in JSON schema ([#2045](https://github.com/databricks/cli/pull/2045)).
* Add validation for volume referenced from `artifact_path` ([#2050](https://github.com/databricks/cli/pull/2050)).
* Handle `${workspace.file_path}` references in source-linked deployments ([#2046](https://github.com/databricks/cli/pull/2046)).
* Set the write bit for files written during template initialization ([#2068](https://github.com/databricks/cli/pull/2068)).
> [Release] Release v0.238.0

- .github/workflows/release.yml
I missed these in #2077 and they failed because of it on the v0.238.0 release.
> Update runner for the create-xyz-pr jobs in the release workflow

- acceptance/README.md
- libs/testdiff/golden.go
It's easier to remember and type and also validated and part of help:
```
% go test ./acceptance -updat 2>&1 | grep updat
flag provided but not defined: -updat
-update
```
> Use -update instead of TESTS_OUTPUT=OVERWRITE

- acceptance/bundle/variables/complex/databricks.yml
- acceptance/bundle/variables/complex/out.default.json
- acceptance/bundle/variables/complex/out.dev.json
- acceptance/bundle/variables/complex/output.txt
- acceptance/bundle/variables/complex/script
- Add override for "libraries".
- Remove complexvar - it serves no purpose - we already have map variable ‘cluster’.
> Add test for overriding list variable

- .github/workflows/publish-winget.yml
This action uses a token to access the release artifacts and, as such, needs to execute on the runner that's on the allowlist.
Related PRs:
* #2098
* #2077
> Update runner for the publish-winget job

- .github/workflows/publish-winget.yml
This workflow only worked if it was triggered on the tag to publish itself. This means it is not possible to release a version if the workflow configuration at that tag is broken (as is the case for v0.238.0 because of #2105).
This change adds a "tag" input that can be set when manually triggering the workflow.
* Succesful run with this change: https://github.com/databricks/cli/actions/runs/12689281843
* Pull request that the run created: https://github.com/microsoft/winget-pkgs/pull/209220
> Pass tag to release as input to publish-winget workflow

- integration/bundle/testdata/default_python/bundle_summary.txt
- libs/template/templates/dbt-sql/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/default-sql/template/{{.project_name}}/databricks.yml.tmpl
This is useful to track telemetry associated with the templates and can later be useful for functional usecases as well.  Mlops stacks does the same here: https://github.com/databricks/mlops-stacks/pull/185
> Add `uuid` to builtin templates

- acceptance/acceptance_test.go
- acceptance/bundle/override/job_tasks/out.development.stderr.txt
- acceptance/bundle/override/job_tasks/output.txt
- acceptance/bundle/override/job_tasks/script
- acceptance/bundle/override/merge-string-map/output.txt
- cmd/bundle/validate.go
Previously diagnostics were not seen in JSON output mode. This change prints them to stderr.
This also fixes acceptance tests to preprocess all output with s/execPath/$CLI/  not just output.txt.
Existing acceptance tests. In one case I've added non-json command to check that they match in output.
> Log warnings to stderr for "bundle validate -o json"

- .github/workflows/close-stale-issues.yml
Giving 7 days to react before closing is too aggressive, IMO. Changed it to 30.
Also changed 'stale' label from 30d to 60d.
Also removed dry-run setting, it does not appear to do anything.
> Increase close-after-stale from 7 to 30 days

- internal/testcli/runner.go
The main CLI entry point used to be a global variable, and the global state had to be cleaned up after every test run. This hasn't been the case for a while, and instead, the CLI is initialized in a function call. State accumulated by a single CLI "instance" can no longer leak into other instances, so we no longer have to perform cleanup.
Existing tests pass.
> Remove cleanup in testcli package

- acceptance/bundle/variables/host/databricks.yml
- acceptance/bundle/variables/host/output.txt
- acceptance/bundle/variables/host/script
Related issue: https://github.com/databricks/cli/issues/2095
> Add a test re using variable in host

- acceptance/bundle/override/job_cluster_var/databricks.yml
- acceptance/bundle/override/job_cluster_var/output.txt
- bundle/phases/initialize.go
Move mutator.Merge{JobClusters,JobParameters,JobTasks,PipelineClusters} after variable resolution. This helps with the case when key contains a variable.
@pietern mentioned here https://github.com/databricks/cli/pull/2101#pullrequestreview-2539168762 it should be safe.
Existing acceptance that was capturing the bug is updated with corrected output.
> Move merge fix-ups after variable resolution

- libs/testdiff/golden.go
They are not necessary because they are added below. Also, they will cause a crash if u.Name is nil.
> Remove redundant lines from PrepareReplacementsUser

- libs/databrickscfg/cfgpickers/clusters.go
- libs/databrickscfg/cfgpickers/clusters_test.go
As of the clusters API v2.1 the results include system clusters. On large workspaces this can lead to long load times and include many irrelevant results. The cluster picker should only show interactive clusters.
Also see #1754.
Manually confirmed the picker runs fast on a large workspace.
> Filter out system clusters in cluster picker

- integration/bundle/apps_test.go
Fixed a typo in TestDeployBundleWithApp test
```
helpers_test.go:148: stderr: Destroy complete!
--- PASS: TestDeployBundleWithApp (647.51s)
PASS
coverage: [no statements]
ok      github.com/databricks/cli/integration/bundle    647.985s        coverage: [no statements]
```
> Fixed a typo in TestDeployBundleWithApp test

- .gitignore
- Makefile
- acceptance/acceptance_test.go
Add two new make commands:
- make acc-cover: runs acceptance tests and outputs coverage-acceptance.txt
- make acc-showcover: show coverage-acceptance.txt locally in browser
Using the GOCOVERDIR functionality: https://go.dev/blog/integration-test-coverage
This works, but there are a couple of issues encountered:
- GOCOVERDIR does not play well with regular "go test -cover". Once this fixed, we can simplify the code and have 'make cover' output coverage for everything at once. We can also probably get rid of CLI_GOCOVERDIR. https://github.com/golang/go/issues/66225
- When running tests in parallel to the same directory there is rare conflict on writing covmeta file. For this reason each tests writes coverage to their own directory which is then merged together by 'make acc-cover'.
<!-- …
> Coverage for acceptance tests

- libs/testdiff/golden.go
Always include both verbatim and json version of replacement.
This helps when the string in question contains \\ or other chars that need to be quoted.
Needed for https://github.com/databricks/cli/pull/2118
> Golden files: always include JSON-ed string

- acceptance/acceptance_test.go
Use name format "TestAccept/bundle/variables/host" (previously slashes were reversed on Windows).
Manually run "go test ./acceptance -v -run TestAccept/bundle/variables/host" in Windows VM.
> Use the same test names on Win as on other OSes

- acceptance/acceptance_test.go
- acceptance/bundle/variables/git-branch/databricks.yml
- acceptance/bundle/variables/git-branch/output.txt
- acceptance/bundle/variables/git-branch/script
- acceptance/script.prepare
This test checks load git details functionality + variable interpolation there.
The variables are not working there because LoadGitDetails mutator is running before variable interpolation.
This also includes a couple fixes for acceptance tests on Windows:
- Correctly replace tmp path that is used for DATABRICKS_TF_EXEC_PATH
- Pass -buildvcs=false to go build. It's not needed on CI but it is needed on my local windows VM.
> Add test about using variable in bundle.git.branch

- libs/template/templates/default-python/template/{{.project_name}}/scratch/exploration.ipynb.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/setup.py.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/src/dlt_pipeline.ipynb.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/src/{{.project_name}}/main.py.tmpl
Format code in default-python template, so it's already pre-formatted.
```
$ databricks bundle init libs/template/templates/default-python
$ ruff format --diff my_project     
6 files already formatted
```
> Format default-python template

- acceptance/acceptance_test.go
I get an error on my local Windows otherwise: error obtaining VCS status: exit status 128
On CI this does not make a difference.
Also, log full path to binary and output of $CLI --version.
> acceptance: add -buildvcs=false when building on Windows

- Makefile
The current default of building a binary is not frequently used.
The new default is useful after switching branches, stashing/unstashing, AI changes.
Note "fmt" and  "lint" are separate steps because "fmt" can fix formatting and imports in presence of compilation errors and "lint" cannot. Without compilation errors, "lint" also does formatting.
> Alias 'make' to 'make vendor fmt lint'

- libs/exec/exec_test.go
When setting up PATH in tests, put desired entry first but keep the rest as well. Otherwise it fails on Windows
```
D:/a/cli/cli/libs/exec/exec_test.go:108
Error: Received unexpected error:
exit status 0xc0000135
```
Explanation from Claude:
> The error code 0xc0000135 is a Windows error indicating "Unable to locate DLL"
> When code coverage is enabled, Go instruments the binary with coverage tracking code, which requires additional DLL dependencies on Windows.
Separate draft PR with coverage enabled on CI: https://github.com/databricks/cli/pull/2141
> exec(test): Do not clear PATH; this breaks coverage on Windows

- acceptance/bundle/init/dbt-sql/output.txt
- acceptance/bundle/init/default-python/output.txt
- acceptance/bundle/init/default-sql/output.txt
- integration/bundle/testdata/default_python/bundle_init.txt
- integration/bundle/testdata/default_python/bundle_summary.txt
- integration/bundle/testdata/default_python/bundle_validate.txt
- libs/testdiff/replacement.go
It covers both https://$DATABRICKS_HOST and http://$DATABRICKS_HOST so the test output does not change between local and the cloud.
Existing tests using golden files (acceptance and integration) catch this and were updated.
> Introduce $DATABRICKS_URL replacement in tests

- acceptance/bundle/variables/complex-with-var-reference/databricks.yml
- acceptance/bundle/variables/complex-with-var-reference/output.txt
- acceptance/bundle/variables/complex-with-var-reference/script
- bundle/config/mutator/resolve_variable_references_test.go
This is the last test referencing ResolveVariableReferencesInComplexVariables, allowing removal of that mutator.
> Migrate TestResolveComplexVariableWithVarReference

- acceptance/bundle/variables/complex-transitive/output.txt
- acceptance/bundle/variables/complex-with-var-reference/databricks.yml
- acceptance/bundle/variables/complex-with-var-reference/output.txt
- acceptance/bundle/variables/complex-with-var-reference/script
- acceptance/bundle/variables/complex-within-complex/output.txt
- bundle/config/mutator/resolve_variable_references.go
- bundle/config/mutator/resolve_variable_references_test.go
- bundle/phases/initialize.go
- Remove ResolveVariableReferencesInComplexVariables - it blocked complex-within-complex for no good reason.
- Repeat regular resolution twice, it helps with a couple test cases we have.
There may be a case for running it 3 times or more in a loop, but there is no test case for that, so this PR is simple incremental improvement.
Existing acceptance tests. Previously all unit tests for complex variables were converted to acceptance tests, to capture this change and ensure nothing breaks.
> Improve resolution of complex variables within complex variables

- integration/bundle/bundles/recreate_pipeline/template/databricks.yml.tmpl
Pipeline backend requires `target` to be always specified.
In order to do this we will create an unique schema as part of `TestBundlePipelineRecreateWithoutAutoApprove` test which will be used in pipelines
```
helpers_test.go:148: stderr: Destroy complete!
--- PASS: TestBundlePipelineRecreateWithoutAutoApprove (415.39s)
PASS
coverage: [no statements]
ok      github.com/databricks/cli/integration/bundle    416.141s        coverage: [no statements]
```
> Add a unique schema for recreate pipeline test

- .golangci.yaml
- bundle/config/validate/validate_sync_patterns.go
- cmd/bundle/generate/utils.go
- integration/cmd/fs/cat_test.go
- integration/cmd/fs/cp_test.go
- integration/cmd/fs/ls_test.go
- integration/cmd/fs/mkdir_test.go
- integration/cmd/fs/rm_test.go
- integration/libs/filer/filer_test.go
- integration/libs/locker/locker_test.go
- libs/filer/files_client.go
- Remove all unnecessary copies of the loop variable, it is not necessary since Go 1.22 https://go.dev/blog/loopvar-preview
- Enable the linter that catches this issue https://github.com/karamaru-alpha/copyloopvar
> Enable linter 'copyloopvar' and fix the issues

- bundle/apps/slow_deploy_message.go
- bundle/apps/validate.go
- bundle/phases/deploy.go
When users create one or more Databricks apps in their bundle it can lead to initial bundle deployment being slower because apps need to wait until their compute is fully provisioned and started.
This PR adds a message to warn about it. This message will be removed when `no_compute` option becomes available in TF provider and used in DABs (https://github.com/databricks/cli/pull/2144)
> Added output message to warn about slower deployments with apps

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/resource_external_location.go
- bundle/internal/tf/schema/root.go
No significant changes to call out for DABs.
> Upgrade TF provider to 1.63.0

- acceptance/bundle/variables/complex-transitive-deep/databricks.yml
- acceptance/bundle/variables/complex-transitive-deep/output.txt
- acceptance/bundle/variables/complex-transitive-deep/script
Follow up to #2157. That PR repeated variable resolution. This test still does not resolve fully but would resolve with 3 passes. This is slightly different from complex-transitive-deeper - this test does not show any errors, the issue is purely not enough  passes.
> Add a test for complex variable resolution with 3 levels

- CHANGELOG.md
You can now manage Databricks Apps using DABs by defining an `app` resource in your bundle configuration.
For more information see Databricks documentation https://docs.databricks.com/en/dev-tools/bundles/resources.html#app
You can now reference complex variables within other complex variables.
For more details see https://github.com/databricks/cli/pull/2157
CLI:
* Filter out system clusters in cluster picker ([#2131](https://github.com/databricks/cli/pull/2131)).
* Add command line flags for fields that are not in the API request body ([#2155](https://github.com/databricks/cli/pull/2155)).
Bundles:
* Added support for Databricks Apps in DABs ([#1928](https://github.com/databricks/cli/pull/1928)).
* Allow artifact path to be located outside the sync root …
> [Release] Release v0.239.0

- .github/workflows/push.yml
- .gitignore
- Makefile
- acceptance/bin/sort_blocks.py
- bundle/tests/python_wheel/environment_key/my_test_code/src/__main__.py
- bundle/tests/python_wheel/python_wheel/my_test_code/src/__main__.py
- bundle/tests/python_wheel/python_wheel_multiple/my_test_code/src/__main__.py
- bundle/tests/python_wheel/python_wheel_no_artifact/my_test_code/__main__.py
- bundle/tests/python_wheel/python_wheel_no_artifact_notebook/my_test_code/__main__.py
- cmd/labs/project/testdata/installed-in-home/.databricks/labs/blueprint/lib/install.py
- cmd/labs/project/testdata/installed-in-home/.databricks/labs/blueprint/lib/main.py
- libs/notebook/testdata/.ruff.toml
- libs/sync/testdata/.ruff.toml
The materialized templates included in #2146 include Python code that we require to be formatted. Instead of running ruff as part of the testcase, we can enforce that all Python code in the repository is formatted. It won't be possible to have a passing acceptance test for template initialization with unformatted code.
> Format Python code with ruff

- cmd/workspace/apps/overrides.go
Added text output templates for apps list and list-deployments
Fixes #2172
```
andrew.nester@HFW9Y94129 ~ % databricks apps list -p u2m
Name                          Url                                                            Compute Status  Deployment Status
abc                           https://abc-***.aws.databricksapps.com                         STOPPED
andre-test                    https://andre-test-***..aws.databricksapps.com                  ACTIVE          SUCCEEDED
andre-test2                   https://andre-test2-***..aws.databricksapps.com                 ACTIVE          SUCCEEDED
...
```
> Added text output templates for apps list and list-deployments

- .golangci.yaml
- libs/testdiff/testdiff.go
- Fix incorrect use Errorf on literal string. This resulted in garbage output in tests diagnostics where % was replaced by "(MISSING)".
- Enable linter on testingT.Errorf.
Note, the autofix by the linter is wrong, it proposes `t.Errorf("%s", string)` but it should be `t.Error(string)`. That can corrected manually though.
Linter was tested manually by reverting the fix on Errorf.
> Fix incorrect TestingT.Errorf usage and enable linting for this

- internal/testcli/runner.go
Setting Verbose=false on testcli.Runner disables all logging related to running process (stdout, stderr, error, args).
I'm using this in #2184 where I'm using testcli runner to run acceptance tests and seeing all output is not useful.
Manually inspecting test output in #2184
> Add NoLog option on testcli.Runner

- Makefile
Otherwise it prints "83 files left unchanged".
> Run 'ruff format' in quiet mode

- .github/workflows/push.yml
- Makefile
Combine 'make cover' and 'make acc-cover' into single command. They still write coverage into different files -- it would be useful to see separate coverage numbers.
Note, we're not making use of coverage information yet. However, running tests in CI with coverage will
- let us catch issues that only manifest when coverage is enabled, like https://github.com/databricks/cli/pull/2150
- will let us know if there are any issues with running coverage on CI before investing in additional coverage support
> Run tests with coverage on CI

- acceptance/help/output.txt
- cmd/cmd.go
This is not needed because the command group is already returned by `workspace.All()`.
The additional command registration was added in #1679.
Acceptance test.
> Fix duplicate "apps" entry in help output

- bundle/config/root.go
The SelectTarget mutator (part of Load phase) clears bundle.git.inferred flag but it is not set until later - Initialize phase / LoadGitDetails mutator.
> Clean up unnecessary cleanup of inferred flag

- acceptance/acceptance_test.go
- acceptance/bundle/sync-paths-dotdot/databricks.yml
- acceptance/bundle/sync-paths-dotdot/output.txt
- acceptance/bundle/sync-paths-dotdot/script
Based on integration test from @andrewnester in #2194
Manually checked that this databricks.yml passes validation on v0.235.0 but fails on v0.236.0, very like it was broken in https://github.com/databricks/cli/pull/1945
This also adds replacements for tmpdir, it's parent and (just in case) grand parent.
> Add acceptance for test for sync.paths equal to two dots

- .github/workflows/push.yml
- acceptance/acceptance_test.go
- acceptance/bin/callserver.py
- acceptance/cmd_server_test.go
- If you pass -inprocess flag to acceptance tests, they will run in the same process as test itself. This enables debugging.
- If you set singleTest variable on top of acceptance_test.go, you'll only run that test and with inprocess mode. This is intended for debugging in VSCode.
- (minor) Converted KeepTmp to flag -keeptmp from env var KEEP_TMP for consistency with other flags.
- I verified that acceptance tests pass with -inprocess mode: `go test -inprocess < /dev/null | cat`
- I verified that debugging in VSCode works: set a test name in singleTest variable, set breakpoints inside CLI and click "debug test" in VSCode.
> Add -inprocess mode for acceptance tests

- acceptance/bundle/syncroot/dotdot-nogit/output.txt
- bundle/config/mutator/load_git_details.go
If git is not detected, set default worktree root to sync root. Otherwise NewFileSet/View raise an error about worktree root being outside view root in acceptance/bundle/sync-paths-dotdot.
This behavior is introduced in https://github.com/databricks/cli/pull/1945
Stacked on https://github.com/databricks/cli/pull/2202
> Set WorktreeRoot to sync root outside git repo

- acceptance/script.prepare
I've seen this error: could not lock config file $TMPDIR_GPARENT/TestAccept3968313522/002/.gitconfig: File exists
This is likely the cause.
> Use local git config in tests

- bundle/bundle.go
- libs/auth/env.go
- libs/auth/env_test.go
`auth.Env` is a generic function that we can use for authenticated tools downstream to the CLI. 
Unit test.
> Add `auth.Env` function

- acceptance/acceptance_test.go
If there are unreadable files in a directory, raise an error but continue with further diagnostics, because the answer is in the script output.
Manually - I'm working on some tests that create unreadable files, the report is much better with this change.
> tests: Improve reporting in case of FS errors

- bundle/deploy/terraform/init.go
- Propagate env vars USE_SDK_V2_RESOURCES and $USE_SDK_V2_DATA_SOURCES to terraform
- This are troubleshooting helpers for resources migrated to new plugin framework, recommended here: https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting#plugin-framework-migration-problems
- This current unblocks deploying quality monitors, see  https://github.com/databricks/terraform-provider-databricks/issues/4229#issuecomment-2520344690
Manually testing that I can deploy quality monitor after this change with `USE_SDK_V2_RESOURCES="databricks_quality_monitor"` set
```
~/work/databricks_quality_monitor_repro % USE_SDK_V2_RESOURCES="databricks_quality_monitor" ../cli/cli-main bundle deploy
Uploading bundle files to …
```
> Pass USE_SDK_V2_{RESOURCES,DATA_SOURCES} to terraform

- acceptance/bundle/includes/non_yaml_in_include/databricks.yml
- acceptance/bundle/includes/non_yaml_in_include/output.txt
- acceptance/bundle/includes/non_yaml_in_include/script
- acceptance/bundle/includes/non_yaml_in_include/test.py
- bundle/config/loader/process_root_includes.go
`include` section is used only to include other bundle configuration YAML files. If any other file type is used, raise an error and guide users to use `sync.include` instead
> Show an error when non-yaml files used in include section

- CHANGELOG.md
CLI:
* Added text output templates for apps list and list-deployments ([#2175](https://github.com/databricks/cli/pull/2175)).
* Fix duplicate "apps" entry in help output ([#2191](https://github.com/databricks/cli/pull/2191)).
Bundles:
* Allow yaml-anchors in schema ([#2200](https://github.com/databricks/cli/pull/2200)).
* Show an error when non-yaml files used in include section ([#2201](https://github.com/databricks/cli/pull/2201)).
* Set WorktreeRoot to sync root outside git repo ([#2197](https://github.com/databricks/cli/pull/2197)).
* fix: Detailed message for using source-linked deployment with file_path specified ([#2119](https://github.com/databricks/cli/pull/2119)).
* Allow using variables in enum fields ([#2199](https://github.com/databricks/cli/pull/2199)).
* Add …
> [Release] Release v0.239.1

- acceptance/bundle/paths/fallback/output.txt
- acceptance/bundle/paths/nominal/output.txt
- acceptance/bundle/variables/arg-repeat/output.txt
- acceptance/script.prepare
Reduce noise in the output and matches how "Exit code" is handled for the whole script.
> acc: only print non-zero exit codes in errcode function

- acceptance/acceptance_test.go
- libs/testdiff/replacement.go
When adding path, a few things should take care of:
- symlink expansion
- forward/backward slashes, so that tests could do sed 's/\\\\/\//g' to make it pass on Windows (see acceptance/bundle/syncroot/dotdot-git/script)
SetPath() function takes care of both.
This PR uses SetPath() on all paths consistently.
> Include EvalSymlinks in SetPath and use SetPath on all paths

- acceptance/server_test.go
Now the test server will only match GET queries for these endpoints
> Limit test server to only accept GET on read endpoints

- NOTICE
- acceptance/acceptance_test.go
- acceptance/config_test.go
- acceptance/test.toml
- go.mod
- go.sum
- Acceptance tests load test.toml to configure test behaviour.
- If file is not found in the test directory, parents are searched, until the test root.
- Currently there is one option: runtime.GOOS to switch off tests per OS.
Using it in https://github.com/databricks/cli/pull/2223 to disable test on Windows that cannot be run there.
> acc: Support per-test configuration; GOOS option to disable OS

- .github/workflows/publish-winget.yml
For the most recent release, I had to re-run the "publish-winget" action a couple of times before it passed. The underlying issue that causes the failure should be solved by the latest version of the action, but upon inspection of the latest version, I found that it always installs the latest version of [Komac](https://github.com/russellbanks/Komac). To both fix the issue and lock this down further, I updated our action to call Komac directly instead of relying on a separate action to do this for us.
Successful run in https://github.com/databricks/cli/actions/runs/12951529979.
> Update publish-winget action to use Komac directly

- acceptance/acceptance_test.go
- libs/testdiff/replacement.go
- File comparison files in acceptance test, print the contents of all applied replacements. Do it once per test.
- Remove duplicate entries in replacement list.
Manually, change out files of existing test, you'll get this printed once, after first assertion:
```
acceptance_test.go:307: Available replacements:
REPL /Users/denis\.bilenko/work/cli/acceptance/build/databricks => $$CLI
REPL /private/var/folders/5y/9kkdnjw91p11vsqwk0cvmk200000gp/T/TestAccept598522733/001 => $$TMPHOME
...
```
> acc: Print replacements on error and rm duplicates

- acceptance/acceptance_test.go
- acceptance/config_test.go
- acceptance/selftest/output.txt
- acceptance/selftest/script
- acceptance/selftest/test.toml
- Ability to extend a list of replacements via test.toml
- Modify selftest to both demo this feature and to get rid of sed on Windows.
Acceptance tests. I'm also using it https://github.com/databricks/cli/pull/2213 for things like pid.
> acc: Support custom replacements

- acceptance/acceptance_test.go
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/databricks.yml
- acceptance/bundle/templates/experimental-jobs-as-code/script
- acceptance/selftest/output.txt
- acceptance/selftest/script
- libs/testdiff/replacement.go
- Replace development version with $DEV_VERSION
- Update experimental-jobs-as-code to make use of it.
- Existing tests.
- Using this in https://github.com/databricks/cli/pull/2213
> Add default regex for DEV_VERSION

- acceptance/acceptance_test.go
- Do not start replacement / comparison if file is too large or not valid utf-8.
- This helps to prevent replacements if there is accidentally a large binary (e.g. terraform).
Found this problem when working on https://github.com/databricks/cli/pull/2242 -- the tests tried to applied replacements on terraform binary and crashed. With this change, an error is reported instead.
> acc: Avoid reading and applying replacements on large files; validate utf8

- acceptance/acceptance_test.go
- If CLOUD_ENV is set to do not override with dummy value. This allows running acceptance tests as integration tests.
- Needed for https://github.com/databricks/cli/pull/2242
Manually run the test suite against dogfood. `CLOUD_ENV=aws go test ./acceptance`
> acc: Use real terraform when CLOUD_ENV is set

- acceptance/script.prepare
Otherwise hooks from universe and custom hooks run in tests.
Needed for running acceptance tests as integration tests: https://github.com/databricks/cli/pull/2242
> acc: Disable git hooks

- acceptance/bundle/variables/env_overrides/databricks.yml
- acceptance/bundle/variables/env_overrides/output.txt
- acceptance/bundle/variables/env_overrides/script
This does not work when this test is run against cloud.
Needed for https://github.com/databricks/cli/pull/2242
> Fix env_overrides not to use variables in workspace.profile

- acceptance/acceptance_test.go
- acceptance/cmd_server_test.go
- acceptance/server_test.go
- libs/testserver/server.go
Just a move, no changes. As recommended here: https://github.com/databricks/cli/pull/2226#discussion_r1932152627
N/A
> Move TestServer from acceptance to libs/testserver

- bundle/config/mutator/python/python_locations.go
- bundle/config/mutator/python/python_locations_test.go
- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/python/python_mutator_test.go
Fix relative path errors in the Python mutator that was failing during deployment since v0.239.1.
Before that:
```
% databricks bundle deploy  
Deploying resources...
Updating deployment state...
Error: failed to compute relative path for job jobs_as_code_project_job: Rel: can't make resources/jobs_as_code_project_job.py relative to /Users/$USER/jobs_as_code_project
```
As a result, the bundle was deployed, but the deployment state wasn't updated.
Unit tests, adding acceptance tests in https://github.com/databricks/cli/pull/2254
> PythonMutator: Fix relative path error

- acceptance/bundle/git-permerror/output.txt
- acceptance/bundle/variables/prepend-workspace-var/output.txt
- bundle/config/git.go
- bundle/config/mutator/load_git_details.go
- bundle/config/mutator/process_target_mode.go
- bundle/deploy/metadata/compute_test.go
- bundle/tests/environment_git_test.go
- bundle/tests/git_test.go
- integration/bundle/testdata/default_python/bundle_summary.txt
The only use case for it was to emit a warning and based on the discussion here https://github.com/databricks/cli/pull/2213/files#r1933558087 the warning it not useful and logging that with reduced severity is also not useful.
> Remove bundle.git.inferred

- CHANGELOG.md
Bundles:
* Added support for double underscore variable references ([#2203](https://github.com/databricks/cli/pull/2203)).
* Do not wait for app compute to start on `bundle deploy` ([#2144](https://github.com/databricks/cli/pull/2144)).
* Remove bundle.git.inferred ([#2258](https://github.com/databricks/cli/pull/2258)).
* libs/python: Remove DetectInterpreters ([#2234](https://github.com/databricks/cli/pull/2234)).
API Changes:
* Added `databricks access-control` command group.
* Added `databricks serving-endpoints http-request` command.
* Changed `databricks serving-endpoints create` command with new required argument order.
* Changed `databricks serving-endpoints get-open-api` command return type to become non-empty.
* Changed `databricks recipients update` command return type to become …
> [Release] Release v0.240.0

- acceptance/bundle/variables/git-branch/output.txt
- acceptance/bundle/variables/prepend-workspace-var/output.txt
- acceptance/bundle/variables/resolve-builtin/output.txt
- acceptance/bundle/variables/resolve-vars-in-root-path/output.txt
- acceptance/server_test.go
This is something terraform provider expects.
Related to https://github.com/databricks/cli/pull/2242
> acc: Include "id" into /api/2.0/preview/scim/v2/Me response

- ruff.toml
The default is 88 which reformats too much.
This has no effect on templates but affects Python script in this PR https://github.com/databricks/cli/pull/2267
For context, we do not set any line length for golang and have 177 .go files with max line length 150 or more.
> Add ruff.toml with increased line-length

- acceptance/acceptance_test.go
It is proven to be not necessary.
```
~/work/cli/acceptance % hyperfine -w 2 'go test'  # with change:
Benchmark 1: go test
Time (mean ± σ):      4.983 s ±  0.209 s    [User: 6.073 s, System: 9.869 s]
Range (min … max):    4.792 s …  5.483 s    10 runs
~/work/cli/acceptance % git stash  # without change:
~/work/cli/acceptance % hyperfine -w 2 'go test'
Benchmark 1: go test
Time (mean ± σ):      5.018 s ±  0.100 s    [User: 6.142 s, System: 10.234 s]
Range (min … max):    4.899 s …  5.182 s    10 runs
```
> acc: Remove initial '$CLI --version' call

- acceptance/acceptance_test.go
- Include compact relPath in the error message title. Include full paths in separate lines below.
- Previously sometimes full paths were printed, sometime only rel path.
Manually trigger the errors.
> acc: Consistent & detailed output for file issues

- .github/workflows/push.yml
- .github/workflows/release-snapshot.yml
- .github/workflows/release.yml
This reduces number of places where we hard-code go version to single place - go.mod.
Note, since we have go version specified without patch version ("1.23") in go.mod, it will use most recent in 1.23.x line. I think this is fine.
https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
> Use go-version-file instead of go-version in  github actions

- acceptance/acceptance_test.go
- acceptance/cmd_server_test.go
- acceptance/config_test.go
- acceptance/server_test.go
- acceptance/workspace/jobs/create-error/out.requests.txt
- acceptance/workspace/jobs/create-error/output.txt
- acceptance/workspace/jobs/create-error/script
- acceptance/workspace/jobs/create-error/test.toml
- libs/testserver/server.go
The APIs at Databricks when returning a non `200` status code will return a response body of the format:
```
{
"error_code": "Error code",
"message": "Human-readable error message."
}
```
This PR adds the ability to stub non-200 status codes in the test server, allowing us to mock API errors from Databricks.
New test
> Allow test servers to return errors responses

- bundle/deploy/terraform/init.go
- bundle/deploy/terraform/init_test.go
Solves #1722 (current solution passes wrong variable)
None, this is a simple find-and-replace on a previous PR.
Proof that this is the correct [variable](https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file).
This just passes the variable along to the Terraform environment, which [should](https://github.com/hashicorp/terraform/issues/25416) be picked up by Terraform.
> Fix env variable for AzureCli local config

- cmd/labs/project/installer.go
- cmd/labs/project/schema.json
- cmd/labs/project/testdata/installed-in-home/.databricks/labs/blueprint/lib/labs.yml
Added support for extras / optional Python dependencies in the labs CLI.
Added new `extras` field under install.
Example:
```yaml
install:
script: install.py
extras: cli
```
Resolves: #2257 
Manual test
> Add support for extras to the labs CLI

- Makefile
Apparently, it's not part of golangci-lint, so you can send PRs that fail this check on CI.
> Include 'go mod tidy' into 'make' and 'make tidy'

- bundle/docsgen/main.go
- bundle/docsgen/nodes.go
- bundle/docsgen/refs.go
- bundle/internal/schema/annotations_openapi_overrides.yml
- bundle/internal/schema/parser.go
- libs/jsonschema/schema.go
1. Allow `any` examples in json-schema type since we have many of them in open api spec
2. Fix issue with missing overrides annotations when re-generating the schema
> Allow 'any' examples in JSON schema

- acceptance/acceptance_test.go
- acceptance/bundle/scripts/output.txt
- acceptance/cmd_server_test.go
- acceptance/server_test.go
- acceptance/workspace/jobs/create/out.requests.txt
- libs/testserver/fake_workspace.go
- libs/testserver/server.go
Extend testserver for bundle deployment:
- Allocate a new workspace per test case to isolate test cases from each other
- Support jobs get/list/create
- Support creation and listing of workspace files
Using existing acceptance tests
> Extend testserver for deployment

- cmd/auth/token.go
The intent of this PR is to clarify that the `databricks auth token` command is not supported for M2M auth. Fixes: https://github.com/databricks/cli/issues/1939
Manually.
> Add doc string for the `auth token` command

- acceptance/bundle/debug/script
Replace timestamps with fixed string before output is sorted (and before test runner replacements are applied).
Otherwise the test sometimes fails with error below. Note, timestamps themselves do not show it, because they were replaced.
```
--- FAIL: TestAccept/bundle/debug (0.78s)
acceptance_test.go:404: Diff:
--- bundle/debug/out.stderr.parallel.txt
+++ /var/folders/5y/9kkdnjw91p11vsqwk0cvmk200000gp/T/TestAcceptbundledebug1859985035/001/out.stderr.parallel.txt
@@ -8,8 +8,8 @@
10:07:59 Debug: ApplyReadOnly pid=12345 mutator=validate mutator (read-only)=parallel mutator (read-only)=validate:files_to_sync
10:07:59 Debug: ApplyReadOnly pid=12345 mutator=validate mutator (read-only)=parallel mutator (read-only)=validate:folder_permissions
10:07:59 Debug: ApplyReadOnly pid=12345 …
```
> Fix flaky acceptance test

- NOTICE
- acceptance/config_test.go
- acceptance/test.toml
- go.mod
- go.sum
Instead of using leaf-most config, all configs from root at acceptance/test.toml to all intermediate ones to leaf config are merged into one. Maps are merged, slices are appended, other values are overridden.
I had to disable caching, because it is tricky when merging is involved - deep copy is needed. There is performance
impact but currently it is tiny, about 1%.
Also, remove empty root config.
Manually checked that inheritance of LocalOnly setting worked for these tests:
Before - integration tests showed:
```
PASS acceptance.TestAccept/bundle/templates/wrong-url (0.70s)
PASS acceptance.TestAccept/bundle/templates/wrong-path (0.44s)
```
After:
```
SKIP acceptance.TestAccept/bundle/templates/wrong-url (0.00s)
SKIP acceptance.TestAccept/bundle/templates/wrong-path (0.00s) …
```
> acc: Implement config merge 

- bundle/config/mutator/apply_presets.go
- bundle/config/mutator/capture_schema_dependency.go
- bundle/config/mutator/capture_schema_dependency_test.go
- bundle/config/mutator/expand_pipeline_glob_paths_test.go
- bundle/config/mutator/initialize_urls_test.go
- bundle/config/mutator/merge_pipeline_clusters_test.go
- bundle/config/mutator/process_target_mode_test.go
- bundle/config/mutator/resolve_variable_references_test.go
- bundle/config/mutator/translate_paths_test.go
- bundle/config/resources/pipeline.go
- bundle/config/validate/single_node_cluster_test.go
- bundle/deploy/metadata/annotate_pipelines.go
- bundle/deploy/metadata/annotate_pipelines_test.go
- bundle/deploy/terraform/convert_test.go
- bundle/deploy/terraform/tfdyn/convert_pipeline.go
- bundle/deploy/terraform/tfdyn/convert_pipeline_test.go
- bundle/deploy/terraform/tfdyn/rename_keys.go
- bundle/internal/schema/annotations.yml
- bundle/internal/schema/annotations_openapi.yml
- bundle/internal/schema/annotations_openapi_overrides.yml
- bundle/internal/schema/main.go
- bundle/permissions/workspace_root_test.go
- bundle/render/render_text_output_test.go
- bundle/resources/completion_test.go
- bundle/resources/lookup_test.go
- bundle/run/pipeline.go
- bundle/schema/jsonschema.json
- cmd/bundle/generate/pipeline.go
- libs/dyn/drop_keys.go
- libs/dyn/drop_keys_test.go
`CreatePipeline` is a more complete structure (superset of PipelineSpec one) which enables support of additional fields such as `run_as` and `allow_duplicate_names` in DABs configuration. Note: these fields are subject to support in TF in order to correctly work.
Existing tests pass + no fields are removed from JSON schema
> Use CreatePipeline instead of PipelineSpec for resources.Pipeline struct

- Makefile
It was not indended to be printed. Follow up to #2298
> Silence a comment in Makefile

- acceptance/acceptance_test.go
When there are many unexpected files, it's good to see them as a list rather than scattered throughout the output.
Manually, example output:
```
acceptance_test.go:363: Test produced unexpected files:
output/my_default_sql/.databricks/bundle/dev/sync-snapshots/71c79ded90615dc7.json
output/my_default_sql/.databricks/bundle/dev/terraform/.terraform/providers/registry.terraform.io/databricks/databricks/1.64.1/darwin_arm64
output/my_default_sql/.databricks/bundle/dev/terraform/plan
output/my_default_sql/.databricks/bundle/prod/sync-snapshots/83e677e75259c93b.json
output/my_default_sql/.databricks/bundle/prod/terraform/.terraform/providers/registry.terraform.io/databricks/databricks/1.64.1/darwin_arm64
```
> acc: Summarize unexpected files

- acceptance/bundle/variables/host/output.txt
- cmd/bundle/run.go
- cmd/bundle/summary.go
- cmd/bundle/validate.go
- Insert newline after rendering indented JSON in bundle validate/summary/run. 
- This prevents "No newline at end of file" message in various cases, for example when switching between recording raw output of the command to output processed by jq, since jq does add a newline or when running diff in acceptance tests.
Manually running validate:
```
~/work/dabs_cuj_brickfood % ../cli/cli-main bundle validate -o json | tail -n 2  # without change
Error: root_path must start with '~/' or contain the current username to ensure uniqueness when using 'mode: development'
}
}%
~/work/dabs_cuj_brickfood % ../cli/cli bundle validate -o json | tail -n 2  # with change
Error: root_path must start with '~/' or contain the current username to ensure uniqueness when using 'mode: development'
}
} …
```
> Append newline to "-o json" for validate/summary/run

- libs/testserver/server.go
Addresses feedback from https://github.com/databricks/cli/pull/2292#discussion_r1946846865
Manually, confirmed that unstubbed API calls still cause acceptance tests to fail.
> Return 501 status code when API stub is not implemented

- Makefile
- acceptance/acceptance_test.go
- Only print replacements if VERBOSE_TEST flag is set.
- This is set on CI but not when you do "go test" or "make test".
Note, env var is used, so that it can be set in Makefile.
Manually.
> acc: Do not show all replacements on every failure

- acceptance/acceptance_test.go
We're not using local server when CLOUD_ENV is enabled, no need to set up a custom one.
> acc: Disable custom server on CLOUD_ENV

- acceptance/acceptance_test.go
- libs/testserver/server.go
Do not paste request body into output if it's not a valid JSON.
While working on #2334 I found that if I try to record a test that calls /api/2.0/preview/scim/v2/Me which has no request body, it crashes.
> acc: Fix RecordRequests to support requests without body

- acceptance/acceptance_test.go
The filtering of tests needs to see forward slashes otherwise it is OS-dependent.
I've also switched to filepath.ToSlash but it should be a no-op.
> acc: Fix singleTest option to support forward slashes

- acceptance/acceptance_test.go
- acceptance/bundle/debug/out.stderr.parallel.txt
- acceptance/bundle/debug/out.stderr.txt
- acceptance/cmd_server_test.go
- acceptance/config_test.go
- acceptance/selftest/server/out.requests.txt
- acceptance/selftest/server/output.txt
- acceptance/selftest/server/script
- acceptance/selftest/server/test.toml
- acceptance/server_test.go
- libs/testserver/fake_workspace.go
- libs/testserver/server.go
Handlers now receive testserver.Request and return any which could be
- string or []byte (returns it as is but sets content-type to json or plain text depending on content)
- struct (encodes it as json and sets content-type to json)
- testserver.Response (full control over status and headers)
Note if testserver.Response is returned from the handler, it's Body attribute can still be an object. In that case, it'll be serialized and appropriate content-type header will be added.
The config is now using the same testserver.Response struct, the same logic applies both configured responses and responses returned from handlers.
As a result, one can set headers both in Golang handlers and in test.toml.
This also fixes a bug with RecordRequest not seeing the body if it was already consumed by the …
> acc: Simplify writing handlers; support headers in responses

- CHANGELOG.md
Bundles:
* Added support to generate Git based jobs ([#2304](https://github.com/databricks/cli/pull/2304)).
* Added support for run_as in pipelines ([#2287](https://github.com/databricks/cli/pull/2287)).
* Raise an error when there are multiple local libraries with the same basename used ([#2297](https://github.com/databricks/cli/pull/2297)).
* Fix env variable for AzureCli local config ([#2248](https://github.com/databricks/cli/pull/2248)).
* Accept JSON files in includes section ([#2265](https://github.com/databricks/cli/pull/2265)).
* Always print warnings and errors; clean up format ([#2213](https://github.com/databricks/cli/pull/2213))
API Changes:
* Added `databricks account budget-policy` command group.
* Added `databricks lakeview-embedded` command group.
* Added `databricks …
> [Release] Release v0.241.0

- acceptance/bundle/artifacts/same_name_libraries/databricks.yml
- acceptance/bundle/artifacts/same_name_libraries/output.txt
- bundle/libraries/same_name_libraries.go
The CheckForSameNameLibraries mutator incorrectly assumed all resource libraries define libraries as paths of the `string` type, but some libraries, such as PyPi and Maven, define them as objects.
This PR addresses this issue. It was introduced in #2297.
Added regression test.
> Fix for regression deploying resources with PyPi and Maven library types

- CHANGELOG.md
Bundles:
* Fix for regression deploying resources with PyPi and Maven library types ([#2341](https://github.com/databricks/cli/pull/2341)).
> [Release] Release v0.241.1

- CHANGELOG.md
This is a bugfix release to address an issue where jobs with tasks with a
libraries section with PyPI packages could not be deployed.
Bundles:
* Revert changes related to basename check for local libraries ([#2345](https://github.com/databricks/cli/pull/2345)).
> [Release] Release v0.241.2

- acceptance/server_test.go
This is needed for b.WorkspaceClient().CurrentWorkspaceID(ctx) which is used by initialize_urls.go mutator ("bundle summary") #2316
It also also needed for to call serverless detection endpoint #2348
Builds on top of #2338
> acc: Set X-Databricks-Org-Id on scim/v2/Me endpoint

- acceptance/acceptance_test.go
It's not interesting since it just dumps what is in the repo. This is especially annoying with bundle/templates tests with a lot of files.
> acc: do not show diff for missing output file

- acceptance/acceptance_test.go
- acceptance/config_test.go
Previously, one could not set `LocalOnly=true` in parent directory and then override it with `LocalOnly=false` in child directory. This is because, `false` is considered empty value by mergo.
In order to distinguish between 'explicitly set to false' and 'not set', I've changed all simple variables in config to be pointers. Now, one can always override those, because non-nil pointers are not empty values (with mergo.WithoutDereference option).
Manually:
```
~/work/cli/acceptance/bundle/templates/default-python % cat test.toml   # add this new file 
LocalOnly = false
~/work/cli/acceptance/bundle/templates/default-python % CLOUD_ENV=aws go test ../../.. -run ^TestAccept$/^bundle$/^templates$/^default-python$ -v
(the test is no longer skipped)
```
> acc: fix override of settings with null values

- integration/bundle/init_default_python_test.go
I'm not completely sure what is lowercasing it, we can investigate this later. This unblocks tests on main.
> Name: project_name_kLvfBngEcUEI
> Uploading project_name_klvfbngecuei-0.0.1+[NUMID].[NUMID]-py3-none-any.whl...
`CLOUD_ENV=aws go test --timeout 3h -v -run TestDefaultPython/3.9 ./integration/bundle`
> Fix failing integration test due to lowercased wheel file

- .codegen/service.go.tmpl
- acceptance/cmd/workspace/apps/input.json
- acceptance/cmd/workspace/apps/out.requests.txt
- acceptance/cmd/workspace/apps/output.txt
- acceptance/cmd/workspace/apps/script
- acceptance/cmd/workspace/apps/test.toml
- cmd/account/budget-policy/budget-policy.go
- cmd/workspace/apps/apps.go
- cmd/workspace/lakeview/lakeview.go
CLI generation template was using RequiredPathField from incorrect request entity (body field from request and not request itself). Thus for some of the commands required path parameters were not required when --json was specified.
Regenerated commands work correctly
> Fixed accessing required path parameters in CLI generation when --json flag

- acceptance/bundle/templates/default-python/output/my_default_python/resources/my_default_python.job.yml
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/resources/my_jobs_as_code_job.py
- integration/bundle/testdata/default_python/bundle_summary.txt
- libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}.job.yml.tmpl
- libs/template/templates/experimental-jobs-as-code/template/{{.project_name}}/resources/{{.project_name}}_job.py.tmpl
1. Change the **default-python** bundle template to set `data_security_mode` of a cluster to SINGLE_USER
2. Change the **experimental-jobs-as-code** bundle template to set `data_security_mode` of a cluster to SINGLE_USER
Explicitly adding this field saves experienced users from confusion onto what security mode is applied to the cluster
Changed existing unit and integration tests to pass with this change
> Set default data_security_mode to "SINGLE_USER" in bundle templates

- acceptance/auth/bundle_and_profile/output.txt
- acceptance/auth/bundle_and_profile/script
- acceptance/auth/bundle_and_profile/test.toml
- cmd/root/auth.go
- cmd/root/bundle.go
Now when `profile` flag is used we won't pick up host from bundle anymore and use the one provided by -p flag
Previous behaviour in the context of bundle
```
databricks current-user me -p profile_name
Error: cannot resolve bundle auth configuration: config host mismatch: profile uses host https://non-existing-subdomain.databricks.com, but CLI configured to use https://foo.com
```
New behaviour (make an api call)
```
databricks current-user me -p profile_name
{
email: "foo@bar.com"
...
}
```
We still load bundle configuration when `-t` flag provide because we want to load host information from the target.
Fixes #1358 
> Do not load host from bundle for CLI commands when profile flag is used

- libs/template/templates/default-python/databricks_template_schema.json
Since at this moment we set default to 'no', interactively it should also default to 'no'. However, it just uses the first option.
Manually running `cli bundle init default-python`
> default-python: Swap order of yes/no in serverless template

- libs/template/templates/default-python/databricks_template_schema.json
Manually running 'bundle init default-python' - no question about serverless.
> Skip serverless prompt in default-python (default is no)

- acceptance/acceptance_test.go
- acceptance/auth/bundle_and_profile/test.toml
- acceptance/auth/credentials/test.toml
- acceptance/bundle/debug/test.toml
- acceptance/bundle/generate/git_job/test.toml
- acceptance/bundle/help/test.toml
- acceptance/bundle/libraries/maven/test.toml
- acceptance/bundle/libraries/pypi/test.toml
- acceptance/bundle/templates-machinery/helpers-error/test.toml
- acceptance/bundle/templates-machinery/helpers/test.toml
- acceptance/bundle/templates-machinery/test.toml
- acceptance/bundle/templates/test.toml
- acceptance/bundle/test.toml
- acceptance/bundle/trampoline/warning_message_with_new_spark/test.toml
- acceptance/bundle/trampoline/warning_message_with_old_spark/test.toml
- acceptance/bundle/variables/test.toml
- acceptance/cmd/workspace/apps/test.toml
- acceptance/config_test.go
- acceptance/selftest/server/test.toml
- acceptance/selftest/test.toml
- acceptance/terraform/test.toml
- acceptance/test.toml
- acceptance/workspace/jobs/create-error/test.toml
- acceptance/workspace/jobs/create/test.toml
Instead of LocalOnly with non-composable semantics there are two composable options:
- Local - enable test locally
- Cloud - enable test on the cloud
By default Cloud is switched off except in bundle (but not in bundle/variables and bundle/help).
Using this in #2383 to have test that runs on cloud but not locally.
> acc: replace LocalOnly option with Local & Cloud

- CHANGELOG.md
Notable changes:
Starting this version CLI does not load bundle auth information when CLI command is executed inside the bundle directory with explicitly provided via `-p` flag profile. For more details see the related GitHub issue https://github.com/databricks/cli/issues/1358
CLI:
* Do not load host from bundle for CLI commands when profile flag is used ([#2335](https://github.com/databricks/cli/pull/2335)).
* Fixed accessing required path parameters in CLI generation when --json flag ([#2373](https://github.com/databricks/cli/pull/2373)).
Bundles:
* Provide instructions for testing in the default-python template ([#2355](https://github.com/databricks/cli/pull/2355)).
* Remove `run_as` from the built-in templates ([#2044](https://github.com/databricks/cli/pull/2044)).
* Change warning …
> [Release] Release v0.242.0

- libs/testserver/server.go
Manually, I have a test that fails.
Before:
```
=== NAME  TestAccept
server.go:195:
----------------------------------------
No stub found for pattern: GET /api/2.1/clusters/get
To stub a response for this request, you can add
the following to test.toml:
[[Server]]
Pattern = "GET /api/2.1/clusters/get"
Response.Body = '''
<response body here>
'''
Response.StatusCode = <response status-code here>
----------------------------------------
```
After:
```
server.go:203: No handler for URL: /api/2.1/clusters/get?cluster_id=0717-132531-5opeqon1
Body: [0 bytes]
For acceptance tests, add this to test.toml:
[[Server]]
Pattern = "GET /api/2.1/clusters/get"
Response.Body = '<response body here>'
```
> acc: Print full URL and request body for missing handlers

- integration/bundle/spark_jar_test.go
- internal/testutil/jdk.go
1. Refactored `TestSparkJarTaskDeployAndRunOnVolumes` and `TestSparkJarTaskDeployAndRunOnWorkspace` to use a table-driven approach for better organization of similar tests
2. Implemented `testutil.HasJDK()` to replace `testutil.RequireJDK` to be able to skip tests
3. Ensured the test suite properly fails if no compatible Java version is found
It can be tricky to have Java 8 installed on modern dev environments (e.g. Mac on Apple M3 chip). The absence of which  previously caused the Spark Jar task tests to fail when run locally. This refactoring allows such environments to be able to run "SparkJar" tests using a newer Databricks Runtime.
1. Ran `TestSparkJarTaskDeployAndRunOnVolumes` and `TestSparkJarTaskDeployAndRunOnWorkspace` locally on Mac with Java11 installed.
2. Checked that tests …
> Refactor TestSparkJarTask* tests to support test environments without Java 8

- acceptance/acceptance_test.go
- acceptance/config_test.go
- acceptance/selftest/basic/script
- acceptance/selftest/basic/test.toml
Ignore output files using gitignore syntax.
New Ignore setting in test.toml that will ignore specified files (syntax is gitignore).
I'm using it in #2396 to ignore virtual env. It includes a lot of files. The regular 'rm -fr .venv' approach only works if script get to that point, but due to errors it might abort early. In that cases test runner prints all unexpected files, polluting output. Ignoring those files at test runner level ensure you never see them.
Updated selftest/basic.
> acc: add Ignore setting to config

- integration/cmd/auth/describe_test.go
1. remove t.Skip directive from TestAuthDescribeSuccess integration test
2. change the test code to account for environments where host value can be prefixed  with the https protocol part
This enables integration test that exercises `databricks auth describe` command, which was previously throwing errors in the CI/CD pipeline
Integration test is passing
> Enable TestAuthDescribeSuccess integration test

- bundle/libraries/same_name_libraries.go
Same name libraries check only valid for local libraries. Local libraries are only supported for Whl and Jar types. Hence we can restrict matching pattern only to these libraries.
Existing acceptance tests pass
> Restrict same name libraries check for only whl and jar types

- integration/bundle/init_default_python_test.go
Lock setuptools version to 75.8.2 (latest as of March 3, 2025)
As part of the tests `uv install` was installing latest version of setuptools which led to all tests started to fail on Feb 25 when 75.8.1 setuptools version was released and which changed the naming of the output built artifacts
https://setuptools.pypa.io/en/stable/history.html#v75-8-1
This change prevents us from breakages like this.
Existing tests pass
> test: Lock setuptools version in TestDefaultPython test

- integration/cmd/auth/describe_test.go
1. remove t.Skip directive from TestAuthDescribeFailure integration test
2. remove checking the host in the test
1. This enables integration test that exercises `databricks auth describe` command, which was previously throwing errors in the CI/CD pipeline. For the nonexistent profile check to fail, we need to create a new profile file for the CLI to check (otherwise the configuration skips checking of the provided profile actually exists). 
2. I removed the assertion for the host part because it is not relevant for the test, and setting that up just required more code in the test setup.
The integration test is passing
> Enable TestAuthDescribeFailure integration test

- bundle/config/resources.go
- bundle/config/resources/schema.go
- bundle/config/resources/schema_test.go
- integration/bundle/bind_resource_test.go
- integration/bundle/bundles/uc_schema_only/databricks_template_schema.json
- integration/bundle/bundles/uc_schema_only/template/databricks.yml.tmpl
1. Changed `FindResourceByConfigKey` to return schema resources
2. Implemented the `Exists` method for schema resources
This PR adds support for schema resources in deployment operations, enabling users to:
- Bind schemas using `databricks bundle deployment bind <myschema_key> <schema_full_name>`
- Unbind schemas using `databricks bundle deployment unbind <myschema_key>`
Where:
- `myschema_key` is a resource key defined in the bundle's .yml file
- `schema_full_name` references an existing schema in the Databricks workspace
These capabilities allow for more flexible resource management of schemas within bundles.
Added a new integration test that tests bind and unbind methods together with bundle deployment and destruction.
> Add support for schemas in deployment bind/unbind commands

- Makefile
There is no perf difference, it's fast in both cases:
```
~/work/cli % hyperfine 'ruff format -qn'
Benchmark 1: ruff format -qn
Time (mean ± σ):      22.5 ms ±   4.1 ms    [User: 23.6 ms, System: 106.7 ms]
Range (min … max):    17.3 ms …  50.2 ms    52 runs
```
but it no longer produces .ruff_cache which can confuse acceptance test runner
```
~/work/cli % find . -type d | grep ruff
./.ruff_cache
./.ruff_cache/0.8.3
./libs/notebook/testdata/.ruff_cache
./libs/notebook/testdata/.ruff_cache/0.8.3
./libs/sync/testdata/.ruff_cache
./libs/sync/testdata/.ruff_cache/0.8.3
./acceptance/bundle/templates/default-sql/.ruff_cache
./acceptance/bundle/templates/default-sql/.ruff_cache/0.8.3
```
> Disable ruff cache

- .vscode/settings.json
VSCode for me resolves `script` as YAML files showing incorrect syntax coloring. This setting forces VSCode to treat all files named `script` as shell scripts leading to better syntax highlighting. 
These files are common place in our acceptance tests.
Manually.
> Update VSCode settings to resolve files named `script` as shell scripts

- .github/workflows/push.yml
- bundle/config/root.go
- bundle/internal/annotation/descriptor.go
- bundle/internal/schema/annotations.go
- bundle/internal/schema/annotations.yml
- bundle/schema/jsonschema.json
- libs/jsonschema/extension.go
- libs/jsonschema/from_type.go
- libs/jsonschema/from_type_test.go
- libs/jsonschema/schema.go
Start outputting `deprecated` and `deprecationMessage` annotations in the JSON schema
So that deprecated fields are shown as deprecated in VSCode (and other editors)
- manually tested
||||
|---|---|---|
|<img width="682" alt="Screenshot 2025-03-03 at 16 04 21" src="https://github.com/user-attachments/assets/9712aa2f-0f41-48a9-8bd0-ec92b8b75c3f" />|<img width="682" alt="Screenshot 2025-03-03 at 16 04 29" src="https://github.com/user-attachments/assets/a14f3523-ad85-4fed-96d7-2a8cf3a458e5" />|<img width="682" alt="Screenshot 2025-03-03 at 16 06 03" src="https://github.com/user-attachments/assets/b9ab1050-048e-4c14-b183-96d615a4fbc1" />|
> Output deprecated annotations in the JSON schema

- CHANGELOG.md
CLI:
* Upgrade Go SDK to 0.59.0 ([#2425](https://github.com/databricks/cli/pull/2425)).
Bundles:
* Added a warning when `config` section is used in apps ([#2416](https://github.com/databricks/cli/pull/2416)).
* Switch to use GET workspaces-files/{name} instead of workspace/export for state files to avoid 10MB limit ([#2423](https://github.com/databricks/cli/pull/2423)).
* Use schema field for pipeline in builtin template ([#2347](https://github.com/databricks/cli/pull/2347)).
* Add warning when variable interpolation is used for auth fields ([#2399](https://github.com/databricks/cli/pull/2399)).
* Add warning when include is used in config files other than databricks.yml ([#2389](https://github.com/databricks/cli/pull/2389)).
* Add support for schemas in deployment bind/unbind commands …
> [Release] Release v0.243.0

- acceptance/acceptance_test.go
- cmd/auth/describe.go
- cmd/root/auth.go
- cmd/root/bundle.go
- cmd/root/bundle_test.go
- libs/command/config_used.go
- libs/command/context.go
This PR moves `ConfigUsed` from the root package to `libs/command`.
Having the ConfigUsed function in the root package is a problem because that means we cannot use that function from outside the `root` package since doing so often leads to an import cycle (because `root` imports everything implicitly).
Moving it to a separate package that consolidates the read interaction and solves the import cycle issue. Example where this would have simplified code: https://github.com/databricks/cli/pull/2432#discussion_r1983368092
I'd like to send PRs to do the same for the workspace client and account client as well. I'll wait however until this one is merged incase people have concerns about the approach here.
> Move `ConfigUsed` to `libs/command`

- .github/PULL_REQUEST_TEMPLATE.md
Make NO_CHANGELOG=true a default in PR template
Quite large amount of our changes are internal and don't need call outs in CHANGELOG hence this is a good default for majority of our PRs. Without NO_CHANGELOG=true CI check expects to have an entry in NEXT_CHANGELOG file as part of same PR.
NO_CHANGELOG=true
> Make NO_CHANGELOG=true a default in PR template

- go.mod
Update Go to 1.23.7
From https://go.dev/doc/devel/release#go1.23.minor
> go1.23.5 (released 2025-01-16) includes security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the compiler, the runtime, and the net package. See the [Go 1.23.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved) on our issue tracker for details.
> go1.23.6 (released 2025-02-04) includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command. See the [Go 1.23.6 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.6+label%3ACherryPickApproved) on our issue tracker for details.
> go1.23.7 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to …
> Update Go to 1.23.7

- libs/testserver/fake_workspace.go
When a file is imported, FakeWorkspace now automatically identifies and records all parent directories in the directories map, ensuring the directory structure is properly maintained without requiring explicit directory creation.
During an acceptance test, production code might want to check a root folder for existence, this change makes sure that root folder is marked as existing when at least one file is imported into the workspace
Tests for another change using this improvement are green: https://github.com/databricks/cli/pull/2463
> Make fake_workspace create all parent folders exist when importing a file

- go.mod
Set Go patch version in go.mod
Our dependabot PRs failing with the following diff
```
Run # Exit with status code 1 if there are differences (i.e. unformatted files)
diff --git a/go.mod b/go.mod
index 5c1cb1d..493152a 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,[7](https://github.com/databricks/cli/actions/runs/13768953030/job/38502532441?pr=2459#step:5:8) @@
module github.com/databricks/cli
-go 1.23
+go 1.23.0
+
```
While I'm not 100% sure why it started to happen, setting the patch version at least should fix these PR.
This might be related to this change in Go https://github.com/golang/go/issues/69095 and the fact that the proposal is to enforce 1.(N-1).0 version in go.mod. 1.24 version of [released in mid of February](https://tip.golang.org/doc/devel/release#go1.24.0) so altogether …
> Set Go patch version in go.mod

- acceptance/acceptance_test.go
- acceptance/bundle/deployment/bind/schema/output.txt
- acceptance/bundle/deployment/bind/schema/script
- acceptance/bundle/deployment/bind/schema/test.toml
- acceptance/server_test.go
1. Change the cloud acceptance test for `bind/schema` to run locally
2. Add debug lines to the mock server
3. Change `fake_workspace` to create directories for imported files
1. Local version of the test run can indicate breaking changes faster than the cloud version and it can be run locally without any predefined environment variables 
1. Ran both acloud and local versions of test, both succeeded
> Make bind/schema acceptance test run locally

- acceptance/acceptance_test.go
Add new option -tail to acceptance test runner. This logs output.txt in real time with relative timestamp prefix.
When working on long running integration tests, it's useful to see what stage they are at.
Manually
```
~/work/cli/acceptance/selftest % testme -v -tail
+ go test .. -run ^TestAccept$/^selftest$ -v -tail
...
=== CONT  TestAccept/selftest/diff
acceptance_test.go:774:  0.051 >>> diff.py out_dir_a out_dir_b
=== NAME  TestAccept/selftest/basic
acceptance_test.go:774:  0.051 === Capturing STDERR
acceptance_test.go:774:  0.051 >>> python3 -c import sys; sys.stderr.write("STDERR\n")
=== NAME  TestAccept/selftest/server
acceptance_test.go:774:  0.050 >>> curl -s http://127.0.0.1:55850/api/2.0/preview/scim/v2/Me
...
acceptance_test.go:774:  0.204 >>> …
```
> acc: add -tail option to see output.txt in real time

- acceptance/acceptance_test.go
- acceptance/config_test.go
New bool config setting CloudSlow in acceptance tests. If set, it enables this test on Cloud but skips it in -short setting there. It does not affect local runs, "Slow" is only applied to Cloud. The reason is that we won't need to wait for cluster with mocked testserver.
Additionally, this setting enables -tail if -v is already enabled. 
Certain tests that use "bundle run" are too long due to starting a cluster.
Using this option in #2471
> acc: Add CloudSlow config setting

- acceptance/selftest/trap/output.txt
- acceptance/selftest/trap/script
Discovered that 'trap' does not work with $CLI on Windows when working #2471
This example shows a workaround.
> acc: Add example on how to do trap

- acceptance/acceptance_test.go
- acceptance/bundle/integration_whl/base/output.txt
- acceptance/bundle/integration_whl/base/script
- acceptance/bundle/integration_whl/custom_params/output.txt
- acceptance/bundle/integration_whl/custom_params/script
- acceptance/bundle/integration_whl/interactive_cluster/output.txt
- acceptance/bundle/integration_whl/interactive_cluster/script
- acceptance/bundle/integration_whl/wrapper/output.txt
- acceptance/bundle/integration_whl/wrapper/script
- acceptance/bundle/integration_whl/wrapper_custom_params/output.txt
- acceptance/bundle/integration_whl/wrapper_custom_params/script
- acceptance/bundle/override/test.toml
This is a follow up to #2471 where incorrect config was used in interactive_cluster test.
- Fixed interactive_cluster to use proper config, it was accidentally referring to config from ../base
- Add $NODE_TYPE_ID env var and replacement to acceptance tests, this is necessary for interactive_cluster test.
- Disable acceptance/bundle/override on cloud. This started failing because it has real node type that gets replaced with NODE_TYPE_ID but only in AWS env. Since the test is focussed on config merging, there is no need to run it against real workspaces.
- Modify all tests in integration_whl to print rendered databricks.yml, to prevent this kind of error.
> acc: Fix interactive_cluster test to use correct config; add NODE_TYPE_ID

- acceptance/bin/find.py
Noticed that it currently turns ".databricks" in "databricks".
> acc: fix find.py not to lose '.' at the beginning of the path

- experimental/python/databricks/bundles/build.py
- experimental/python/databricks/bundles/core/__init__.py
- experimental/python/databricks/bundles/core/_bundle.py
- experimental/python/databricks/bundles/core/_diagnostics.py
- experimental/python/databricks/bundles/core/_load.py
- experimental/python/databricks/bundles/core/_location.py
- experimental/python/databricks/bundles/core/_resource.py
- experimental/python/databricks/bundles/core/_resource_mutator.py
- experimental/python/databricks/bundles/core/_resources.py
- experimental/python/databricks/bundles/core/_transform.py
- experimental/python/databricks/bundles/core/_transform_to_json.py
- experimental/python/databricks/bundles/core/_variable.py
- experimental/python/databricks/bundles/jobs/__init__.py
- experimental/python/databricks/bundles/jobs/_models/job.py
- experimental/python/databricks_tests/core/test_bundle.py
- experimental/python/databricks_tests/core/test_diagnostics.py
- experimental/python/databricks_tests/core/test_load.py
- experimental/python/databricks_tests/core/test_resources.py
- experimental/python/databricks_tests/core/test_transform.py
- experimental/python/databricks_tests/core/test_transform_to_json.py
- experimental/python/databricks_tests/core/test_transform_variable.py
- experimental/python/databricks_tests/core/test_variable.py
- experimental/python/databricks_tests/fixtures/dummy_module.py
- experimental/python/databricks_tests/fixtures/error_module.py
- experimental/python/databricks_tests/test_build.py
Add databricks.bundles.core package to experimental/python.
It contains an implementation of resource-independent code for Python support. As a follow-up, we will add Python code generated using bundle schema.
Unit tests
> [Python] Add databricks.bundles.core

- experimental/python/databricks/bundles/core/_resource_mutator.py
Clarify the behavior of Python mutators.
> [Python] Clarify mutators behaviour

- experimental/python/databricks/bundles/core/_transform.py
- libs/dyn/dynvar/ref.go
Reformat variable regex in Python code to follow Golang. The effective regex is not changed.
We need to keep both regexes in sync.
Using existing tests and manually inspecting resulting regex.
> [Python] Reformat variable regex

- acceptance/acceptance_test.go
If set, all skip directives are ignored.
It is useful to run test on OS / Cloud where it is not normally enabled without having to edit test.toml
> acc: add -forcerun flag

- experimental/python/databricks/bundles/core/_resource_mutator.py
Clarify rationale for design of `@job_mutator`
> [Python] Clarify rationale for mutator design

- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/pyproject.toml
- libs/template/templates/experimental-jobs-as-code/template/{{.project_name}}/pyproject.toml.tmpl
Upgrade databricks-bundles to 0.7.2
It fixes problems with bundles using more than one resource loader or mutator.
> Upgrade databricks-bundles to 0.7.2

- acceptance/acceptance_test.go
- acceptance/internal/cmd_server.go
- acceptance/internal/config.go
- acceptance/internal/server.go
Move acceptance/*_test.go to acceptance/internal (except for acceptance_test.go).
Some of this code needs its own tests, having it in package supports the separation between "acceptance tests" and "acceptance test runner tests".
> acc: Create acceptance/internal package

- acceptance/bundle/deployment/bind/experiment/test.toml
1. Enable local mode and write the server mocks
Acceptance tests that can run locally can indicate a breaking change without waiting for a cloud run
Ran the `bundle/deployment/bind/experiment` acceptance test locally
> Enable bind/experiment acceptance test to run locally

- .goreleaser.yaml
This warning surfaced in recent builds where GoReleaser >= v2.6 was used.
https://goreleaser.com/deprecations/#archivesformat
See the "Run GoReleaser" step in this job: https://github.com/databricks/cli/actions/runs/13680013259/job/38249650135
Local run of GoReleaser no longer emits the warning.
> Fix GoReleaser deprecation warning

- experimental/python/databricks/bundles/build.py
- experimental/python/databricks_tests/test_build.py
Fix issues with multiple resource loaders. 
Previously, we discarded outputs of all loaders except the last one. That worked well if there is only a single resource loader.
- Unit tests
- Acceptance tests in https://github.com/databricks/cli/pull/2493
> [Python] Fix issues with multiple resource loaders

- acceptance/bundle/integration_whl/test.toml
When this tests were integration tests, they did not do run() part in -short mode.
After converting them to acceptance I kept them on always in #2471
This PR disables them in short mode (they will still run on main) because it seems they do expand PR integration test time.
> Disable integration_whl tests on PRs

- NEXT_CHANGELOG.md
- acceptance/cmd/workspace/query-history/output.txt
- acceptance/cmd/workspace/query-history/script
- acceptance/cmd/workspace/query-history/test.toml
- acceptance/cmd/workspace/test.toml
- cmd/workspace/query-history/overrides.go
Fixed `Error: template: command:1:8: executing "command" at <.>: range can't iterate over` for query-history list command
`query-history list` command has an override to use a different output template for list command. This template got outdated comparing to underlying API response structure and hence led to the error above.
it was found by automatically generated tests here: https://github.com/databricks/cli/pull/2501
> Fixed `query-history list` command

- .goreleaser.yaml
Builds on #2513 to support multiple archive formats.
See #2351 and #1296.
Instead of producing tarballs only for a subset of operating systems, I figured we should produce them for every operating system/architecture combination to avoid unnecessary conditionals when writing platform-independent installers (for example, the `setup-cli` installer scripts).
I manually confirmed that GoReleaser now produces both ZIP files and tarballs:
```
% ls -1 dist/*.{zip,tar.gz}                      
dist/databricks_cli_darwin_amd64.tar.gz
dist/databricks_cli_darwin_amd64.zip
dist/databricks_cli_darwin_arm64.tar.gz
dist/databricks_cli_darwin_arm64.zip
dist/databricks_cli_linux_amd64.tar.gz
dist/databricks_cli_linux_amd64.zip
dist/databricks_cli_linux_arm64.tar.gz
dist/databricks_cli_linux_arm64.zip …
```
> Include tarballs in releases

- libs/patchwheel/parse.go
- libs/patchwheel/parse_test.go
This is a minor change but makes it easier to use, no need to remember doing this on the caller side.
Relying on this in #2520
Follow up to #2427
> Fix patchwheel.ParseWheelFilename to extract basename

- NEXT_CHANGELOG.md
- bundle/libraries/local_path.go
- bundle/libraries/local_path_test.go
Support all version identifiers as per PEP440 in environment deps
Some customers define their libraries dependencies like below and this should be supported by DABs
```
dependencies:
- my_package==1.2.3.dev1
```
Added unit test to cover all the cases
> Support all version identifiers as per PEP440 in environment deps

- acceptance/acceptance_test.go
- acceptance/bundle/apps/app_yaml/script
- acceptance/bundle/apps/config_section/script
- acceptance/bundle/state/script
- acceptance/telemetry/success/out.requests.txt
- acceptance/telemetry/success/output.txt
- acceptance/telemetry/success/script
- acceptance/telemetry/success/test.toml
Modifies the telemetry acceptance test to assert that the same value of `cmd-exec-id` is used in both the user agent and the telemetry payload.
To facilitate this, this PR also requires the acceptance testing framework to write the request logs to disk without applying the replacements.
Asserting a consistent value of `cmd-exec-id` is an important correctness check because this is what we will use to get a completeness signal for our telemetry tables.
N/A
> Assert command exec id is correctly set

- .github/workflows/release.yml
Update homebrew tap step to distinguish hashes for zip and tar.gz
Homebrew tap release PRs are currently failing because they incorrectly use checksum hashes for tar.gz archives instead of zip
> Update homebrew tap step to distinguish hashes for zip and tar.gz

- acceptance/bundle/artifacts/build_and_files_whl/databricks.yml
- acceptance/bundle/artifacts/build_and_files_whl/output.txt
- acceptance/bundle/artifacts/build_and_files_whl/script
- acceptance/bundle/artifacts/build_and_files_whl/test.toml
This test highlights inconsistency between type:whl and non-whl artifacts.
The test for non-whl artifacts exists [here](https://github.com/databricks/cli/tree/main/acceptance/bundle/artifacts/build_and_files) added in https://github.com/databricks/cli/pull/2526
> Add acc test for case where both 'build' and 'files' are specified

- acceptance/acceptance_test.go
Same reason as for https://github.com/databricks/cli/pull/2380
This makes $UNIQUE_NAME usable in PyPI distribution names, which are lowercased: https://github.com/pypa/setuptools/pull/4766
> acc: lower case UNIQUE_NAME

- libs/daemon/daemon_test.go
This unit test is inherently flaky and will fail if the gap between process scheduling exceeds 10 seconds. I am hypothesizing that is what happened in the failure here (or some equivalent issue, the exact cause does not matter):
https://github.com/databricks/cli/actions/runs/13957485937/job/39072078260
Since we do not use the daemon package anywhere, let's disable this unit test for now.
> Disable unit test in daemon package

- NEXT_CHANGELOG.md
- acceptance/acceptance_test.go
- acceptance/bundle/deployment/bind/volume/databricks.yml
- acceptance/bundle/deployment/bind/volume/databricks.yml.tmpl
- acceptance/bundle/deployment/bind/volume/output.txt
- acceptance/bundle/deployment/bind/volume/script
- acceptance/bundle/deployment/bind/volume/test.toml
- bundle/config/resources.go
- bundle/config/resources/volume.go
- bundle/config/resources/volume_test.go
1. Changed `FindResourceByConfigKey` to return volume resources
2. Implemented `Exists` method on Volume resource
This PR adds support for volume resources in deployment operations, enabling users to:
- Bind experiments using `databricks bundle deployment bind <myvolume_key> <myvolume_full_name>`
- Unbind experiments using `databricks bundle deployment unbind <myvolume_key>`
Where:
- `myvolume_key` is a resource key defined in the bundle's .yml file
- `myvolume_full_name` references an existing volume in the Databricks workspace using its fully qualified (3-level) name
These capabilities allow for more flexible resource management of volumes within bundles.
Added a new acceptance test that tests bind and unbind methods together with bundle deployment and destruction.
> Add support for volumes in deployment bind/unbind commands

- bundle/config/resources.go
1. Rename a local variable `resources` that collided with an imported package of the same name 
2. Changed doc comments for several methods to match the doc style of other methods
More idiomatic source code is easier to read and comprehend
Existing unit and integration tests are part of CI/CD checks
> Minor refactoring of resources.go: rename a variable that collides with an imported package name; improve doc comments

- .git-blame-ignore-revs
To avoid polluting the git blame because of this package rename.
Prompted by: https://github.com/databricks/cli/pull/2462
N/A
> Ignore command -> cmdctx rename in git blame

- acceptance/acceptance_test.go
- acceptance/internal/config.go
- acceptance/telemetry/timeout/test.toml
Use `time.Duration` for the testserver delay. It conveniently zero-initializes, so by default, there is no delay.
The TOML library natively supports `time.Duration`, so we should use it.
> acc: Use time.Duration to configure testserver delay

- NEXT_CHANGELOG.md
- acceptance/acceptance_test.go
- acceptance/bundle/deployment/bind/dashboard/databricks.yml
- acceptance/bundle/deployment/bind/dashboard/databricks.yml.tmpl
- acceptance/bundle/deployment/bind/dashboard/output.txt
- acceptance/bundle/deployment/bind/dashboard/recreation/databricks.yml.tmpl
- acceptance/bundle/deployment/bind/dashboard/recreation/output.txt
- acceptance/bundle/deployment/bind/dashboard/recreation/sample-dashboard.lvdash.json
- acceptance/bundle/deployment/bind/dashboard/recreation/script
- acceptance/bundle/deployment/bind/dashboard/sample-dashboard.lvdash.json
- acceptance/bundle/deployment/bind/dashboard/script
- acceptance/bundle/deployment/bind/dashboard/test.toml
- acceptance/internal/config.go
- bundle/config/resources.go
- bundle/phases/deploy.go
1. Changed `FindResourceByConfigKey` to return dashboard resources
2. Changed deploy phase to detect dashboard recreation and request user's approval before deploying
This PR adds support for dashboard resources in deployment operations, enabling users to:
- Bind experiments using `databricks bundle deployment bind <mydashboard_key> <mydashboard_id>`
- Unbind experiments using `databricks bundle deployment unbind <mydashboard_key>`
Where:
- `mydashboard_key` is a resource key defined in the bundle's .yml file
- `mydashboard_id` references an existing dashboard in the Databricks workspace
These capabilities allow for more flexible resource management of dashboards within bundles.
Added two new acceptance tests that tests bind and unbind methods together with bundle deployment and …
> Add support for dashboards in deployment bind/unbind commands

- acceptance/bundle/templates/telemetry/custom-template/output.txt
- acceptance/bundle/templates/telemetry/custom-template/script
- acceptance/bundle/templates/telemetry/dbt-sql/output.txt
- acceptance/bundle/templates/telemetry/dbt-sql/script
- acceptance/bundle/templates/telemetry/default-python/output.txt
- acceptance/bundle/templates/telemetry/default-python/script
- acceptance/bundle/templates/telemetry/default-sql/output.txt
- acceptance/bundle/templates/telemetry/default-sql/script
- acceptance/bundle/templates/telemetry/test.toml
- acceptance/telemetry/failure/output.txt
- acceptance/telemetry/failure/script
- acceptance/telemetry/partial-success/output.txt
- acceptance/telemetry/partial-success/script
- acceptance/telemetry/success/output.txt
- acceptance/telemetry/success/script
- acceptance/telemetry/test.toml
- acceptance/telemetry/timeout/output.txt
- acceptance/telemetry/timeout/script
Before the telemetry payload was a single line of encoded JSON in `out.requests.txt.  This can be hard to review and catch regressions in.
After, the JSON payload is filtered and pretty printed in `output.txt` which will be a lot easier to review.
N/A
> Pretty print telemetry payload in acceptance tests

- NEXT_CHANGELOG.md
- acceptance/bundle/deployment/bind/registered-model/databricks.yml.tmpl
- acceptance/bundle/deployment/bind/registered-model/output.txt
- acceptance/bundle/deployment/bind/registered-model/script
- acceptance/bundle/deployment/bind/registered-model/test.toml
- bundle/config/resources.go
1. Changed `FindResourceByConfigKey` to return registered models resources
This PR adds support for registered models in deployment operations, enabling users to:
- Bind experiments using `databricks bundle deployment bind <mymodel_key> <mymodel_full_name>`
- Unbind experiments using `databricks bundle deployment unbind <mymodel_key>`
Where:
- `mymodel_key` is a resource key defined in the bundle's .yml file
- `mymodel_full_name` references an existing model in the Unity Catalog using its fully qualified (3-level) name
These capabilities allow for more flexible resource management of registered models within bundles.
Added a new acceptance test that tests bind and unbind methods together with bundle deployment and destruction.
> Add support for registered models in deployment bind/unbind commands

- acceptance/acceptance_test.go
- acceptance/bundle/python/mutator-ordering/output.txt
- acceptance/bundle/python/mutator-ordering/script
- acceptance/bundle/python/resolve-variable/output.txt
- acceptance/bundle/python/resolve-variable/script
- acceptance/bundle/python/resource-loading/output.txt
- acceptance/bundle/python/resource-loading/script
- acceptance/bundle/python/test.toml
- experimental/python/LICENSE
- experimental/python/pyproject.toml
- experimental/python/uv.lock
Run acceptance tests against the latest snapshot. We add matrix tests, including both the latest snapshot and the latest release, so we don't break compatibility.
We prebuild a wheel with the latest code and reuse it across acceptance tests. The approach of installing from the source directory doesn't work:
1. uv doesn't have a build tool, so it takes 10 seconds for setuptools
2. we can't reuse the same directory and cache, because setuptools can't be used concurrently
> [Python] Run acceptance tests against the latest snapshot

- acceptance/acceptance_test.go
- acceptance/internal/config.go
Disable/enable tests based for specific clouds. Sometimes we need to break tests by cloud due to difference in the output, like we have in https://github.com/databricks/cli/pull/2532 with GCP/servicePrincipal issue.
> acc: Add CloudEnvs setting

- cmd/selftest/patchwhl.go
- libs/patchwheel/patch.go
- libs/patchwheel/patch_test.go
- Do not pass ctx parameter to PatchWheel; it no longer does any logs
- Return isBuilt flag from PatchWheel
While working on #2520 I realized that it's better to have logging in one place & style,
thus caller should control how the log message looks like.
> Remove ctx argument to PatchWheel

- acceptance/bundle/integration_whl/serverless/test.toml
It was passing for the whole week since it was added in https://github.com/databricks/cli/pull/2519 but started failing on the recent commits, so it does not exhibit consistent behaviour without wheel patching.
Note, that we do have integration_whl/serverless_dynamic_version which tests the same but with wheel patching #2520
> acc: Disable integration_whl/serverless

- bundle/config/resources_test.go
Add new unit test TestResourcesBindSupport to detect that all resources meet preconditions for binding support
When a new resource is added, this unit test will fail if the resource does not properly support `FindResourceByConfigKey` and `Exists` methods. The author of a new resource would need to change these methods to add the new resource, or explicitly set this resource as unbindable in this unit test.
New unit test is passing
> Introduce new unit test for bindable resources

- acceptance/bundle/templates/telemetry/custom-template/script
- acceptance/bundle/templates/telemetry/dbt-sql/script
- acceptance/bundle/templates/telemetry/default-python/script
- acceptance/bundle/templates/telemetry/default-sql/script
Caught in https://github.com/databricks/cli/pull/2554. When `-o pipefail` is set in bash, a SIGPIPE is triggered in linux systems if downstream applications exit while upstream applications in a pipeline are still outputting logs.
head can exit early if the command has determined that reading more from stdin will not change its output. Those cases will cause a SIGPIPE on linux systems. 
Because by default bash returns the exit code of the last command in a pipeline. `pipefail` makes bash return the exit code of the first failing command instead. That's a nice global property to have.
For more details about the gotchas you can read: https://mywiki.wooledge.org/BashPitfalls#pipefail
N/A
> Disable pipefail in bundle init acceptance tests

- .github/workflows/push.yml
- .golangci.yaml
- NEXT_CHANGELOG.md
1. Bump golangci-lint version to v2.0.2 from v1.63.4
2. Migrate the configuration file to v2 format
3. Disable certain lint checks that were disabled in v1, but are enabled by default now
[golangci-lint v2](https://golangci-lint.run/product/changelog/#v200) is a major update that provides multiple enhancements, new linter and new features support  and bug fixes
Existing `make lintcheck` is passing
> Update golangci-lint to v2

- acceptance/acceptance_test.go
Main use case for `-update` run is to write new outputs. It's faster and safer (no concurrent writes to the same directory) to only run single test case from the matrix.
Manually running -update.
> acc: If -update is passed, only run single test from each EnvMatrix

- Makefile
> Fix 'make fmt' after upgrading golangci-lint to v2

- acceptance/bundle/templates/default-python/integration_classic/output.txt
- acceptance/bundle/templates/default-python/integration_classic/script
- acceptance/bundle/templates/default-python/integration_classic/test.toml
This failure is caused by 6 digit timestamp being converted to 5 digit if there is a leading zero:
```
>>> [CLI] bundle deploy -t dev
Building python_artifact...
-Uploading dist/project_name_[UNIQUE_NAME]-0.0.1+[NUMBER].[NUMBER]-py3-none-any.whl...
+Uploading dist/project_name_[UNIQUE_NAME]-0.0.1+[NUMBER].63807-py3-none-any.whl...
Uploading bundle files to /Workspace/Users/[USERNAME]/.bundle/project_name_[UNIQUE_NAME]/dev/files...
Deploying resources...
Updating deployment state...
```
Also fix Python selection variable: it's not UV_VERSION, it's UV_PYTHON.
> acc: Fix default-python integration test

- libs/appproxy/appproxy_test.go
Fixed TestProxyHandleWebSocket flakiness
Websocket ReadMessage on a closed host might fail with different error messages depending on when host is closed. The actual message does not really matter as long as it's one of the expected error messages
Existing test is not flaky anymore
> Fixed TestProxyHandleWebSocket flakiness

- NEXT_CHANGELOG.md
Forgot to include this when merging https://github.com/databricks/cli/pull/2591. This change calls out the fix in the changelog.
> Include databricks api usage text fix in changelog

- bundle/config/mutator/paths/app_paths_visitor.go
- bundle/config/mutator/paths/app_paths_visitor_test.go
- bundle/config/mutator/paths/artifact_paths_visitor.go
- bundle/config/mutator/paths/artifact_paths_visitor_test.go
- bundle/config/mutator/paths/dashboard_paths_visitor.go
- bundle/config/mutator/paths/dashboard_paths_visitor_test.go
- bundle/config/mutator/paths/job_paths_visitor.go
- bundle/config/mutator/paths/job_paths_visitor_test.go
- bundle/config/mutator/paths/pipeline_paths_visitor.go
- bundle/config/mutator/paths/pipeline_paths_visitor_test.go
- bundle/config/mutator/paths/translation_mode.go
- bundle/config/mutator/paths/visitor.go
- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/translate_paths.go
- bundle/config/mutator/translate_paths_apps.go
- bundle/config/mutator/translate_paths_artifacts.go
- bundle/config/mutator/translate_paths_dashboards.go
- bundle/config/mutator/translate_paths_jobs.go
- bundle/config/mutator/translate_paths_pipelines.go
Extract relative path visitors so we can implement path normalization using them.
Replace `PathKind` with `TranslateMode` because there is no difference in how we use them.
By splitting the logic that visits all fields that contain a path from the code that performs the path translation, it becomes possible to make this a 2-pass operation.
In the first pass, we make all paths relative to the bundle root (incorporating their location). This can happen as early as possible. Then, in the second pass, we know that all relative paths have already been normalized to be relative to the bundle root, and we can perform path translation without relying on the location information.
Added unit tests in addition to the existing coverage
> Extract relative path visitors

- acceptance/bin/extract_command_exec_id.py
- acceptance/bundle/telemetry/deploy-no-uuid/script
- acceptance/bundle/telemetry/deploy/script
- acceptance/bundle/templates/telemetry/custom-template/script
- acceptance/bundle/templates/telemetry/dbt-sql/script
- acceptance/bundle/templates/telemetry/default-python/script
- acceptance/bundle/templates/telemetry/default-sql/script
The previous approach of using a pipeline was flaky on windows. Unix tools have slightly different semantics on different operating systems so it's hard to use and maintain them for acceptance tests.
That's why this PR switches to using a python script to extract the command exec id.
Existing tests pass.
> Use python script to extract command exec id

- acceptance/bundle/debug/out.stderr.txt
- bundle/config/mutator/resolve_variable_references.go
- bundle/config/mutator/resolve_variable_references_test.go
- bundle/config/mutator/translate_paths_test.go
- bundle/phases/build.go
- bundle/phases/initialize.go
- bundle/tests/apps_test.go
- bundle/tests/interpolation_test.go
- cmd/bundle/destroy.go
- libs/dyn/merge/select.go
- libs/dyn/merge/select_test.go
Separate variable resolution for "resources" from the rest of the configuration.
It allows keeping a part of the bundle with unresolved variables and resolving them as a separate stage.
Using existing tests
> Separate variable resolution for resources

- acceptance/bundle/telemetry/deploy/script
We no longer needed to disable pipefail following https://github.com/databricks/cli/pull/2602 but I missed removing this comment. Just a minor cleanup.
> Cleanup SIGPIPE comment in acceptance test

- libs/testserver/fake_workspace.go
Addresses a comment from #2465
Existing tests
> minor refactoring: use path.Dir when splitting a file path into parts in fake_workspace.go

- .github/workflows/push.yml
- Makefile
Also use 'make ws' in github action.
Follow up to #2603
> Include whitespace check in 'make' and 'make ws'

- acceptance/acceptance_test.go
- libs/testserver/server.go
- New option to acceptance test runner: -logrequests. When specified request + responses from testserver are logged.
- Debugging the test server & CLI interaction.
Manually: `go test .. -run ^TestAccept$/^selftest$ -v -logrequests`
```
acceptance_test.go:409: 200 GET /api/2.0/preview/scim/v2/Me
> User-Agent: curl/8.7.1
> Accept: */*
```
> acc: add -logrequests option

- acceptance/acceptance_test.go
Addresses a [comment](https://github.com/databricks/cli/pull/2516#discussion_r2011934945) from #2516:
this change eliminates an unnecessary second call to `os.Getenv` when the initial check has already confirmed the variable is empty
Existing tests
> minor clean up: remove always-empty variables from log lines in acceptance_test.go

- libs/template/renderer_test.go
Fails on CI with:
```
Building python_artifact...
renderer_test.go:103:
Error Trace:	D:/a/cli/cli/libs/template/renderer_test.go:103
D:/a/cli/cli/libs/template/renderer_test.go:151
Error:      	Received unexpected error:
build failed python_artifact, error: exit status 1, output: C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing '0.0.1+20250403.095813' to '0.0.1+20250403.95813'
warnings.warn(tmpl.format(**locals()))
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
Test:       	TestBuiltinPythonTemplateValid
```
> Disable build in TestBuiltinPythonTemplateIsValid

- libs/template/renderer_test.go
This reverts commit 9e43332079000b8b2bc20155b17874404b017cd1.
Broken version of `wheel` package was released which caused the initial problem, package is yanked so we can bring back the test
https://pypi.org/project/wheel/0.46.0/
> Revert "Disable build in TestBuiltinPythonTemplateIsValid (#2641)"

- acceptance/bundle/apps/test.toml
- acceptance/bundle/artifacts/test.toml
- acceptance/bundle/debug/test.toml
- acceptance/bundle/deploy/experimental-python/test.toml
- acceptance/bundle/deploy/python-notebook/test.toml
- acceptance/bundle/generate/git_job/test.toml
- acceptance/bundle/help/test.toml
- acceptance/bundle/override/test.toml
- acceptance/bundle/python/test.toml
- acceptance/bundle/state/test.toml
- acceptance/bundle/telemetry/test.toml
- acceptance/bundle/templates-machinery/test.toml
- acceptance/bundle/templates/test.toml
- acceptance/bundle/test.toml
- acceptance/bundle/trampoline/warning_message_with_new_spark/test.toml
- acceptance/bundle/trampoline/warning_message_with_old_spark/test.toml
- acceptance/bundle/validate/sync_patterns/test.toml
- acceptance/bundle/variables/test.toml
Setting to true by default goes against regular default and is not what most subdirectories need.
This makes bundle tests similar to other acceptance tests wrt to Cloud setting: if you want to run on cloud, you set it to true explicitly.
> acc: Fix default Cloud setting in bundle/

- NEXT_CHANGELOG.md
- acceptance/bundle/help/bundle-sync/output.txt
- acceptance/bundle/sync/databricks.yml
- acceptance/bundle/sync/output.txt
- acceptance/bundle/sync/sample-dashboard.lvdash.json
- acceptance/bundle/sync/script
- acceptance/cmd/sync/output.txt
- acceptance/cmd/sync/script
- cmd/bundle/sync.go
- cmd/sync/sync.go
This allows users to specify file patterns to include / exclude from syncs using respective flags in sync and bundle sync commands:
* `$ databricks sync <SRC> <DEST> --exclude "*.bak" --include "node_modules/mylib"`
* `$ databricks bundle sync --exclude "*.bak" --include "node_modules/mylib"`
[gitignore syntax](https://git-scm.com/docs/gitignore) for advanced pattern matching is supported.
Note that in the current implementation excludes always takes higher priority over includes. The order in which the flags are provided in the prompt does not change this behavior. To overcome this behavior users can provide an `--include` flag with a negated pattern (prefixed by a `!`) instead of using an `--exclude` flag in the combinations of patterns.
Manual testing + introduced new acceptance tests
> Add include/exclude flags to sync and bundle-sync commands

- acceptance/acceptance_test.go
This helps when having a custom executable script in the test dir.
> acc: When copying files, include permissions

- .github/workflows/start-integration-tests.yml
- tools/start_integration_tests.py
- New script to start integration tests for PRs that were approved by team members.
- New workflow to run this script every 10 minutes.
When dependabot posts many PR you need to start the integration tests. If rebased, the results are lost and you need to do that again. This script automates starting these tests.
Manually.
> Add tools/start_integration_tests.py + periodic workflow

- NEXT_CHANGELOG.md
- cmd/bundle/generate/app.go
The --config-dir and --source-dir for "bundle generate app" no longer join value with bundle root. 
Related: #1928
This arguments should be interpreted relative to CWD, as is the case for all other generate commands.
> Fix "generate app" to interpret args relative to cwd

- .github/workflows/start-integration-tests.yml
> Fix start-integration-tests to start script without +x permissions

- acceptance/bundle/telemetry/deploy-whl-artifacts/script
Otherwise it requires system Python to have setuptools.
> acc: Use uv in deploy-whl-artifacts test

- .github/workflows/start-integration-tests.yml
Partially reverts #2688
With those settings at least getting the token worked.
The job current fails at Generate GitHub App Token stage with:
https://github.com/databricks/cli/actions/runs/14375161919/job/40305746689
```
message: 'Although you appear to have the correct authorization credentials, the `***` organization has an IP allow list enabled, and your IP address is not permitted to access this resource.',
documentation_url: 'https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app',
status: '403'
```
The previous settings that this PR restores it was able to generate the token and failed when running the script:
https://github.com/databricks/cli/actions/runs/14356228123/job/40246162712
```
Run python3 ./start_integration_tests.py -R ***/*** …
```
> Stop start-integration-tests and revert runner change

- experimental/python/README.md
Add a minimal README that will be used for the PyPi package.
We need to give the PyPi package README in case it gets discovered before CLI.
> [Python] Add README

- NEXT_CHANGELOG.md
- acceptance/bundle/trampoline/warning_message/output.txt
- acceptance/bundle/trampoline/warning_message_with_old_spark/output.txt
- bundle/trampoline/python_dbr_warning.go
- bundle/trampoline/python_dbr_warning_test.go
Do not exit early when checking incompatible tasks
This allows us to find all tasks with local libraries and old DBR versions setup and not only the first one.
Existing tests pass
> Do not exit early when checking incompatible tasks

- NEXT_CHANGELOG.md
- acceptance/bundle/help/bundle-sync/output.txt
- acceptance/bundle/sync/databricks.yml
- acceptance/bundle/sync/output.txt
- acceptance/bundle/sync/script
- cmd/bundle/sync.go
Recently introduced (#2650) `--include` and `--exclude` flag in `bundle sync` command duplicate the existing functionality of files inclusion and exclusion [via settings in .yml file](https://docs.databricks.com/aws/en/dev-tools/bundles/settings#include-and-exclude). This change removes the ability to supply include/exclude patterns via CLI flags which removes the confusion before the two methods
Updated existing tests
> Remove include/exclude flags support from bundle sync command

- .github/workflows/release.yml
Add release workflow to publish `databricks-bundles` PyPi package
Should be merged after https://github.com/databricks/cli/pull/2676
It publishes PyPi package that is co-versioned with CLI
> [Python] Add release workflow

- NEXT_CHANGELOG.md
- acceptance/bundle/deploy/fail-on-active-runs/databricks.yml
- acceptance/bundle/deploy/fail-on-active-runs/my_notebook.py
- acceptance/bundle/deploy/fail-on-active-runs/output.txt
- acceptance/bundle/deploy/fail-on-active-runs/script
- acceptance/bundle/deploy/fail-on-active-runs/test.toml
- bundle/phases/deploy.go
Check for running resources with `--fail-on-active-runs` before any mutative operation during deploy
Fixes #2671 
We should check for running resources and fail if there are any earlier before any mutative operations such as artifacts folder clean up happens
> Check for running resources with `--fail-on-active-runs` before any mutative operation during deploy

- libs/dyn/convert/from_typed.go
- libs/dyn/convert/normalize.go
- libs/dyn/convert/normalize_test.go
- libs/dyn/jsonloader/json.go
- libs/dyn/jsonsaver/marshal_test.go
- libs/dyn/mapping.go
- libs/dyn/mapping_test.go
- libs/dyn/merge/merge.go
- libs/dyn/merge/override.go
- libs/dyn/merge/override_test.go
- libs/dyn/merge/select.go
- libs/dyn/pattern.go
- libs/dyn/visit.go
- libs/dyn/visit_map.go
- libs/dyn/visit_set.go
- libs/dyn/walk.go
- libs/dyn/yamlloader/loader.go
- libs/dyn/yamlsaver/utils.go
- Add Mapping.SetLoc(string, []Location, Value), which is a replacement for Set() that does not return an error and only accepts string keys.
- Migrate all code to use this function.
The original function returned an error if key was holding value of wrong type but the error was never checked. The new function does not return an error.
This interface embraces string key rather than pretending that all types are supported. 
Note, in some cases this increases number of MustString() calls in the code, however, this 
- only happens where there already is MustString()
- is temporary - once we add a function to iterate over string keys rather than values or pairs, it won't be necessary.
> dyn: replace Mapping.Set with Mapping.SetLoc

- .codegen.json
Update `experimental/python/README.md` during tagging to reference the latest version of CLI.
README is used as the package description on PyPi. We highlight that versions of the CLI and PyPi package have to be in sync.
Not tested
> [Python] Update README.md during tagging

- .codegen.json
- .github/workflows/tagging.yml
- experimental/python/uv.lock
Update `uv.lock` during tagging and fix `uv.lock` broken during the previous release.
Previously, we used the genkit version substitution mechanism, which didn't work because it replaced all versions in the UV lock file, and we reverted it in https://github.com/databricks/cli/pull/2731
Having an outdated `uv.lock` breaks Python builds after release.
Not tested
> [Python] Update uv.lock during tagging

- acceptance/bundle/variables/env_overrides/output.txt
- bundle/config/mutator/select_target.go
- bundle/config/root.go
Add prefixes with context for errors in target override.
Saw an error that looks like
```
Error: invalid path '.'
```
The error was caused by some other breaking changes, so I don't have a test, but still, if users ever see that it's not very helpful (e.g. path does not refer to file system but it is related to dyn.Value).
> Improve error when target override fails

- acceptance/acceptance_test.go
Automatically clean up old wheels instead of aborting the tests.
Manually:
```
~/work/cli-main/acceptance/build/darwin_arm64 % cp -r databricks_bundles-0.249.0-py3-none-any.whl databricks_bundles-0.255.0-py3-none-any.whl
~/work/cli-main/acceptance/selftest/basic % testme -v
+ go test ../.. -run ^TestAccept$/^selftest$/^basic$ -v
=== RUN   TestAccept
...
acceptance_test.go:879: Cleaning up /Users/denis.bilenko/work/cli-main/acceptance/build/darwin_arm64/databricks_bundles-0.249.0-py3-none-any.whl
acceptance_test.go:741: [uv build --no-cache -q --wheel --out-dir /Users/denis.bilenko/work/cli-main/acceptance/build/darwin_arm64] took 408.369459ms
acceptance_test.go:879: Cleaning up /Users/denis.bilenko/work/cli-main/acceptance/build/darwin_arm64/databricks_bundles-0.255.0-py3-none-any.whl
```
> acc: auto clean up old wheels

- NEXT_CHANGELOG.md
- experimental/python/databricks/bundles/core/_load.py
- experimental/python/databricks/bundles/core/_location.py
- experimental/python/databricks_tests/core/test_load.py
- experimental/python/databricks_tests/core/test_location.py
Fix `load_resources_from_current_package_module` to produce 1-based column offsets instead of 0-based.
Enforce that all locations have 1-based column and line numbers, and clearly document their semantics.
VSCode fails to display resources declared in Python code:
> Illegal argument: character must be non-negative
The problem didn't affect resources added through `Resources.add_job` and `Resources.add_pipeline` because these methods implement 1-based indexing.
Unit tests
> [Python] Fix "Bundle resource explorer" in VSCode

- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/test.toml
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- bundle/config/mutator/normalize_paths.go
Add missing nil checks in normalize_paths.go
Tests added previously in #2771 and #2774
> Fix nil crash when job has no fields defined

- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- bundle/config/mutator/resourcemutator/apply_presets.go
Modify ApplyPresets to never return errors and instead create necessary inner struct (unless full resource is declared as null).
The errors that it returned were not very helpful:
```
Error: dashboard set_to_true s is not defined
```
(If there are some required fields missing, we should have validators specifically for that).
Besides bad error message other issues were:
- Checking embedded pointer is not helpful, that could be empty if only fields on the outside struct are set.
- Checking outer pointer was often omitted, giving a possibility of a crash.
This made ApplyPresets behave different for different resources depending on whether those resources have default. If they have a default (e.g. dashboards), then those defaults would initialize embedded struct and ApplyPresets would work. …
> Make apply_presets.go more resilient and consistent

- .github/workflows/push.yml
- Makefile
- go.mod
- go.sum
That way there is no need to install it separately and it's managed by dependabot.
> Manage gotestsum via tool section in go.mod

- acceptance/bundle/includes/yml_outside_root/output.txt
- acceptance/bundle/integration_whl/script.prepare
- acceptance/bundle/integration_whl/test.toml
- acceptance/bundle/override/job_cluster/output.txt
- acceptance/bundle/override/job_cluster_var/output.txt
- acceptance/bundle/override/job_tasks/output.txt
- acceptance/bundle/paths/git_source_jobs/output.txt
- acceptance/bundle/paths/relative_path_outside_root/output.txt
- acceptance/bundle/python/mutator-ordering/output.txt
- acceptance/bundle/python/resolve-variable/output.txt
- acceptance/bundle/python/resource-loading/output.txt
- acceptance/bundle/templates/default-python/integration_classic/output.txt
- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- acceptance/bundle/validate/presets_name_prefix/output.txt
- acceptance/bundle/variables/complex/out.default.json
- acceptance/bundle/variables/complex/out.dev.json
- acceptance/bundle/variables/complex_multiple_files/output.txt
- acceptance/bundle/variables/prepend-workspace-var/output.txt
- acceptance/bundle/variables/resolve-nonstrings/output.txt
- bundle/config/mutator/resourcemutator/resource_mutator.go
Initialize jobs resources with the defaults that terraform applies (except for num_workers).
This makes those defaults visible for users (bundle validate -o json) and PyDABs.
This makes terraform-removal branch simpler as there is no hidden modification of resources that terraform does on deploy.
num_workers is skipped because it has a conflict with SingleNodeCluster validator. We should find a better place for that (and other validators), somewhere before applying defaults.
> Add defaults on jobs that terraform applies

- acceptance/bundle/override/pipeline_cluster/output.txt
- acceptance/bundle/paths/invalid_pipeline_globs/output.txt
- acceptance/bundle/paths/pipeline_expected_file_got_notebook/output.txt
- acceptance/bundle/paths/pipeline_globs/output.txt
- acceptance/bundle/python/pipelines-support/output.txt
- acceptance/bundle/templates/default-python/integration_classic/out.validate.dev.json
- acceptance/bundle/templates/default-python/integration_classic/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- acceptance/bundle/variables/variable_overrides_in_target/output.txt
- bundle/config/mutator/resourcemutator/resource_mutator.go
Set defaults for pipelines: edition and channel, same as added by terraform.
See https://github.com/databricks/cli/pull/2767
> Add defaults on pipelines that terraform applies

- .github/workflows/push.yml
- We don't use coverage info at the moment but we would like to speed up CI runs on PRs.
- Keep 'push' event unchanged, so that we validate that 'make cover' is still working, as it could get broken otherwise. Related: https://github.com/databricks/cli/pull/2141
> Run tests without coverage on CI

- acceptance/bundle/integration_whl/wrapper/test.toml
- acceptance/bundle/integration_whl/wrapper_custom_params/test.toml
Temporarily disable wheel wrapper acceptance tests on GCP
They are currently failing due to new DBR release, still investigating
> Temporarily disable wheel wrapper acceptance tests on GCP

- acceptance/bundle/debug/out.stderr.txt
- acceptance/bundle/templates/default-python/integration_classic/out.validate.dev.json
- acceptance/bundle/templates/default-python/integration_classic/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/variables/resolve-field-within-complex/output.txt
- bundle/config/mutator/resourcemutator/apply_bundle_permissions.go
- bundle/config/mutator/resourcemutator/resource_mutator.go
- bundle/config/validate/fast_validate.go
- Set default num_workers=0 on jobs
- Move SingleNodeCluster() validator to run before applying defaults, otherwise it complains about num_workers being 0 even though users did not set it.
See https://github.com/databricks/cli/pull/2767 for justification.
Needed for https://github.com/databricks/cli/pull/2791
> Enable 'num_workers: 0' default on jobs

- acceptance/bundle/artifacts/script.prepare
- acceptance/bundle/integration_whl/script.prepare
- acceptance/bundle/templates/default-python/integration_classic/script
- acceptance/test.toml
Tests are run in fresh directory, so don't benefit from caching. No need to filter out `__pycache__` manually everywhere.
> acc: set PYTHONDONTWRITEBYTECODE=1 in all tests

- acceptance/acceptance_test.go
If test detects an unexpected output file, use a heuristic on whether it's useful to print its contents. Note, you can always see the contents by running the test with -output setting, so it's okay to print less there.
In some tests (e.g. experimental-jobs-as-code), where .venv is not ignored but is located inside output folder, this prints a lot of contents, making it hard to read the output.
Manually caused experimental-jobs-as-code to see the effect.
> acc: Avoid printing too many unexpected files

- acceptance/acceptance_test.go
This check originally was added to prevent printing large binary files (e.g. zip files). However, "bundle deploy --debug" can output binary data as well (request and response bodies), causing test failure and not showing the contents, preventing debugging.
> acc: Skip utf-8 check for main output file

- .codegen.json
- experimental/python/databricks/bundles/compute/_models/environment.py
- experimental/python/databricks/bundles/jobs/_models/job.py
- experimental/python/databricks/bundles/jobs/_models/performance_target.py
- experimental/python/databricks/bundles/pipelines/_models/file_library.py
- experimental/python/databricks/bundles/pipelines/_models/ingestion_gateway_pipeline_definition.py
- experimental/python/databricks/bundles/pipelines/_models/notebook_library.py
- experimental/python/databricks/bundles/pipelines/_models/notifications.py
- experimental/python/databricks/bundles/pipelines/_models/pipeline_cluster.py
- experimental/python/databricks/bundles/pipelines/_models/pipeline_cluster_autoscale.py
- experimental/python/databricks/bundles/pipelines/_models/pipeline_cluster_autoscale_mode.py
- experimental/python/databricks/bundles/pipelines/_models/pipeline_library.py
- experimental/python/databricks/bundles/pipelines/_models/report_spec.py
- experimental/python/databricks/bundles/pipelines/_models/schema_spec.py
- experimental/python/databricks/bundles/pipelines/_models/table_spec.py
- experimental/python/databricks/bundles/pipelines/_models/table_specific_config.py
Regenerated Python code after Go SDK upgrade
It should be part of Go SDK upgrade but was not done, also added it to the generate step
> Regenerated Python code after Go SDK upgrade

- acceptance/acceptance_test.go
Currently all tests log a message about running with empty env, this PR removes that:
```
=== NAME  TestAccept/workspace/jobs/create
acceptance_test.go:236: Running test with env []
=== CONT  TestAccept/bundle/telemetry/deploy-mode
acceptance_test.go:236: Running test with env []
=== CONT  TestAccept/bundle/help/bundle-schema
acceptance_test.go:236: Running test with env []
```
> acc: Clean up redundant log message

- acceptance/acceptance_test.go
- acceptance/internal/prepare_server.go
- integration/bundle/apps_test.go
- libs/testdiff/replacement.go
This PR modified the test runner to use the `auth.ProcessEnv` function to compute the environment variables to pass to the test run instead of inheriting all environment variables by default.
Before acceptance, test runs would fail if an authentication method was configured in your environment. Now, they will pass.
> Unset existing auth env vars in acceptance tests

- acceptance/bundle/templates/experimental-jobs-as-code/test.toml
I saw it failing with timeout a few times.
> acc: Raise timeout for jobs-as-code and ignore .venv

- acceptance/internal/cmd_server.go
We need to cleanup existing env vars in the parent CLI process in inprocess mode. Just setting new environment variables is not enough. This was noticed in https://github.com/databricks/cli/pull/2720 and is necessarily for it to work since otherwise we end up with conflicting auth.
Manually, before local tests would fail when non PAT auth was configured in terminal, for example `selftest/server` fails with when OAuth is configured:
```
Error: inner token: Post "[UUID]/oauth2/token": Post "[UUID]/oauth2/token": unsupported protocol scheme ""
```
Now these local tests pass.
> acc: Unset all env vars in inprocess mode

- NEXT_CHANGELOG.md
- go.mod
- go.sum
Upgrade to use Go SDK 0.68.0
It uses the same OpenAPI spec as 0.67.0 so no CLI commands changes
> Upgrade to use Go SDK 0.68.0

- acceptance/acceptance_test.go
- acceptance/internal/handlers.go
- acceptance/internal/prepare_server.go
- libs/testserver/fake_workspace.go
- libs/testserver/server.go
- Make testserver.FakeWorkspace thread-safe.
- Make testserver.Server have granular locking for selecting/creating fake workspace. Otherwise it's unlocked.
- Make acceptance test runner use its own lock for recording requests. This can be reused with proxy implementation (https://github.com/databricks/cli/pull/2720).
This makes use of testserver.Server as safe as it was before but makes handlers run concurrently. Note, although most handlers run quickly, there is Delay option that sleeps in the handler when lock is acquired. With this change, sleep is done when lock is released.
This enables us to refactor acceptance test server to reuse single server rather than create a new listening socket & server per test, which adds more and more overhead as we add more tests.
This also enables more …
> acc: Use granular locking in testserver

- acceptance/bundle/sync/dryrun/output.txt
- acceptance/bundle/sync/dryrun/script
- acceptance/bundle/sync/output.txt
- acceptance/bundle/sync/script
- acceptance/cmd/sync-from-file/output.txt
- acceptance/cmd/sync-from-file/script
- acceptance/cmd/sync/output.txt
- acceptance/cmd/sync/script
- libs/sync/event.go
Addresses [comment](https://github.com/databricks/cli/pull/2657#discussion_r2046683238) in #2657: we want to get rid of non-determinism in output where feasible. Deterministic output of CLI commands improves testing and any possible automation that relies on the CLI.
Existing acceptance tests were modified to not filter out the non-deterministic line
> Sort file names in the "action" line output of sync commands

- .github/workflows/tagging.yml
Point to correct tagging.py in tagging.yml
This file is updated on every genkit update-sdk run and points to tagging.py in root but since we moved it to internal folder we need to keep as is
> Point to correct tagging.py in tagging.yml

- Makefile
- experimental/python/databricks/bundles/jobs/_models/authentication_method.py
- experimental/python/databricks/bundles/jobs/_models/power_bi_model.py
- experimental/python/databricks/bundles/jobs/_models/power_bi_table.py
- experimental/python/databricks/bundles/jobs/_models/power_bi_task.py
- experimental/python/databricks/bundles/jobs/_models/storage_mode.py
- experimental/python/databricks/bundles/jobs/_models/task.py
Generated new Python types by running `pushd experimental/python && make codegen`
This PR https://github.com/databricks/cli/pull/2788 introduced new task types but Python types were not generated causing schema checks to fail.
> Generated new Python types

- internal/testutil/helpers.go
We often see repos integration tests fail with object already exists errors. One hypothesis is that the Random string generator is not truly random and pulls from a small seed pool in CI. This PR attempts to fix that hypothetical issue by using UUIDs instead to generate the random string.
Example failure:
```
=== FAIL: integration/cmd/repos TestReposGet (3.83s)
repos_test.go:80: CLOUD_ENV=***
repos_test.go:47: 
Error Trace:	C:/a/eng-dev-ecosystem/eng-dev-ecosystem/ext/cli/integration/cmd/repos/repos_test.go:47
C:/a/eng-dev-ecosystem/eng-dev-ecosystem/ext/cli/integration/cmd/repos/repos_test.go:83
Error:      	Received unexpected error:
a Workspace object at path /Repos/***/empty-repo-integration-pIdzKaCkfhBq already exists. Try a different path for your Repo or rename the existing …
```
> Fix flaky repos integration tests

- acceptance/internal/config.go
Since there are several toml files involved for a given test, it's useful to know which one is it.
> acc: in case of TOML parse errors, print the path

- bundle/run/job.go
We overlooked returning the error itself when starting a job run. This PR fixes that.
> Return error when bundle run fails to start a job

- libs/apps/python.go
Minor UX improvement. Provides users with context for why searching for *.py files failed for them. Prompted by: https://github.com/databricks/cli/pull/2843#pullrequestreview-2832190899
Not tested.
> Return error when glob pattern matching fails for apps

- NEXT_CHANGELOG.md
- acceptance/bundle/environments/dependencies/databricks.yml
- acceptance/bundle/environments/dependencies/output.txt
- acceptance/bundle/environments/dependencies/resources/job.yml
- acceptance/bundle/environments/dependencies/script
- bundle/config/mutator/normalize_paths.go
- bundle/config/mutator/normalize_paths_test.go
Fixed normalising requirements file path in dependencies section
Fixes #2849 
Previously we incorrectly normalised requirements file passed not treating `-r` prefix in such paths.
Instead we should normalise the path after `-r` and then prefix it with `-r` again/
> Fixed normalising requirements file path in dependencies section

- acceptance/bundle/run/inline-script/basic/output.txt
- acceptance/bundle/run/inline-script/basic/script
This PR fixes a typo where the `cat -` command was supposed to be run via the inline script execution functionality but was not.
> Fix stdin test for inline script execution

- acceptance/acceptance_test.go
Acceptance test runner already writes coverage to individual directory per test because there is an error otherwise. However, this is not the case for EnvMatrix-produced tests, which currently share the directory and thus still sometimes trigger this issue.
> acc: fix sporadic errors in 'make cover'

- NEXT_CHANGELOG.md
- acceptance/bundle/python/unicode-support/databricks.yml
- acceptance/bundle/python/unicode-support/output.txt
- acceptance/bundle/python/unicode-support/resources.py
- acceptance/bundle/python/unicode-support/script
- acceptance/bundle/python/unicode-support/test.toml
- experimental/python/databricks/bundles/build.py
- experimental/python/databricks_tests/test_build.py
Fix the Unicode support in the Python mutator. 
By default, `json.dump` escapes non-ASCII characters. We use the `ensure_ascii=False` to preserve the Unicode characters.
Fixes https://github.com/databricks/cli/issues/2859
Acceptance and unit tests
> [Python] Fix unicode support

- libs/exec/shell_execv.go
- libs/exec/shell_execv_test.go
ShellExecv is a variant of the Execv method that also configures a shell to be used before running the command.
We need it for the scripts section in DABs: https://github.com/databricks/cli/pull/2813.
Why:
1. We'll need to perform lexical analysis to figure out where the boundaries for args in the script are. It's better to defer that to a shell.
2. Direct calls to execv do not perform any environment variable interpolation, so we need to go through a shell. This is neat because it provides customers a way to configure inputs to their scripts.
3. Multiline scripts require a shell since, without them, we cannot parse where a command ends.
Note: This uses the same priority order for shells as the `artifacts.build` field, that is bash > sh > powershell.
Unit test. Also acceptance tests in …
> Add ShellExecv method

- acceptance/bundle/run/diagnostics/databricks.yml
- acceptance/bundle/run/diagnostics/output.txt
- acceptance/bundle/run/diagnostics/script
- acceptance/bundle/run/inline-script/no-bundle/output.txt
- acceptance/bundle/run/inline-script/no-separator/output.txt
- cmd/bundle/deploy.go
- cmd/bundle/run.go
`diags.Error()` only returns the`Details` in the diagnostic, and only returns `Summary` if the details are empty. We should render both In `bundle run` to be consistent with `bundle deploy`.
At the same time, this PR also renders all `warnings` and `recommendations` if the user encounters an error. These warnings could have helpful context on what they need to fix in their configuration.
New acceptance test. Existing tests pass.
> Render full diagnostics in `bundle run`

- acceptance/bundle/paths/fallback_metric/output.txt
- acceptance/bundle/telemetry/deploy-artifact-path-type/output.txt
- acceptance/bundle/telemetry/deploy-compute-type/databricks.yml
- acceptance/bundle/telemetry/deploy-compute-type/notebook.py
- acceptance/bundle/telemetry/deploy-compute-type/output.txt
- acceptance/bundle/telemetry/deploy-compute-type/script
- acceptance/bundle/telemetry/deploy-compute-type/test.py
- acceptance/bundle/telemetry/deploy-compute-type/test.toml
- acceptance/bundle/telemetry/deploy-config-file-count/out.telemetry.txt
- acceptance/bundle/telemetry/deploy-mode/output.txt
- acceptance/bundle/telemetry/deploy-no-uuid/out.telemetry.txt
- acceptance/bundle/telemetry/deploy-target-count/output.txt
- acceptance/bundle/telemetry/deploy-variable-count/output.txt
- acceptance/bundle/telemetry/deploy-whl-artifacts/output.txt
- acceptance/bundle/telemetry/deploy/out.telemetry.txt
- bundle/metrics/track_used_compute.go
- bundle/phases/deploy.go
Add metrics for compute type used 
This allows us to track which compute (serverless or classic and which type) is used in bundle tasks.
> Add metrics for compute type used

- NEXT_CHANGELOG.md
- experimental/python/databricks/bundles/core/_transform.py
- experimental/python/databricks_tests/core/test_transform.py
Add support for floats to Python code. Previously, attempting to deserialize a float resulted in an error.
There is only one example of a float. It's in `spot_bid_max_price` in `compute.AzureAttributes`, which was previously unsupported. Implement support for floats with all implications of precision loss.
Fixes https://github.com/databricks/cli/issues/2875
Unit tests and manually
> [Python] Fix missing support for floats

- acceptance/bundle/telemetry/deploy-compute-type/databricks.yml
- acceptance/bundle/telemetry/deploy-compute-type/output.txt
- acceptance/bundle/telemetry/deploy-compute-type/script
Speed up deploy-compute-type telemetry test
It's enough to have 2 targets (instead of 4) with multiple tasks to have the same coverage but we can do 2 times less deployments
Existing tets pass
> acc: Speed up deploy-compute-type telemetry test

- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- bundle/apps/validate.go
- bundle/apps/validate_test.go
Validate that source_code_path for app resources is not empty
`source_code_path` is a required field for apps, so we need to fail the validation if it's not provided.
> Validate that source_code_path for app resources is not empty

- acceptance/bundle/templates/default-python/combinations/check_output.py
- acceptance/bundle/templates/default-python/combinations/input.json.tmpl
- acceptance/bundle/templates/default-python/combinations/output.txt
- acceptance/bundle/templates/default-python/combinations/script
- acceptance/bundle/templates/default-python/combinations/test.toml
This checks all combinations of input parameters against cloud environments.
Relies on https://github.com/databricks/cli/pull/2894 to skip environments + configurations that cannot work together.
> acc: Enable default-python/combinations on cloud

- acceptance/acceptance_test.go
- acceptance/bundle/deploy/mlops-stacks/config.json.tmpl
- acceptance/bundle/deploy/mlops-stacks/output.txt
- acceptance/bundle/deploy/mlops-stacks/script
- acceptance/bundle/deploy/mlops-stacks/test.toml
- integration/bundle/init_test.go
1. Convert TestBundleInitOnMlopsStacks into an acceptance test
2. Make `CLOUD_ENV_BASE` environment variable (with possible values of: "azure", "aws", "gcp") available to the acceptance tests' script
One change in the series of changes for converting integration tests into acceptance tests.
This will allow for easier testing of various backing solutions for bundle deployment
> Convert TestBundleInitOnMlopsStacks into an acceptance test 

- acceptance/internal/handlers.go
- libs/testserver/fake_workspace.go
- libs/testserver/pipelines.go
- Support editing pipelines in testserver.
- Rewrite pipeline code to match best practice in testserver (separate file in libs/testserver and separate block in handlers.go).
Enables new acceptance tests, I'm using this in terraform-removal branch https://github.com/databricks/cli/pull/2926
New edit functionality is tested via https://github.com/databricks/cli/pull/2926
> acc: support pipeline update

- acceptance/acceptance_test.go
- acceptance/selftest/envmatrix/inner/script
- acceptance/selftest/envmatrix/inner/test.toml
Mainly to exclude "yes" and "no" in templates tests that cause messages like this:
`Error: can[SERVERLESS]t create pipeline: The service at /api/2.0/pipelines is taking too long to process your request.`
> acc: Do not auto enable EnvRepl for short strings

- libs/jsonschema/schema.go
- libs/jsonschema/schema_test.go
This method is useful for https://github.com/databricks/cli/pull/2940. It's needed to traverse the bundle schema and retrieve the required fields in the bundle config tree.
Unit test.
> Add GetDefinition to libs/jsonschema

- libs/template/renderer_test.go
This test is redundant (the same functionality is better covered by https://github.com/databricks/cli/tree/5f30b6a212a6f1b81bc0c09b1db9e4bebeb2ef73/acceptance/bundle/templates/default-python/combinations).
The test relies on on system Python, so it might fail depending on your system/virtualenv state.
I'd like the tests not to depend on system python and set up their own env with uv instead: https://github.com/databricks/cli/pull/2783
> Remove TestBuiltinPythonTemplateValid test

- acceptance/bin/read_state.py
- acceptance/bundle/resources/pipelines/output.txt
- acceptance/bundle/resources/pipelines/script
- acceptance/internal/handlers.go
- acceptance/script.prepare
- libs/testserver/pipelines.go
- Update testserver's pipeline/get to match the output of the real server.
- Update resources/pipelines test to test destruction of resources.
- Add 'musterr' helper to better show intent that command must fail.
Using this test in https://github.com/databricks/cli/pull/2926
> make testserver pipelines 404 match real backend

- acceptance/bundle/templates/default-python/integration_classic/output.txt
- bundle/config/artifact.go
No need for those empty strings to show up in the output.
> Artifact: add omitempty on "patched" and "remote_path"

- acceptance/test.toml
It was added for completeness, not because it is actually used but  it makes certain integration tests flaky:
```
FAIL acceptance.TestAccept/bundle/deployment/bind/experiment (18.05s)
-Successfully bound experiment with an id '[NUMID]'. Run 'bundle deploy' to deploy changes to your workspace736
+Successfully bound experiment with an id '[UNIX_TIME_MICROS]'. Run 'bundle deploy' to deploy changes to your workspace
FAIL acceptance.TestAccept/bundle/deploy/mlops-stacks (28.72s)
-  "experiment_id": "[NUMID]",
+  "experiment_id": "[UNIX_TIME_MICROS]",
```
> acc: Disable UNIX_TIME_MICROS replacement

- NEXT_CHANGELOG.md
- libs/auth/arguments.go
- libs/auth/arguments_test.go
It's a common flow for a user to copy the URL of their workspace from the browser to login with the CLI. All that we need to successfully login is the hostname, but the URL contains much more information, such as the path of the page they were on or their workspace ID as a query parameter.
Today, if a user tries to use this URL verbatim with `databricks auth login`, they get an error like `Error: fetching oauth config: fetching OAuth endpoints: databricks OAuth is not supported for this host`.
This PR ensures that the CLI uses the same normalization as the Go SDK config on the provided hostname before starting the OAuth login flow, resolving this error.
This reduces friction for those logging in with the CLI.
Unit tests to verify that such URLs are tolerated.
> Tolerate URLs copied from the browser with `databricks auth login`

- libs/structwalk/util_test.go
- libs/structwalk/walktype.go
- libs/structwalk/walktype_test.go
Walking intermediate nodes is a more general extension of `WalkType` and is useful for required / enum validation codegen.
New unit test and existing unit tests.
> Call visit on intermediate nodes during WalkType

- integration/cmd/secrets/secrets_test.go
Started to fail consistently with
```
FAIL integration/cmd/secrets.TestSecretsPutSecretStringValue (re-run 2) (1201.25s)
secrets_test.go:73:   args: secrets, put-secret, cli-acc-c4ea35e34b52466cbf9a090c431d6a0b, test-key, --string-value, test-value
with-newlines
secrets_test.go:40:
Error Trace:	/home/runner/work/eng-dev-ecosystem/eng-dev-ecosystem/ext/cli/integration/internal/acc/workspace.go:75
Error:      	Received unexpected error:
wait: timed out: Finding instances for new nodes, acquiring more instances if necessary
Messages:   	Unexpected error from EnsureClusterIsRunning for clusterID=***
```
> Disable TestSecretsPutSecret*Value on aws-prod-ucws

- Makefile
Otherwise it does not print names of failing files.
> Run "ruff format" without -q

- NEXT_CHANGELOG.md
- acceptance/bundle/templates/dbt-sql/output/my_dbt_sql/databricks.yml
- acceptance/bundle/templates/default-python/classic/output/my_default_python/databricks.yml
- acceptance/bundle/templates/default-python/serverless/output/my_default_python/databricks.yml
- acceptance/bundle/templates/default-sql/output/my_default_sql/databricks.yml
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/databricks.yml
- acceptance/bundle/templates/telemetry/dbt-sql/out.databricks.yml
- acceptance/bundle/templates/telemetry/default-python/out.databricks.yml
- acceptance/bundle/templates/telemetry/default-sql/out.databricks.yml
- libs/template/templates/dbt-sql/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/default-python/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/default-sql/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/experimental-jobs-as-code/template/{{.project_name}}/databricks.yml.tmpl
- libs/template/templates/lakeflow-pipelines/databricks_template_schema.json
Update default includes to allow pipeline folders under the `resources` folder.
DABs in the Workspace is adding a feature that adds pipeline folders under `resources/`. This change makes sure that projects initialized from templates don't need to be modified in order to includes these pipelines.
> Add `resources/*/*.yml` as default include in templates

- acceptance/acceptance_test.go
Made ./tools/ available for acceptance tests.
Some tools are useful both in project and in tests, for example yamlfmt (https://github.com/databricks/cli/pull/3026) is useful to check templates without materializing them (https://github.com/databricks/cli/pull/3032).
> acc: include tools in PATH

- .codegen/service.go.tmpl
Change Comment to CliComment for Methods.
Currently, Comment returns the summary + description for a method. But for the SDKs, the summary does not make sense, as it is almost the same as the method name. So, we are removing the summary for the comment. But the CLI does not have a method name, so it makes sense to have a summary in the comment. This change will be a no-op for the CLI, as the CliComment outputs the same string as the Current Comment.
Generated CLI no diff.
> Use CliComment for summary + description

- acceptance/bundle/deploy/dashboard/nested-folders/test.toml
- acceptance/bundle/deploy/dashboard/simple/test.toml
- acceptance/bundle/deploy/dashboard/simple_outside_bundle_root/test.toml
- acceptance/bundle/deploy/dashboard/simple_syncroot/test.toml
- acceptance/internal/handlers.go
- libs/testserver/dashboards.go
1. Add DELETE endpoint for lakeview dashboards in test server
1. Remove the mocks for DELETE calls in acceptance tests for dashboards deployment
This is the first in the series of changes for using testserver instead of mocks in acceptance tests for dashboards deployment
#3047
> Add DELETE endpoint for lakeview dashboards in test server

- acceptance/bundle/debug/out.stderr.txt
- bundle/config/mutator/translate_paths.go
This change was suggested in #3006 [comment](https://github.com/databricks/cli/pull/3006#discussion_r2139375127)
This simplifies the translatePaths mutator and adds explicit naming for the translatePathsDashboards, which is visible in debug logs.
Existing acceptance tests for dashboards deployment
> Refactor: extract translatePathsDashboards into a separate mutator

- acceptance/bundle/resources/clusters/run/spark_python_task/test.toml
- acceptance/test.toml
Using it in https://github.com/databricks/cli/pull/3042
> acc: Support milliseconds and tz in default timestamp replacement

- .wsignore
- acceptance/bundle/artifacts/shell/err-bash/databricks.yml
- acceptance/bundle/artifacts/shell/err-bash/out.shell.txt
- acceptance/bundle/artifacts/shell/err-bash/output.txt
- acceptance/bundle/artifacts/shell/err-bash/script
- acceptance/bundle/artifacts/shell/err-sh/databricks.yml
- acceptance/bundle/artifacts/shell/err-sh/out.shell.txt
- acceptance/bundle/artifacts/shell/err-sh/output.txt
- acceptance/bundle/artifacts/shell/err-sh/script
- libs/exec/shell_bash.go
- libs/exec/shell_execv_test.go
- libs/exec/shell_sh.go
This PR fixes a regression introduced in https://github.com/databricks/cli/pull/2896 where we stopped passing the `-e` flag to the shell, which makes both sh and bash bail out at the first command with a non-zero exit code.
Adding back `-e` keeps the behaviour consistent with the one before https://github.com/databricks/cli/pull/2896 was introduced.
Newly added regression tests
> Fix: Pass -e to sh and bash during command execution

- acceptance/bundle/deploy/mlops-stacks/output.txt
- acceptance/bundle/deploy/secret-scope/output.txt
- acceptance/bundle/deploy/volume/recreate/output.txt
- bundle/deploy/terraform/showplanfile.go
- bundle/deployplan/plan.go
- bundle/phases/deploy.go
- bundle/phases/deploy_test.go
- bundle/phases/destroy.go
- Modify deployplan.Action to be deployment method-neutral: use resource group name ("jobs") instead of terraform resource ("databricks_jobs").
- Implement ShowPlanFile, a wrapper for tf.ShowPlanFile which returns neutral []deployplan.Action.
- Use this wrapper in deploy and destroy.
- Implement deployplan.Filter and deployplan.FilterGroup helper methods and use those.
- Do not show auxiliary resources (grants, permissions, secret_acls) in diff output.
This abstracts terraform away, facilitating addition of direct deployment method: https://github.com/databricks/cli/pull/2926
> Implement neutral ShowPlanFile wrapper

- integration/cmd/fs/cp_test.go
* Fix potential panic
* Reuse ctx variable
I observed the following panic. The code could access `r` after a failed assertion here:
https://github.com/databricks/cli/blob/fb2b646997789ef15d89c805f2b77548e4665dfe/integration/cmd/fs/cp_test.go#L41-L46
```
=== FAIL: integration/cmd/fs TestFsCpFileToFile (99.64s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e4b13]
goroutine 344 [running]:
testing.tRunner.func1.2({0x1450540, 0x25334c0})
/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.linux-amd64/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1() …
```
> Update integration tests for the fs command

- acceptance/bundle/resources/pipelines/test.toml
Saw that this test is failing due to 20s timeout here: https://github.com/databricks/cli/actions/runs/15776275558/job/44471399166?pr=3089
> Increase timeout of bundle/resources/pipelines acc test to 30s

- bundle/bundle.go
- bundle/deploy/terraform/plan.go
Pointer is unnecessary. User code already checks Plan.Path == "" rather than Path == nil.
> internal: Bundle: replace *Plan with Plan

- integration/libs/filer/filer_test.go
Temporary workaround to make tests pass while debugging.
Hypothesis: I'm unable to repro the same situation through the Python SDK, and suspect that the Go SDK performs a reconnect under the hood. This might route us to a different backend instance and return a cached copy where reusing the original connection would return the right contents.
Tests pass with the workaround.
> Inject delay in filer tests on GCP

- integration/libs/filer/filer_test.go
This reverts commit 72d7830eedf02a3eeebdf71279809d6d8c8651fc (#3101).
The backend has been updated and the workaround is no longer necessary.
> Revert "Inject delay in filer tests on GCP"

- bundle/deploy/state.go
- bundle/deploy/state_pull.go
- bundle/deploy/state_test.go
- bundle/deploy/state_update.go
Keeping methods private to the package makes the code easier to comprehend - private methods are used only inside the package where they are defined
Existing tests
> Make FromSlice and ToSlice methods private to the `deploy` package

- acceptance/acceptance_test.go
- acceptance/selftest/basic/test.toml
- Do not load env variables from ~/.databricks/debug-env.json, revert https://github.com/databricks/cli/pull/2765
- Better check in TestInprocess that test is actually run and not selected.
Loading those env vars sets CLOUD_ENV which makes test runner ignore local tests.
Manually. Set selftest/basic Cloud=false and run it via IDE.
> acc: Fix local inprocess tests when run from IDE

- bundle/terranova/apply.go
- bundle/terranova/plan.go
- bundle/terranova/tnresources/app.go
- bundle/terranova/tnresources/job.go
- bundle/terranova/tnresources/pipeline.go
- bundle/terranova/tnresources/resource.go
- bundle/terranova/tnresources/resource_test.go
- bundle/terranova/tnresources/schema.go
There is no need for this to be a method, since type is static. Better to track it centrally, since it defines schema in resources.json.
> Remove IResource.GetType() method

- acceptance/bundle/deploy/secret-scope/output.txt
- bundle/config/resources/apps.go
- bundle/config/resources/secret_scope.go
- bundle/deploy/terraform/convert.go
- bundle/deploy/terraform/convert_test.go
When doing Terraform.Load (bundle summary/run/open), do not override app.name and secret_scope.name fields that come from the config with the one stored in Terraform state. Instead store state value in the "id" field.
Conceptually, we separate configuration field (Name) and stored state field (ID, which is Name from last deployment). This means as a user I can see both. Today, configuration's Name is lost in "bundle summary". However, in "bundle validate" Name would be equal to the one from the config, which is confusing -- potentially they could be different.
Internally, this makes TerraformToBundle simpler - it only updates ID field and ModifiedStatus (both are always computed and don't come from the user). This means configuration is preserved and also we can make TerraformToBundle …
> summary/run/open: pull App and SecretScope's name into ID field, not Name

- acceptance/acceptance_test.go
Experiencing many timeouts recently. If it's due to CI machines being slower, this could help. Maybe.
> acc: Multiply timeouts by 2 on CI

- acceptance/acceptance_test.go
- acceptance/bundle/deploy/dashboard/detect-change/test.toml
- acceptance/bundle/generate/dashboard-inplace/output.txt
- libs/testserver/dashboards.go
- libs/testserver/fake_workspace.go
- Improve dashboards in test server to better match real ones.
- Improve testserver's file system to track metadata.
- Enable TEST_DEFAULT_WAREHOUSE_ID in local tests.
- Enable dashboard/detect-change test to run locally in addition to cloud.
Running tests on local server gives faster feedback.
> acc: Improve dashboards testserver; enable detect-change test on local

- acceptance/bundle/deploy/dashboard/detect-change/output.txt
- acceptance/bundle/deploy/dashboard/detect-change/script
- acceptance/bundle/deploy/jobs/check-metadata/output.txt
- acceptance/bundle/deploy/jobs/check-metadata/script
- acceptance/bundle/deploy/secret-scope/output.txt
- acceptance/bundle/deploy/secret-scope/script
For jobs,  dashboards, secret scopes check that "id" and "modified_status" fields are set correctly by printing more output from "bundle summary".
This highlights the issue with secret scopes - modified_status is not correct there.
To support refactoring (https://github.com/databricks/cli/pull/3134) and adding support for direct deployment to bundle summary.
> Expand coverage for "bundle summary"

- .github/workflows/push.yml
- acceptance/acceptance_test.go
The "direct deployment" PR has a last minute change of env var value from "direct" to "direct-exp" (https://github.com/databricks/cli/pull/2926/commits/b47b1f60f738261c61629182fa8cba7bb6a7bf0c) but CI settings were not updated, thus disabling direct tests on CI. This enables them back 
Manually:
```
~/work/cli/acceptance/bundle/resources/jobs % ENVFILTER=DATABRICKS_CLI_DEPLOYMENT=terraform testme -v -count=1 | egrep 'PASS|SKIP|FAIL'
+ go test ../../.. -run ^TestAccept$/^bundle$/^resources$/^jobs$ -v -count=1
--- SKIP: TestAccept/bundle/resources/jobs/DATABRICKS_CLI_DEPLOYMENT=direct-exp (0.01s)
--- PASS: TestAccept/bundle/resources/jobs/DATABRICKS_CLI_DEPLOYMENT=terraform (4.74s)
~/work/cli/acceptance/bundle/resources/jobs % ENVFILTER=DATABRICKS_CLI_DEPLOYMENT=direct testme -v -count=1 | …
```
> Enable "direct" deployment method tests on CI

- acceptance/bundle/summary/missing-libraries-file-path/output.txt
- acceptance/bundle/summary/missing-libraries-file-path/test.toml
- cmd/bundle/validate.go
Fix crash in "bundle summary" when there was an error. Crash introduced in https://github.com/databricks/cli/pull/3123 (not released yet).
New acceptance test added in https://github.com/databricks/cli/pull/3138
> Fix crash in "bundle summary"

- acceptance/bundle/destroy/all-resources/databricks.yml
- acceptance/bundle/destroy/all-resources/output.txt
- acceptance/bundle/destroy/all-resources/script
- bundle/terranova/apply.go
- bundle/terranova/tnresources/app.go
- bundle/terranova/tnresources/job.go
- bundle/terranova/tnresources/pipeline.go
- bundle/terranova/tnresources/resource.go
- bundle/terranova/tnresources/schema.go
Remove DoDelete method from IResource, add a static function per resource.
Delete operation is special - it does not require config. In fact, it is often run when config is gone. 
On the other hand all other operations need config. 
To support both delete and non-delete operation in one class we would need to have constant checks/asserts config != nil. To avoid this complication, I'm taking delete out of IResource.
> Refactor deletes in direct deployment

- Makefile
Inspired by this https://github.com/databricks/cli/actions/runs/16021325523/job/45198831160
```
=== FAIL: acceptance  (0.00s)
panic: test timed out after 10m0s
running tests:
TestAccept/cmd/workspace/apps/run-local/DATABRICKS_CLI_DEPLOYMENT=terraform (2m44s)
goroutine 10059 [running]:
testing.(*M).startAlarm.func1()
C:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.windows-amd64/src/testing/testing.go:2484 +0x394
created by time.goFunc
C:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.windows-amd64/src/time/sleep.go:215 +0x2d
goroutine 1 [chan receive, 8 minutes]:
testing.(*T).Run(0xc0000036c0, {0x182d05c?, 0x7ffb6b657690?}, 0x193d280)
C:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.windows-amd64/src/testing/testing.go:1859 +0x414 …
```
> Increase test timeout to 30m

- acceptance/bundle/templates/lakeflow-pipelines/python/output/my_lakeflow_pipelines/resources/my_lakeflow_pipelines_pipeline/transformations/sample_trips_my_lakeflow_pipelines.py
- acceptance/bundle/templates/lakeflow-pipelines/python/output/my_lakeflow_pipelines/resources/my_lakeflow_pipelines_pipeline/transformations/sample_zones_my_lakeflow_pipelines.py
- libs/template/templates/lakeflow-pipelines/template/{{.project_name}}/resources/{{.project_name}}_pipeline/transformations/sample_trips_{{.project_name}}.py.tmpl
- libs/template/templates/lakeflow-pipelines/template/{{.project_name}}/resources/{{.project_name}}_pipeline/transformations/sample_zones_{{.project_name}}.py.tmpl
- ruff.toml
Replaced single-line return statements with multi-line format in two transformation templates to fix linter warnings.
- `sample_trips_{{.project_name}}.py.tmpl`: Multi-line Spark DataFrame operation
- `sample_zones_{{.project_name}}.py.tmpl`: Multi-line Spark aggregation operation
Removed from `ruff.toml`.
Now matches cli-pipelines format.
Single-line statements were triggering linter warnings due to excessive line length. Multi-line format resolves these issues while maintaining identical functionality and improving readability.
- Verified functional equivalence between old and new formats
- Modified output to match the new format
> Fix linter formatting in lakeflow-pipelines template

- bundle/statemgmt/state_load_test.go
Added missing asserts for secret scopes in StateToBundle tests
It appears to be an oversight that the asserts were not added
Existing tests
> Added missing asserts for secret scopes in StateToBundle tests

- acceptance/pipelines/deploy/render-diagnostics-warning/databricks.yml
- acceptance/pipelines/deploy/render-diagnostics-warning/output.txt
- acceptance/pipelines/deploy/render-diagnostics-warning/script
- acceptance/pipelines/deploy/render-diagnostics-warning/test.toml
Added acceptance test for rendering diagnostics warnings when unknown properties are encountered during pipeline deployment.
Follow-up to [PR #3107](https://github.com/databricks/cli/pull/3107) - ensures the diagnostics system correctly identifies and reports unknown properties in pipeline configurations, providing users with helpful feedback about potential configuration issues.
Added acceptance test case `render-diagnostics-warning` that verifies warning messages are properly displayed for unknown bundle configuration properties.
> Add diagnostics warning test for pipelines deploy

- libs/dyn/pattern_trie.go
- libs/dyn/pattern_trie_test.go
A prefix tree datastructure for patterns allows us to do quick lookup for patterns. This will be useful for required and enum field validation.
Downstream validation PR: https://github.com/databricks/cli/pull/3044
Unit tests.
> Add trie for patterns

- bundle/config/resources.go
This change slightly improves developer experience when introducing a new resource type to the asset bundle. 
Before it was easy to miss that in
```
func (r *Resources) AllResources() []ResourceGroup {
descriptions := SupportedResources()
return []ResourceGroup{
collectResourceMap(descriptions["jobs"], r.Jobs),
collectResourceMap(descriptions["pipelines"], r.Pipelines),
collectResourceMap(descriptions["models"], r.Models),
collectResourceMap(descriptions["experiments"], r.Experiments),
collectResourceMap(descriptions["model_serving_endpoints"], r.ModelServingEndpoints),
collectResourceMap(descriptions["registered_models"], r.RegisteredModels),
collectResourceMap(descriptions["quality_monitors"], r.QualityMonitors),
collectResourceMap(descriptions["schemas"], r.Schemas), …
```
> Add a panic if a resource description is empty when collecting AllResources

- integration/cmd/sync/sync_test.go
Tests run into this timeout, especially during integration test runs when we put a lot of load on our test workspace. Increasing this timeout should help reduce flakyness:
logs:
```
=== FAIL: integration/cmd/sync TestSyncIncrementalFileOverwritesFolder (re-run 2) (120.09s)
sync_test.go:76: CLOUD_ENV=***
fixtures.go:23: Creating workspace directory /Users/***/integration-test-sync-9308e0589a2a45db9fcc68e53f472319
Warn: Failed to read git info: stat /.git: no such file or directory
sync_test.go:113: timed out waiting for sync to complete
```
> Increase waitForCompletionMarker timeout in sync integration tests

- acceptance/bundle/destroy/jobs-and-pipeline/out.test.toml
- acceptance/bundle/destroy/jobs-and-pipeline/test.toml
It requires "bundle summary" which we have since https://github.com/databricks/cli/pull/3162
> acc: Enable destroy/jobs-and-pipeline on direct

- acceptance/pipelines/deploy/auto-approve/out.test.toml
- acceptance/pipelines/deploy/auto-approve/test.toml
- acceptance/pipelines/deploy/create-pipeline/out.test.toml
- acceptance/pipelines/deploy/create-pipeline/test.toml
- acceptance/pipelines/deploy/render-diagnostics-warning/out.test.toml
- acceptance/pipelines/deploy/render-diagnostics-warning/test.toml
- acceptance/pipelines/deploy/var-flag/out.test.toml
- acceptance/pipelines/deploy/var-flag/test.toml
Pipelines are supported by direct backend.
> acc: enable pipelines tests on direct

- libs/testserver/fake_workspace.go
New 404 message looks like this: Resource catalog.VolumeInfo not found: main.myschema.myvolume
This allows distinguishing between handler not set up correct and object not found issues.
Manually.
> testserver: better error message in resource not found case

- acceptance/bundle/integration_whl/base/out.test.toml
- acceptance/bundle/integration_whl/base/test.toml
- acceptance/bundle/integration_whl/custom_params/out.test.toml
- acceptance/bundle/integration_whl/custom_params/test.toml
- acceptance/bundle/integration_whl/interactive_cluster/out.test.toml
- acceptance/bundle/integration_whl/interactive_cluster/test.toml
- acceptance/bundle/integration_whl/interactive_single_user/out.test.toml
- acceptance/bundle/integration_whl/interactive_single_user/test.toml
- acceptance/bundle/integration_whl/wrapper/out.test.toml
- acceptance/bundle/integration_whl/wrapper/test.toml
- acceptance/bundle/integration_whl/wrapper_custom_params/out.test.toml
- acceptance/bundle/integration_whl/wrapper_custom_params/test.toml
- bundle/config/mutator/resourcemutator/job_cluster_fixups.go
- bundle/config/mutator/resourcemutator/resource_mutator.go
Apply changes in resource normalization that are applied by TF and cause invalid configuration to be fixed and accepted by the backend.
For example, when InstancePoolId is set, clear NodeTypeId field.
For direct deployment we do all resource transformations in initialize phase rather than before deployment.
This makes no effect on the resource - the APIs are called with the same payload because this transformations are idempotent when applied for the second time.
However,
- this makes it visible to user (via bundle validate -o json) what is the final configuration that is being sent to the backend
- makes the same configuration work equally in terraform and direct backend even through direct backend does not transform resources in any way.
Same reasoning as in …
> Normalize clusters in jobs according to Terraform provider logic

- acceptance/bundle/integration_whl/serverless/test.toml
- acceptance/bundle/integration_whl/serverless_dynamic_version/test.toml
Reverts: https://github.com/databricks/cli/pull/3195
These tests started failing because of the missing repl. Diff:
```
->>> cp [TESTROOT]/bundle/resources/clusters/run/spark_python_task/../../deploy/simple/hello_world.py .
+>>> cp [TESTROOT]\bundle\resources\clusters\run\spark_python_task/../../deploy/simple/hello_world.py .
```
> Fix slash in bundle/integration_whl acceptance tests

- Makefile
- acceptance/acceptance_test.go
- acceptance/bundle/integration_whl/base/out.test.toml
- acceptance/bundle/integration_whl/base/test.toml
- acceptance/bundle/integration_whl/custom_params/out.test.toml
- acceptance/bundle/integration_whl/custom_params/test.toml
- acceptance/bundle/integration_whl/interactive_cluster/out.test.toml
- acceptance/bundle/integration_whl/interactive_cluster/test.toml
- acceptance/bundle/integration_whl/interactive_cluster_dynamic_version/out.test.toml
- acceptance/bundle/integration_whl/interactive_single_user/out.test.toml
- acceptance/bundle/integration_whl/interactive_single_user/test.toml
- acceptance/bundle/integration_whl/serverless/out.test.toml
- acceptance/bundle/integration_whl/serverless_dynamic_version/out.test.toml
- acceptance/bundle/integration_whl/wrapper/out.test.toml
- acceptance/bundle/integration_whl/wrapper_custom_params/out.test.toml
- acceptance/bundle/integration_whl/wrapper_custom_params/test.toml
- acceptance/bundle/resources/clusters/run/spark_python_task/out.test.toml
- acceptance/bundle/run/app-with-job/out.test.toml
Extract from https://github.com/databricks/cli/pull/3224 that
- Automatically enables Cloud if CloudSlow is enabled. Note, this only affects out.test.toml but behaviour is the same.
- Disables broken tests.
Commit and run with non-short tests enabled: https://github.com/databricks/cli/commit/8a9e80b3bd1297ab5f592ba24acd08966944784d
https://go/deco-tests/16198082279
> acc: Fix CloudSlow tests; auto-enable Cloud on CloudSlow

- acceptance/pipelines/version/out.test.toml
- acceptance/pipelines/version/output.txt
- acceptance/pipelines/version/script
Acceptance tests for `pipelines --version` and `pipelines version` commands.
Following up on #3221
> acc: `pipelines --version` and `pipelines version`

- NEXT_CHANGELOG.md
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/databricks.yml.tmpl
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/out.test.toml
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/output.txt
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/pipeline.json.tmpl
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/script
- acceptance/bundle/deploy/pipeline/allow-duplicate-names/test.toml
- bundle/deploy/terraform/tfdyn/convert_pipeline.go
- bundle/deploy/terraform/tfdyn/convert_pipeline_test.go
- bundle/internal/schema/main.go
- bundle/schema/jsonschema.json
- experimental/python/databricks/bundles/pipelines/_models/pipeline.py
- Fixed pipeline resource conversion to preserve `allow_duplicate_names` configuration field
- Updated schema and codegen to reflect the `allow_duplicate_names` field
The `allow_duplicate_names` field was being dropped from pipeline resources during conversion, preventing users from configuring pipelines that allow duplicate names. This change ensures the field is properly preserved and passed through to the Terraform Provider
- Added a new acceptance test
> Preserve `allow_duplicate_names` field in the pipeline resource 

- NEXT_CHANGELOG.md
- cmd/account/network-connectivity/network-connectivity.go
- cmd/workspace/alerts-v2/alerts-v2.go
- cmd/workspace/database/database.go
- cmd/workspace/external-lineage/external-lineage.go
- cmd/workspace/external-metadata/external-metadata.go
- cmd/workspace/feature-store/feature-store.go
- cmd/workspace/lakeview/lakeview.go
Add required query parameters as positional arguments in CLI commands
Fixes #3271
Relies on a fix in the genkit code
Manually. Regenerated on fixed genkit
> Add required query parameters as positional arguments in CLI commands

- acceptance/bundle/run/refresh-flags/databricks.yml
- acceptance/bundle/run/refresh-flags/out.test.toml
- acceptance/bundle/run/refresh-flags/output.txt
- acceptance/bundle/run/refresh-flags/pipeline_file.py
- acceptance/bundle/run/refresh-flags/script
- acceptance/bundle/run/refresh-flags/test.toml
- bundle/run/pipeline_options.go
- bundle/run/pipeline_options_test.go
Added acceptance tests to check if both flags can be specified at once, --refresh and --full-refresh flags
Added tests for bundle run pipeline [refresh-flags]
Acceptance tests:
- for pipelines, adds one new test for --full-refresh table1,table2 --refresh table3,table4
- for bundles, adds all tests to match tests present in the pipelines tests
Follows https://github.com/databricks/cli/pull/3300
> acc: pipelines and bundle run --refresh and --full-refresh flags

- acceptance/bundle/run_as/empty_run_as_dict/databricks.yml
- acceptance/bundle/run_as/empty_run_as_dict/out.test.toml
- acceptance/bundle/run_as/empty_run_as_dict/output.txt
- acceptance/bundle/run_as/empty_run_as_dict/script
The semantics of nulls is going to change in https://github.com/databricks/cli/pull/3230 but empty dictionary behaviour should stay the same. This test ensures that.
> acc: expand run_as test with empty dictionary

- acceptance/bundle/deploy/empty-bundle/databricks.yml
- acceptance/bundle/deploy/empty-bundle/databricks.yml.tmpl
- acceptance/bundle/deploy/empty-bundle/output.txt
- acceptance/bundle/deploy/empty-bundle/script
Otherwise there are conflicts when running on cloud.
```
Error: Failed to acquire deployment lock: deploy lock acquired by [USERNAME] at [TIMESTAMP].[NUMID] +0000 UTC. Use --force-lock to override
Error: deploy lock acquired by [USERNAME] at [TIMESTAMP].[NUMID] +0000 UTC. Use --force-lock to override
```
> acc: Use unique name in deploy/empty-bundle

- bundle/terranova/apply.go
- bundle/terranova/tnresources/resource.go
To facilitate parallel operations where ID is known and stable and to catch logic errors where ID is changed where it is not supposed to.
> direct: Add UpdateableIDResource setting

- libs/dyn/convert/from_typed.go
- libs/dyn/convert/struct_info.go
- libs/dyn/convert/struct_info_test.go
The fields have natural order, existing API destroys it by returning map.
This PR changes FieldValues() to return a more appropriate data structure. Needed for / extracted from #3230
> dyn: Modify FieldValues to return ordered fields

- NEXT_CHANGELOG.md
- cmd/auth/login.go
Show `"DEFAULT"` as the default profile for the `databricks auth login` command. This change uses the same UX as seen in the `databricks bundle init` command, i.e. it shows the default value between square backets rather than in the input field.
This change aims to make `databricks auth login` more self-documenting. I want to reference it from templates in the future.
> Show "DEFAULT" as the default profile for `databricks auth login`

- acceptance/install_terraform.py
Add a capability of providing a dev_override for the Databricks Terraform provider in acceptance tests via an environment variable.
Usage:
`DATABRICKS_TF_PROVIDER_DEV_OVERRIDE=<PATH_TO_LOCAL_FOLDER> make test`
This allows CLI developers to use a "dev preview" of Databricks Terraform Provider in the acceptance tests.
Manually checked that in the absence of `DATABRICKS_TF_PROVIDER_DEV_OVERRIDE` the generated .terraformrc remains intact. When `DATABRICKS_TF_PROVIDER_DEV_OVERRIDE` is provided a new section is added to the file and acceptance tests start using a local custom version of the Databricks Terraform provider:
```
provider_installation {
dev_overrides {
"databricks/databricks" = <REDACTED>
}
filesystem_mirror {
path = <REDACTED>
include = …
```
> Add a capability of providing a dev_override for the Databricks Terraform provider

- acceptance/bundle/debug/direct/out.stderr.txt
- acceptance/bundle/debug/direct/output.txt
- acceptance/bundle/debug/tf/out.stderr.txt
- bundle/config/mutator/resolve_lookup_variables.go
- bundle/config/mutator/resolve_lookup_variables_test.go
- bundle/phases/initialize.go
ResourceResourceReferences sounds like it would be resolving ${resources...} like references which is also something we do.
> Rename ResolveResourceReferences to mutator.ResolveLookupVariables

- NEXT_CHANGELOG.md
- acceptance/bundle/artifacts/whl_implicit_notebook/output.txt
- acceptance/bundle/deploy/experimental-python/output.txt
- acceptance/bundle/deploy/jobs/check-metadata/output.txt
- acceptance/bundle/deploy/jobs/task-source/databricks.yml
- acceptance/bundle/deploy/jobs/task-source/notebook.py
- acceptance/bundle/deploy/jobs/task-source/out.test.toml
- acceptance/bundle/deploy/jobs/task-source/output.txt
- acceptance/bundle/deploy/jobs/task-source/script
- acceptance/bundle/deploy/jobs/task-source/test.toml
- acceptance/bundle/deploy/python-notebook/output.txt
- acceptance/bundle/deployment/bind/job/job-spark-python-task/output.txt
- acceptance/bundle/override/job_tasks/output.txt
- acceptance/bundle/paths/fallback/output.job.json
- acceptance/bundle/paths/nominal/output.job.json
- acceptance/bundle/paths/relative_path_outside_root/output.txt
- acceptance/bundle/python/resolve-variable/output.txt
- acceptance/bundle/templates/default-python/integration_classic/out.validate.dev.json
- acceptance/bundle/templates/default-python/integration_classic/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/terraform/output.txt
- bundle/config/mutator/resourcemutator/apply_default_task_source.go
- bundle/config/mutator/resourcemutator/resource_mutator.go
If the job has `git_source` set, DABs will set `source: GIT` to all the tasks where source is not already set
If the job has no `git_source` set, DABs will set `source: WORKSPACE` to all the tasks where source is not already set
We only do this for a subset of task types which support source field as per https://docs.databricks.com/api/workspace/jobs/create
Fixes https://github.com/databricks/cli/issues/2561
Added an acceptance test
> Always set default value for source field for tasks if not explicitly set already

- acceptance/cmd/workspace/apps/run-local/out.test.toml
- acceptance/cmd/workspace/apps/run-local/test.toml
Temporary disable run-local test
It is currently frequently failing on macos runner for direct deployment. No clear cause yet, disabling until will figure it out.
> acc: Temporary disable run-local test

- NEXT_CHANGELOG.md
- acceptance/bundle/help/bundle-run/output.txt
- acceptance/bundle/run/jobs/partial_run/databricks.yml
- acceptance/bundle/run/jobs/partial_run/notebook1.py
- acceptance/bundle/run/jobs/partial_run/notebook2.py
- acceptance/bundle/run/jobs/partial_run/out.test.toml
- acceptance/bundle/run/jobs/partial_run/output.txt
- acceptance/bundle/run/jobs/partial_run/script
- acceptance/bundle/run/jobs/partial_run/test.toml
- bundle/run/job_options.go
Added support for running specified job tasks instead of all job tasks.
This change introduces a new flag `--only` for the `bundle run` command when executed on a job.
It allows specifying which specific tasks out of all in the jobs to run.
Usage
```
databricks bundle run my_job --only task_1,task_2
```
The feature was relatively recently added to Jobs API
https://docs.databricks.com/api/workspace/jobs/runnow#only
Added an acceptance tests.
Skipped running on Cloud because the test is really slow but verified manually it works as expected too.
> Added support for running specified job tasks instead of all job tasks

- NEXT_CHANGELOG.md
- bundle/config/resources/volume.go
- bundle/deploy/terraform/tfdyn/convert_volume_test.go
- bundle/internal/schema/annotations.yml
- bundle/internal/schema/annotations_openapi_overrides.yml
- bundle/schema/jsonschema.json
Add an enum for volume grant privileges.
Possible values are:
- `ALL_PRIVILEGES`
- `APPLY_TAG` (missing in Terraform docs but supported)
- `MANAGE`
- `READ_VOLUME`
- `WRITE_VOLUME`
It follows documented privileges in Terraform documentation: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants#volume-grants
I will add `APPLY_TAG` to Terraform as a follow-up.
Using enums gives better typing in JSON schema and allows generating enums in Python code
By inspecting the resulting JSON schema
> Add enum for volume grant privileges

- NEXT_CHANGELOG.md
- acceptance/bundle/variables/resolve-resources-fields/output.txt
- bundle/config/mutator/resolve_variable_references.go
This reverts commit 9681b7f323eb760f551a2914fb9110db79e6747f.
This breaks deployments due to swapping the order of resolution and preset application.
> Revert "Resolves $resources as regular variables if set by user (#3370)"

- NEXT_CHANGELOG.md
- acceptance/bundle/deploy/lakebase/database-catalog/databricks.yml.tmpl
- acceptance/bundle/deploy/lakebase/database-catalog/out.test.toml
- acceptance/bundle/deploy/lakebase/database-catalog/output.txt
- acceptance/bundle/deploy/lakebase/database-catalog/script
- acceptance/bundle/deploy/lakebase/database-catalog/test.toml
- acceptance/bundle/deploy/lakebase/database-instance/single-instance/test.toml
- acceptance/bundle/deploy/lakebase/test.toml
- acceptance/internal/handlers.go
- bundle/config/mutator/resourcemutator/apply_bundle_permissions.go
- bundle/config/mutator/resourcemutator/apply_target_mode_test.go
- bundle/config/mutator/resourcemutator/run_as_test.go
- bundle/config/resources.go
- bundle/config/resources/database_catalog.go
- bundle/config/resources_test.go
- bundle/deploy/terraform/pkg.go
- bundle/deploy/terraform/tfdyn/convert_database_catalog.go
- bundle/internal/schema/annotations.yml
- bundle/schema/jsonschema.json
- bundle/statemgmt/state_load_test.go
- libs/testserver/database_catalogs.go
- libs/testserver/fake_workspace.go
Added support for creating Lakebase database catalogs in DABs
This change allows users to define database catalogs as part of their assets bundle:
```
...
resources:
...
database_instances:
my_database_instance:
name: my_database_instance
capacity: CU_1
database_catalogs:
my_catalog:
database_instance_name: ${resources.database_instances.my_instance.name}
database_name: "my_database"
name: my_catalog_$UNIQUE_NAME
create_database_if_not_exists: true
```
Added acceptance tests for database instances deployments
> Add support for lakebase catalog 

- NEXT_CHANGELOG.md
- acceptance/cmd/auth/token/out.test.toml
- acceptance/cmd/auth/token/output.txt
- acceptance/cmd/auth/token/script
- acceptance/cmd/auth/token/test.toml
- cmd/auth/token.go
Update the "auth token" command to return the same error as CLI v0.263.0.
Older versions of Databricks SDKs call this command to retrieve an OAuth token. They perform a substring match on the returned error to determine if the CLI experienced a real error or if OAuth is not an applicable authentication mechanism in the user's context. By changing the error message (see databricks/databricks-sdk-go#1250), these older SDKs no longer fall through but return an error `cache: no token found` when checking if they can use OAuth to authenticate.
Adds an acceptance test. It passes with the previous version of the CLI and passes with this commit.
> Fix "cache: token not found" for auth token command

- bundle/terranova/apply.go
- bundle/terranova/graph.go
- bundle/terranova/plan.go
- libs/dagrun/dagrun.go
More clear responsibility of makeResourceGraph.
Also doing more validation on planned actions there.
> direct: internal: simplify makeResourceGraph function

- experimental/python/Makefile
Fix the cleanup stage in the codegen script to remove unnecessary `__init__` files.
We have unnescessary `compute/__init__.py` that shouldn't have existed in the first place.
Codegen script is executed on every commit in CI
> [Python] Fix cleanup in codegen script

- bundle/deploy/terraform/showplanfile.go
- bundle/phases/deploy_test.go
When introducing a new resource to the system it does not get a mention in the plan automatically. Instead, developer must know that the new resource has to be added to the GroupToTerraformName map for it. The warning message is a good indicator for the developer of the new resource that an extra step is needed for the resource support. I opted for the warning message instead of panicking because apparently there are resources that do not need to be in the plan, but there is no comprehensive list of such resources provided and I am not sure that the test suite covers every such resource, it is not a great experience for the bundle operation to be blocked just because the resource is in neither of the lists.
Existing tests are green
> Show a warning message if a resource is not in GroupToTerraformName

- bundle/terranova/tnresources/app.go
- bundle/terranova/tnresources/util.go
Copied an implementation from TF so both behaviours are in line
https://github.com/databricks/terraform-provider-databricks/blob/9346a78bde642b3ee4e8caec80439a71fa681a9b/internal/providers/pluginfw/products/app/resource_app.go#L161
Behaviour in TF and direct should be same, currently difference causing app related acceptance test to fail
Existing acceptance/bundle/run/app-with-job should pass
> direct: Add waiting for the app after create same as in TF implementation

- internal/testarchive/archive_test.go
- internal/testarchive/downloader_test.go
Feedback in https://github.com/databricks/cli/pull/3453#discussion_r2297493314 recommended not using build tags. This PR enables these tests by default. 
These tests will be skipped when `-short` flag is provided. Note: We do not specify the `-short` flag in CI so these tests will run by default.
> Run testarchive unit tests on PRs

- internal/testarchive/archive.go
- internal/testarchive/archive_test.go
- internal/testarchive/downloader_test.go
We do not need ARM binaries right now, so skip downloads for them.
Builds on top of: https://github.com/databricks/cli/pull/3500
Modified unit tests.
> Do not download ARM binaries in testarchive

- acceptance/bin/allocate_ports.py
- acceptance/cmd/workspace/apps/run-local-node/out.test.toml
- acceptance/cmd/workspace/apps/run-local-node/script
- acceptance/cmd/workspace/apps/run-local-node/test.toml
- acceptance/cmd/workspace/apps/run-local/out.test.toml
- acceptance/cmd/workspace/apps/run-local/script
- acceptance/cmd/workspace/apps/run-local/test.toml
Reverts databricks/cli#3490
The tests still failing https://github.com/databricks/cli/actions/runs/17289620395/job/49073700178
```
+++ /var/folders/x7/ch5v91h56_zbvbd1y2f600dm0000gn/T/TestAcceptcmdworkspaceappsrun-local1357262386/001/output.txt
@@ -10,25 +10,6 @@
=== Waiting
=== Checking app is running...
>>> curl -s -o - http://127.0.0.1:$(port)/
-{
-  "Accept": "*/*",
-  "Accept-Encoding": "gzip",
-  "Host": "127.0.0.1:$(port)",
-  "User-Agent": "curl/(version)",
-  "X-Forwarded-Email": "[USERNAME]",
-  "X-Forwarded-Host": "localhost",
-  "X-Forwarded-Preferred-Username": "",
-  "X-Forwarded-User": "[USERNAME]",
-  "X-Real-Ip": "127.0.0.1",
-  "X-Request-Id": "[UUID]"
-}
+jq: parse error: Invalid numeric literal at line 1, column 6
```
> Revert "acc: Use fixed ports instead of dynamically allocated ones for run-local tests"

- tools/gh_parse.py
The previous character (\u200c) is a zero-width non-joiner and renders incorrectly in some terminals.
Also see:
* https://en.wikipedia.org/wiki/Zero-width_space
* https://en.wikipedia.org/wiki/Zero-width_non-joiner
> Use correct zero-width space character

- acceptance/bundle/deploy/lakebase/database-catalog/out.test.toml
- acceptance/bundle/deploy/lakebase/database-catalog/output.txt
- acceptance/bundle/deploy/lakebase/database-catalog/test.toml
- bundle/terranova/resource.go
- bundle/terranova/tnresources/database_catalog.go
This change allows to deploy database catalogs when using `direct-exp` deployment method
Existing test is expanded to run using `direct-exp`
> Implement database_catalog in direct deployment

- acceptance/acceptance_test.go
- acceptance/bundle/artifacts/test.toml
- acceptance/bundle/integration_whl/test.toml
- acceptance/internal/config.go
Certain tests would need to be skipped on DBR because of quirks in the workspace file system. This PR adds a flag to do so and disables artfic-related acceptance tests for now.
Manually, these tests were indeed skipped on runs.
> acc: Add SkipOnDbr flag

- bundle/apps/interpolate_variables_test.go
- bundle/config/mutator/initialize_urls_test.go
- bundle/config/resources/apps.go
- bundle/config/resources/base.go
- bundle/config/resources/clusters.go
- bundle/config/resources/dashboard.go
- bundle/config/resources/database_catalog.go
- bundle/config/resources/database_instance.go
- bundle/config/resources/job.go
- bundle/config/resources/mlflow_experiment.go
- bundle/config/resources/mlflow_model.go
- bundle/config/resources/model_serving_endpoint.go
- bundle/config/resources/pipeline.go
- bundle/config/resources/quality_monitor.go
- bundle/config/resources/registered_model.go
- bundle/config/resources/schema.go
- bundle/config/resources/secret_scope.go
- bundle/config/resources/sql_warehouses.go
- bundle/config/resources/synced_database_table.go
- bundle/config/resources/volume.go
- bundle/deploy/metadata/compute_test.go
- bundle/deploy/terraform/convert_test.go
- bundle/render/render_text_output_test.go
- bundle/run/job_test.go
- bundle/run/pipeline_test.go
- libs/structaccess/bundle_test.go
- libs/structwalk/walktype_test.go
Extract common resource fields into a separate embedded struct `BaseResource`
Based on feedback from https://github.com/databricks/cli/pull/3448#discussion_r2330023305
Existing tests pass
> refactor: Extract common resource fields into a separate embedded struct

- acceptance/bundle/debuglog/out.stderr.direct-exp.txt
- acceptance/bundle/debuglog/out.stderr.terraform.txt
- acceptance/bundle/resource_deps/job_tasks/databricks.yml
- acceptance/bundle/resource_deps/job_tasks/out.test.toml
- acceptance/bundle/resource_deps/job_tasks/output.txt
- acceptance/bundle/resource_deps/job_tasks/script
- acceptance/bundle/resource_deps/job_tasks/test.toml
- acceptance/bundle/resource_deps/missing_map_key_tffix/output.txt
- acceptance/bundle/resource_deps/missing_map_key_tffix/script
- acceptance/bundle/resource_deps/missing_map_key_tffix/test.toml
- acceptance/bundle/resource_deps/resources_var/out.requests.txt
- acceptance/bundle/resource_deps/resources_var/output.txt
- acceptance/bundle/resource_deps/resources_var/script
- acceptance/bundle/telemetry/deploy-artifacts-variables/script
- acceptance/script.prepare
- bundle/config/mutator/log_resource_references.go
- bundle/config/mutator/log_resource_references_test.go
- bundle/config/mutator/resourcemutator/process_static_resources.go
For every $resource.group.key.field1.field2 reference add resref_group_field1_field2 bool metric.
If we encounter map key, place "mapkey" in case of actual value.
If we encounter error during struct traversal, log what we can with resreferr_ prefix instead.
With remote state lookups added in https://github.com/databricks/cli/pull/3531 we use API / SDK struct schema for accessing remote fields, which is different from Terraform schema. Having telemetry allows to estimate number of customers using $resources references and estimate usage of incompatible references.
Existing tests expanded to log telemetry.
New acceptance test which includes longer path.
New helper in tests to log boolean fields from telemetry request.
> Log to telemetry redacted $resources references

- bundle/terranova/tnresources/all_test.go
This is running against local testserver.
Before:
```
--- PASS: TestAll (3.74s)
--- PASS: TestAll/pipelines (0.34s)
--- PASS: TestAll/schemas (0.40s)
--- PASS: TestAll/volumes (0.40s)
--- PASS: TestAll/apps (0.47s)
--- PASS: TestAll/sql_warehouses (0.40s)
--- PASS: TestAll/database_instances (0.47s)
--- PASS: TestAll/database_catalogs (0.47s)
--- PASS: TestAll/synced_database_tables (0.40s)
--- PASS: TestAll/jobs (0.40s)
```
After:
```
--- PASS: TestAll (0.01s)
--- PASS: TestAll/schemas (0.00s)
--- PASS: TestAll/database_instances (0.00s)
--- PASS: TestAll/synced_database_tables (0.00s)
--- PASS: TestAll/jobs (0.00s)
--- PASS: TestAll/pipelines (0.00s)
--- PASS: TestAll/volumes (0.00s)
--- PASS: TestAll/apps (0.00s)
--- PASS: TestAll/sql_warehouses (0.00s)
--- PASS: …
```
> Disable rate limit in tnresources unit tests

- experimental/ssh/cmd/connect.go
- experimental/ssh/cmd/setup.go
- experimental/ssh/internal/client/client.go
- experimental/ssh/internal/setup/setup.go
- Add a cluster selector UI to the `ssh setup` command. We don't filter or check the clusters during that stage, as it's done later by the `validateClusterAccess`. Cluster option is no longer required for the `setup` command. A few customers asked for this already.
- Add an `--auto-start-cluster` flag to both `ssh setup` and `ssh connect` commands, which defaults to true. Useful for PyCharm users, where the IDE checks every host in the config to see the if the connection can be established, starting all the clusters.
- Change a few `client.go` functions to accept ClientOptions instead of a long list of separate arguments 
Based on https://github.com/databricks/cli/pull/3569
No unit tests, integration tests will be in the follow ups.
> Add cluster selector UI and auto-start option to ssh commands

- acceptance/install_terraform.py
Noticed it does not work on Linux clusters.
> acc: fix install_terraform.py on aarch64

- libs/dyn/convert/to_typed_test.go
- libs/dyn/kind.go
- libs/dyn/value.go
- libs/dyn/value_test.go
- Fix IsZero() method for types like int64. This fixes ToConvert for NumWorkers field in ClusterSpec.
- Do not panic in dyn.V() if other int types are encountered.
- If panic does happen, include type name.
ToConvert() depends on it and is broken. This unblocks https://github.com/databricks/cli/pull/3650 https://github.com/databricks/cli/pull/3646
> dyn: fix zero values conversion / IsZero() method

- NEXT_CHANGELOG.md
- acceptance/bundle/run/no-state/output.txt
- acceptance/bundle/run/state-wiped/output.txt
- bundle/statemgmt/state_load.go
Improve the output of bundle run when the bundle is not deployed
Makes it a bit more user-friendly, why the error appears
Acceptance tests
> Improve the output of bundle run when bundle is not deployed

- acceptance/bundle/resources/jobs/update/output.txt
- acceptance/bundle/resources/volumes/change-name/out.plan.direct-exp.txt
- acceptance/bundle/resources/volumes/change-name/out.plan.terraform.txt
- bundle/deploy/terraform/showplanfile.go
- bundle/deployplan/action.go
- bundle/deployplan/action_test.go
- bundle/direct/bundle_plan.go
- "update(id_stable)" becomes "update"
- "update(id_changes)" becomes "update_id"
- StringFull() becomes String()
This names show up in JSON plan and "update" is most common action, so seeing "update(id_stable)" feels like unnecessary noise.
> Simplify action name "update(id_stable)" -> "update"

- acceptance/bundle/resources/jobs/update/output.txt
- bundle/direct/apply.go
- bundle/direct/bundle_plan.go
- cmd/bundle/plan.go
- cmd/bundle/utils/utils.go
Include 'skip' nodes in JSON plan.
We need to process 'skip' resources as well (e.g. to resolve references). Today, we have these nodes in the graph but not in the plan. Once we move to serialized plan https://github.com/databricks/cli/pull/3636 we will build graph from the plan so they must match. This prepares for that (and minimizes that PR).
This also gives more information to users of JSON plan, e.g. they can count unchanged count. 
> Include skip actions in JSON plan

- acceptance/bundle/resources/jobs/update_single_node/databricks.yml
- acceptance/bundle/resources/jobs/update_single_node/out.test.toml
- acceptance/bundle/resources/jobs/update_single_node/output.txt
- acceptance/bundle/resources/jobs/update_single_node/script
- libs/dyn/convert/end_to_end_test.go
- libs/dyn/convert/from_typed.go
- libs/dyn/convert/from_typed_test.go
- libs/dyn/convert/struct_info.go
- libs/dyn/convert/to_typed.go
- libs/dyn/convert/to_typed_test.go
Fix ToTyped / FromTyped wrt ForceSendFields when there are (multiple) embedded structs.
Incorrect conversion between typed & dynamic value can result in subtle bugs. In direct engine it is even more important, as we rely on typed structs more here. Enables https://github.com/databricks/cli/pull/3646
> dyn/convert: Fix ForceSendFields handling for embedded structs

- bundle/deploy/metadata/compute.go
- bundle/deploy/metadata/compute_test.go
- bundle/metadata/metadata.go
Output `id` and `relative_path` for each pipeline to `metadata.json` during deploy
To enable DABs integrations in the Lakeflow UI
Updated existing test
> Add pipeline info to metadata.json

- bundle/config/mutator/initialize_urls_test.go
- bundle/config/mutator/resourcemutator/apply_target_mode_test.go
- bundle/config/resources/mlflow_experiment.go
- bundle/config/resources_test.go
- bundle/deploy/terraform/convert_test.go
- bundle/deploy/terraform/tfdyn/convert_experiment_test.go
- bundle/internal/schema/testdata/pass/ml.yml
- bundle/internal/validation/generated/required_fields.go
- bundle/permissions/workspace_root_test.go
- bundle/schema/jsonschema.json
- bundle/statemgmt/state_load_test.go
This PR changes the experiments resource definition to use `ml.CreateExperiment` instead of using `ml.Experiment`.
This removes output only fields from the resource schema. Those fields were never settable in the first place.
for reference, here are the structs:
```
type CreateExperiment struct {
// Location where all artifacts for the experiment are stored. If not
// provided, the remote server will select an appropriate default.
ArtifactLocation string `json:"artifact_location,omitempty"`
// Experiment name.
Name string `json:"name"`
// A collection of tags to set on the experiment. Maximum tag size and
// number of tags per request depends on the storage backend. All storage
// backends are guaranteed to support tag keys up to 250 bytes in size and
// tag values up to 5000 bytes in …
```
> Fix bundle representation for experiments

- libs/testproxy/server.go
This PR modifies the proxy server to use the new API client from the Go SDK and then pass through the `X-Databricks-Org-Id`
To make the `w.CurrentWorkspaceId()` SDK call work, which relies on this header.
Existing tests pass. `bundle summary` which failed before with `RecordRequests = true` passes now.
> Fix proxy server for CurrentWorkspaceId method

- acceptance/README.md
- acceptance/bundle/artifacts/whl_dynamic/databricks.yml
- acceptance/bundle/artifacts/whl_explicit/databricks.yml
- acceptance/bundle/telemetry/deploy-whl-artifacts/databricks.yml
- acceptance/bundle/templates/default-python/integration_classic/script
Document steps to make the acceptance tests pass on a fresh Windows VM.
The test runners use a different edition from the one you can install with Parallels.
Reproducing Windows-specific issues is easier interactively on a VM.
> Document prerequisites for running tests on Windows

- NEXT_CHANGELOG.md
- acceptance/bundle/environments/dependencies/databricks.yml
- acceptance/bundle/environments/dependencies/output.txt
- bundle/config/mutator/normalize_paths.go
- bundle/config/mutator/normalize_paths_test.go
- bundle/config/mutator/paths/job_libraries_paths_visitor.go
- bundle/config/mutator/paths/translation_mode.go
- bundle/config/mutator/translate_paths.go
- bundle/libraries/local_path.go
- bundle/libraries/local_path_test.go
Fix processing short pip flags in environment dependencies
Fixes https://github.com/databricks/cli/issues/3674
Added unit test case
> Fix processing short pip flags in environment dependencies

- acceptance/bundle/telemetry/deploy/output.txt
- acceptance/bundle/telemetry/deploy/script
The test checks that at least 5 mutators recorded execution times, but on fast machines, many mutators complete in under 1ms and are not recorded (per the threshold in bundle/mutator.go). This caused intermittent failures when exactly 5 mutators were recorded.
The test's purpose is to verify that the telemetry mechanism works, not to enforce a specific count. We changed the assertion to check for at least one recorded mutator execution time, making the test robust across all machine speeds.
This failed here https://github.com/databricks/cli/actions/runs/18225329786/job/51894965321
> Fix timing-related flakiness in telemetry acceptance test

- bundle/internal/schema/annotations_openapi_overrides.yml
- bundle/schema/jsonschema.json
- experimental/python/codegen/codegen/jsonschema_patch.py
- experimental/python/codegen/codegen/packages.py
- experimental/python/databricks/bundles/jobs/__init__.py
- experimental/python/databricks/bundles/jobs/_models/cluster_spec.py
- experimental/python/databricks/bundles/jobs/_models/kind.py
Fix missing `compute.Kind`. There is a single documented value that applies a behaviour different from the absent value.
Add an enum annotation because it's missing in the OpenAPI spec.
Fixes https://github.com/databricks/cli/issues/3622
Looking at the diff for the generated code
> [Python] Fix missing compute.Kind

- tools/gh_parse.py
- tools/gh_report.py
The gh_parse.py / gh_report.py scripts now download and parse known_failures.txt and highlight matching tests https://github.com/databricks/cli/blob/ciconfig/known_failures.txt
See https://github.com/databricks/cli/pull/3733
Additional context on test status.
Manually:
`~/work/cli-main % ./tools/gh_report.py --run 18343557422 --markdown`
|    | Env                | ✅pass | 💚RECOVERED | 🙈skip | 🟨KNOWN |
| -- | ------------------ | ------ | ----------- | ------ | ------- |
| 🟨 | aws linux          | 321    |             | 543    | 1       |
| 🟨 | aws windows        | 322    |             | 542    | 1       |
| 🟨 | aws-ucws linux     | 437    |             | 439    | 1       |
| 🟨 | aws-ucws windows   | 438    |             | 438    | 1       |
| 🟨 | azure linux        | 319    | 2 …
> Highlight known failures in PR tests summary
