cmd/auth/login.go
go.mod
go.sum

Added configure-cluster flag for auth login which will allow to configure cluster ID and save it in Databricks profile
Note: the build will fail until this one is merged and released
https://github.com/databricks/databricks-sdk-go/pull/524
```
andrew.nester@HFW9Y94129 cli % ./cli auth login https://xxxxxxx.databricks.com --configure-cluster
✔ Databricks Profile Name: my-profile█
Search: █
? Choose cluster:
10.1 ML beta (1029-yyyyy-xxxxxx)
10.5 ML standard cluster
12.2 LTS
↓ 13.1 free for all
andrew.nester@HFW9Y94129 cli % cat ~/.databrickscfg
[DEFAULT]
host       = https://xxxxx.databricks.com
cluster_id = 1029-xxxxx-yyyyy
auth_type  = databricks-cli
```

Added configure-cluster flag for auth login

---

cmd/sync/output.go
libs/cmdio/render.go
libs/git/reference.go

Removes carriage character from new line prints for json output mode and sync events
Manually

Remove \r from new line print statments

---

cmd/auth/login.go
libs/databrickscfg/loader.go
libs/databrickscfg/ops.go

When running `./cli auth login <host> --configure-cluster` and providing a new name, CLI failed with
```
Error: resolve: /Users/andrew.nester/.databrickscfg has no d123 profile configured. Config: host=<host>, profile=d123, databricks_cli_path=./cli. Env: DATABRICKS_CLI_PATH
```
In order to resolve this, we need to save profile information before we use it to configure a new client.
When configuring multiple profiles for the same host, CLI was failing with
```
Error: multiple profiles matched: my-demo-profile, aaaa, xxxx, bbbbb, asdasd, xxxxx
```
Running `./cli auth login <host> --configure-cluster` multiple times for the same host and different profile names succeeds

Fixed error on multiple profiles and failure to create a new profile with configured cluster

---

bundle/config/interpolation/interpolation.go
bundle/config/interpolation/interpolation_test.go

Modified interpolation logic to use: `\$\{([a-zA-Z]+([-_]*[a-zA-Z0-9]+)*(\.[a-zA-Z]+([-_]*[a-zA-Z0-9]+)*)*)\}`
**Edit**: Suggested by @pietern `\$\{([a-zA-Z]+([-_]?[a-zA-Z0-9]+)*(\.[a-zA-Z]+([-_]?[a-zA-Z0-9]+)*)*)\}` to be more selective and not allow consequent hyphens or underscores to make the keys more readable.
Explanation:
1. All interpolation starts with `${` and ends with `}`
2. All interpolated locations are split by by `.`
3. All sections are expected to start with a alphabet `[a-zA-Z]`; no numbers, hyphens or underscores.
4. All sections are expected to end with an alphanumeric `[a-zA-Z0-9]` no hyphens or underscores
This change allows the current interpolation to be more permissive.
**Note** it does break backwards compatibility because `[a-zA-Z] != [\w]`. `\w` includes …

Update variable regex to support hyphens

---

libs/filer/workspace_files_client.go

Use the download method from the SDK in the read method for the WSFS implementation of the filer interface.
Closes #452.
Tested by existing integration tests

Use direct download for workspace filer read

---

cmd/workspace/repos/overrides.go
internal/repos_test.go

The repos commands take a repo ID. It is more convenient to specify repos by their paths.
Closes #523.
New integration tests pass.

Allow specifying repo by path for repos commands

---

cmd/workspace/workspace/overrides.go
internal/workspace_test.go
libs/cmdio/render.go

Also see #525.
The direct download flag has been removed in newer versions because of the content type issue.
Instead, we can make the command decode the base64 output when the output mode is text.
```
$ databricks workspace export /some/path/script.sh
#!/bin/bash
echo "this is a script"
```
New integration test.

Decode contents by default in workspace export command

---

CHANGELOG.md

CLI:
* Add --absolute flag for ls command ([#508](https://github.com/databricks/cli/pull/508)).
* Add dbfs scheme prefix to paths in cp command output ([#516](https://github.com/databricks/cli/pull/516)).
* Add provider detection to the repos create command ([#528](https://github.com/databricks/cli/pull/528)).
* Added configure-cluster flag for auth login ([#500](https://github.com/databricks/cli/pull/500)).
* Added prompts for Databricks profile for auth login command ([#502](https://github.com/databricks/cli/pull/502)).
* Allow specifying repo by path for repos commands ([#526](https://github.com/databricks/cli/pull/526)).
* Decode contents by default in workspace export command ([#531](https://github.com/databricks/cli/pull/531)).
* Fixed jobs create command to only accept JSON payload …

Release v0.200.1

---

.codegen/cmds-workspace.go.tmpl
.codegen/service.go.tmpl
bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_test.go
bundle/deploy/terraform/convert_test.go
cmd/account/billable-usage/billable-usage.go
cmd/account/groups/groups.go
cmd/account/settings/settings.go
cmd/auth/login.go
cmd/workspace/clusters/clusters.go
cmd/workspace/dashboards/dashboards.go
cmd/workspace/groups/groups.go
cmd/workspace/instance-pools/instance-pools.go
cmd/workspace/jobs/jobs.go
cmd/workspace/pipelines/pipelines.go
cmd/workspace/queries/queries.go
cmd/workspace/secrets/secrets.go
cmd/workspace/serving-endpoints/serving-endpoints.go
cmd/workspace/system-schemas/system-schemas.go
go.mod
go.sum

* Regenerate CLI commands
* Ignore `account-access-control-proxy` (see #505)
Unit and integration tests pass.

Bump Go SDK to v0.12.0

---

cmd/workspace/secrets/overrides.go
internal/acc/debug.go
internal/acc/helpers.go
internal/acc/workspace.go
internal/secrets_test.go
libs/cmdio/io.go

Two issues with this command:
* The command line arguments for the secret value were ignored
* If the secret value was piped through stdin, it would still prompt
The second issue prevented users from using multi-line strings because the prompt reads until end-of-line.
This change adds testing infrastructure for:
* Setting up a workspace focused test (common between many tests)
* Running a snippet of Python through the command execution API
Porting more integration tests to use this infrastructure will be done in later commits.
New integration test passes.
The interactive path cannot be integration tested just yet.

Fix secrets put-secret command

---

bundle/phases/destroy.go

Adds the following steps to the destroy phase:
1. interpolate
2. write
Resolves #518 
Tested manually due there not being an examples for tests to use.

Fix: bundle destroy fails when bundle.tf.json file is deleted

---

.codegen/service.go.tmpl

Renamed method to HasRequiredNonBodyField in line with 
https://github.com/databricks/databricks-sdk-go/pull/536

Renamed method to HasRequiredNonBodyField

---

bundle/config/mutator/process_root_includes.go
bundle/config/mutator/process_root_includes_test.go
bundle/config/root.go
bundle/tests/include_invalid/bundle.yml
bundle/tests/include_test.go
bundle/tests/include_with_glob/bundle.yml
bundle/tests/include_with_glob/job.yml

Fixed error reporting when included invalid files in include section
Case 1. When the file to include is invalid, throw an error
Case 2. When the file is loaded but the schema is wrong, indicate which file is failed to load
With non-existent notexists.yml
```
databricks bundle deploy
Error: notexists.yml defined in 'include' section does not match any files
```
With malformed notexists.yml
```
databricks bundle deploy
Error: failed to load /Users/andrew.nester/dabs/wheel/notexists.yml: error unmarshaling JSON: json: cannot unmarshal string into Go value of type config.Root
```

Fixed error reporting when included invalid files in include section

---

bundle/internal/tf/schema/config.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/resource_catalog_workspace_binding.go
bundle/internal/tf/schema/resource_grants.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_model_serving.go
bundle/internal/tf/schema/resource_service_principal.go
bundle/internal/tf/schema/resource_sql_global_config.go
bundle/internal/tf/schema/resource_user.go
bundle/internal/tf/schema/resources.go

Generated from 47857a63c7242fc43aba833cdd28b222fd25c399 (next release after 1.20).
The change is additive and unit tests pass.

Update Terraform provider schema structs

---

bundle/config/root.go

Tested manually. `"workspace"` is no longer a required field in the generated JSON schema

Make top level workspace optional in JSON schema

---

CHANGELOG.md

CLI:
* Fix secrets put-secret command ([#545](https://github.com/databricks/cli/pull/545)).
* Fixed ignoring required positional parameters when --json flag is provided ([#535](https://github.com/databricks/cli/pull/535)).
* Update cp help message to not require file scheme ([#554](https://github.com/databricks/cli/pull/554)).
Bundles:
* Fix: bundle destroy fails when bundle.tf.json file is deleted ([#519](https://github.com/databricks/cli/pull/519)).
* Fixed error reporting when included invalid files in include section ([#543](https://github.com/databricks/cli/pull/543)).
* Make top level workspace optional in JSON schema ([#562](https://github.com/databricks/cli/pull/562)).
* Propagate TF_CLI_CONFIG_FILE env variable ([#555](https://github.com/databricks/cli/pull/555)).
* Update …

Release v0.200.2

---

cmd/root/auth.go
libs/databrickscfg/profiles.go

Currently, `databricks --profile <TAB>` autocompletes with the shell default behavior, listing files in the local directory. This is not a great experience. Especially given that the suggested profile names for accounts are so long, it can be cumbersome to type them out by hand. This PR configures autocompletion for `--profile` to inspect the profiles of ~/.databrickscfg.
One potential improvement is to filter the response based on whether the command is known to be account-level or workspace-level.
Manual test.

Support tab completion for profiles

---

libs/sync/path.go
libs/sync/path_test.go

Earlier we removed recursive deletion from sync. This makes it safe enough for us to not restrict sync to just the namespace of the user.
This PR removes that base path validation. 
Note: If the sync destination is under `/Repos` we still only create missing directories required if the path is under my namespace ie matches `/Repos/@me/`
Manually
Before:
```
shreyas.goenka@THW32HFW6T hello-bundle % cli bundle deploy
Starting upload of bundle files
Error: path must be nested under /Users/shreyas.goenka@databricks.com or /Repos/shreyas.goenka@databricks.com
```
After:
```
shreyas.goenka@THW32HFW6T hello-bundle % cli bundle deploy
Starting upload of bundle files
Uploaded bundle files at /Shared/common-test/hello-bundle/files!
Starting resource deployment
Resource deployment completed!
```

Remove base path checks during sync

---

.codegen.json
.codegen/changelog.md.tmpl

- added changelog template
- added `toolchain` to `.codegen.json`
none

Integrate with auto-release infra

---

libs/template/renderer.go

Due to a bug in Github UI, https://github.com/databricks/cli/pull/589 got merged without passing the go/fmt formatting checks
This PR fixes the formatting which breaks the PR checks

Fix formatting in renderer.go

---

.github/workflows/push.yml
bundle/tests/bundle/python_wheel/bundle.yml
bundle/tests/bundle/wheel_test.go

Fixed python wheel test

---

cmd/bundle/run.go
cmd/root/auth.go
cmd/root/bundle.go
cmd/root/bundle_test.go
cmd/root/io.go
cmd/root/logger.go
cmd/root/progress_logger.go
cmd/root/progress_logger_test.go
cmd/root/root.go

This change is another step towards a CLI without globals. Also see #595.
The flags for the root command are now encapsulated in struct types.

Remove dependency on global state for the root command

---

.github/workflows/push.yml

Also see [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).
n/a

Add merge_group trigger for build

---

internal/fs_cat_test.go
internal/fs_ls_test.go
internal/fs_mkdir_test.go
internal/fs_rm_test.go

Fs integration tests were not running on our nightlies before because the nightlies only run tests with the `TestAcc` prefix. A couple of them were also broken!
This PR fixes the tests and adds the prefix to all fs integration tests.
As a followup we can automate the check for this prefix.
Fs tests are green and pass on both azure and aws

Add TestAcc prefix to filer test and fix any failing tests

---

internal/fs_mkdir_test.go

GCP returns a different error here incase of a conflict. This PR fixes the test.

Fix mkdir integration test on GCP

---

.github/workflows/push.yml

Commits going through the merge queue are tested there using their final SHA as if they were already in main. The push-to-main trigger therefore duplicates the builds that were already triggered from the merge queue.

Remove push to main trigger for build workflow

---

bundle/config/environment.go
bundle/config/mutator/expand_workspace_root_test.go
bundle/config/mutator/populate_current_user.go
bundle/config/mutator/populate_current_user_test.go
bundle/config/mutator/process_environment_mode.go
bundle/config/mutator/process_environment_mode_test.go
bundle/config/workspace.go
bundle/deploy/files/sync.go
bundle/tests/job_and_pipeline/databricks.yml
internal/sync_test.go
libs/sync/path.go
libs/sync/sync.go

This adds `mode: production` option. This mode doesn't do any transformations but verifies that an environment is configured correctly for production:
```
environments:
prod:
mode: production
root_path: /Shared/non_user_path/...
run_as:
user_name: Alice
permissions:
- level: CAN_MANAGE
user_name: Alice
```
Additionally, this extends the existing `mode: development` option,
* now prefixing deployed assets with `[dev your.user]` instead of just `[dev`]
* validating that development deployments _are_ scoped to a user
https://github.com/databricks/cli/pull/578/files (in draft)
Manual testing to validate the experience, error messages, and functionality with all resource types. Automated unit tests.

Extend deployment mode support

---

internal/fs_mkdir_test.go

Regex check was missing a "." character and adding it in fixes the test. The test now passes on all three cloud providers

Fix failing fs mkdir test on azure

---

cmd/auth/login.go

A pretty annoying part of the current CLI experience is that when logging in with `databricks auth login`, you always need to type the name of the host. This seems unnecessary if you have already logged into a host before, since the CLI can read the previous host from your `.databrickscfg` file.
This change handles this case by setting the host if unspecified to the host in the corresponding profile. Combined with autocomplete, this makes the login process simple:
```
databricks auth login --profile prof<tab><enter>
```
Logged in to an existing profile by running the above command (but for a real profile I had).

Infer host from profile during login

---

bundle/libraries/libraries.go
bundle/tests/bundle/python_wheel/bundle.yml
bundle/tests/bundle/python_wheel_dbfs_lib/bundle.yml
bundle/tests/bundle/wheel_test.go

Some library paths such as for Spark jobs, can reference a lib on remote path, for example DBFS.
This PR fixes how CLI handles such libraries and do not report them as missing locally.
Added unit tests + ran `databricks bundle deploy` manually

Fixed processing jobs libraries with remote path

---

libs/template/renderer_test.go

Adds a Unit test that directories and files in the file tree are executed as templates

Add unit test for file name execution during rendering

---

CHANGELOG.md

CLI:
* Infer host from profile during `auth login` ([#629](https://github.com/databricks/cli/pull/629)).
Bundles:
* Extend deployment mode support ([#577](https://github.com/databricks/cli/pull/577)).
* Add validation for Git settings in bundles ([#578](https://github.com/databricks/cli/pull/578)).
* Only treat files with .tmpl extension as templates ([#594](https://github.com/databricks/cli/pull/594)).
* Add JSON schema validation for input template parameters ([#598](https://github.com/databricks/cli/pull/598)).
* Add DATABRICKS_BUNDLE_INCLUDE_PATHS to specify include paths through env vars ([#591](https://github.com/databricks/cli/pull/591)).
* Initialise a empty default bundle if BUNDLE_ROOT and DATABRICKS_BUNDLE_INCLUDES env vars are present …

Release v0.203.0

---

bundle/config/environment.go
bundle/config/workspace.go
bundle/schema/schema.go
bundle/schema/schema_test.go

This PR:
1. Introduces the "internal" tag to bundle configs that should not be visible to customers.
2. Annotates "metadata_service_url" as an internal field.
Unit tests.

Add internal tag for bundle fields to be skipped from schema

---

bundle/bundle.go
bundle/bundle_test.go
bundle/root_test.go
bundle/tests/bundle/wheel_test.go
bundle/tests/conflicting_resource_ids_test.go
bundle/tests/include_test.go
bundle/tests/loader.go
cmd/root/bundle.go
cmd/root/bundle_test.go

Pass through the `context.Context` to the bundle loader functions.

Log the bundle root configuration file if applicable

---

libs/template/renderer.go
libs/template/renderer_test.go
libs/template/testdata/template-in-path/library/my_funcs.tmpl

The `.tmpl` extension is only meant as a qualifier for whether the file content is executed as a template. All file paths in the `template` directory should be treated as valid go text templates. 
Before only paths with the `.tmpl` extensions would be resolved as templates, after this change, all file paths are interpreted as templates.
Unit test. The newly added unit tests also asserts that the file path is correct, even when the `.tmpl` extension is missing.

Execute paths without the .tmpl extension as templates

---

bundle/config/resources.go
bundle/config/resources/job.go
bundle/config/resources/job_test.go
bundle/config/root.go
bundle/tests/override_job_cluster/databricks.yml
bundle/tests/override_job_cluster_test.go

While they are a slice, we can identify a job cluster by its job cluster key. A job definition with multiple job clusters with the same key is always invalid.  We can therefore merge definitions with the same key into one. This is compatible with how environment overrides are applied; merging a slice means appending to it. The override will end up in the job cluster slice of the original, which gives us a deterministic way to merge them.
Since the alternative is an invalid configuration, this doesn't change behavior.
New test coverage.

Enable environment overrides for job clusters

---

cmd/auth/env.go
cmd/auth/login.go
cmd/auth/profiles.go
cmd/root/auth.go
libs/databrickscfg/profiles.go
libs/databrickscfg/profiles_test.go

#629 introduced a change to autopopulate the host from .databrickscfg if the user is logging back into a host they were previously using. This did not respect the DATABRICKS_CONFIG_FILE env variable, causing the flow to stop working for users with no .databrickscfg file in their home directory.
This PR refactors all config file loading to go through one interface, `databrickscfg.GetDatabricksCfg()`, and an auxiliary `databrickscfg.GetDatabricksCfgPath()` to get the configured file path. 
Closes #655.
```
$ databricks auth login --profile abc
Error: open /Users/miles/.databrickscfg: no such file or directory
$ ./cli auth login --profile abc
Error: cannot load Databricks config file: open /Users/miles/.databrickscfg: no such file or directory
$ DATABRICKS_CONFIG_FILE=~/.databrickscfg.bak …
```

Always resolve .databrickscfg file

---

bundle/deploy/terraform/init.go

Locked terraform binary version to <= 1.5.5

Locked terraform binary version to <= 1.5.5

---

libs/jsonschema/schema.go
libs/jsonschema/schema_test.go
libs/template/config.go
libs/template/config_test.go
libs/template/utils.go
libs/template/utils_test.go

Adds a function to validate json schema types added by the author. The default json unmarshaller does not validate that the parsed type matches the enum defined in `jsonschema.Type`
Includes some other improvements to provide better error messages.
This PR was prompted by usability difficulties reported by @mingyu89 during mlops stack migration.
Unit tests

Return better error messages for invalid JSON schema types in templates

---

libs/template/helpers.go
libs/template/helpers_test.go
libs/template/testdata/map-pair/library/abc.tmpl
libs/template/testdata/map-pair/template/hello.tmpl

Go text templates allows only specifying one input argument for invocations of associated templates (ie `{{template ...}}`). This PR introduces the map and pair functions which allow template authors to work around this limitation by passing multiple arguments as key value pairs in a map.
This PR is based on feedback from the mlops stacks migration where otherwise a bunch of duplicate code is required for computed values and fixtures.
Unit test

Add map and pair helper functions for bundle templates

---

cmd/bundle/deploy.go
internal/locker_test.go
libs/locker/locker.go

As discussed here, the name for this flag should be `force-lock`: https://github.com/databricks/cli/pull/578#discussion_r1276233445
Manually and existing tests

Correct name for force acquire deploy flag

---

bundle/tests/environment_overrides/resources/databricks.yml
bundle/tests/environment_overrides_test.go

This is not desirable and will be addressed by representing our configuration in a different structure (e.g. with cty, or with 
plain `any`), instead of Go structs.
Pass.

Confirm that override with a zero value doesn't work

---

CHANGELOG.md

CLI:
* Always resolve .databrickscfg file ([#659](https://github.com/databricks/cli/pull/659)).
Bundles:
* Add internal tag for bundle fields to be skipped from schema ([#636](https://github.com/databricks/cli/pull/636)).
* Log the bundle root configuration file if applicable ([#657](https://github.com/databricks/cli/pull/657)).
* Execute paths without the .tmpl extension as templates ([#654](https://github.com/databricks/cli/pull/654)).
* Enable environment overrides for job clusters ([#658](https://github.com/databricks/cli/pull/658)).
* Merge artifacts and resources block with overrides enabled ([#660](https://github.com/databricks/cli/pull/660)).
* Locked terraform binary version to <= 1.5.5 ([#666](https://github.com/databricks/cli/pull/666)).
* Return better error messages for …

Release v0.203.1

---

bundle/artifacts/whl/autodetect.go
bundle/libraries/libraries.go

Fixes #673 
It also includes a change for `libraries` from #635 to get the list of wheel tasks

Do not try auto detect Python package if no Python wheel tasks defined

---

cmd/bundle/init.go
libs/template/materialize.go

This PR:
1. Renames the project-dir flag to output-dir
2. Makes the project dir flag optional. When unspecified we default to the current working directory.
Manually

Rename init project-dir flag to output-dir

---

libs/fileset/fileset.go
libs/git/fileset.go
libs/git/fileset_test.go
libs/git/repository.go
libs/git/testdata/.gitignore
libs/git/view_test.go

The pattern `.*` in a `.gitignore` file can match `.` when walking all files in a repository. If it does, then the walker immediately aborts and no files are returned. The root directory (an unnamed directory) must never be ignored.
Reported in https://github.com/databricks/databricks-vscode/issues/837.
New tests pass.

Never ignore root directory when enumerating files in a repository

---

cmd/account/o-auth-enrollment/overrides.go
libs/cmdio/io.go

This command takes the user through the interactive flow to set up OAuth for a fresh account, where only Basic authentication works.

Added `databricks account o-auth-enrollment enable` command

---

CHANGELOG.md

CLI:
* Added `databricks account o-auth-enrollment enable` command ([#687](https://github.com/databricks/cli/pull/687)).
Bundles:
* Do not try auto detect Python package if no Python wheel tasks defined ([#674](https://github.com/databricks/cli/pull/674)).
* Renamed `environments` to `targets` in bundle configuration ([#670](https://github.com/databricks/cli/pull/670)).
* Rename init project-dir flag to output-dir ([#676](https://github.com/databricks/cli/pull/676)).
* Added support for sync.include and sync.exclude sections ([#671](https://github.com/databricks/cli/pull/671)).
* Add template directory flag for bundle templates ([#675](https://github.com/databricks/cli/pull/675)).
* Never ignore root directory when enumerating files in a repository …

Release v0.203.2

---

.gitignore
.vscode/__builtins__.pyi
.vscode/settings.json
bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go
cmd/bundle/init.go
cmd/root/auth.go
cmd/root/bundle.go
libs/auth/service_principal.go
libs/databrickscfg/profiles.go
libs/template/helpers.go
libs/template/helpers_test.go
libs/template/materialize.go
libs/template/renderer.go
libs/template/renderer_test.go
libs/template/templates/default-python/databricks_template_schema.json
libs/template/templates/default-python/defaults.json
libs/template/templates/default-python/template/{{.project_name}}/README.md
libs/template/testdata/workspace-host/template/file.tmpl

This pull request extends the templating support in preparation of a new, default template (WIP, https://github.com/databricks/cli/pull/686):
* builtin templates that can be initialized using e.g. `databricks bundle init default-python`
* builtin templates are embedded into the executable using go's `embed` functionality, making sure they're co-versioned with the CLI
* new helpers to get the workspace name, current user name, etc. help craft a complete template
* (not enabled yet) when the user types `databricks bundle init` they can interactively select the `default-python` template
And makes two tangentially related changes:
* IsServicePrincipal now uses the "users" API rather than the "principals" API, since the latter is too slow for our purposes.
* mode: prod no longer requires the …

Add a foundation for built-in templates

---

bundle/config/mutator/override_compute.go
bundle/config/mutator/override_compute_test.go

Support `databricks bundle deploy --compute-id my_all_purpose_cluster` in two missing cases.

Support cluster overrides with cluster_key and compute_key

---

cmd/root/bundle.go
cmd/root/bundle_test.go

Fixed --environment flag
Fixes https://github.com/databricks/setup-cli/issues/35

Fixed --environment flag

---

bundle/libraries/libraries.go
bundle/libraries/libraries_test.go
bundle/tests/bundle/wheel_test.go

Correctly identify local paths in libraries section

---

CHANGELOG.md

Bundles:
* Support cluster overrides with cluster_key and compute_key ([#696](https://github.com/databricks/cli/pull/696)).
* Allow referencing local Python wheels without artifacts section defined ([#703](https://github.com/databricks/cli/pull/703)).
* Fixed --environment flag ([#705](https://github.com/databricks/cli/pull/705)).
* Correctly identify local paths in libraries section ([#702](https://github.com/databricks/cli/pull/702)).
* Fixed path joining in FindFilesWithSuffixInPath ([#704](https://github.com/databricks/cli/pull/704)).
*  Added transformation mutator for Python wheel task for them to work on DBR <13.1 ([#635](https://github.com/databricks/cli/pull/635)).
Internal:
* Add a foundation for built-in templates ([#685](https://github.com/databricks/cli/pull/685)).
* Test …

Release v0.203.3

---

.github/workflows/push.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml

Version 4 enables caching by default so we no longer need to explicitly enable it: https://github.com/actions/setup-go#v4.
The build cache only reuses a cache from a repo's default branch, which for this repository is `main`. After enabling the merge queue, we no longer run builds on the `main` branch after push, but on merge queue branches. With no more builds on the `main` branch there is no longer a cache to reuse.
This change fixes that by making the `release(-snapshot)?` workflows use the same caching mechanism. These run off of the `main` branch, so the cache they save can be reused by builds triggered on PRs or from the merge queue.
We have to merge this to see if it works.

Upgrade to actions/setup-go@v4

---

bundle/artifacts/artifacts.go
bundle/artifacts/artifacts_test.go
bundle/python/transform.go

Fixed artifact file uploading on Windows and wheel execution on DBR 13.3
Fixes #719, #720
Added regression test for Windows

Fixed artifact file uploading on Windows and wheel execution on DBR 13.3

---

cmd/cmd.go

Before:
```
Usage:
databricks instance-pools [command]
Available Commands:
create                Create a new instance pool.
delete                Delete an instance pool.
edit                  Edit an existing instance pool.
get                   Get instance pool information.
get-permission-levels Get instance pool permission levels.
get-permissions       Get instance pool permissions.
list                  List instance pool info.
set-permissions       Set instance pool permissions.
update-permissions    Update instance pool permissions.
```
After:
```
Usage:
databricks instance-pools [command]
Available Commands
create                Create a new instance pool.
delete                Delete an instance pool.
edit                  Edit an existing instance pool.
get …
```

Group permission related commands

---

.github/workflows/push.yml

* Run the build workflow on push to main to properly use the build cache
Same as https://github.com/databricks/databricks-sdk-go/pull/601.
n/a

Work on GitHub Action

---

cmd/root/auth.go
cmd/root/auth_test.go

This reduces the latency of every workspace command by the duration of a single API call to retrieve the current user (which can take up to a full second).
Note: the better place to verify that a request can be authenticated is the SDK itself.
* Unit test to confirm an the empty `*http.Request` can be constructed
* Manually confirmed that the additional API call no longer happens

Replace API call to test configuration with dummy authenticate call

---

bundle/config/mutator/process_target_mode.go
libs/auth/service_principal.go
libs/auth/service_principal_test.go
libs/template/helpers.go

The latest rendition of isServicePrincipal no longer worked for non-admin users as it used the "principals get" API.
This new version relies on the property that service principals always have a UUID as their userName. This was tested with the eng-jaws principal (8b948b2e-d2b5-4b9e-8274-11b596f3b652).

Fix IsServicePrincipal() only working for workspace admins

---

internal/fs_mkdir_test.go

Fixes test for all cloud provider after the Go SDK bump which introduces the `non retryable error` prefix to errors. The test passes now.

Fix regex error check in mkdir integration test

---

libs/template/templates/default-python/template/__preamble.tmpl

This fixes a typo that caused the notebook.ipynb file to show up even if the user answered "no" to the question about including a notebook.
We have matrix validation tests for all the yes/no combinations and whether the build + validate. There is no current test for the absence of files.

Fix notebook showing up in template when not selected

---

bundle/deploy/terraform/convert.go
bundle/deploy/terraform/convert_test.go

Another example of singular/plural conversion.
Longer term solution is we do a full sweep of the type using reflection to make sure we cover all fields.
Unit test passes.

Fix conversion of job parameters

---

bundle/deploy/terraform/init.go
internal/bundle/bundles/python_wheel_task/databricks_template_schema.json
internal/bundle/bundles/python_wheel_task/template/databricks.yml.tmpl
internal/bundle/bundles/python_wheel_task/template/setup.py.tmpl
internal/bundle/bundles/python_wheel_task/template/{{.project_name}}/__init__.py
internal/bundle/bundles/python_wheel_task/template/{{.project_name}}/__main__.py
internal/bundle/helpers.go
internal/bundle/python_wheel_test.go
internal/helpers.go

Added end-to-end test for deploying and running Python wheel task
Test successfully passed on all environments, takes about 9-10 minutes to pass.
```
Deleted snapshot file at /var/folders/nt/xjv68qzs45319w4k36dhpylc0000gp/T/TestAccPythonWheelTaskDeployAndRun1845899209/002/.databricks/bundle/default/sync-snapshots/1f7cc766ffe038d6.json
Successfully deleted files!
2023/09/06 17:50:50 INFO Releasing deployment lock mutator=destroy mutator=seq mutator=seq mutator=deferred mutator=lock:release
--- PASS: TestAccPythonWheelTaskDeployAndRun (508.16s)
PASS
coverage: 77.9% of statements in ./...
ok      github.com/databricks/cli/internal/bundle       508.810s        coverage: 77.9% of statements in ./...
```

Added end-to-end test for deploying and running Python wheel task

---

bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go
bundle/config/resources.go
bundle/config/resources/model_serving_endpoint.go
bundle/deploy/terraform/convert.go
bundle/deploy/terraform/convert_test.go
bundle/deploy/terraform/interpolate.go
bundle/schema/docs/bundle_descriptions.json
bundle/schema/openapi.go
bundle/tests/model_serving_endpoint/databricks.yml
bundle/tests/model_serving_endpoint_test.go

Add Model Serving Endpoints to Databricks Bundles
Unit tests and manual testing via https://github.com/databricks/bundle-examples-internal/pull/76

Support Model Serving Endpoints in bundles

---

internal/bundle/bundles/python_wheel_task/template/databricks.yml.tmpl

It helps to make sure jobs in the tests are deployed and executed uniquely and isolated
```
Bundle remote directory is /Users/61b77d30-bc10-4214-9650-29cf5db0e941/.bundle/4b630810-5edc-4d8f-85d1-0eb5baf7bb28
Deleted snapshot file at /var/folders/nt/xjv68qzs45319w4k36dhpylc0000gp/T/TestAccPythonWheelTaskDeployAndRun3933198431/001/.databricks/bundle/default/sync-snapshots/dd9db100465e3d91.json
Successfully deleted files!
--- PASS: TestAccPythonWheelTaskDeployAndRun (346.28s)
PASS
coverage: 93.5% of statements in ./...
ok      github.com/databricks/cli/internal/bundle       346.976s        coverage: 93.5% of statements in ./...
```

Use unique bundle root path for Python E2E test

---

bundle/run/output/job.go

Do not include empty output in job run output
Running a job from CLI, the result:
```
andrew.nester@HFW9Y94129 wheel % databricks bundle run some_other_job --output json
Run URL: https://***/?o=6051921418418893#job/780620378804085/run/386695528477456
2023-09-08 11:33:24 "[default] My Wheel Job" TERMINATED SUCCESS 
{
"task_outputs": [
{
"TaskKey": "TestTask",
"Output": {
"result": "Hello from my func\nGot arguments v2:\n['python']\n"
},
"EndTime": 1694165597474
}
]
```

Do not include empty output in job run output

---

bundle/deploy/terraform/state_push.go

Close local Terraform state file when pushing to remote
Should help fix E2E test cleanup
```
testing.go:1225: TempDir RemoveAll cleanup: remove 
C:\Users\RUNNER~1\AppData\Local\Temp\TestAccPythonWheelTaskDeployAndRun1395546390\001\.databricks\bundle\default\terraform\terraform.tfstate: 
The process cannot access the file because it is being used by another process.
```

Close local Terraform state file when pushing to remote

---

bundle/artifacts/whl/autodetect.go
bundle/artifacts/whl/from_libraries.go
bundle/libraries/libraries.go
bundle/python/transform.go
bundle/python/transform_test.go

Process only Python wheel tasks which have local libraries used
Updated uni test to catch the regression

Process only Python wheel tasks which have local libraries used

---

python/utils.go

Close python wheel directory file descriptor after read

Close python wheel directory file descriptor after read

---

bundle/config/root.go
bundle/schema/docs/bundle_descriptions.json

This PR:
1. Makes the bundle and sync properties optional in the generated schema. 
2. Fixes schema generation that was broken due to a rogue "description" field in the bundle docs.
Tested manually. The generated schema no longer has "bundle" and "sync" marked as required.

Make bundle and sync fields optional

---

cmd/bundle/init.go

This PR fixes a bug where the temp directory created to download the template would not be cleaned up.
Tested manually. The exact process is described in a comment below.

Fix temporary directory cleanup for init repository downloading

---

CHANGELOG.md

Bundles:
* Fix conversion of job parameters ([#744](https://github.com/databricks/cli/pull/744)).
* Add schema and config validation to jsonschema package ([#740](https://github.com/databricks/cli/pull/740)).
* Support Model Serving Endpoints in bundles ([#682](https://github.com/databricks/cli/pull/682)).
* Do not include empty output in job run output ([#749](https://github.com/databricks/cli/pull/749)).
* Fixed marking libraries from DBFS as remote ([#750](https://github.com/databricks/cli/pull/750)).
* Process only Python wheel tasks which have local libraries used ([#751](https://github.com/databricks/cli/pull/751)).
* Add enum support for bundle templates ([#668](https://github.com/databricks/cli/pull/668)).
* Apply Python wheel trampoline if workspace library is used …

Release v0.204.1

---

bundle/config/interpolation/interpolation.go
bundle/config/interpolation/interpolation_test.go

This PR makes the error message clearer for when interpolation fails. 
Existing unit test and manually

Use clearer error message when no interpolation value is found.

---

cmd/root/auth.go
cmd/root/auth_test.go
libs/cmdio/io.go
libs/cmdio/testing.go

The previous implementation ran the risk of infinite looping for the account client due to a mismatch in determining what constitutes an account client between the CLI and SDK (see [here](https://github.com/databricks/cli/blob/83443bae8d8ad4df3758f4192c6bbe613faae9c4/libs/databrickscfg/profiles.go#L61) and [here](https://github.com/databricks/databricks-sdk-go/blob/0fdc5165e57a4e7af6ec97b47595c6dddf37b10b/config/config.go#L160)).
Ultimately, this code must never infinite loop. If a user is prompted and selects a profile that cannot be used, they should receive that feedback immediately and try again, instead of being prompted again.
Related to #726.

Prompt once for a client profile

---

bundle/run/job.go
bundle/run/keys.go
bundle/run/pipeline.go
bundle/run/runner.go
cmd/bundle/run.go

Display an interactive prompt with a list of resources to run if one isn't specified and the command is run interactively.
Manually confirmed:
* The new prompt works
* Shell completion still works
* Specifying a key argument still works

Use interactive prompt to select resource to run if not specified

---

cmd/root/auth_test.go
cmd/root/bundle_test.go
internal/testutil/env.go

If the caller running the test has one or more environment variables that are used in the test already set, they can interfere and make tests fail.
Ran tests in `./cmd/root` with Databricks related environment variables set.

Run environment related tests in a pristine environment

---

cmd/bundle/bundle.go

Help output:
```
shreyas.goenka@THW32HFW6T ~ % cli bundle -h
Databricks Asset Bundles.
Documentation URL: https://docs.databricks.com/en/dev-tools/bundles.
Usage:
databricks bundle [command]
```

Add documentation link bundle command group description

---

CHANGELOG.md

This release marks the public preview phase of Databricks Asset Bundles.
For more information, please refer to our online documentation at
https://docs.databricks.com/en/dev-tools/bundles/.
CLI:
* Prompt once for a client profile ([#727](https://github.com/databricks/cli/pull/727)).
Bundles:
* Use clearer error message when no interpolation value is found. ([#764](https://github.com/databricks/cli/pull/764)).
* Use interactive prompt to select resource to run if not specified ([#762](https://github.com/databricks/cli/pull/762)).
* Add documentation link bundle command group description ([#770](https://github.com/databricks/cli/pull/770)).

Release v0.205.0

---

libs/template/templates/default-python/databricks_template_schema.json

This PR changes schema to use the enum type for the default template yes/no questions.
Manually

Use enums for default python template

---

bundle/bundle.go
bundle/deploy/terraform/apply.go
bundle/deploy/terraform/convert.go
bundle/deploy/terraform/convert_test.go
bundle/deploy/terraform/state_push.go
bundle/deploy/terraform/write.go
internal/bundle/bundles/deploy_then_remove_resources/databricks_template_schema.json
internal/bundle/bundles/deploy_then_remove_resources/template/databricks.yml.tmpl
internal/bundle/bundles/deploy_then_remove_resources/template/foo.py
internal/bundle/bundles/deploy_then_remove_resources/template/resources.yml.tmpl
internal/bundle/bundles/empty_bundle/databricks.yml
internal/bundle/deploy_then_remove_resources_test.go
internal/bundle/empty_bundle_test.go

This PR sets "resource" to nil in the terraform representation if no resources are defined in the bundle configuration. This solves two problems:
1. Makes bundle deploy work without any resources specified. 
2. Previously if a `resources` block was removed after a deployment, that would fail with an error. Now the resources would get destroyed as expected.
Also removes `TerraformHasNoResources` which is no longer needed.
New e2e tests.

Make bundle deploy work if no resources are defined

---

internal/init_test.go
internal/testdata/init/field-does-not-exist/databricks_template_schema.json
internal/testdata/init/field-does-not-exist/template/bar.tmpl
libs/template/renderer.go
libs/template/renderer_test.go

Error when unknown keys are encounters during template execution

---

libs/git/clone.go
libs/git/clone_test.go

Git repos hosted over HTTP do not support shallow cloning. This PR adds retry logic if we detect shallow cloning is not supported. 
Note I saw the match string `dumb http transport does not support shallow capabilities` being reported in for different hosts on the internet, so this should work accross a large class of git servers. Howerver, it's not strictly necessary to have the `--depth` flag so we can remove it if this issue is reported again.
Tested manually. `bundle init` successfully downloads the private HTTP repo reported during by internal user.

Fall back to full Git clone if shallow clone is not supported

---

go.mod
go.sum

This bump includes:
* A fix for token refreshes on Azure
* A fix for retrying requests without a request body (e.g. GET)
Full comparison at https://github.com/databricks/databricks-sdk-go/compare/v0.19.1...dacb7f4fc878.
n/a

Update Go SDK to v0.19.3 (unreleased)

---

bundle/config/resources.go
bundle/config/resources/job.go
bundle/config/resources/job_test.go
bundle/config/root.go
bundle/tests/override_job_tasks/databricks.yml
bundle/tests/override_job_tasks_test.go

Follow up for https://github.com/databricks/cli/pull/658
When a job definition has multiple job tasks using the same key, it's considered invalid. Instead we should combine those definitions with the same key into one. This is consistent with environment overrides. This way, the override ends up in the original job tasks, and we've got a clear way to put them all together.

Enable environment overrides for job tasks

---

bundle/run/job.go

It's not uncommon for job runs to take more than 2 hours. On the client side, we should not stop waiting for a job to complete if it is intentionally running for a long time. If a job isn't supposed to run this long, the user can specify a run timeout in the job specification itself.
n/a

Increase timeout waiting for job run to 1 day

---

CHANGELOG.md

Bundles:
* Use enums for default python template ([#765](https://github.com/databricks/cli/pull/765)).
* Make bundle deploy work if no resources are defined ([#767](https://github.com/databricks/cli/pull/767)).
* Added support for experimental scripts section ([#632](https://github.com/databricks/cli/pull/632)).
* Error when unknown keys are encounters during template execution ([#766](https://github.com/databricks/cli/pull/766)).
* Fall back to full Git clone if shallow clone is not supported ([#775](https://github.com/databricks/cli/pull/775)).
* Enable environment overrides for job tasks ([#779](https://github.com/databricks/cli/pull/779)).
* Increase timeout waiting for job run to 1 day ([#786](https://github.com/databricks/cli/pull/786)).
Internal:
* Update Go SDK to v0.19.3 …

Release v0.205.1

---

cmd/auth/login.go

Do not prompt for profiles if not in interactive mode
Running sample Go code
```
cmd := exec.Command("databricks", "auth", "login", "--host", "***")
out, err := cmd.CombinedOutput()
```
Before the change
```
Error: ^D
exit status 1
```
After
```
No error (empty output)
```

Prompt for profile only in interactive mode

---

bundle/config/resources.go
bundle/config/resources/pipeline.go
bundle/config/resources/pipeline_test.go
bundle/config/root.go
bundle/tests/override_pipeline_cluster/databricks.yml
bundle/tests/override_pipeline_cluster_test.go

This is a follow-up to #658 and #779 for jobs.
This change applies label normalization the same way the backend does.
Unit and config loading tests.

Enable target overrides for pipeline clusters

---

bundle/config/experimental.go
bundle/config/mutator/if.go
bundle/config/mutator/noop.go
bundle/python/conditional_transform_test.go
bundle/python/transform.go
bundle/python/transform_test.go
internal/bundle/bundles/python_wheel_task/databricks_template_schema.json
internal/bundle/bundles/python_wheel_task/template/databricks.yml.tmpl
internal/bundle/python_wheel_test.go

Instead of always using notebook wrapper for Python wheel tasks, let's make this an opt-in option.
Now by default Python wheel tasks will be deployed as is to Databricks platform.
If notebook wrapper required (DBR < 13.1 or other configuration differences), users can provide a following experimental setting
```
experimental:
python_wheel_wrapper: true
```
Fixes #783, https://github.com/databricks/databricks-asset-bundles-dais2023/issues/8
Added unit tests.
Integration tests passed for both cases
```
helpers.go:163: [databricks stdout]: Hello from my func
helpers.go:163: [databricks stdout]: Got arguments:
helpers.go:163: [databricks stdout]: ['my_test_code', 'one', 'two']
...
Bundle remote directory is ***/.bundle/ac05d5e8-ed4b-4e34-b3f2-afa73f62b021
Deleted snapshot file at …
```

Make a notebook wrapper for Python wheel tasks optional

---

bundle/phases/initialize.go
bundle/python/warning.go
bundle/python/warning_test.go

Added a warning when Python wheel wrapper needs to be used
Added unit tests + manual run with different bundle configurations

Added a warning when Python wheel wrapper needs to be used

---

bundle/config/artifact.go
bundle/scripts/scripts.go
libs/env/context.go
libs/env/context_test.go
libs/git/clone.go
libs/process/background.go
libs/process/background_test.go
libs/process/forwarded.go
libs/process/forwarded_test.go
libs/process/opts.go
libs/process/opts_test.go
python/runner.go
python/runner_test.go

This PR adds higher-level wrappers for calling subprocesses. One of the steps to get https://github.com/databricks/cli/pull/637 in, as previously discussed.
The reason to add `process.Forwarded()` is to proxy Python's `input()` calls from a child process seamlessly. Another use-case is plugging in `less` as a pager for the list results.
`make test`

Added `process.Background()` and `process.Forwarded()`

---

CHANGELOG.md

Bundles:
* Enable target overrides for pipeline clusters ([#792](https://github.com/databricks/cli/pull/792)).
* Add support for regex patterns in template schema ([#768](https://github.com/databricks/cli/pull/768)).
* Make the default `databricks bundle init` template more self-explanatory ([#796](https://github.com/databricks/cli/pull/796)).
* Make a notebook wrapper for Python wheel tasks optional ([#797](https://github.com/databricks/cli/pull/797)).
* Added a warning when Python wheel wrapper needs to be used ([#807](https://github.com/databricks/cli/pull/807)).
Internal:
* Added `process.Background()` and `process.Forwarded()` ([#804](https://github.com/databricks/cli/pull/804)).
* Bump golang.org/x/term from 0.11.0 to 0.12.0 …

Release v0.206.0

---

bundle/config/mutator/populate_current_user.go
bundle/config/mutator/populate_current_user_test.go

Digits were previously replaced by `_`.
Additional test cases with uncommon variations of email addresses.

Allow digits in the generated short name

---

internal/bundle/tags_test.go
internal/tags_test.go
internal/testutil/cloud.go
internal/testutil/env.go
internal/testutil/requirement.go

Validation rules on tags are different per cloud (they are passed through to the underlying clusters and as such must comply with cloud-specific validation rules). This change adds tests to confirm the current behavior to ensure the normalization we can apply is in line with how the backend behaves.
The new integration tests pass (tested locally).

Run tests to verify backend tag validation behavior

---

internal/bundle/tags_test.go
internal/tags_test.go
internal/testutil/cloud.go
internal/testutil/env.go
internal/testutil/requirement.go
libs/tags/aws.go
libs/tags/aws_test.go
libs/tags/azure.go
libs/tags/azure_test.go
libs/tags/cloud.go
libs/tags/cloud_test.go
libs/tags/gcp.go
libs/tags/gcp_test.go
libs/tags/latin.go
libs/tags/latin_test.go
libs/tags/tag.go
libs/tags/transform.go
libs/tags/transform_test.go

Prompted by the proposed fix for a tagging-related problem in #810, I investigated how tag validation works. This turned out to be quite a bit more complex than anticipated. Tags at the job level (or cluster level) are passed through to the underlying compute infrastructure and as such are tested against cloud-specific validation rules. GCP appears to be the most restrictive. It would be disappointing to always restrict to `\w+`, so this package implements validation and normalization rules for each cloud. It can pick the right cloud to use using a Go SDK configuration.
Exhaustive unit tests. The regular expressions were pulled by #814.

Library to validate and normalize cloud specific tags

---

bundle/python/warning.go
bundle/python/warning_test.go

Follow up for https://github.com/databricks/cli/pull/807 to also validate configuration if existing cluster id is used.

Emit an error when incompatible all purpose cluster used with Python wheel tasks

---

bundle/bundle.go
bundle/config/mutator/populate_current_user.go
bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go
libs/template/renderer_test.go

The jobs backend propagates job tags to the underlying cloud provider's resources. As such, they need to match the constraints a cloud provider places on tag values. The display name can contain anything. With this change, we modify the tag value to equal the short name as used in the name prefix.
Additionally, we leverage tag normalization as introduced in #819 to make sure characters that aren't accepted are removed before using the value as a tag value.
This is a new stab at #810 and should completely eliminate this class of problems.
Tests pass.

Use normalized short name for tag value in development mode

---

CHANGELOG.md

CLI:
* Refactor change computation for sync ([#785](https://github.com/databricks/cli/pull/785)).
Bundles:
* Allow digits in the generated short name ([#820](https://github.com/databricks/cli/pull/820)).
* Emit an error when incompatible all purpose cluster used with Python wheel tasks ([#823](https://github.com/databricks/cli/pull/823)).
* Use normalized short name for tag value in development mode ([#821](https://github.com/databricks/cli/pull/821)).
* Added `python.DetectInterpreters` and other utils ([#805](https://github.com/databricks/cli/pull/805)).
* Mark artifacts properties as optional ([#834](https://github.com/databricks/cli/pull/834)).
* Added support for glob patterns in pipeline libraries section ([#833](https://github.com/databricks/cli/pull/833)).
Internal:
* Run tests to …

Release v0.207.0

---

internal/workspace_test.go

We should be using the path package here because they are paths in WSFS

Fix import export integration tests on windows

---

internal/workspace_test.go

Windows and unix have different new line characters. Separating the string assertions here to make the test pass.

Fix workspace import test

---

bundle/config/mutator/expand_pipeline_glob_paths.go
bundle/config/mutator/expand_pipeline_glob_paths_test.go
bundle/libraries/libraries.go
bundle/libraries/libraries_test.go

Fixed using repo files as pipeline libraries

Fixed using repo files as pipeline libraries

---

libs/fileset/glob.go
libs/fileset/glob_test.go
libs/fileset/ignorer.go
libs/sync/sync.go
libs/sync/sync_test.go

Support .gitignore syntax in sync section and make sure it works recursively

---

.github/workflows/release.yml

Automatically create a release PR in homebrew-tap repo
Ran ` act -j create-homebrew-tap-release-pr -s DECO_GITHUB_TOKEN="$(gh auth token)"`
Result: https://github.com/databricks/homebrew-tap/pull/29

Automatically create a release PR in homebrew-tap repo

---

bundle/config/root.go
bundle/config/target.go
bundle/tests/override_sync/databricks.yml
bundle/tests/override_sync_no_root/databricks.yml
bundle/tests/override_sync_test.go

Allow target overrides for sync section
Added tests

Allow target overrides for sync section

---

cmd/auth/login.go
cmd/auth/token.go

Use stored profile information when the user provides the profile flag when using the `databricks auth token` command.
Run the command with and without the profile flag
```
./cli auth token
Databricks Host: https://e2-dogfood.staging.cloud.databricks.com/
{
"access_token": "****",
"token_type": "Bearer",
"expiry": "2023-10-10T14:24:11.85617+02:00"
}%
./cli auth token --profile DEFAULT
{
"access_token": "*****",
"token_type": "Bearer",
"expiry": "2023-10-10T14:24:11.85617+02:00"
}%
./cli auth token https://e2-dogfood.staging.cloud.databricks.com/
{
"access_token": "*****",
"token_type": "Bearer",
"expiry": "2023-10-11T09:24:55.046029+02:00"
}%   
./cli auth token --profile DEFAULT https://e2-dogfood.staging.cloud.databricks.com/
Error: providing both a profile and a host parameters is not …
```

Use profile information when getting a token using the CLI

---

CHANGELOG.md

CLI:
* Improve `workspace import` command by allowing references to local files for content ([#793](https://github.com/databricks/cli/pull/793)).
* Add `--file` flag to workspace export command ([#794](https://github.com/databricks/cli/pull/794)).
* Ensure profile flag is respected for sync command ([#837](https://github.com/databricks/cli/pull/837)).
* Add hint to delete sync snapshot if parsing fails ([#853](https://github.com/databricks/cli/pull/853)).
* Use profile information when getting a token using the CLI ([#855](https://github.com/databricks/cli/pull/855)).
Bundles:
* Minor template tweaks ([#832](https://github.com/databricks/cli/pull/832)).
* Fixed using repo files as pipeline libraries ([#847](https://github.com/databricks/cli/pull/847)).
* Support .gitignore syntax in sync …

Release v0.207.1

---

cmd/sync/sync.go
cmd/sync/sync_test.go

Since we use `root.MustWorkspaceClient` now, we should use already initialised version of WorkspaceClient instead of instantiating a new one.
Fixes #836

Use already instantiated WorkspaceClient in sync command

---

cmd/bundle/init.go

Allows users to initialize mlops-stack by running `bundle init mlops-stack`
Manually
```
shreyas.goenka@THW32HFW6T playground % cli bundle init            
Template to use [default-python]: mlops-stack
Project Name [my-mlops-project]: ^C
shreyas.goenka@THW32HFW6T playground % cli bundle init mlops-stack
Project Name [my-mlops-project]: ^C
```

Add alias for mlops-stack template URL

---

bundle/config/resources/job.go
bundle/config/resources/job_test.go

Previous we (erroneously) kept the reference and merged into the original tasks and not the copies which we later used to replace existing tasks. Thus the merging of slices and references was incorrect.
Fixes #864 
Added a regression test

Fixed merging task libraries from targets

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/data_source_cluster.go
bundle/internal/tf/schema/data_source_current_user.go
bundle/internal/tf/schema/data_source_group.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/data_source_service_principal.go
bundle/internal/tf/schema/data_source_user.go
bundle/internal/tf/schema/resource_catalog.go
bundle/internal/tf/schema/resource_cluster.go
bundle/internal/tf/schema/resource_external_location.go
bundle/internal/tf/schema/resource_grants.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_metastore.go
bundle/internal/tf/schema/resource_metastore_data_access.go
bundle/internal/tf/schema/resource_mlflow_model.go
bundle/internal/tf/schema/resource_model_serving.go
bundle/internal/tf/schema/resource_pipeline.go
bundle/internal/tf/schema/resource_registered_model.go
bundle/internal/tf/schema/resource_share.go
bundle/internal/tf/schema/resource_sql_alert.go
bundle/internal/tf/schema/resource_sql_dashboard.go
bundle/internal/tf/schema/resource_sql_query.go
bundle/internal/tf/schema/resource_sql_table.go
bundle/internal/tf/schema/resource_storage_credential.go
bundle/internal/tf/schema/resource_system_schema.go
bundle/internal/tf/schema/resources.go

Regenerate structs for Terraform provider v1.28.0 ([release](https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.28.0)).
n/a

Bump Terraform provider to v1.28.0

---

.codegen/service.go.tmpl
cmd/account/billable-usage/billable-usage.go

The update to the Go SDK v0.23.0 in #772 included a change to make the billable usage API return its streaming response. This still did not make the command print out the CSV returned by the API, however. To do so, we call `cmdio.RenderReader` in case the response is a byte stream.
Note: there is an opportunity to parse the CSV and return JSON if requested, but that is out of scope for this PR (it is a rather big customization of the command).
Fixes #574.
Manually confirmed that `databricks account billable-usage download` now returns CSV.

Fix rendering of streaming response

---

cmd/bundle/init.go

Rename `mlops-stack` `bundle init` redirect to `mlops-stacks`.
N/A

Rename MLOps Stack to MLOps Stacks

---

CHANGELOG.md

CLI:
* Fix rendering of streaming response ([#876](https://github.com/databricks/cli/pull/876)).
Bundles:
* Rename MLOps Stack to MLOps Stacks ([#881](https://github.com/databricks/cli/pull/881)).
* Support Python wheels larger than 10MB ([#879](https://github.com/databricks/cli/pull/879)).
* Improve the output of the `databricks bundle init` command ([#795](https://github.com/databricks/cli/pull/795)).

Release v0.208.1

---

cmd/root/auth.go
cmd/root/auth_options.go
cmd/root/auth_options_test.go
cmd/sync/sync.go

The first stab at this was added in #837 but only included the `NoPrompt` check in `MustAccountClient`. I renamed it to `SkipPrompt` (in preparation for another option that skips bundle load) and made it work for `MustWorkspaceClient` as well.
Manually confirmed that the completion hook no longer prompts for a profile (when called directly with `databricks __complete`).

Skip prompt on completion hook

---

.codegen/service.go.tmpl
cmd/account/groups/groups.go
cmd/account/service-principals/service-principals.go
cmd/account/users/users.go
cmd/workspace/catalogs/catalogs.go
cmd/workspace/external-locations/external-locations.go
cmd/workspace/groups/groups.go
cmd/workspace/pipelines/pipelines.go
cmd/workspace/providers/providers.go
cmd/workspace/recipients/recipients.go
cmd/workspace/registered-models/registered-models.go
cmd/workspace/service-principals/service-principals.go
cmd/workspace/shares/shares.go
cmd/workspace/storage-credentials/storage-credentials.go
cmd/workspace/users/users.go

Some commands such as update commands have an argument in their url, for example in pipeline we have `PUT pipelines/<id>` to update the pipeline. 
Such parameters must be required and respected even if `--json` flag with the payload passed.
Note: this depends on these PRs in Go SDK:
https://github.com/databricks/databricks-sdk-go/pull/660
https://github.com/databricks/databricks-sdk-go/pull/661
Manually running `databricks pipelines update`

Fixed requiring positional arguments for API URL parameters

---

bundle/config/workspace.go
bundle/config/workspace_test.go
cmd/root/bundle_test.go
libs/databrickscfg/loader.go
libs/databrickscfg/loader_test.go
libs/databrickscfg/ops.go

If a bundle configuration specifies a workspace host, and the user specifies a profile to use, we perform a check to confirm that the workspace host in the bundle configuration and the workspace host from the profile are identical. If they are not, we return an error. The check was introduced in #571.
Previously, the code included an assumption that the client configuration was already loaded from the environment prior to performing the check. This was not the case, and as such if the user intended to use a non-default path to `.databrickscfg`, this path was not used when performing the check.
The fix does the following:
* Resolve the configuration prior to performing the check.
* Don't treat the configuration file not existing as an error.
* Add unit tests.
Fixes #884.
Unit tests and …

Resolve configuration before performing verification

---

internal/bundle/python_wheel_test.go

Added test for tasks with python wheel wrapper on
```
2023/10/20 16:42:07 [INFO] Listing secrets from ...
=== RUN   TestAccPythonWheelTaskDeployAndRunWithWrapper
python_wheel_test.go:13: aws
helpers.go:43: Configuration for template:  {"node_type_id":"i3.xlarge","python_wheel_wrapper":true,"spark_version":"12.2.x-scala2.12","unique_id":"224a58a5-7ecb-4e7a-9c89-c7f5ea57924e"}
...
Resource deployment completed!
Run URL: ...
2023-10-20 16:42:33 "[default] Test Wheel Job 224a58a5-7ecb-4e7a-9c89-c7f5ea57924e" RUNNING 
2023-10-20 16:47:27 "[default] Test Wheel Job 224a58a5-7ecb-4e7a-9c89-c7f5ea57924e" TERMINATED SUCCESS 
helpers.go:169: [databricks stdout]: Hello from my func
helpers.go:169: [databricks stdout]: Got arguments:
helpers.go:169: [databricks stdout]: ['my_test_code', 'one', 'two'] …
```

Added test for tasks with python wheel wrapper on

---

bundle/python/warning.go
bundle/python/warning_test.go

This lets us recognize 13.x as "13.1 or higher," making it possible to use wheel tasks on 13.x-snapshot clusters.

Fix wheel task not working with with 13.x clusters

---

CHANGELOG.md

CLI:
* Never load authentication configuration from bundle for sync command ([#889](https://github.com/databricks/cli/pull/889)).
* Fixed requiring positional arguments for API URL parameters ([#878](https://github.com/databricks/cli/pull/878)).
Bundles:
* Add support for validating CLI version when loading a jsonschema object ([#883](https://github.com/databricks/cli/pull/883)).
* Do not emit wheel wrapper error when python_wheel_wrapper setting is true ([#894](https://github.com/databricks/cli/pull/894)).
* Resolve configuration before performing verification ([#890](https://github.com/databricks/cli/pull/890)).
* Fix wheel task not working with with 13.x clusters ([#898](https://github.com/databricks/cli/pull/898)).
Internal:
* Skip prompt on completion hook …

Release v0.208.2

---

cmd/bundle/init.go

The doc URL link went stale. This PR updates the URL to the correct one. 
Fixes https://github.com/databricks/cli/issues/899

Fix URL for bundle template documentation

---

libs/cmdio/logger.go
libs/cmdio/logger_test.go

This PR splits the question prompt at the last new line character to make multiline selection prompts work with `promptui`
Tested manually
https://github.com/databricks/cli/assets/88374338/027e5210-f7f4-479d-98df-744d15b7a8fb

Add support for multiline descriptions when using template enums

---

bundle/config/filename.go
bundle/config/filename_test.go
bundle/config/root.go
bundle/config/root_test.go

This is unrelated to the config root so belongs in a separate file (this was added in #580).
n/a

Move bundle configuration filename code

---

libs/config/convert/normalize.go
libs/config/convert/normalize_test.go
libs/diag/diagnostic.go
libs/diag/severity.go

This is similar to #904 but instead of converting the dynamic configuration to Go structs, this normalizes a `config.Value` according to the type of a Go struct and returns the new, normalized `config.Value`.
This will be used to ensure that two `config.Value` trees are type-compatible before we can merge them (i.e. instances from different files).
Warnings and errors during normalization are accumulated and returned as a `diag.Diagnostics` structure. We can use this to surface warnings about unknown fields, or errors about invalid types, in aggregate instead of one-by-one. This approach is inspired by the pattern to accumulate diagnostics in Terraform provider code.

Add configuration normalization code

---

libs/jsonschema/extension.go
libs/template/materialize.go
libs/template/templates/default-python/databricks_template_schema.json

Adds a welcome_message field to templates and the default python template.
Manually.
Here's the output logs during template init now:
```
shreyas.goenka@THW32HFW6T bricks % cli bundle init                              
Template to use [default-python]: 
Welcome to the sample Databricks Asset Bundle template! Please enter the following information to initialize your sample DAB.
Unique name for this project [my_project]: abcde
Include a stub (sample) notebook in 'abcde/src': no
Include a stub (sample) Delta Live Tables pipeline in 'abcde/src': yes
Include a stub (sample) Python package in 'abcde/src': no
✨ Your new project has been created in the 'abcde' directory!
Please refer to the README.md of your project for further instructions on getting started.
Or read the documentation on …
```

Add welcome message to bundle templates

---

bundle/bundle.go
bundle/config/root.go
bundle/config/root_test.go

There were two functions related to loading a bundle configuration file; one as a package function and one as a member function on the configuration type. Loading the same configuration object twice doesn't make sense and therefore we can consolidate to only using the package function.
The package function would scan for known file names if the specified path was a directory. This functionality was not in use because the top-level bundle loader figures out the filename itself as of #580.
Pass.

Consolidate bundle configuration loader function

---

bundle/phases/deploy.go

Upload terraform state even if apply fails
Fixes #893 
Manually running `databricks bundle deploy` with incorrect permissions in bundle config and observe that it gets uploaded correctly

Upload terraform state even if apply fails

---

bundle/config/mutator/process_target_mode.go

Use UserName instead of Id to check if identity used is a service principal

Use UserName instead of Id to check if identity used is a service principal

---

Makefile

Goreleaser builds binary in 10-15 seconds, but go build does it just in 3-5 seconds. Target is `.databricks` folder in the current checkout, which is already in `.gitignore`. Make sure you have the following $PATH:
```
PATH="/path/to/cli/checkout/.databricks:$PATH"
```

`make snapshot` to build file in `.databricks/databricks`

---

.github/workflows/push.yml

I noticed we weren't running `goimports` from our formatting job. If we run `make fmt`, we do.
The fmt job passes.

Run make fmt from fmt job

---

internal/git_clone_test.go
libs/git/clone.go

This functionality is not exercised (and will not be anytime soon). Instead we use a map to have first party aliases for supported templates. 
https://github.com/databricks/cli/blob/1e46b9f88a7dfe96ddc509b014beaa48ba0efef8/cmd/bundle/init.go#L21 
Existing tests and manually, bundle init still works.

Remove resolution of repo names against the Databricks Github account

---

bundle/deploy/terraform/convert.go
bundle/deploy/terraform/load.go
bundle/deploy/terraform/load_test.go
bundle/phases/deploy.go
cmd/bundle/run.go

This PR fixes metadata computation for empty bundle. Before we would error because the `terraform.Load()` mutator errors on a empty / no state file.
Failing integration tests now pass.

Fix metadata computation for empty bundle

---

CHANGELOG.md

CLI:
* Added GitHub issue templates for CLI and DABs issues ([#925](https://github.com/databricks/cli/pull/925)).
* Added override to support YAML inputs for apps ([#921](https://github.com/databricks/cli/pull/921)).
* Simplified code generation logic for handling path and request body parameters and JSON input ([#905](https://github.com/databricks/cli/pull/905)).
Bundles:
* Fixed URL for bundle template documentation in init command help docs ([#903](https://github.com/databricks/cli/pull/903)).
* Fixed pattern validation for input parameters in a bundle template ([#912](https://github.com/databricks/cli/pull/912)).
* Fixed multiline description rendering for enum input parameters in bundle templates ([#916](https://github.com/databricks/cli/pull/916)).
* Changed production mode check …

Release v0.209.0

---

libs/config/merge/merge.go
libs/config/merge/merge_test.go

Semantics for merging two instances of `config.Value`:
* Merging x with nil or nil with x always yields x
* Merging maps a and b means entries from map b take precedence
* Merging sequences a and b means concatenating them
These are the same semantics that we use today when calling into mergo in `bundle/config`.

Function to merge two instances of `config.Value`

---

libs/jsonschema/schema.go
libs/jsonschema/schema_test.go

This PR removes validation for default value against the regex pattern specified in a JSON schema at schema load time. This is required because https://github.com/databricks/cli/pull/795 introduces parameterising the default value as a Go text template impling that the default value now does not necessarily have to match the pattern at schema load time.
This will also unblock: https://github.com/databricks/mlops-stacks/pull/108
Note, this does not remove runtime validation for input parameters right before template initialization, which happens here: https://github.com/databricks/cli/blob/fb32e78c9b9fb000ce898b8a60b0b47920f487d3/libs/template/materialize.go#L76
Changes to existing test.

Remove validation for default value against pattern

---

internal/helpers.go

This PR enables testing commands with stdin
https://github.com/databricks/cli/pull/914

Make Cobra runner compatible with testing interactive flows

---

bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_jobs.go
bundle/config/mutator/translate_paths_test.go

Support path rewrites for Dbt and SQL file job taks.
* Added unit test

Bundle path rewrites for dbt and SQL file tasks

---

cmd/root/progress_logger.go

At the moment, these flags are mostly used for VSCode integration for bundles, but they're not effective for the majority of commands.

Hide `--progress-format` global flag

---

bundle/config/mutator/initialize_variables.go
bundle/config/mutator/initialize_variables_test.go
bundle/config/mutator/mutator.go
bundle/tests/variables/without_definition/databricks.yml
bundle/tests/variables_test.go

We can debate whether or not variable definitions without properties are valid, but in no case should this panic the CLI.
Fixes #934.
Unit.

Initialize variable definitions that are defined without properties

---

cmd/auth/env.go
cmd/auth/login.go
cmd/auth/profiles.go
cmd/root/auth.go
libs/databrickscfg/profiles.go
libs/databrickscfg/profiles_test.go
libs/databrickscfg/testdata/sample-home/.databrickscfg
libs/env/context.go
libs/env/context_test.go
libs/env/loader.go
libs/env/loader_test.go

`os.Getenv(..)` is not friendly with `libs/env`. This PR makes the relevant changes to places where we need to read user home directory.
Mainly done in https://github.com/databricks/cli/pull/914

Added `env.UserHomeDir(ctx)` for parallel-friendly tests

---

.codegen/service.go.tmpl
cmd/account/log-delivery/log-delivery.go
cmd/account/networks/networks.go
cmd/account/private-access/private-access.go
cmd/account/vpc-endpoints/vpc-endpoints.go
cmd/account/workspaces/workspaces.go
cmd/workspace/catalogs/catalogs.go
cmd/workspace/cluster-policies/cluster-policies.go
cmd/workspace/clusters/clusters.go
cmd/workspace/experiments/experiments.go
cmd/workspace/external-locations/external-locations.go
cmd/workspace/git-credentials/git-credentials.go
cmd/workspace/global-init-scripts/global-init-scripts.go
cmd/workspace/instance-pools/instance-pools.go
cmd/workspace/instance-profiles/instance-profiles.go
cmd/workspace/metastores/metastores.go
cmd/workspace/model-registry/model-registry.go
cmd/workspace/providers/providers.go
cmd/workspace/recipients/recipients.go
cmd/workspace/registered-models/registered-models.go
cmd/workspace/repos/repos.go
cmd/workspace/schemas/schemas.go
cmd/workspace/secrets/secrets.go
cmd/workspace/shares/shares.go
cmd/workspace/storage-credentials/storage-credentials.go
cmd/workspace/token-management/token-management.go
cmd/workspace/volumes/volumes.go
cmd/workspace/workspace/workspace.go

Improve error message when --json input is provided
```
cli % databricks model-registry create-model mymodel --json @./input.json              
Error: when --json flag is specified, no positional arguments are required. Provide NAME in your JSON input
```

Improve error message when `--json` flag is specified

---

libs/template/config.go
libs/template/config_test.go
libs/template/testdata/config-test-schema/invalid-test-schema.json
libs/template/testdata/config-test-schema/test-schema.json

We rely on the descriptions to render the prompts to a user. Thus we should not allow empty descriptions here. Note, both mlops stacks and the default-python template have descriptions for all their properties so this should not be an issue.
Unit test

Do not allow empty descriptions for bundle template inputs

---

cmd/root/logger.go

This PR exposes simpler interfaces to end users.

Add `--debug` as shortcut for `--log-level debug`

---

libs/process/background.go
libs/process/forwarded.go
libs/process/stub.go
libs/process/stub_test.go

This PR makes unit testing with subprocesses fast.
```
ctx := context.Background()
ctx, stub := process.WithStub(ctx)
stub.WithDefaultOutput("meeee")
ctx = env.Set(ctx, "FOO", "bar")
out, err := process.Background(ctx, []string{"/usr/local/bin/meeecho", "1", "--foo", "bar"})
require.NoError(t, err)
require.Equal(t, "meeee", out)
require.Equal(t, 1, stub.Len())
require.Equal(t, []string{"meeecho 1 --foo bar"}, stub.Commands())
allEnv := stub.CombinedEnvironment()
require.Equal(t, "bar", allEnv["FOO"])
require.Equal(t, "bar", stub.LookupEnv("FOO"))
```
This should make further iterations of https://github.com/databricks/cli/pull/914 easier
`make test`

Added process stubbing for easier testing of launched subprocesses

---

internal/testdata/init/field-does-not-exist/databricks_template_schema.json

Recent descriptions were made mandatory for input parameters so this test started failing.
The test passes now.

Fix integration test asserting errors on unknown template parameters

---

cmd/auth/login.go
cmd/configure/configure.go
cmd/configure/configure_test.go

Save only explicit fields to the config file
This applies to two commands: `configure` and `auth login`. 
The latter only pulls env vars in the case of the `--configure-cluster` flag
Manual, plus additional unit test for the `configure` command

Make `databricks configure` save only explicit fields

---

libs/process/background_test.go

`TestBackgroundCombinedOutputFailure` was occasionally failing because combined output could have been in different order, see
https://github.com/databricks/cli/actions/runs/6823883271/job/18558675165?pr=928

Fixed flaky TestBackgroundCombinedOutputFailure

---

bundle/config/root.go
bundle/config/target.go
bundle/permissions/mutator.go
bundle/permissions/mutator_test.go
bundle/permissions/utils.go
bundle/permissions/workspace_root.go
bundle/permissions/workspace_root_test.go
bundle/phases/deploy.go
bundle/phases/initialize.go
bundle/tests/bundle_permissions/databricks.yml
bundle/tests/bundle_permissions_test.go

Now it's possible to define top level `permissions` section in bundle configuration and permissions defined there will be applied to all resources defined in the bundle.
Supported top-level permission levels: CAN_MANAGE, CAN_VIEW, CAN_RUN.
Permissions are applied to: Jobs, DLT Pipelines, ML Models, ML Experiments and Model Service Endpoints
```
bundle:
name: permissions
workspace:
host: ***
permissions:
- level: CAN_VIEW
group_name: test-group
- level: CAN_MANAGE
user_name: user@company.com
- level: CAN_RUN
service_principal_name: 123456-abcdef
```
Added corresponding unit tests + ran `bundle validate` and `bundle deploy` manually

Added support for top-level permissions

---

bundle/metadata/metadata.go

The Jobs service expects these fields to always be present in the metadata in their validation logic, which is reasonable. This PR removes the omit empty tags so these fields are always uploaded to the workspace `metadata.json` file.

Serialise empty files_path and job.relative_path in the deployment metadata

---

cmd/bundle/init.go

Tested manually. Specified branch / tag are indeed cloned and used by bundle init.

Add `--tag` and `--branch` options to bundle init command

---

libs/config/convert/end_to_end_test.go
libs/config/convert/from_typed.go
libs/config/convert/from_typed_test.go
libs/config/convert/struct_info.go
libs/config/convert/struct_info_test.go
libs/config/convert/to_typed.go

This PR is the counterpart to #904. With this change, we are able to convert a `config.Value` into a Go struct, make modifications to the Go struct, and reflect those changes in a new `config.Value`.
This functionality allows us to incrementally introduce this configuration representation to existing bundle mutators. Bundle mutators expect a `*bundle.Bundle` argument and mutate its configuration directly. These mutations are not reflected in the corresponding `config.Value` (once introduced), which means we cannot use the `config.Value` as source of truth until we update _all_ mutators. To address this, we can run `convert.ToTyped` and `convert.FromTyped` at the mutator boundary (from `bundle.Apply`) and capture changes made to the Go struct. Then we can incrementally make mutators aware …

Function to convert Go struct back to `config.Value`

---

bundle/artifacts/artifacts.go
bundle/config/mutator/default_workspace_paths.go
bundle/config/mutator/default_workspace_paths_test.go
bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go
bundle/config/mutator/trampoline.go
bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_test.go
bundle/config/workspace.go
bundle/deploy/files/sync.go
bundle/deploy/files/upload.go
bundle/deploy/metadata/compute.go
bundle/deploy/metadata/compute_test.go
bundle/metadata/metadata.go
cmd/bundle/sync.go
cmd/sync/sync.go
cmd/sync/sync_test.go
internal/bundle/artifacts_test.go
internal/bundle/job_metadata_test.go

This PR:
1. Renames `FilesPath` -> `FilePath` and `ArtifactsPath` -> `ArtifactPath` in the bundle and metadata configuration to make them consistant with the json tags.
2. Fixes development / production mode error messages to point to `file_path` and `artifact_path`
Existing unit tests. This is a strightforward renaming of the fields.

Make `file_path` and `artifact_path` fields consistent with json tag

---

bundle/bundle.go
bundle/config/mutator/default_target_test.go
bundle/config/mutator/default_workspace_paths_test.go
bundle/config/mutator/default_workspace_root_test.go
bundle/config/mutator/expand_workspace_root_test.go
bundle/config/mutator/override_compute_test.go
bundle/config/mutator/process_include_test.go
bundle/config/mutator/process_root_includes_test.go
bundle/config/mutator/process_target_mode_test.go
bundle/config/mutator/select_default_target_test.go
bundle/config/mutator/select_target_test.go
bundle/config/mutator/set_variables_test.go
bundle/config/mutator/translate_paths_test.go
bundle/config/mutator/validate_git_details_test.go
bundle/context.go
bundle/deferred_test.go
bundle/deploy/terraform/init_test.go
bundle/mutator_test.go
bundle/python/transform_test.go
bundle/seq_test.go

All calls to apply a mutator must go through `bundle.Apply`. This conflicts with the existing use of the variable `bundle`. This change un-aliases the variable from the package name by renaming all variables to `b`.
Pass.

Rename variable `bundle -> b`

---

bundle/config/mutator/default_target_test.go
bundle/config/mutator/default_workspace_paths_test.go
bundle/config/mutator/default_workspace_root_test.go
bundle/config/mutator/expand_workspace_root_test.go
bundle/config/mutator/override_compute_test.go
bundle/config/mutator/process_include_test.go
bundle/config/mutator/process_root_includes_test.go
bundle/config/mutator/process_target_mode_test.go
bundle/config/mutator/select_default_target.go
bundle/config/mutator/select_default_target_test.go
bundle/config/mutator/select_target_test.go
bundle/config/mutator/set_variables_test.go
bundle/config/mutator/translate_paths_test.go
bundle/config/mutator/validate_git_details_test.go
bundle/deploy/metadata/compute_test.go
bundle/deploy/terraform/init_test.go
bundle/tests/bundle/wheel_test.go

Some test call sites called directly into the mutator's `Apply` function instead of `bundle.Apply`. Calling into `bundle.Apply` is preferred because that's where we can run pre/post logic common across all mutators.
Pass.

Replace direct calls with `bundle.Apply`

---

libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}_pipeline.yml.tmpl
libs/template/templates/default-python/template/{{.project_name}}/src/dlt_pipeline.ipynb.tmpl

DLT currently doesn't always set `$PYTHONPATH` correctly (ES-947370). This restores the original workaround to make new pipelines work while that issue is being addressed. The workaround was removed in #832.
Manually tested.

Work around DLT issue with `$PYTHONPATH` not being set correctly

---

bundle/config/mutator/translate_paths_jobs.go
bundle/config/mutator/translate_paths_test.go

Previously local JAR paths were transformed to remote path during initialisation and thus artifact building logic did not recognise such libraries as local to be handled and uploaded.
Now it's possible to use spark_jar_tasks with local JAR libraries on 14.1+ DBR clusters
Example configuration
```
bundle:
name: spark-jar
workspace:
host: ***
artifacts:
my_java_code:
path: ./sample-java
build: "javac PrintArgs.java && jar cvfm PrintArgs.jar META-INF/MANIFEST.MF PrintArgs.class"
files:
- source: "/Users/andrew.nester/dabs/wheel/sample-java/PrintArgs.jar"
resources:
jobs:
print_args:
name: "Print Args"
tasks:
- task_key: Print
new_cluster:
num_workers: 0
spark_version: 14.2.x-scala2.12
node_type_id: i3.xlarge
spark_conf:
"spark.databricks.cluster.profile": "singleNode"
"spark.master": …
```

Enable `spark_jar_task` with local JAR libraries

---

bundle/deploy/terraform/init.go
bundle/deploy/terraform/init_test.go

It appears that `USERPROFILE` env variable indicates where Azure CLI stores configuration data (aka `.azure` folder).
https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file
Passing it to terraform executable allows it to correctly authenticate using Azure CLI.
Fixes #983 
Ran deployment on Window VM before and after the fix.

Pass `USERPROFILE` environment variable to Terraform

---

cmd/auth/login.go
cmd/auth/login_test.go

`databricks configure` creates a new .databrickscfg if one doesn't already exist, but `databricks auth login` fails in this case. Because `databricks auth login` anyways writes out the config file, we gracefully handle this error and continue.
Unit test.
```
$ ls ~/.databrickscfg*    
/Users/miles/.databrickscfg.bak
$ ./cli auth login
Databricks Profile Name: test
Databricks Host: https://<HOST>
Profile test was successfully saved
$ ls ~/.databrickscfg*
/Users/miles/.databrickscfg     /Users/miles/.databrickscfg.bak
$ cat ~/.databrickscfg
; The profile defined in the DEFAULT section is to be used as a fallback when no profile is explicitly specified.
[DEFAULT]
[test]
host      = https://<HOST>
auth_type = databricks-cli
```

Tolerate missing .databrickscfg file during `databricks auth login`

---

cmd/configure/configure.go
cmd/configure/flags.go
cmd/configure/flags_test.go
cmd/configure/host.go
cmd/configure/host_test.go

This breaks out the flags into a separate struct to make it easier to pass around.
If specified, the flag calls into the `cfgpicker` to prompt for a cluster to associated with the profile.
Existing tests pass; added one for host validation.

Add `--configure-cluster` flag to configure command

---

.github/workflows/release.yml

Similar to how we do it for setup-cli and homebrew-tap repos.
The PR on the extension side: https://github.com/databricks/databricks-vscode/pull/948

Update cli version in the vscode extension during release

---

bundle/artifacts/artifacts.go
bundle/artifacts/whl/autodetect.go
bundle/artifacts/whl/build.go
bundle/artifacts/whl/infer.go
internal/bundle/artifacts_test.go

Removed hash from the upload path since it's not useful anyway.
The main reason for that change was to make it work on all-purpose clusters. But in order to make it work, wheel version needs to be increased anyway. So having only hash in path is useless.
Note: using --build-number (build tag) flag does not help with re-installing libraries on all-purpose clusters. The reason is that `pip` ignoring build tag when upgrading the library and only look at wheel version.
Build tag is only used for sorting the versions and the one with higher build tag takes priority when installed. It only works if no library is installed.
See https://github.com/pypa/pip/blob/a15dd75d98884c94a77d349b800c7c755d8c34e4/src/pip/_internal/index/package_finder.py#L522-L556
https://github.com/pypa/pip/issues/4781 …

Do not add wheel content hash in uploaded Python wheel path

---

bundle/config/mutator/expand_pipeline_glob_paths.go
bundle/config/mutator/expand_pipeline_glob_paths_test.go
bundle/tests/bundle/pipeline_glob_paths/databricks.yml
bundle/tests/bundle/pipeline_glob_paths/dlt/nyc_taxi_loader.py
bundle/tests/bundle/pipeline_glob_paths_test.go

If there are no matches when doing Glob call for pipeline library defined, leave the entry as is. 
The next mutators in the chain will detect that file is missing and the error will be more user friendly.
Before the change
```
Starting resource deployment
Error: terraform apply: exit status 1
Error: cannot create pipeline: libraries must contain at least one element
```
After
```
Error: notebook ./non-existent not found
```
Added regression unit tests

Do not replace pipeline libraries if there are no matches for pattern

---

cmd/root/auth.go

We didn't return the error upon creating a workspace or account client. If there is an error, it must always propagate up the stack. The result of this bug was that we were setting a `nil` account or workspace client, which in turn caused SIGSEGVs.
Fixes #913.
Manually confirmed this fixes the linked issue. The CLI now correctly returns an error when the client cannot be constructed.
The issue was reproducible using a `.databrickscfg` with a single, incorrectly configured profile.

Fix bug where the account or workspace client could be `nil`

---

.github/workflows/push.yml

Test runs don't need access to the repository history and only need the commit being tested.

No need to fetch repository history when running tests

---

.goreleaser.yaml

Build failure for 32-bit Windows binary due to integer overflow in the SDK.
We don't test 32-bit anywhere. I propose we stop publishing these builds until we receive evidence they are still useful.
n/a

Discontinue 32-bit Windows build

---

CHANGELOG.md

This release includes the new `databricks labs` command to install, manage, and run Databricks Labs projects.
CLI:
* Add `--debug` as shortcut for `--log-level debug` ([#964](https://github.com/databricks/cli/pull/964)).
* Improved usability of `databricks auth login ... --configure-cluster` ([#956](https://github.com/databricks/cli/pull/956)).
* Make `databricks configure` save only explicit fields ([#973](https://github.com/databricks/cli/pull/973)).
* Add `databricks labs` command group ([#914](https://github.com/databricks/cli/pull/914)).
* Tolerate missing .databrickscfg file during `databricks auth login` ([#1003](https://github.com/databricks/cli/pull/1003)).
* Add `--configure-cluster` flag to configure command ([#1005](https://github.com/databricks/cli/pull/1005)).
* Fix bug …

Release v0.210.0

---

.github/workflows/release-snapshot.yml
.github/workflows/release.yml

The manual unshallow step is superfluous and can be done as part of the `actions/checkout` step.
Companion to #1022.
Manual trigger of the snapshot build workflow.

Use `fetch-tags` option in release workflows

---

CHANGELOG.md

This is a bugfix release to address issues with v0.210.0.
CLI:
* Fix `panic: $HOME is not set` ([#1027](https://github.com/databricks/cli/pull/1027)).
* Fix `databricks configure` if new profile is specified ([#1030](https://github.com/databricks/cli/pull/1030)).
* Filter out system clusters for `--configure-cluster` ([#1031](https://github.com/databricks/cli/pull/1031)).
Bundles:
* Fixed panic when job has trigger and in development mode ([#1026](https://github.com/databricks/cli/pull/1026)).
Internal:
* Use `fetch-tags` option in release workflows ([#1025](https://github.com/databricks/cli/pull/1025)).

Release v0.210.1

---

libs/jsonschema/extension.go
libs/template/config.go
libs/template/config_test.go

This PR adds versioning for bundle templates. Right now there's only logic for the maximum version of templates supported. At some point in the future if we make a breaking template change we can also include a minimum version of template supported by the CLI.
Unit tests.

Add versioning for bundle templates

---

cmd/auth/login.go

Ask for host when .databrickscfg doesn't exist
This fixes a regression introduced by https://github.com/databricks/cli/pull/1003

Ask for host when .databrickscfg doesn't exist

---

CHANGELOG.md

CLI:
* Add documentation for positional args in commands generated from the Databricks OpenAPI specification ([#1033](https://github.com/databricks/cli/pull/1033)).
* Ask for host when .databrickscfg doesn't exist ([#1041](https://github.com/databricks/cli/pull/1041)).
* Add list of supported values for flags that represent an enum field ([#1036](https://github.com/databricks/cli/pull/1036)).
Bundles:
* Fix panic when bundle auth resolution fails ([#1002](https://github.com/databricks/cli/pull/1002)).
* Add versioning for bundle templates ([#972](https://github.com/databricks/cli/pull/972)).
* Add support for conditional prompting in bundle init ([#971](https://github.com/databricks/cli/pull/971)).
* Pass parameters to task when run with `--python-params` and `python_wheel_wrapper` is …

Release v0.210.2

---

cmd/labs/project/installer_test.go
libs/process/stub.go

This PR removes 15 seconds from `make test` runtime

Stub out Python virtual environment installation for `labs` commands

---

bundle/deploy/terraform/convert.go
bundle/deploy/terraform/convert_test.go

Notifications weren't passed along because of a plural vs singular mismatch.
* Added unit test coverage.
* Manually confirmed it now works in an example bundle.

Fix passthrough of pipeline notifications

---

CHANGELOG.md

Bundles:
* Improve default template ([#1046](https://github.com/databricks/cli/pull/1046)).
* Fix passthrough of pipeline notifications ([#1058](https://github.com/databricks/cli/pull/1058)).
Internal:
* Stub out Python virtual environment installation for `labs` commands ([#1057](https://github.com/databricks/cli/pull/1057)).
* Upgrade Terraform schema version to v1.31.1 ([#1055](https://github.com/databricks/cli/pull/1055)).
* Bump github.com/hashicorp/hc-install from 0.6.1 to 0.6.2 ([#1054](https://github.com/databricks/cli/pull/1054)).
* Bump github.com/databricks/databricks-sdk-go from 0.26.1 to 0.26.2 ([#1053](https://github.com/databricks/cli/pull/1053)).

Release v0.210.3

---

libs/databrickscfg/loader.go
libs/databrickscfg/loader_test.go

If a user configures a workspace host in a bundle and wants to use the "azure-cli" authentication type, we would still run profile resolution. If the databrickscfg has a matching profile, we still load it, even though it should be a fallback.
* Unit test.
* Manually confirmed that setting `DATABRICKS_AUTH_TYPE=azure-cli` now works as expected.

Skip profile resolution if `DATABRICKS_AUTH_TYPE` is set

---

bundle/tests/job_with_spark_conf/databricks.yml
bundle/tests/job_with_spark_conf_test.go

This test is expected to fail when we enable the custom YAML loader.

Test existing behavior when loading non-string spark conf values

---

cmd/bundle/init.go
cmd/bundle/run.go
cmd/labs/project/installer.go
cmd/labs/project/login.go
cmd/root/auth.go
libs/cmdio/io.go
libs/cmdio/io_test.go
libs/template/config.go

Likely due to fact that Git Bash does not correctly support ANSI escape sequences, we cannot use `promptui` package there. See known issues:
- https://github.com/manifoldco/promptui/issues/208
- https://github.com/chzyer/readline/issues/191

Do not allow input prompts in Git Bash terminal

---

libs/template/config.go

Fixes nightly test `TestAccBundleInitErrorOnUnknownFields`. 
`TestAccBundleInitErrorOnUnknownFields` has an interactive shell by default so the test fails on waiting for prompt.
This was introduced in #1069.
Nightly test succeed.

Revert using IsPromptSupported from promptOrAssignDefaultValues

---

CHANGELOG.md

CLI:
* Upgrade Go SDK to 0.27.0 ([#1064](https://github.com/databricks/cli/pull/1064)).
* Skip profile resolution if `DATABRICKS_AUTH_TYPE` is set ([#1068](https://github.com/databricks/cli/pull/1068)).
* Do not allow input prompts in Git Bash terminal ([#1069](https://github.com/databricks/cli/pull/1069)).
* Added output template for list-secrets command ([#1074](https://github.com/databricks/cli/pull/1074)).
Bundles:
* Set metadata fields required to enable break-glass UI for jobs ([#880](https://github.com/databricks/cli/pull/880)).
* Do not prompt for template values in Git Bash ([#1082](https://github.com/databricks/cli/pull/1082)).
* Tune output of bundle deploy command ([#1047](https://github.com/databricks/cli/pull/1047)).
API Changes:
* Changed `databricks connections update` …

Release v0.211.0

---

libs/config/path.go
libs/config/path_string.go
libs/config/path_string_test.go
libs/config/path_test.go
libs/config/walk.go
libs/config/walk_test.go

This change adds:
* A `config.Walk` function to walk a configuration tree
* A `config.Path` type to represent a value's path inside a tree
* Functions to create a `config.Path` from a string, or convert one to a string
Additional unit tests with full coverage.

Functionality to walk a `config.Value` tree

---

bundle/permissions/mutator.go
bundle/permissions/mutator_test.go

The code relied on the `Name` property being accessible for every resource. This is generally true, but because these property structs are embedded as pointer, they can be nil. This is also why the tests had to initialize the embedded struct to pass. This changes the approach to use the keys from the resource map instead, so that we no longer rely on the non-nil embedded struct.
Note: we should evaluate whether we should turn these into values instead of pointers. I don't recall if we get value from them being pointers.

Use resource key as name in permissions code

---

cmd/bundle/bundle.go
cmd/fs/fs.go
cmd/sync/sync.go
cmd/workspace/grants/grants.go
cmd/workspace/groups.go

This tweaks the help output shown when using `databricks help`:
* make`jobs` appears under `Workflows` (as done in baseline OpenAPI). 
* move `bundle` and `sync` under a new group called `Developer Tools` (similar to what we have in docs)
* minor wording changes

Tweak command groups in CLI help

---

bundle/deploy/lock/acquire.go

This improves the error when deploying to a bundle root that the current user doesn't have write access to. This can come up slightly more often since the change of https://github.com/databricks/cli/pull/1091.
Before this change:
```
$ databricks bundle deploy --target prod
Building my_project...
Error: no such directory: /Users/lennart.kats@databricks.com/.bundle/my_project/prod/state
```
After this change:
```
$ databricks bundle deploy --target prod
Building my_project...
Error: cannot write to deployment root (this can indicate a previous deploy was done with a different identity): /Users/lennart.kats@databricks.com/.bundle/my_project/prod
```
Note that this change uses the "no such directory" error returned from the filer.

Improve error when bundle root is not writable

---

cmd/root/auth.go
cmd/root/auth_test.go

Allow account client auth with environment variables when no .databrickscfg file present
Makes the behaviour to be in line with WorkspaceClient auth.

Allow account client auth with environment variables when no .databrickscfg file present

---

bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go
libs/template/templates/default-python/template/{{.project_name}}/databricks.yml.tmpl

This PR changes the default and `mode: production` recommendation to target `/Users` for deployment. Previously, we used `/Shared`, but because of a lack of POSIX-like permissions in WorkspaceFS this meant that files inside would be readable and writable by other users in the workspace.
Detailed change:
* `default-python` no longer uses a path that starts with `/Shared`
* `mode: production` no longer requires a path that starts with `/Shared`
Docs: https://github.com/databricks/docs/pull/14585
Examples: https://github.com/databricks/bundle-examples/pull/17
* Manual tests
* Template unit tests (with an extra check to avoid /Shared)

Change recommended production deployment path from /Shared to /Users

---

cmd/root/logger.go

The JSON logger is excellent as a machine-readable logger with lots of metadata, but the resulting logs are difficult to read:
Currently, we only use the friendly log printer when run from a TTY. This PR removes that restriction, so logs will be pretty-printed by default, regardless of TTY or not. If a user needs machine-readable logs, they can still use `--log-format JSON`.
Manual test: `databricks current-user me --debug | cat` uses the pretty-printing logger.

Always log with text format by default

---

libs/dyn/value.go
libs/dyn/value_underlying.go
libs/dyn/value_underlying_test.go

The file `value.go` had a couple `AsZZZ` and `MustZZZ` functions.
This change backfills missing versions and moves all of them to a separate file.
Tests pass; full coverage.

Consolidate functions to convert `dyn.Value` to native types

---

libs/dyn/kind.go
libs/dyn/kind_test.go
libs/dyn/value.go
libs/dyn/value_test.go

The nil value is a real valid value that we need to represent. To accommodate this we introduced `dyn.KindInvalid` as the zero-value for `dyn.Kind` (see #904), but did not yet update the comments on `dyn.NilValue` or add tests for `kind.go`.
This also moves `KindNil` to be last in the definition order (least likely to care about it).
Tests pass.

Define constant for the invalid `dyn.Value`

---

CHANGELOG.md

CLI:
* Tweak command groups in CLI help ([#1092](https://github.com/databricks/cli/pull/1092)).
* Fixed storage-credentials list command in text output ([#1094](https://github.com/databricks/cli/pull/1094)).
* Allow account client auth with environment variables when no `.databrickscfg` file present ([#1097](https://github.com/databricks/cli/pull/1097)).
* Always log with text format by default ([#1096](https://github.com/databricks/cli/pull/1096)).
Bundles:
* Added exec.NewCommandExecutor to execute commands with correct interpreter ([#1075](https://github.com/databricks/cli/pull/1075)).
* Use resource key as name in permissions code ([#1087](https://github.com/databricks/cli/pull/1087)).
* Add support for reprompts if user input does not match template schema …

Release v0.212.0

---

cmd/fs/cp.go
internal/fs_cp_test.go

Copying a local file in windows to remote directory in DBFS would fail if the path was specified as a windows style path (compared to a UNIX style path). This PR fixes that.
Note, UNIX style paths will continue to work because `filepath.Base` respects both `/` and `\` as file separators. See: `IsPathSeparator` in https://go.dev/src/os/path_windows.go.
Fixes issue: https://github.com/databricks/cli/issues/1109.
Integration test and manually
```
C:\Users\shreyas.goenka>Desktop\cli.exe fs cp .\Desktop\foo.txt dbfs:/Users/shreyas.goenka@databricks.com
.\Desktop\foo.txt -> dbfs:/Users/shreyas.goenka@databricks.com/foo.txt
C:\Users\shreyas.goenka>Desktop\cli.exe fs cat  dbfs:/Users/shreyas.goenka@databricks.com/foo.txt
hello, world
````

Fix windows style file paths in fs cp command

---

bundle/run/job.go
bundle/run/job_options.go
bundle/run/job_options_test.go
bundle/run/pipeline.go
bundle/run/pipeline_options.go
bundle/run/pipeline_options_test.go

This change adds support for job parameters. If job parameters are specified for a job that doesn't define job parameters it returns an error. Conversely, if task parameters are specified for a job that defines job parameters, it also returns an error.
This change moves the options structs and their functions to separate files and backfills test coverage for them.
Job parameters can now be specified with `--params foo=bar,bar=qux`.
Unit tests and manual integration testing.

Support passing job parameters to bundle run

---

.codegen/service.go.tmpl
bundle/schema/docs/bundle_descriptions.json
cmd/workspace/cluster-policies/cluster-policies.go
cmd/workspace/clusters/clusters.go
cmd/workspace/instance-pools/instance-pools.go
cmd/workspace/jobs/jobs.go
cmd/workspace/tokens/tokens.go
cmd/workspace/workspace/workspace.go

Do not require positional arguments if they should be provided in JSON
Fixes #1122

Do not require positional arguments if they should be provided in JSON

---

.codegen/service.go.tmpl
cmd/account/budgets/budgets.go
cmd/account/workspace-assignment/workspace-assignment.go
cmd/workspace/alerts/alerts.go
cmd/workspace/artifact-allowlists/artifact-allowlists.go
cmd/workspace/connections/connections.go
cmd/workspace/dashboard-widgets/dashboard-widgets.go
cmd/workspace/query-visualizations/query-visualizations.go
cmd/workspace/vector-search-indexes/vector-search-indexes.go

Always require path parameters as positional arguments
Note: uses a generator with this SDK change: https://github.com/databricks/databricks-sdk-go/pull/773
Fixes https://github.com/databricks/cli/issues/1121

Always require path parameters as positional arguments

---

CHANGELOG.md

CLI:
* Fix windows style file paths in fs cp command ([#1118](https://github.com/databricks/cli/pull/1118)).
* Do not require positional arguments if they should be provided in JSON ([#1125](https://github.com/databricks/cli/pull/1125)).
* Always require path parameters as positional arguments ([#1129](https://github.com/databricks/cli/pull/1129)).
Bundles:
* Add debug log line for when bundle init is run from non-TTY interface ([#1117](https://github.com/databricks/cli/pull/1117)).
* Added `databricks bundle generate job` command ([#1043](https://github.com/databricks/cli/pull/1043)).
* Support passing job parameters to bundle run ([#1115](https://github.com/databricks/cli/pull/1115)).
* Bump golang.org/x/oauth2 from 0.15.0 to 0.16.0 …

Release v0.212.1

---

bundle/bundle.go
bundle/config/mutator/resolve_resource_references_test.go
bundle/permissions/workspace_root_test.go
bundle/python/warning_test.go
go.mod
go.sum

Use MockWorkspaceClient from SDK instead of WithImpl mocking

Use MockWorkspaceClient from SDK instead of WithImpl mocking

---

cmd/labs/project/entrypoint.go
cmd/labs/project/installer.go
cmd/labs/project/login.go

There's a lot of end-user friction for projects that require account-level commands. This is mainly related to the fact that, as of January 2024, workspace administrators do not necessarily have access to call account-level APIs. Ongoing discussions exist on how to implement this on a platform level best.
A temporary workaround is creating a dummy ~/.databrickscfg profile with the `account_id` field, though it doesn't remove the end-user friction. Hence, we don't require an account profile during installation (anymore) and just prompt it when the context requires it. This also means that we always prompt for account-level commands unless users specify a `--profile` flag.
- `go run main.go labs install ucx`, don't see an account profile prompt
- `go run main.go labs ucx …

Prompt for account profile only for account-level command execution instead of during `databricks labs install` flow

---

bundle/phases/initialize.go

This PR sets run as permissions after variable interpolation.
Terraform does not allow specifying permissions for current user.
The following configuration would fail becuase we would assign a permission block for self, bypassing this check here: https://github.com/databricks/cli/blob/4ee926b8858bf1583fcd8bbe9a5222b1594e72ec/bundle/config/mutator/run_as.go#L47
```
run_as:
user_name: ${workspace.current_user.userName}
```
Manually, setting run_as to ${workspace.current_user.userName} works now

Set run_as permissions after variable interpolation

---

libs/dyn/path.go
libs/dyn/value.go
libs/dyn/visit.go
libs/dyn/visit_get.go
libs/dyn/visit_get_test.go
libs/dyn/visit_map.go
libs/dyn/visit_map_test.go
libs/dyn/visit_set.go
libs/dyn/visit_set_test.go
libs/dyn/visit_test.go

This change adds the following functions:
* `dyn.Get(value, "foo.bar") -> (dyn.Value, error)`
* `dyn.Set(value, "foo.bar", newValue) -> (dyn.Value, error)`
* `dyn.Map(value, "foo.bar", func) -> (dyn.Value, error)`
And equivalent functions that take a previously constructed `dyn.Path`:
* `dyn.GetByPath(value, dyn.Path) -> (dyn.Value, error)`
* `dyn.SetByPath(value, dyn.Path, newValue) -> (dyn.Value, error)`
* `dyn.MapByPath(value, dyn.Path, func) -> (dyn.Value, error)`
Changes made by the "set" and "map" functions are never reflected in the input argument; they return new `dyn.Value` instances for all nodes in the path leading up to the changed value.
New unit tests cover all critical paths.

Add functionality to visit values in `dyn.Value` tree

---

.github/workflows/push.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml

This silences the following warning as seen in action output:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v4.

Update actions/setup-go to v5

---

.github/workflows/push.yml

v1 has been deprecated for a long time and produces warnings in action output.

Update codecov/codecov-action to v3

---

bundle/config/generate/pipeline.go
cmd/bundle/generate.go
cmd/bundle/generate/generate_test.go
cmd/bundle/generate/job.go
cmd/bundle/generate/pipeline.go
cmd/bundle/generate/utils.go
internal/bundle/generate_pipeline_test.go

Added `bundle generate pipeline` command
Usage as the following
```
databricks bundle generate pipeline --existing-pipeline-id f3b8c580-0a88-4b55-xxxx-yyyyyyyyyy
```
Manually + added E2E test

Added `bundle generate pipeline` command

---

cmd/workspace/workspace-conf/workspace-conf.go

--json flag was removed from this command when MustUseJson / CanUseJson generator functions were introduced which did not take requests types of map.
This PR bring the flag back.
Relies on this Go SDK change: https://github.com/databricks/databricks-sdk-go/pull/786

Bring back `--json` flag for workspace-conf set-status command

---

.github/workflows/push.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml

This was pinned to 1.21.0 and included a vulnerability as reported in #1150. The vulnerability does not affect the prior CLI releases as it requires a user to execute Go commands from within compromised module directories.
Fixes #1150.

Use latest patch release of Go toolchain

---

CHANGELOG.md

CLI:
* Prompt for account profile only for account-level command execution instead of during `databricks labs install` flow ([#1128](https://github.com/databricks/cli/pull/1128)).
* Bring back `--json` flag for workspace-conf set-status command ([#1151](https://github.com/databricks/cli/pull/1151)).
Bundles:
* Set `run_as` permissions after variable interpolation ([#1141](https://github.com/databricks/cli/pull/1141)).
* Add functionality to visit values in `dyn.Value` tree ([#1142](https://github.com/databricks/cli/pull/1142)).
* Add `dynvar` package for variable resolution with a `dyn.Value` tree ([#1143](https://github.com/databricks/cli/pull/1143)).
* Add support for `anyOf` to `skip_prompt_if` ([#1133](https://github.com/databricks/cli/pull/1133)).
* Added `bundle generate pipeline` …

Release v0.212.2

---

cmd/bundle/generate.go
cmd/bundle/generate/generate_test.go
cmd/bundle/generate/job.go
cmd/bundle/generate/pipeline.go
internal/bundle/generate_job_test.go
internal/bundle/generate_pipeline_test.go

Add --key for generate commands to specify resource key.
Also, resource config files are now not prefixed anymore.
Integration tests passed

Add `--key` flag for generate commands to specify resource key

---

CHANGELOG.md

CLI:
* Release Windows packages to winget-pkgs ([#1144](https://github.com/databricks/cli/pull/1144)).
Bundles:
* Add `--key` flag for generate commands to specify resource key ([#1165](https://github.com/databricks/cli/pull/1165)).
* Bump github.com/google/uuid from 1.5.0 to 1.6.0 ([#1160](https://github.com/databricks/cli/pull/1160)).
* Update Go SDK to v0.30.1 ([#1162](https://github.com/databricks/cli/pull/1162)).

Release v0.212.3

---

libs/dyn/convert/end_to_end_test.go
libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go

In the dynamic configuration, the nil value (dyn.NilValue) denotes a value that should not be serialized, ie a value being nil is the same as it not existing in the first place.
This is not true for zero values in maps and slices. This PR fixes the conversion from typed values to dyn.Value, to treat zero values in maps and slices as zero and not nil.
Unit tests

Fix dynamic representation of zero values in maps and slices

---

bundle/config/artifact.go
libs/exec/exec.go
libs/exec/shell.go
libs/exec/shell_bash.go
libs/exec/shell_cmd.go
libs/exec/shell_sh.go

Allow specifying executable in artifact section
```
artifacts:
test:
type: whl
executable: bash
...
```
We also skip bash found on Windows if it's from WSL because it won't be correctly executed, see the issue above
Fixes #1159

Allow specifying executable in artifact section and skip bash from WSL

---

bundle/artifacts/artifacts.go
bundle/config/artifact.go
bundle/libraries/helpers.go
bundle/libraries/helpers_test.go
bundle/libraries/libraries.go
bundle/libraries/libraries_test.go
bundle/libraries/local_path.go
bundle/libraries/local_path_test.go
bundle/libraries/match.go
bundle/libraries/match_test.go
bundle/libraries/workspace_path.go
bundle/libraries/workspace_path_test.go
bundle/tests/bundle/wheel_test.go
internal/bundle/artifacts_test.go

The approach to do this was:
1. Iterate over all libraries in all job tasks
2. Find references to local libraries
3. Store pointer to `compute.Library` in the matching artifact file to signal it should be uploaded
This breaks down when introducing #1098 because we can no longer track unexported state across mutators. The approach in this PR performs the path matching twice; once in the matching mutator where we check if each referenced file has an artifacts section, and once during artifact upload to rewrite the library path from a local file reference to an absolute Databricks path.
Integration tests pass.

Refactor library to artifact matching to not use pointers

---

libs/dyn/value.go
libs/dyn/visit_map_test.go

This function could panic when either side of the comparison is a nil or empty slice. This logic is triggered when comparing the input value to the output value when calling `dyn.Map`.
Unit tests.

Harden `dyn.Value` equality check

---

libs/dyn/dynvar/resolve.go
libs/dyn/dynvar/resolve_test.go

References to keys that themselves are also variable references were shortcircuited in the previous approach. This meant that certain fields were resolved even if the lookup function would have instructed to skip resolution.
To fix this we separate the memoization of resolved variable references from the memoization of lookups. Now, every variable reference is passed through the lookup function.
Before this change, the new test failed with:
```
=== RUN   TestResolveWithSkipEverything
[...]/libs/dyn/dynvar/resolve_test.go:208: 
Error Trace:	[...]/libs/dyn/dynvar/resolve_test.go:208
Error:      	Not equal: 
expected: "${d} ${c} ${c} ${d}"
actual  : "${b} ${a} ${a} ${b}"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-${d} ${c} ${c} ${d}
+${b} ${a} ${a} ${b}
Test: …
```

Ensure every variable reference is passed to lookup function

---

libs/dyn/convert/to_typed.go
libs/dyn/convert/to_typed_test.go

Not doing this means that the output struct is not a true representation of the `dyn.Value` and unrepresentable state (e.g. unexported fields) can be carried over across `convert.ToTyped` calls.
Unit tests.

Zero destination struct in `convert.ToTyped`

---

libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go

This was an issue in cases where the typed structure contains a non-nil pointer to an empty struct. After conversion to a `dyn.Value` and back to the typed structure, the pointer became nil.
Unit tests.

Empty struct should yield empty map in `convert.FromTyped`

---

bundle/run/options.go
libs/cmdgroup/command.go
libs/cmdgroup/command_test.go
libs/cmdgroup/template.go

Make sure grouped flags are added to the command flag set
Added regression tests

Make sure grouped flags are added to the command flag set

---

internal/bundle/bundles/deploy_then_remove_resources/template/resources.yml.tmpl

The indentation mistake on the `path` field under `notebook` meant the pipeline had a single entry with a `nil` notebook field. This was allowed but incorrect.
While working on the `dyn.Value` approach, this yielded a non-nil but zeroed `notebook` field and a failure to translate an empty path.
Correcting the indentation made the test fail because the file is not a notebook. I changed it to a `file` reference and the test now passes.

Fix integration test with invalid configuration

---

bundle/config/bundle.go
bundle/config/deployment.go
bundle/deploy/check_running_resources.go
bundle/deploy/check_running_resources_test.go
bundle/deploy/lock/acquire.go
bundle/deploy/lock/release.go
bundle/phases/deploy.go
cmd/bundle/deploy.go
cmd/bundle/destroy.go

Deploying bundle when there are bundle resources running at the same time can be disruptive for jobs and pipelines in progress.
With this change during deployment phase (before uploading any resources) if there is `--fail-if-running` specified DABs will check if there are any resources running and if so, will fail the deployment
Manual + add tests

Added warning when trying to deploy bundle with `--fail-if-running` and running resources

---

CHANGELOG.md

Bundles:
* Allow specifying executable in artifact section and skip bash from WSL ([#1169](https://github.com/databricks/cli/pull/1169)).
* Added warning when trying to deploy bundle with `--fail-if-running` and running resources ([#1163](https://github.com/databricks/cli/pull/1163)).
* Group bundle run flags by job and pipeline types ([#1174](https://github.com/databricks/cli/pull/1174)).
* Make sure grouped flags are added to the command flag set ([#1180](https://github.com/databricks/cli/pull/1180)).
* Add short_name helper function to bundle init templates ([#1167](https://github.com/databricks/cli/pull/1167)).
Internal:
* Fix dynamic representation of zero values in maps and slices ([#1154](https://github.com/databricks/cli/pull/1154)).
* Refactor library to artifact matching to not …

Release v0.212.4

---

cmd/auth/profiles.go

Aids debugging why `auth profiles` may take longer than expected.
Confirmed manually that timing information shows up in the log output.

Log time it takes for profile to load

---

bundle/deploy/metadata/compute.go
bundle/deploy/metadata/compute_test.go

When new fields are added they should not automatically propagate to the bundle metadata.
Test passes.

Use allowlist for Git-related fields to include in metadata

---

cmd/auth/profiles.go
cmd/auth/profiles_test.go

If environment variables related to unified authentication are set and a user runs `auth profiles`, the environment variables will interfere with the output. This change only takes profile data into account for the output.
Added a unit test.

Ignore environment variables for `auth profiles`

---

cmd/bundle/init.go

Templates can take a long time to download. This PR adds a spinner to give feedback to users.
Manually
https://github.com/databricks/cli/assets/88374338/b453982c-3233-40f4-8d6f-f31606ff0195

Add spinner when downloading templates for bundle init

---

libs/exec/exec.go
libs/exec/exec_test.go

`executor.Exec` now uses `cmd.CombinedOutput`. Previous implementation was hanging on my windows VM during `bundle deploy` on the `ReadAll(MultiReader(stdout, stderr))` line.
The problem is related to the fact the MultiReader reads sequentially, and the `stdout` is the first in line. Even simple `io.ReadAll(stdout)` hangs on me, as it seems like the command that we spawn (python wheel build) waits for the error stream to be finished before closing stdout on its own side? Reading `stderr` (or `out`) in a separate go-routine fixes the deadlock, but `cmd.CombinedOutput` feels like a simpler solution.
Also noticed that Exec was not removing `scriptFile` after itself, fixed that too.
Unit tests and manually

Avoid race-conditions while executing sub-commands

---

libs/dyn/convert/from_typed.go
libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

Before this change, any error in a subtree would cause the entire subtree to be dropped from the output.
This is not ideal when debugging, so instead we drop only the values that cannot be normalized. Note that this doesn't change behavior if the caller is properly checking the returned diagnostics for errors.
Note: this includes a change to use `dyn.InvalidValue` as opposed to `dyn.NilValue` when returning errors.
Added unit tests for the case where nested struct, map, or slice elements contain an error.

Retain partially valid structs in `convert.Normalize`

---

bundle/schema/openapi.go
bundle/schema/schema.go

Bundle schema generation does not support recursive API fields. This PR skips generation for for_each_task until we add proper support for recursive types in the bundle schema.
Manually. This fixes the generation of the CLI and the bundle schema command works as expected, with the sub-schema for `for_each_task` being set to null in the output. 
```
"for_each_task": null,
```

Skip `for_each_task` when generating the bundle schema

---

cmd/bundle/generate/generate_test.go
cmd/bundle/generate/job.go
cmd/bundle/generate/pipeline.go
internal/bundle/generate_job_test.go
internal/bundle/generate_pipeline_test.go
libs/dyn/yamlsaver/saver.go
libs/dyn/yamlsaver/saver_test.go

These fields (key and values) needs to be double quoted in order for yaml loader to read, parse and unmarshal it into Go struct correctly because these fields are `map[string]string` type.
Added regression unit and E2E tests

Generate correct YAML if custom_tags or spark_conf is used for pipeline or job cluster configuration

---

libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

This feature supports variable lookups in a `dyn.Value` that are present in the type but haven't been initialized with a value.
For example: `${bundle.git.origin_url}` is present in the `dyn.Value` only if it was assigned a value. If it wasn't assigned a value it should resolve to the empty string. This normalization option, when set, ensures that all fields that are represented in the specified type are present in the return value.
This change is in support of #1098.
Added unit test.

Add option to include fields present in the type but not in the value

---

CHANGELOG.md

CLI:
* Ignore environment variables for `auth profiles` ([#1189](https://github.com/databricks/cli/pull/1189)).
* Update LICENSE file to match Databricks license language ([#1013](https://github.com/databricks/cli/pull/1013)).
Bundles:
* Added `bundle deployment bind` and `unbind` command ([#1131](https://github.com/databricks/cli/pull/1131)).
* Use allowlist for Git-related fields to include in metadata ([#1187](https://github.com/databricks/cli/pull/1187)).
* Added `--restart` flag for `bundle run` command ([#1191](https://github.com/databricks/cli/pull/1191)).
* Generate correct YAML if `custom_tags` or `spark_conf` is used for pipeline or job cluster configuration ([#1210](https://github.com/databricks/cli/pull/1210)).
Internal:
* Move folders package into libs …

Release v0.213.0

---

.github/workflows/release.yml

From https://github.com/vedantmgoyal2009/winget-releaser:
> If you are forking [winget-pkgs](https://github.com/microsoft/winget-pkgs) on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.
This PR makes that change.

Add fork-user to winget release workflow

---

bundle/deploy/terraform/convert_test.go
bundle/internal/tf/codegen/templates/data_sources.go.tmpl
bundle/internal/tf/codegen/templates/resources.go.tmpl
bundle/internal/tf/schema/data_sources.go
bundle/internal/tf/schema/resources.go

We plan to use the any-equivalent of a `dyn.Value` such that we can use variable references for non-string fields (e.g. `${databricks_job.some_job.id}` where an integer is expected), as well as properly emit zero values for primitive types (e.g. 0 for integers or false for booleans).
This change is in preparation for the above.
Unit tests.

Use `any` as type for data sources and resources in `tf/schema`

---

libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

This is a follow-up to #1211 prompted by the addition of a recursive type in the Go SDK v0.31.0 (`jobs.ForEachTask`).
When populating missing fields with their zero values we must not inadvertently recurse into a recursive type.
New unit test fails with a stack overflow if the fix if the check is disabled.

Avoid infinite recursion when normalizing a recursive type

---

libs/dyn/dynvar/resolve.go
libs/dyn/dynvar/resolve_test.go

When resolving a value returned by the lookup function, the code would call into `resolveRef` with the key that `resolveKey` was called with. In doing so, it would cache the _new_ ref under that key.
We fix this by caching ref resolution only at the top level and relying on lookup caching to avoid duplicate work.
This came up while testing #1098.
Unit test.

Fix issue where interpolating a new ref would rewrite unrelated fields

---

bundle/config/mutator/resolve_variable_references.go
bundle/config/mutator/resolve_variable_references_test.go
libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go
libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go
libs/dyn/convert/to_typed.go
libs/dyn/convert/to_typed_test.go
libs/dyn/dynvar/ref.go
libs/dyn/dynvar/ref_test.go

This change enables the use of bundle variables for boolean, integer, and floating point fields.
* Unit tests.
* I ran a manual test to confirm parameterizing the number of workers in a cluster definition works.

Allow use of variables references in primitive non-string fields

---

CHANGELOG.md

CLI:
* Add support for UC Volumes to the `databricks fs` commands ([#1209](https://github.com/databricks/cli/pull/1209)).
Bundles:
* Use dynamic configuration model in bundles ([#1098](https://github.com/databricks/cli/pull/1098)).
* Allow use of variables references in primitive non-string fields ([#1219](https://github.com/databricks/cli/pull/1219)).
* Add an experimental default-sql template ([#1051](https://github.com/databricks/cli/pull/1051)).
* Add an experimental dbt-sql template ([#1059](https://github.com/databricks/cli/pull/1059)).
Internal:
* Add fork-user to winget release workflow ([#1214](https://github.com/databricks/cli/pull/1214)).
* Use `any` as type for data sources and resources in `tf/schema` ([#1216](https://github.com/databricks/cli/pull/1216)).
* Avoid infinite …

Release v0.214.0

---

cmd/root/auth.go
libs/databrickscfg/profiles.go

Improved error message when no .databrickscfg

---

bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go

Fixes #922
Added regression test case

Add correct tag value for models in dev mode

---

cmd/bundle/deploy.go

Fixes an issue when `compute_id` is defined in the bundle config, correctly replaced in `validate` command but not used in `deploy` command
Previously when `compute_id` was set in bundle.yml and `bundle deploy` was executed with no --compute-id flag, compute_id from bundle configuration file was reset to an empty string which is unexpected.
Now, the value of `compute_id` from bundle config only changed when the `--compute-id` flag is passed 
Manually

Only set ComputeID value when `--compute-id` flag provided

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/data_source_cluster.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/data_source_storage_credential.go
bundle/internal/tf/schema/data_source_storage_credentials.go
bundle/internal/tf/schema/data_sources.go
bundle/internal/tf/schema/resource_cluster.go
bundle/internal/tf/schema/resource_file.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_pipeline.go
bundle/internal/tf/schema/resource_vector_search_endpoint.go
bundle/internal/tf/schema/resource_volume.go
bundle/internal/tf/schema/resources.go
bundle/internal/tf/schema/root.go

Upgrade Terraform provider to 1.37.0
Currently we're using 1.36.2 version which uses Go SDK 0.30 which does not have U2M enabled for all clouds.
Upgrading to 1.37.0 allows TF provider (and thus DABs) to use U2M
Fixes #1231

Upgrade Terraform provider to 1.37.0

---

CHANGELOG.md

CLI:
* Improved error message when no .databrickscfg ([#1223](https://github.com/databricks/cli/pull/1223)).
* Use Go SDK Iterators when listing resources with the CLI ([#1202](https://github.com/databricks/cli/pull/1202)).
Bundles:
* Only set ComputeID value when `--compute-id` flag provided ([#1229](https://github.com/databricks/cli/pull/1229)).
* Add correct tag value for models in dev mode ([#1230](https://github.com/databricks/cli/pull/1230)).
* Upgrade Terraform provider to 1.37.0 ([#1235](https://github.com/databricks/cli/pull/1235)).
Internal:
* Fix CLI nightlies on our UC workspaces ([#1225](https://github.com/databricks/cli/pull/1225)).
* Handle alias types for map keys in toTyped conversion ([#1232](https://github.com/databricks/cli/pull/1232)).

Release v0.214.1

---

bundle/deploy/terraform/pkg.go
bundle/deploy/terraform/write.go
cmd/bundle/summary.go

Check if `bundle.tf.json` doesn't exist and create it before executing `terraform init` (inside `terraform.Load`)
Fixes a problem when during `terraform.Load` it fails with: 
```
Error: Failed to load plugin schemas
Error while loading schemas for plugin components: Failed to obtain provider
schema: Could not load the schema for provider
registry.terraform.io/databricks/databricks: failed to instantiate provider
"registry.terraform.io/databricks/databricks" to obtain schema: unavailable
provider "registry.terraform.io/databricks/databricks"..
```

Fix summary command when internal terraform config doesn't exist

---

cmd/bundle/deploy.go
cmd/bundle/destroy.go
cmd/bundle/run.go
cmd/bundle/schema.go
cmd/bundle/summary.go
cmd/bundle/validate.go

Return an error if unused arguments are passed to these commands.
n/a

Configure cobra.NoArgs for bundle commands where applicable

---

bundle/run/pipeline_options.go
bundle/run/pipeline_options_test.go

This flag starts a "validation-only" update.
Unit and manual confirmation it does what it should.

Add `--validate-only` flag to run validate-only pipeline update

---

bundle/python/conditional_transform_test.go
bundle/python/transform.go

Only transform wheel libraries when using trampoline

Only transform wheel libraries when using trampoline

---

.codegen/lookup.go.tmpl
bundle/config/mutator/resolve_resource_references_test.go
bundle/config/variable/lookup.go

Return ApplicationId for service principals lookups
Fixes #1234 
Added (regression) tests

Return `application_id` for service principal lookups

---

bundle/artifacts/artifacts.go
bundle/artifacts/build.go
bundle/artifacts/upload.go
bundle/artifacts/upload_test.go

Support relative paths in artifact files source section and always upload all artifact files
Fixes #1156

Support relative paths in artifact files source section and always upload all artifact files

---

libs/template/templates/default-python/template/{{.project_name}}/requirements-dev.txt.tmpl
libs/template/templates/default-python/template/{{.project_name}}/scratch/exploration.ipynb.tmpl
libs/template/templates/default-python/template/{{.project_name}}/src/dlt_pipeline.ipynb.tmpl
libs/template/templates/default-python/template/{{.project_name}}/src/notebook.ipynb.tmpl
libs/template/templates/default-python/template/{{.project_name}}/src/{{.project_name}}/main.py.tmpl
libs/template/templates/default-python/template/{{.project_name}}/tests/main_test.py.tmpl

With the current template, we can't execute the Python file and the jobs notebook using DBConnect from VSCode because we import `from pyspark.sql import SparkSession`, which doesn't support Databricks unified auth. This PR fixes this by passing spark into the library code and by explicitly instantiating a spark session where the spark global is not available.
Other changes:
* add auto-reload to notebooks
* add DLT typings for code completion

Fix DBConnect support in VS Code

---

CHANGELOG.md

CLI:
* The SDK update fixes `fs cp` calls timing out when copying large files.
Bundles:
* Fix summary command when internal Terraform config doesn't exist ([#1242](https://github.com/databricks/cli/pull/1242)).
* Configure cobra.NoArgs for bundle commands where applicable ([#1250](https://github.com/databricks/cli/pull/1250)).
* Fixed building Python artifacts on Windows with WSL ([#1249](https://github.com/databricks/cli/pull/1249)).
* Add `--validate-only` flag to run validate-only pipeline update ([#1251](https://github.com/databricks/cli/pull/1251)).
* Only transform wheel libraries when using trampoline ([#1248](https://github.com/databricks/cli/pull/1248)).
* Return `application_id` for service principal lookups ([#1245](https://github.com/databricks/cli/pull/1245)).
* Support …

Release v0.215.0

---

bundle/config/mutator/merge_job_clusters.go
bundle/config/mutator/merge_job_tasks.go
bundle/config/mutator/merge_pipeline_clusters.go
bundle/config/mutator/rewrite_sync_paths.go
bundle/config/root.go
bundle/deploy/terraform/tfdyn/convert_job.go
libs/dyn/merge/elements_by_key.go
libs/dyn/visit.go
libs/dyn/visit_get.go
libs/dyn/visit_map.go
libs/dyn/visit_map_test.go
libs/dyn/visit_set.go

This change means the callback supplied to `dyn.Foreach` can introspect the path of the value it is being called for. It also prepares for allowing visiting path patterns where the exact path is not known upfront.
Unit tests.

Include `dyn.Path` as argument to the visit callback function

---

libs/dyn/visit_map_test.go

The `dyn.Path` argument wasn't tested and could regress. Spotted this while working on related code. Follow up to #1260.
Unit tests.

Add assertions for the `dyn.Path` argument to the visit callback

---

libs/dyn/pattern.go
libs/dyn/pattern_test.go
libs/dyn/visit.go
libs/dyn/visit_get.go
libs/dyn/visit_map.go
libs/dyn/visit_map_test.go
libs/dyn/visit_set.go

The new `dyn.Pattern` type represents a path pattern that can match one or more paths in a configuration tree. Every `dyn.Path` can be converted to a `dyn.Pattern` that matches only a single path.
To accommodate this change, the visit function needed to be modified to take a `dyn.Pattern` suffix. Every component in the pattern implements an interface to work with the visit function. This function can recurse on the visit function for one or more elements of the value being visited. For patterns derived from a `dyn.Path`, it will work as it did before and select the matching element. For the new pattern components (e.g. `dyn.AnyKey` or `dyn.AnyIndex`), it recurses on all the elements in the container.
Unit tests. Confirmed full coverage for the new code.

Add `dyn.MapByPattern` to map a function to values with matching paths

---

bundle/permissions/filter.go
bundle/permissions/filter_test.go
bundle/phases/initialize.go

The databricks terraform provider does not allow changing permission of the current user. Instead, the current identity is implictly set to be the owner of all resources on the platform side.
This PR introduces a mutator to filter permissions from the bundle configuration at deploy time, allowing users to define permissions for their own identities in their bundle config.
This would allow configurations like, allowing both alice and bob to collaborate on the same DAB:
```
permissions:
level: CAN_MANAGE
user_name: alice
level: CAN_MANAGE
user_name: bob
```
This PR is a reincarnation of https://github.com/databricks/cli/pull/1145. The earlier attempt had to be reverted due to metadata loss converting to and from the dynamic configuration representation (reverted here: …

Filter current user from resource permissions

---

bundle/config/mutator/expand_pipeline_glob_paths.go
bundle/config/mutator/expand_pipeline_glob_paths_test.go
libs/dyn/location.go
libs/dyn/location_test.go

We now keep location metadata associated with every configuration value. When expanding globs for pipeline libraries, this annotation was erased because of the conversion to/from the typed structure. This change modifies the expansion mutator to work with `dyn.Value` and retain the location of the value that holds the glob pattern.

Retain location annotation when expanding globs for pipeline libraries

---

libs/auth/oauth.go
libs/auth/oauth_test.go

This PR migrates `databricks auth login` HTTP client to the one from Go SDK, making API calls more robust and containing our unified user agent.
Unit tests left almost unchanged

Propagate correct `User-Agent` for CLI

---

internal/init_test.go

aws-prod-ucws has CLOUD_ENV set to "ucws" which was failing the validation checks in the template itself. This PR fixes the test.
The tests pass now

Fix TestAccBundleInitOnMlopsStacks to work on aws-prod-ucws

---

.github/workflows/push.yml

This addresses a Node 16 deprecation warning in our GHA output.

Update actions/setup-python to v5

---

.github/workflows/push.yml

This addresses a Node 16 deprecation warning in our GHA output.
Full release notes of v4 at https://github.com/codecov/codecov-action/releases/tag/v4.0.0

Update codecov/codecov-action to v4

---

bundle/phases/deploy.go
internal/bundle/basic_test.go
internal/bundle/helpers.go

CheckRunningResource does `terraform.Show` which (I believe) expects valid `bundle.tf.json` which is only written as part of `terraform.Write` later.
With this PR order is changed.
Fixes #1286 
Added regression E2E test

Do CheckRunningResource only after terraform.Write

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/root.go

Update to the latest release. No schema changes.
Unit tests pass. Integration to be done as part of the release PR.

Upgrade Terraform provider to 1.38.0

---

CHANGELOG.md

CLI:
* Propagate correct `User-Agent` for CLI during OAuth flow ([#1264](https://github.com/databricks/cli/pull/1264)).
* Add usage string when command fails with incorrect arguments ([#1276](https://github.com/databricks/cli/pull/1276)).
Bundles:
* Include `dyn.Path` as argument to the visit callback function ([#1260](https://github.com/databricks/cli/pull/1260)).
* Inline logic to set a value in `dyn.SetByPath` ([#1261](https://github.com/databricks/cli/pull/1261)).
* Add assertions for the `dyn.Path` argument to the visit callback ([#1265](https://github.com/databricks/cli/pull/1265)).
* Add `dyn.MapByPattern` to map a function to values with matching paths ([#1266](https://github.com/databricks/cli/pull/1266)).
* Filter current user from resource permissions …

Release v0.216.0

---

internal/init_test.go
libs/auth/service_principal.go
libs/template/helpers.go

Use UserName field to identify if service principal is used
Integration test passed

Use UserName field to identify if service principal is used

---

libs/template/config.go
libs/template/config_test.go
libs/template/testdata/config-assign-from-file-unknown-property/config.json

Before we would error if a property was defined in the config file, that was not defined in the schema.
Unit tests. Also manually that the e2e flow works file.
Before:
```
shreyas.goenka@THW32HFW6T playground % cli bundle init default-python --config-file config.json
Welcome to the default Python template for Databricks Asset Bundles!
Error: failed to load config from file config.json: property include_pytho is not defined in the schema
```
After:
```
shreyas.goenka@THW32HFW6T playground % cli bundle init default-python --config-file config.json
Welcome to the default Python template for Databricks Asset Bundles!
Workspace to use (auto-detected, edit in 'test/databricks.yml'): https://dbc-a39a1eb1-ef95.cloud.databricks.com
✨ Your new project has been created in the 'test' directory! …
```

Allow unknown properties in the config file for template initialization

---

bundle/config/bundle.go

Makes the field optional by adding the `omitempty` tag.
This gets rid of the red squiggly lines in the bundle schema.

Make `bundle.deployment` optional in the bundle schema

---

.github/workflows/push.yml
bundle/schema/schema.go

This PR fixes bundle schema being broken because `for_each_task: null` was set in the generated schema. This is not valid according to the JSON schema specification and thus the Red Hat YAML VSCode extension was failing to parse the YAML configuration. 
This PR fixes: https://github.com/databricks/cli/issues/1312
The fix itself was tested manually. I asserted that the autocompletion works now. This was mistakenly overlooked the first time around when the regression was introduced in https://github.com/databricks/cli/pull/1204 because the YAML extension provides best-effort autocomplete suggestions even if the JSON schema fails to load.
To prevent future regressions we also add a test to assert that the JSON schema generated itself is a valid JSON schema object. This is done via using the …

Fix the generated DABs JSON schema

---

libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

It's not necessary to error out if a configuration field is present but not set.
For example, the following would error out, but after this change only produces a warning:
```yaml
workspace:
host:
```
Updated the unit tests to match the new behavior.

Return warning for nil primitive types during normalization

---

NOTICE
bundle/config/bundle.go
bundle/config/mutator/mutator.go
bundle/config/mutator/verify_cli_version.go
bundle/config/mutator/verify_cli_version_test.go
go.mod
go.sum
internal/build/variables.go

Allow specifying CLI version constraints required to run the bundle
Example of configuration:
```
bundle:
name: my-bundle
databricks_cli_version: "0.210.0"
```
```
bundle:
name: my-bundle
databricks_cli_version: "0.210.*"
```
```
bundle:
name: my-bundle
databricks_cli_version: ">= 0.210.0"
```
```
bundle:
name: my-bundle
databricks_cli_version: ">= 0.210.0, <= 1.0.0"
```
For other examples see: https://github.com/Masterminds/semver?tab=readme-ov-file#checking-version-constraints
Example error
```
sh-3.2$ databricks bundle validate
Error: Databricks CLI version constraint not satisfied. Required: >= 1.0.0, current: 0.216.0
```
Added unit test cover all possible configuration permutations

Allow specifying CLI version constraints required to run the bundle

---

libs/diag/diagnostic.go
libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

This adds context to warnings and errors. For example:
* Summary: `unknown field bar`
* Location: `foo.yml:6:10`
* Path: `.targets.dev.workspace`
Unit tests.

Include `dyn.Path` in normalization warnings and errors

---

bundle/tests/relative_path_translation/databricks.yml
bundle/tests/relative_path_translation/resources/job.yml
bundle/tests/relative_path_translation_test.go
libs/dyn/dynvar/resolve.go

Variable substitution works as if the variable reference is literally replaced with its contents.
The following fields should be interpreted in the same way regardless of where the variable is defined:
```yaml
foo: ${var.some_path}
bar: "./${var.some_path}"
```
Before this change, `foo` would inherit the location information of the variable definition. After this change, it uses the location information of the variable reference, making the behavior for `foo` and `bar` identical.
Fixes #1330.
The new test passes only with the fix.

Retain location information of variable reference

---

libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

Errors in normalization mean hard failure as of #1319.
We currently allow malformed configurations and ignore the malformed fields and should continue to do so.
* Tests pass.
* No calls to `diag.Errorf` from `libs/dyn`

Make normalization return warnings instead of errors

---

cmd/auth/describe.go

Fixed message for successful auth describe run

Fixed message for successful auth describe run

---

CHANGELOG.md

Breaking Change:
* Add allow list for resources when bundle `run_as` is set ([#1233](https://github.com/databricks/cli/pull/1233)).
* Make bundle validation print text output by default ([#1335](https://github.com/databricks/cli/pull/1335)).
CLI:
* Added `auth describe` command ([#1244](https://github.com/databricks/cli/pull/1244)).
* Fixed message for successful auth describe run ([#1336](https://github.com/databricks/cli/pull/1336)).
Bundles:
* Use UserName field to identify if service principal is used ([#1310](https://github.com/databricks/cli/pull/1310)).
* Allow unknown properties in the config file for template initialization ([#1315](https://github.com/databricks/cli/pull/1315)).
* Remove support for DATABRICKS_BUNDLE_INCLUDES …

Release v0.217.0

---

cmd/auth/profiles.go
cmd/auth/profiles_test.go

This makes the command almost instant, no matter how many profiles cfg file has. One downside is that we don't set AuthType for profiles that don't have it defined.
We can technically infer AuthType based on ConfigAttributes tags, but their names are different from the names of actual auth providers (and some tags cover multiple providers at the same time).

Don't attempt auth in `auth profiles --skip-validate`

---

bundle/config/mutator/mutator.go

`preinit` script needs to be executed before processing configuration files to allow the script to modify the configuration or add own configuration files.

Fixed pre-init script order

---

bundle/tests/loader.go
bundle/tests/yaml_anchors_separate_block/databricks.yml
bundle/tests/yaml_anchors_test.go
libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

In 0.217.0 we started to emit warning on unknown fields in YAML configuration but wrongly considered YAML anchor blocks as unknown field.
This PR fixes this by skipping normalising of YAML blocks.
Added regression tests

Do not emit warning on YAML anchor blocks

---

CHANGELOG.md

CLI:
* Don't attempt auth in `auth profiles --skip-validate` ([#1282](https://github.com/databricks/cli/pull/1282)).
* Fixed typo in error template for auth describe ([#1341](https://github.com/databricks/cli/pull/1341)).
Bundles:
* Correctly transform libraries in for_each_task block ([#1340](https://github.com/databricks/cli/pull/1340)).
* Do not emit warning on YAML anchor blocks ([#1354](https://github.com/databricks/cli/pull/1354)).
* Fixed pre-init script order ([#1348](https://github.com/databricks/cli/pull/1348)).
* Execute preinit after entry point to make sure scripts are loaded ([#1351](https://github.com/databricks/cli/pull/1351)).
* Bump internal terraform provider version to `1.39` ([#1339](https://github.com/databricks/cli/pull/1339)).
* Bump …

Release v0.217.1

---

bundle/config/mutator/override_compute.go
bundle/config/mutator/override_compute_test.go

Fix compute override for foreach tasks.
```
$ databricks bundle deploy --compute-id=xxx
```
I added unit tests

Fix compute override for foreach tasks

---

.github/workflows/release.yml
.goreleaser.yaml
Dockerfile
bundle/deploy/terraform/init.go
bundle/deploy/terraform/init_test.go
docker/config.tfrc
docker/setup.sh

This PR makes changes to support creating a docker image for the CLI with the `terraform` dependencies built in. This is useful for customers that operate in a network-restricted environment. Normally DABs makes API calls to registry.terraform.io to setup the terraform dependencies, with this setup the CLI/DABs will rely on the provider binaries bundled in the docker image.
----------------
Modifies the CLI release workflow to publish the docker images in the Github Container Registry. URL: https://github.com/databricks/cli/pkgs/container/cli. 
We use docker support in `goreleaser` to build and publish the images. Using goreleaser ensures the CLI packaged in the docker image is the same release artifact as the normal releases. For more information see:
1. …

Add docker images for the CLI

---

bundle/artifacts/build.go
bundle/artifacts/upload.go
bundle/artifacts/upload_test.go

Transform artifact files source patterns in build not upload stage
Resolves the following warning
```
artifact section is not defined for file at /Users/andrew.nester/dabs/wheel/target/myjar.jar. Skipping uploading. In order to use the define 'artifacts' section
```
Unit test pass

Transform artifact files source patterns in build not upload stage

---

cmd/auth/auth.go

```
➜  cli git:(fix/better-auth-docs) ✗ cli auth -h
Authentication related commands. For more information regarding how
authentication for the Databricks CLI and SDKs work please refer to the documentation
linked below.
AWS: https://docs.databricks.com/en/dev-tools/auth/index.html
Azure: https://learn.microsoft.com/en-us/azure/databricks/dev-tools/auth
GCP: https://docs.gcp.databricks.com/en/dev-tools/auth/index.html
```

Add URLs for authentication documentation to the auth command help

---

cmd/auth/auth.go

This PR is a minor UX improvement. By not autofilling the https:// prefix in Databricks Host we allow users to directly copy-paste from their browser.
UX:
```
➜  cli git:(fix/copy-host) cli auth login
Databricks Profile Name: my-profile
Databricks Host (e.g. https://<databricks-instance>.cloud.databricks.com): https://foobar.cloud.databricks.com
Profile my-profile was successfully saved
```
Manually.

Do not prefill https:// in prompt for Databricks Host

---

.github/workflows/release-snapshot.yml

We don't need docker images for the snapshot version of the CLI. 
Trigged workflow for snapshot passes. https://github.com/databricks/cli/actions/runs/8703599475/job/23870125852?pr=1367

Skip building docker images in release snapshot workflow

---

.github/workflows/release.yml
.goreleaser.yaml

This PR follows instructions in https://goreleaser.com/cookbooks/multi-platform-docker-images/ to create a multi-arch docker CLI image. Thus customers can simply specify `docker pull ghcr.io/databricks/cli:latest` to pull and run the image. 
The current approach uses the `docker manifest` support in goreleaser to create a multi-arch image. This has a couple of pros and cons. TLDR; The changes as is in the PR are good to go and very low risk. The information provided here is just FYI.
pros: 
Fewer configurations/workflows for us to manage/maintain. Goreleaser makes sure the correct CLI binary is in place when building the CLI and also takes care of publishing it to the Github Container Registry. 
cons:
Goreleaser only supports [docker …

Add support for multi-arch Docker images

---

libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

We currently issue a warning if an integer is used where a floating point number is expected. But if they are convertible, we should convert and not issue a warning. This change fixes normalization if they are convertible between each other. We still produce a warning if the type conversion leads to a loss in precision.

Convert between integer and float in normalization

---

bundle/config/mutator/resolve_resource_references.go
bundle/config/mutator/resolve_resource_references_test.go
bundle/config/mutator/resolve_variable_references.go
bundle/phases/initialize.go

Allows for the syntax below
```
variables:
service_principal_app_id:
description: 'The app id of the service principal for running workflows as.'
lookup:
service_principal: "sp-${bundle.environment}"
```
Fixes #1259

Resolve variable references inside variable lookup fields

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/data_source_external_location.go
bundle/internal/tf/schema/data_source_external_locations.go
bundle/internal/tf/schema/data_source_instance_pool.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/data_source_metastore.go
bundle/internal/tf/schema/data_sources.go
bundle/internal/tf/schema/resource_catalog.go
bundle/internal/tf/schema/resource_cluster.go
bundle/internal/tf/schema/resource_instance_pool.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_lakehouse_monitor.go
bundle/internal/tf/schema/resource_pipeline.go
bundle/internal/tf/schema/resource_recipient.go
bundle/internal/tf/schema/resource_schema.go
bundle/internal/tf/schema/root.go

Upgrade terraform-provider-databricks to 1.40.0

Upgrade terraform-provider-databricks to 1.40.0

---

NOTICE

We package the terraform 1.5.5 binary in our docker container images for the CLI. This thus needs to be included in our notice for the repository.

Add NOTICE for using Terraform 1.5.5 licensed under MPL 2.0

---

cmd/bundle/validate.go

Fixes to get host from the workspace client rather than only printing the host when it's configured in the bundle config.
Manually. When a profile was specified for auth.
Before:
```
➜  bundle-playground git:(master) ✗ cli bundle validate
Name: bundle-playground
Target: default
Workspace:
Host: 
User: shreyas.goenka@databricks.com
Path: /Users/shreyas.goenka@databricks.com/.bundle/bundle-playground/default
```
After:
```
➜  bundle-playground git:(master) ✗ cli bundle validate
Name: bundle-playground
Target: default
Workspace:
Host: https://e2-dogfood.staging.cloud.databricks.com
User: shreyas.goenka@databricks.com
Path: /Users/shreyas.goenka@databricks.com/.bundle/bundle-playground/default
```

Print host in `bundle validate` when passed via profile or environment variables

---

bundle/deploy/files/delete.go
internal/bundle/destroy_test.go
libs/sync/snapshot.go
libs/sync/sync.go

The sync struct initialization would recreate the deleted `file_path`. This PR moves to not initializing the sync object to delete the snapshot, thus fixing the lingering `file_path` after `bundle destroy`.
Manually, and a integration test to prevent regression.

Cleanup remote file path on bundle destroy

---

libs/cmdgroup/command_test.go
libs/cmdgroup/template.go

The default template includes a final newline but this was missing from the cmdgroup template. This change also adds test coverage for inherited flags and the flag group description.

Add trailing newline in usage string

---

.github/workflows/publish-winget.yml
.github/workflows/release.yml

We are starting to sign Windows CLI executables, but this has to be done from a machine with a Yubikey storing the signing certificate for the immediate future. As such, we will only trigger Winget publishing once the signed binaries have been uploaded to Github.
Additionally, as an extra precaution, we will only release the signed binaries via Winget.

Decouple winget release

---

.github/workflows/release.yml

`needs.goreleaser.outputs.artifacts` already contains valid JS object so no need to make it a string and try to parse

Remove `JSON.parse` call from homebrew-tap action

---

cmd/auth/profiles.go
cmd/auth/profiles_test.go

* Currently, we use `auth profiles` command with `DATABRICKS_CONFIG_FILE` env var set, the file pointed to by the env var is ONLY used for loading the profile names (ini file sections). It is not passed to go sdk config object. We also don't use env variable loader in the go sdk config object, so this env var is ignored by the config and only default file is read. 
* This PR explicitly sets the config file path in the go sdk config object.
* integration tests in vscode

Pass `DATABRICKS_CONFIG_FILE` env var to sdk config during `auth profiles`

---

cmd/labs/project/installer.go
cmd/labs/project/installer_test.go

The installer.Upgrade() processing did not install Python dependencies. This resulted in errors such as:
```
ModuleNotFoundError: No module named 'databricks.labs.blueprint'
```
Any new dependencies are now installed during the upgrade process.
Resolves: databrickslabs/ucx#1276
The TestUpgraderWorksForReleases test now checks to see if the upgrade process resulted in the dependencies being installed.

Ensure that python dependencies are installed during upgrade

---

bundle/config/root.go
bundle/tests/variables/variable_overrides_in_target/databricks.yml
bundle/tests/variables_test.go

Before variable overrides that were not string in a target would not work. This PR fixes that. Tested manually and via a unit test.

Fix variable overrides in targets for non-string variables

---

bundle/schema/schema.go
bundle/schema/schema_test.go
libs/dyn/dynvar/ref.go

Verified manually.
Before:
After:
Manually verified the schema diff is sane. Example:
```
<                               "type": "boolean",
<                               "description": "If inference tables are enabled or not. NOTE: If you have already disabled payload logging once, you cannot enable again."
---
>                               "description": "If inference tables are enabled or not. NOTE: If you have already disabled payload logging once, you cannot enable again.",
>                               "anyOf": [
>                                 {
>                                   "type": "boolean"
>                                 },
>                                 {
>                                   "type": "string",
>                                   "pattern": …
```

Allow variable references in non-string fields in the JSON schema

---

bundle/config/mutator/set_variables.go
bundle/schema/schema.go
cmd/bundle/schema.go
libs/jsonschema/schema.go
libs/jsonschema/schema_test.go

This PR fixes the variable schema to:
1. Allow non-string values in the "default" value of a variable.
2. Allow non-string overrides in a target for a variable. 
Manually. There are no longer squiggly lines. 
Before:
After:

Fix bundle schema for variables

---

bundle/schema/docs.go
bundle/schema/docs/bundle_descriptions.json
bundle/schema/openapi.go
bundle/schema/openapi_test.go

Fixes https://github.com/databricks/cli/issues/559
The CLI generation is now stable and does not produce a diff for the `bundle_descriptions.json` file.
Before a pointer to the schema was stored in the memo, which would be mutated later to include the description. This lead to duplicate documentation for schema components that were used in multiple places. This PR fixes this issue. 
Eg: Before all references of `pause_status` would have the same description.
Added regression test.

Fix description memoization in bundle schema

---

bundle/parallel_test.go

Around 0.5% to 1% of the time, the tests would fail due to concurrent access to the underlying slice in the mutator. This PR makes the test thread safe preventing race conditions.
Example of failed run: https://github.com/databricks/cli/actions/runs/9004657555/job/24738145829

Fix flaky tests for the parallel mutator

---

bundle/config/resources_test.go

This PR ensures every resource implements a custom marshaller / unmarshaller. This is required because we directly embed Go SDK structs. which implement custom marshalling overrides. Since the struct is embedded, the [customer marshalling overrides](https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON) are promoted to the top level. If the embedded struct itself is nil, then JSON marshal / unmarshal will panic because it tries to call `MarshalJSON` / `UnmarshalJSON` on a nil object.  
Fixing this issue at the Go SDK level does not seem possible. Discussed with @hectorcast-db.

Assert customer marshalling is implemented for resources

---

bundle/deploy/terraform/check_running_resources.go
bundle/deploy/terraform/check_running_resources_test.go
bundle/phases/deploy.go
internal/bundle/bundles/deploy_then_remove_resources/databricks_template_schema.json
internal/bundle/bundles/deploy_then_remove_resources/template/bar.py
internal/bundle/bundles/deploy_then_remove_resources/template/resources.yml.tmpl
internal/bundle/deploy_then_remove_resources_test.go

`check_running_resources` now pulls the remote state without modifying the bundle state, similar to how it was doing before. This avoids a problem when we fail to compute deployment metadata for a deleted job (which we shouldn't do in the first place)
`deploy_then_remove_resources_test` now also deploys and deletes a job (in addition to a pipeline), which catches the error that this PR fixes.
Unit and integ tests

Don't merge-in remote resources during depolyments

---

.codegen/service.go.tmpl
cmd/workspace/apps/apps.go
cmd/workspace/consumer-fulfillments/consumer-fulfillments.go
cmd/workspace/consumer-installations/consumer-installations.go
cmd/workspace/consumer-listings/consumer-listings.go
cmd/workspace/consumer-personalization-requests/consumer-personalization-requests.go
cmd/workspace/consumer-providers/consumer-providers.go
cmd/workspace/provider-exchange-filters/provider-exchange-filters.go
cmd/workspace/provider-exchanges/provider-exchanges.go
cmd/workspace/provider-files/provider-files.go
cmd/workspace/provider-listings/provider-listings.go
cmd/workspace/provider-personalization-requests/provider-personalization-requests.go
cmd/workspace/provider-provider-analytics-dashboards/provider-provider-analytics-dashboards.go
cmd/workspace/provider-providers/provider-providers.go

Currently, the help output of services in preview doesn't show any of their commands because the commands themselves are hidden as well.
This change updates that behavior to not hide commands in preview if the service itself is also in preview. This makes the help output of services in preview actually usable.
n/a

Don't hide commands of services that are already hidden

---

bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_jobs.go
bundle/config/mutator/translate_paths_pipelines.go
bundle/config/paths/paths.go

This is one step toward removing the `path.Paths` struct embedding from resource types.
Going forward, we'll exclusively use the `dyn.Value` tree for location information.
Existing unit tests that cover path resolution with fallback behavior pass.

Remove dependency on `ConfigFilePath` from path translation mutator

---

bundle/config/mutator/default_queueing_test.go
bundle/config/resources.go
bundle/config/resources/job.go
bundle/config/resources/mlflow_experiment.go
bundle/config/resources/mlflow_model.go
bundle/config/resources/model_serving_endpoint.go
bundle/config/resources/pipeline.go
bundle/config/resources/registered_model.go
bundle/config/root.go
bundle/permissions/filter_test.go
bundle/permissions/mutator_test.go
bundle/permissions/workspace_root_test.go
bundle/tests/include_multiple/my_first_job/resource.yml
bundle/tests/include_multiple/my_second_job/resource.yml
bundle/tests/include_with_glob/job.yml
bundle/tests/undefined_job/databricks.yml
bundle/tests/undefined_job_test.go

If only key was defined for a job in YAML config, validate previously failed with segfault.
This PR validates that jobs are correctly defined and returns an error if not.

Fixed panic when loading incorrectly defined jobs

---

libs/dyn/convert/end_to_end_test.go
libs/dyn/convert/from_typed.go

This PR also fixes empty values variable overrides using the --var flag. Now, using `--var="my_variable="` will set the value of `my_variable` to the empty string instead of ignoring the flag altogether.
The change using a unit test. Manually verified the `--var` flag works now.

Fix conversion of zero valued scalar pointers to a dynamic value

---

CHANGELOG.md

CLI:
* Add line about Docker installation to README.md ([#1363](https://github.com/databricks/cli/pull/1363)).
* Improve token refresh flow ([#1434](https://github.com/databricks/cli/pull/1434)).
Bundles:
* Upgrade Terraform provider to v1.42.0 ([#1418](https://github.com/databricks/cli/pull/1418)).
* Upgrade Terraform provider to v1.43.0 ([#1429](https://github.com/databricks/cli/pull/1429)).
* Don't merge-in remote resources during deployments ([#1432](https://github.com/databricks/cli/pull/1432)).
* Remove dependency on `ConfigFilePath` from path translation mutator ([#1437](https://github.com/databricks/cli/pull/1437)).
* Add `merge.Override` transform ([#1428](https://github.com/databricks/cli/pull/1428)).
* Fixed panic when loading incorrectly defined jobs …

Release v0.220.0

---

libs/filer/local_client.go
libs/filer/local_root_path.go

The prior join call calls `filepath.Join` which returns a cleaned result.
Path cleaning, in turn, calls `filepath.FromSlash`.
* Unit tests.

Remove unnecessary `filepath.FromSlash` calls

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/data_source_catalog.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/data_source_mlflow_experiment.go
bundle/internal/tf/schema/data_source_table.go
bundle/internal/tf/schema/data_sources.go
bundle/internal/tf/schema/resource_automatic_cluster_update_workspace_setting.go
bundle/internal/tf/schema/resource_cluster.go
bundle/internal/tf/schema/resource_compliance_security_profile_workspace_setting.go
bundle/internal/tf/schema/resource_enhanced_security_monitoring_workspace_setting.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_model_serving.go
bundle/internal/tf/schema/resource_quality_monitor.go
bundle/internal/tf/schema/resource_sql_table.go
bundle/internal/tf/schema/resource_vector_search_index.go
bundle/internal/tf/schema/resources.go
bundle/internal/tf/schema/root.go

Release notes in https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.46.0
Notable changes since 1.43.0:
* The job resource has been migrated to the Go SDK. More fields are now passed through from DABs into TF.
* Improved zero-value handling.
n/a

Upgrade TF provider to 1.46.0

---

internal/filer_test.go
libs/filer/fs.go
libs/filer/workspace_files_extensions_client.go

This worked fine if the notebooks are located in the filer's root and didn't if they are nested in a directory.
This change adds test coverage and fixes the underlying issue.
Ran integration test manually.

Fix listing notebooks in a subdirectory

---

CHANGELOG.md

CLI:
* Update OpenAPI spec ([#1466](https://github.com/databricks/cli/pull/1466)).
Bundles:
* Upgrade TF provider to 1.46.0 ([#1460](https://github.com/databricks/cli/pull/1460)).
* Add support for Lakehouse monitoring ([#1307](https://github.com/databricks/cli/pull/1307)).
* Make dbt-sql and default-sql templates public ([#1463](https://github.com/databricks/cli/pull/1463)).
Internal:
* Abstract over filesystem interaction with libs/vfs ([#1452](https://github.com/databricks/cli/pull/1452)).
* Add `filer.Filer` to read notebooks from WSFS without omitting their extension ([#1457](https://github.com/databricks/cli/pull/1457)).
* Fix listing notebooks in a subdirectory ([#1468](https://github.com/databricks/cli/pull/1468)).
API Changes:
* Changed `databricks account storage-credentials …

Release v0.221.0

---

libs/template/templates/default-sql/template/{{.project_name}}/src/orders_daily.sql.tmpl
libs/template/templates/default-sql/template/{{.project_name}}/src/orders_raw.sql.tmpl

This fixes a last-minute regression that snuck into https://github.com/databricks/cli/pull/1463: unfortunately we need to use `USE IDENTIFIER('schema')` to select a schema for now. In the future we expect we can just use `USE SCHEMA 'schema'`.

Fix SQL schema selection in default-sql template

---

libs/template/templates/dbt-sql/databricks_template_schema.json
libs/template/templates/default-sql/databricks_template_schema.json

This applies changes suggested by @juliacrawf-db

Copy-editing for SQL templates

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/data_source_aws_unity_catalog_assume_role_policy.go
bundle/internal/tf/schema/data_sources.go
bundle/internal/tf/schema/resource_mws_workspaces.go
bundle/internal/tf/schema/resource_storage_credential.go
bundle/internal/tf/schema/resource_system_schema.go
bundle/internal/tf/schema/root.go

This includes a bugfix for provisioning jobs with `num_workers = 0`.
Fixes #1472.
Manually tested this fixes the issue.

Upgrade TF provider to 1.47.0

---

.github/workflows/release.yml
.goreleaser.yaml

Same as https://github.com/databricks/terraform-provider-databricks/pull/3645.
n/a

Use latest version of goreleaser action

---

CHANGELOG.md

Bundles:
This releases fixes an issue introduced in v0.221.0 where managing jobs with a single-node cluster would fail.
* Fix SQL schema selection in default-sql template ([#1471](https://github.com/databricks/cli/pull/1471)).
* Copy-editing for SQL templates ([#1474](https://github.com/databricks/cli/pull/1474)).
* Upgrade TF provider to 1.47.0 ([#1476](https://github.com/databricks/cli/pull/1476)).
Internal:
* Use latest version of goreleaser action ([#1477](https://github.com/databricks/cli/pull/1477)).

Release v0.221.1

---

libs/template/helpers.go
libs/template/helpers_test.go
libs/template/testdata/randintn/template/hello.tmpl
libs/template/testdata/random-int/template/hello.tmpl

Add support for `math/rand.Intn` to DAB templates.
Unit tests.

Add randIntn function

---

bundle/bundle.go
bundle/deploy/files/upload.go
bundle/deploy/state_update.go
bundle/deploy/state_update_test.go
cmd/bundle/sync.go
cmd/sync/sync.go
libs/sync/sync.go

To run bundle deploy from DBR we use an abstraction over the workspace import / export APIs to create a `filer.Filer` and abstract the file system. Walking the file tree in such a filer is expensive and requires multiple API calls. This PR remove the two duplicate file tree walks that happen by caching the result.

Avoid multiple file tree traversals on bundle deploy

---

libs/git/repository.go
libs/git/repository_test.go

We set the origin URL as metadata in any jobs created by DABs. This PR makes sure user credentials do not leak into the set metadata in the job.
Unit test

Remove user credentials specified in the Git origin URL

---

bundle/config/mutator/mutator.go
libs/sync/snapshot.go
libs/sync/sync.go

1. Removes `DefaultMutatorsForTarget` which is no longer used anywhere
2. Makes SnapshotPath a private field. It's no longer needed by data structures outside its package.
FYI, I also tried finding other instances of dead code but I could not find anything else that was safe to remove. I used https://go.dev/blog/deadcode to search for them, and the other instances either implemented an interface, increased test coverage for some of our other code paths or there was some other reason I could not remove them (like autogenerated functions or used in tests).
Good sign our codebase is mostly clean (at least superficially).

Clean up unused code

---

bundle/config/root.go
cmd/bundle/validate.go
internal/bundle/helpers.go
internal/bundle/validate_test.go
internal/testutil/file.go
internal/testutil/touch.go

Using dynamic values allows us to retain references like `${resources.jobs...}` even when the type of field is not integer, eg: `run_job_task`, or in general values that do not map to the Go types for a field.
Integration test

Serialize dynamic value for `bundle validate` output

---

bundle/config/mutator/resolve_resource_references_test.go
bundle/config/mutator/set_variables.go
bundle/config/root.go
bundle/tests/variables/env_overrides/databricks.yml
bundle/tests/variables_test.go

This PR fixes the behaviour when variables were not overridden with lookup value from targets if these variables had any default value set in the default target.
Fixes #1449 

Override variables with lookup value even if values has default value set

---

libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go

This came up in integration testing for #1511. One of the tests converted a `map[string]any` to a dynamic value and encountered a `nil` and errored out. We can safely return a nil in this case.
Unit test passes.

Allow the any type to be set to nil in `convert.FromTyped`

---

bundle/config/generate/job.go
bundle/config/mutator/rewrite_sync_paths.go
bundle/deploy/terraform/tfdyn/rename_keys.go
libs/dyn/merge/merge.go
libs/dyn/merge/merge_test.go
libs/dyn/yamlloader/loader.go
libs/dyn/yamlloader/yaml.go
libs/dyn/yamlsaver/utils.go

With https://github.com/databricks/cli/pull/1507 and https://github.com/databricks/cli/pull/1511 we are clarifying the semantics associated with `dyn.InvalidValue` and `dyn.NilValue`. An invalid value is the default zero value and is used to signals the complete absence of the value. 
A nil value, on the other hand, is a valid value for a piece of configuration and signals explicitly setting a key to nil in the configuration tree. In keeping with that theme, this PR returns `dyn.InvalidValue` instead of `dyn.NilValue` at error sites. This change is not expected to have a material change in behaviour and is being done to set the right convention since we have well-defined semantics associated with both `NilValue` and `InvalidValue`.
Unit tests and integration tests pass. Also manually …

Return `dyn.InvalidValue` instead of `dyn.NilValue` when errors happen

---

bundle/config/mutator/mutator.go
bundle/config/mutator/python/python_mutator.go
bundle/config/mutator/python/python_mutator_test.go
bundle/phases/initialize.go

Replace stdin/stdout with files in `PythonMutator`. Files are created in a temporary directory.
Rename `ApplyPythonMutator` to `PythonMutator`.
Add test for `dyn.Location` behavior during the "load" stage.
Unit tests

PythonMutator: replace stdin/stdout with files

---

libs/filer/workspace_files_client.go
libs/filer/workspace_files_client_test.go

Not doing this meant file system traversal ended upon reaching a Git folder. By marking these objects as a directory globbing traverses into these folders as well.
Added a unit test for coverage.

Return `fs.ModeDir` for Git folders in the workspace

---

bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_artifacts.go
bundle/config/mutator/translate_paths_jobs.go
bundle/config/mutator/translate_paths_pipelines.go

For a future change where the inner rewriting functions need access to the underlying bundle, this change makes preparations.
All values were passed via the stack before and adding yet another value would make the code less readable.

Add context type and value to path rewriting

---

libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go

There are four different treatments location metadata can receive in the `convert.FromTyped` method.
1. Location metadata is **retained** for maps, structs and slices if the value is **not nil**
2. Location metadata is **lost** for maps, structs and slices if the value is **is nil**
3. Location metadata is **retained** if a scalar type (eg. bool, string etc) does not change.
4. Location metadata is **lost** if the value for a scalar type changes.
This PR ensures that location metadata is not lost in any case; that is, it's always preserved.
For (2), this serves as a bug fix so that location information is not lost on conversion to and from typed for nil values of complex types (struct, slices, and maps).
For (4) this is a change in semantics. For primitive values modified in a `typed` …

Retain location metadata for values in `convert.FromTyped`

---

libs/dyn/convert/from_typed.go
libs/dyn/convert/from_typed_test.go

This reverts commit dac5f09556875003986832f74829bdbc326e725f (#1523).
Retaining the location for nil values means equality checks no longer pass.
We need #1520 to be merged first.
Integration test `TestAccPythonWheelTaskDeployAndRunWithWrapper`.

Revert "Retain location metadata for values in `convert.FromTyped`"

---

bundle/internal/tf/codegen/schema/version.go
bundle/internal/tf/schema/config.go
bundle/internal/tf/schema/data_source_external_location.go
bundle/internal/tf/schema/data_source_job.go
bundle/internal/tf/schema/data_source_storage_credential.go
bundle/internal/tf/schema/resource_job.go
bundle/internal/tf/schema/resource_online_table.go
bundle/internal/tf/schema/root.go

This includes a fix for library order not being respected.
Manually confirmed the fix works in https://github.com/databricks/bundle-examples/pull/29.

Upgrade TF provider to 1.48.0

---

CHANGELOG.md

CLI:
* Add link to documentation for Homebrew installation to README ([#1505](https://github.com/databricks/cli/pull/1505)).
* Fix `databricks configure` to use `DATABRICKS_CONFIG_FILE` environment variable if exists as config file ([#1325](https://github.com/databricks/cli/pull/1325)).
Bundles:
The Terraform upgrade to v1.48.0 includes a fix for library order not being respected.
* Fix conditional in query in `default-sql` template ([#1479](https://github.com/databricks/cli/pull/1479)).
* Remove user credentials specified in the Git origin URL ([#1494](https://github.com/databricks/cli/pull/1494)).
* Serialize dynamic value for `bundle validate` output ([#1499](https://github.com/databricks/cli/pull/1499)).
* Override variables with lookup value even if values has default value set …

Release v0.222.0

---

bundle/deploy/terraform/init.go
bundle/deploy/terraform/init_test.go

Register user agent product following RFC 9110.
See https://github.com/databricks/terraform-provider-databricks/pull/3520 for Terraform change.
Unit tests

PythonMutator: register product in user agent extra

---

libs/dyn/visit.go
libs/dyn/visit_map.go
libs/dyn/visit_map_test.go

The map function ignores cases where either a key in a map is not present or an index in a sequence is out of bounds. As of recently, we retain nil values as valid values in a configuration tree. As such, it makes sense to also ignore cases where a map or sequence is expected but nil is found. This is semantically no different from an empty map where a key is not found.
Without this fix, all calls to `dyn.Map` would need to be updated with nil-checks at every path component.
Related PRs:
* #1507
* #1511

Ignore `dyn.NilValue` when traversing value from `dyn.Map`

---

bundle/config/mutator/resolve_variable_references.go
bundle/config/mutator/resolve_variable_references_test.go

Fixes #1541 
Added regression unit test

Fixed resolving variable references inside slice variable

---

bundle/config/mutator/python/python_mutator.go
bundle/config/mutator/python/python_mutator_test.go

Allow insert 'resources' and 'resources.jobs' because they can be absent in incoming bundle.
Unit tests

PythonMutator: allow insert 'resources' and 'resources.jobs'

---

bundle/bundle.go
bundle/bundle_read_only.go
bundle/config/mutator/load_git_details.go
bundle/config/mutator/translate_paths.go
bundle/config/mutator/translate_paths_test.go
bundle/config/validate/validate_sync_patterns.go
bundle/deploy/files/sync.go
bundle/deploy/state.go
bundle/deploy/state_pull.go
bundle/deploy/state_pull_test.go
bundle/deploy/state_test.go
cmd/sync/sync_test.go

Note: this doesn't cover _all_ filesystem interaction.
To intercept calls where read or stat files to determine their type, we need a layer between our code and the `os` package calls that interact with the local file system. Interception is necessary to accommodate differences between a regular local file system and the FUSE-mounted Workspace File System when running the CLI on DBR.
This change makes use of #1452 in the bundle struct.
It uses #1525 to access the bundle variable in path rewriting.
* Unit tests pass.
* Integration tests pass.

Use `vfs.Path` for filesystem interaction

---

CHANGELOG.md

Bundles:
As of this release you can interact with bundles when running the CLI on DBR (e.g. via the Web Terminal).
* Fix non-default project names not working in dbt-sql template ([#1500](https://github.com/databricks/cli/pull/1500)).
* Improve `bundle validate` output ([#1532](https://github.com/databricks/cli/pull/1532)).
* Fixed resolving variable references inside slice variable ([#1550](https://github.com/databricks/cli/pull/1550)).
* Fixed bundle not loading when empty variable is defined ([#1552](https://github.com/databricks/cli/pull/1552)).
* Use `vfs.Path` for filesystem interaction ([#1554](https://github.com/databricks/cli/pull/1554)).
* Replace `vfs.Path` with extension-aware filer when running on DBR ([#1556](https://github.com/databricks/cli/pull/1556)).
Internal:
* …

Release v0.223.0

---

cmd/root/root.go

This snuck into #1532 right before merging. The result is that error output is no longer logged. This includes actual execution errors as well as help output if arguments or flags are incorrectly specified.
We don't have test coverage for the `root.Execute` function. This is to be fixed later.
Manually confirmed we observe error output again.

Fix logic error in #1532

---

CHANGELOG.md

This bugfix release fixes missing error messages in v0.223.0.
CLI:
* Fix logic error in [#1532](https://github.com/databricks/cli/pull/1532) ([#1564](https://github.com/databricks/cli/pull/1564)).

Release v0.223.1

---

.github/workflows/release-snapshot.yml
.github/workflows/release.yml

This addresses a deprecation warning in our GHA output.
Full release notes of v4 at https://github.com/actions/upload-artifact/releases/tag/v4.0.0

Update actions/upload-artifact to v4

---

.github/workflows/push.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml
go.mod
libs/process/background_test.go

This has been released for a while. Blog post: https://go.dev/blog/go1.22.
None besides the unit tests.

Use Go 1.22 to build and test

---

.github/workflows/release-snapshot.yml
.github/workflows/release.yml

The goreleaser jobs perform a cross-platform build of the main binary without test files. It should use a different cache than the jobs that run tests for a single platform.
This change also updates the `release-snapshot` job to use the latest goreleaser action, as was done in #1477.
Ran `release-snapshot` job from this PR.

Use different Go cache key for goreleaser jobs

---

bundle/config/root.go
bundle/config/root_test.go
bundle/tests/complex_variables_test.go
bundle/tests/variables/complex/databricks.yml
go.mod

At the moment we merge values of complex variables while more expected behaviour is overriding the value with the target one.

Override complex variables with target overrides instead of merging

---

bundle/artifacts/artifacts.go
bundle/artifacts/artifacts_test.go

Now local library path in `libraries` section of foreach each tasks are correctly replaced with remote path for this library when it's uploaded to Databricks

Rewrite local path for libraries in foreach tasks

---

libs/filer/workspace_files_client.go
libs/filer/workspace_files_client_test.go
libs/filer/workspace_files_extensions_client.go

This consolidates the two separate status calls into one.
The extension-aware filer now doesn't need the direct API client anymore and fully relies on the underlying filer.
* Unit tests.
* Ran the filer integration tests manually.

Move bespoke status call to main workspace files filer

---

bundle/config/mutator/set_variables.go
bundle/config/mutator/set_variables_test.go
bundle/config/mutator/translate_paths_test.go

Previously `SetVariables` mutator mutated typed configuration by using `v.Set` for variables. This lead to variables `value` field not having location information.
By using dynamic configuration mutation, we keep the same functionality but also preserve location information for value when it's set from default.
Fixes #1568 #1538

Change SetVariables mutator to mutate dynamic configuration instead

---

bundle/render/render_text_output.go
bundle/render/render_text_output_test.go
bundle/scripts/scripts.go
cmd/bundle/deploy.go
cmd/bundle/validate.go

Print diagnostics in 'bundle deploy' similar to 'bundle validate'. This way if a bundle has any errors or warnings, they are going to be easy to notice.
NB: due to how we render errors, there is one extra trailing new line in output, preserved in examples below
```
% databricks bundle deploy
Building default...
Deploying resources...
Updating deployment state...
Deployment complete!
```
```
% databricks bundle deploy
Error: Databricks CLI version constraint not satisfied. Required: >= 1337.0.0, current: 0.0.0-dev
```
```
% databricks bundle deploy
Building default...
Deploying resources...
Updating deployment state...
Deployment complete!
Warning: unknown field: foo
in databricks.yml:6:1
```
```
% databricks bundle deploy
Warning: unknown field: foo
in databricks.yml:6:1
Error: something …
```

Print diagnostics in 'bundle deploy'

---

CHANGELOG.md

Bundles:
* Override complex variables with target overrides instead of merging ([#1567](https://github.com/databricks/cli/pull/1567)).
* Rewrite local path for libraries in foreach tasks ([#1569](https://github.com/databricks/cli/pull/1569)).
* Change SetVariables mutator to mutate dynamic configuration instead ([#1573](https://github.com/databricks/cli/pull/1573)).
* Return early in bundle destroy if no deployment exists ([#1581](https://github.com/databricks/cli/pull/1581)).
* Let notebook detection code use underlying metadata if available ([#1574](https://github.com/databricks/cli/pull/1574)).
* Remove schema override for variable default value ([#1536](https://github.com/databricks/cli/pull/1536)).
* Print diagnostics in 'bundle deploy' …

Release v0.223.2

---

bundle/deploy/state.go
bundle/deploy/state_update.go
bundle/deploy/state_update_test.go

We need a mechanism to invalidate the locally cached deployment state if a user uses the same working directory to deploy to multiple distinct deployments (separate targets, root_paths or even hosts).
This PR just adds the UUID to the deployment state in preparation for invalidating this cache. The actual invalidation will follow up at a later date (tracked in internal backlog).
Unit test. Manually checked the deployment state is actually being written.

Add UUID to uniquely identify a deployment state

---

libs/filer/files_client.go

This PR fixes a performance bug that led downloaded files (e.g. with `databricks fs cp dbfs:/Volumes/.../somefile .`) to be buffered in memory before being written. 
Results from profiling the download of a ~100MB file:
Before:
```
Type: alloc_space
Showing nodes accounting for 374.02MB, 98.50% of 379.74MB total
```
After:
```
Type: alloc_space
Showing nodes accounting for 3748.67kB, 100% of 3748.67kB total
```
Note that this fix is temporary. A longer term solution should be to use the API provided by the Go SDK rather than making an HTTP request directly from the CLI. 
fix #1575 
Verified that the CLI properly download the file when doing the profiling.

[Fix] Do not buffer files in memory when downloading

---

bundle/deploy/terraform/init.go
bundle/deploy/terraform/init_test.go

This PR adds cli to the user agent sent downstream to the databricks terraform provider when invoked via DABs.
Unit tests. Based on the comment here (https://github.com/databricks/cli/blob/10fe02075fec0b2e18d2eacf7412816d6e81d6bc/bundle/config/mutator/verify_cli_version_test.go#L113) we don't need to set the version to make the test assertion work correctly. This is likely because we use `go test` to run the tests while the CLI is compiled and the version is set via `goreleaser`.

Attribute Terraform API requests the CLI

---

bundle/config/mutator/configure_wsfs.go
libs/filer/workspace_files_extensions_client.go

By default, construct a read/write instance. If constructed in read-only mode, the underlying filer is wrapped in a readahead cache.
* Filer integration tests pass.
* Manual test that caching is enabled when running on WSFS.

Add read-only mode for extension aware workspace filer

---

libs/filer/workspace_files_cache_test.go

Backfill unit tests for #1582.
New tests pass.

Add tests for the Workspace API readahead cache

---

libs/template/helpers.go
libs/template/helpers_test.go
libs/template/testdata/uuid/template/hello.tmpl

Add support for google/uuid.New() to DAB templates.
This is needed to generate UUIDs in downstream templates like MLOps Stacks.
Unit tests.

Add UUID function to bundle template functions 

---

cmd/labs/project/installer.go

The install script might require the up-to-date Python dependencies, explained in more detail in the referenced issue below
Fixes #1623 
! Need support with testing !

Update Python dependencies before install when upgrading a labs project

---

bundle/config/mutator/python/python_diagnostics.go
bundle/config/mutator/python/python_diagnostics_test.go
bundle/config/mutator/run_as.go
bundle/config/validate/files_to_sync.go
bundle/config/validate/job_cluster_key_defined.go
bundle/config/validate/validate_sync_patterns.go
bundle/render/render_text_output.go
bundle/render/render_text_output_test.go
bundle/tests/sync_include_exclude_no_matches_test.go
libs/diag/diagnostic.go
libs/dyn/convert/normalize.go
libs/dyn/convert/normalize_test.go

Some diagnostics can have multiple paths associated with them. For instance, ensuring that unique resource keys are used across all resources. This PR extends `diag.Diagnostic` to accept multiple paths.
This PR is symmetrical to https://github.com/databricks/cli/pull/1610/files
Unit tests

Support multiple paths for diagnostics

---

CHANGELOG.md

Bundles:
* Add UUID function to bundle template functions  ([#1612](https://github.com/databricks/cli/pull/1612)).
* Upgrade TF provider to 1.49.0 ([#1617](https://github.com/databricks/cli/pull/1617)).
* Upgrade TF provider to 1.49.1 ([#1626](https://github.com/databricks/cli/pull/1626)).
* Support multiple locations for diagnostics ([#1610](https://github.com/databricks/cli/pull/1610)).
* Split artifact cleanup into prepare step before build ([#1618](https://github.com/databricks/cli/pull/1618)).
* Move to a single prompt during bundle destroy ([#1583](https://github.com/databricks/cli/pull/1583)).
Internal:
* Add tests for the Workspace API readahead cache ([#1605](https://github.com/databricks/cli/pull/1605)).
* Update Python dependencies before install when upgrading a labs project …

Release v0.224.1

---

cmd/labs/project/installer.go
cmd/labs/project/installer_test.go

Add upgrade and upgrade eager flags to pip install call for Databricks labs projects. See [this documentation](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-U) for more information about the flags.
Resolves #1634

Add upgrade and upgrade eager flags to pip install call

---

bundle/config/validate/validate_sync_patterns.go
bundle/tests/sync/negate/databricks.yml
bundle/tests/sync_include_exclude_no_matches_test.go
libs/sync/sync_test.go

Added test for negation pattern in sync include exclude section

Added test for negation pattern in sync include exclude section

---

CHANGELOG.md

Bundles:
* Add resource for UC schemas to DABs ([#1413](https://github.com/databricks/cli/pull/1413)).
Internal:
* Use dynamic walking to validate unique resource keys ([#1614](https://github.com/databricks/cli/pull/1614)).
* Regenerate TF schema ([#1635](https://github.com/databricks/cli/pull/1635)).
* Add upgrade and upgrade eager flags to pip install call ([#1636](https://github.com/databricks/cli/pull/1636)).
* Added test for negation pattern in sync include exclude section ([#1637](https://github.com/databricks/cli/pull/1637)).
* Use precomputed terraform plan for `bundle deploy` ([#1640](https://github.com/databricks/cli/pull/1640)).

Release v0.225.0

---

internal/bundle/bundles/python_wheel_task/databricks_template_schema.json
internal/bundle/bundles/python_wheel_task/template/databricks.yml.tmpl
internal/bundle/python_wheel_test.go

A new Service Control Policy has removed the `ec2.RunInstances` permission from our service principal for our AWS integration tests. This PR switches over to using the instance pool which does not require creating new clusters.
The integration tests pass now.

Fix python wheel task integration tests

---

bundle/config/mutator/merge_job_parameters.go
bundle/config/mutator/merge_job_parameters_test.go
bundle/phases/initialize.go
bundle/tests/loader.go
bundle/tests/override_job_parameters/databricks.yml
bundle/tests/override_job_parameters_test.go

This change enables overriding the default value of job parameters in target overrides.
This is the same approach we already take for job clusters and job tasks.
Closes #1620.
Mutator unit tests and lightweight end-to-end tests.

Merge job parameters based on their name

---

internal/bundle/bundles/spark_jar_task/databricks_template_schema.json
internal/bundle/bundles/spark_jar_task/template/databricks.yml.tmpl
internal/bundle/spark_jar_test.go

Enable Spark JAR task test
```
Updating deployment state...
Deleting files...
Destroy complete!
--- PASS: TestAccSparkJarTaskDeployAndRunOnVolumes (194.13s)
PASS
coverage: 51.9% of statements in ./...
ok      github.com/databricks/cli/internal/bundle       194.586s        coverage: 51.9% of statements in ./...
```

Enable Spark JAR task test

---

internal/bundle/bundles/spark_jar_task/template/databricks.yml.tmpl
internal/bundle/helpers.go
internal/bundle/spark_jar_test.go
internal/testutil/jdk.go

This explores error messages on older DBRs and UC vs non-UC.
Integration tests pass.

Run Spark JAR task test on multiple DBR versions

---

internal/completer_test.go
internal/helpers.go

The integration test for `fs ls` tried to produce completions for the temporary directory without a trailing slash. The command will list the parent directory to see if there are more directories with the same prefix that are also valid completions. The test intends to test completions for files inside the temporary directory, so we need that trailing slash.
This test was hanging because the parent directory of the temporary DBFS directory has more than 1k entries (on our integration testing workspaces) and the line buffer in the test runner has a capacity of 1k lines. To avoid the same hang in the future, this change modifies the test runner to panic if the line buffer is full.
Confirmed the integration test no longer hangs.

Add trailing slash to directory to produce completions for

---

bundle/phases/destroy.go

Following up https://github.com/databricks/cli/pull/1583#discussion_r1681126323.
We can skip pushing because right after `root_path` is deleted, making this a no-op effectively.

Skip pushing Terraform state after destroy

---

.vscode/settings.json

This updates the `python.envFile` property from VS Code's settings file to use the value that is set by the latest version of the IDE plugin. This change will make it a bit easier for contributors who work on the CLI code base with the plugin enabled.

Update VS Code settings to match latest value from IDE plugin

---

.codegen/lookup.go.tmpl

Relies on this PR from Go SDK https://github.com/databricks/databricks-sdk-go/pull/1016
See explanation there

Use `service.NamedIdMap` to make lookup generation deterministic

---

bundle/schema/docs.go
bundle/schema/openapi.go
bundle/schema/openapi_test.go
bundle/schema/spec.go

This PR removes the dependency to the `databricks-sdk-go/openapi` package by copying the struct and functions that are needed in a new `schema/spec.go` file. 
The reason to remove this dependency is that it is being deprecated. Copying the code in the `cli` repo seems reasonable given that it only uses a couple of very small structs. 
Verified that CLI code can be properly generated after this change.

[Internal] Remove dependency to the `openapi` package of the Go SDK

---

CHANGELOG.md

CLI:
* Add command line autocomplete to the fs commands ([#1622](https://github.com/databricks/cli/pull/1622)).
* Add trailing slash to directory to produce completions for ([#1666](https://github.com/databricks/cli/pull/1666)).
* Fix ability to import the CLI repository as module ([#1671](https://github.com/databricks/cli/pull/1671)).
* Fix host resolution order in `auth login` ([#1370](https://github.com/databricks/cli/pull/1370)).
* Print text logs in `import-dir` and `export-dir` commands ([#1682](https://github.com/databricks/cli/pull/1682)).
Bundles:
* Expand and upload local wheel libraries for all task types ([#1649](https://github.com/databricks/cli/pull/1649)).
* Clarify file format required for the `config-file` flag in `bundle init` …

[Release] Release v0.226.0

---

libs/template/templates/default-sql/databricks_template_schema.json

The `default-sql` template inadvertently mentioned dbt in one of the prompts. This PR removes that reference.

Remove reference to "dbt" in the default-sql template

---

bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go

This makes it so that the pipelines `continuous` property is set to false by default when using `mode: development`.

Pause continuous pipelines when 'mode: development' is used

---

bundle/libraries/local_path.go
bundle/libraries/local_path_test.go

Fixes https://github.com/databricks/setup-cli/issues/124

Correctly mark package names with versions as remote libraries

---

bundle/artifacts/whl/infer.go
bundle/config/experimental.go
bundle/config/mutator/python/python_mutator.go
bundle/config/mutator/python/python_mutator_test.go
libs/python/detect.go
libs/python/detect_test.go

Make `pydabs/venv_path` optional. When not specified, CLI detects the Python interpreter using `python.DetectExecutable`, the same way as for `artifacts`. `python.DetectExecutable` works correctly if a virtual environment is activated or `python3` is available on PATH through other means.
Extract the venv detection code from PyDABs into `libs/python/detect`. This code will be used when we implement the `python/venv_path` section in `databricks.yml`.
Unit tests and manually

Make `pydabs/venv_path` optional

---

internal/filer_test.go
libs/filer/workspace_files_client.go
libs/filer/workspace_files_extensions_client.go
libs/filer/workspace_files_extensions_client_test.go

`TestAccFilerWorkspaceFilesExtensionsErrorsOnDupName` recently started failing in our nightlies because the upstream `import` API was changed to [prohibit conflicting file paths](https://docs.databricks.com/en/release-notes/product/2024/august.html#files-can-no-longer-have-identical-names-in-workspace-folders). Because existing conflicting file paths can still be grandfathered in, we need to retain coverage for the test. To do this, this PR:
1. Removes the failing `TestAccFilerWorkspaceFilesExtensionsErrorsOnDupName`
2. Add an equivalent unit test with the `list` and `get-status` API calls mocked.

Use API mocks for duplicate path errors in workspace files extensions client

---

bundle/libraries/local_path.go
bundle/libraries/local_path_test.go

Improves detection of PyPi package names in environment dependencies

Improves detection of PyPI package names in environment dependencies

---

bundle/config/mutator/apply_presets.go
bundle/config/mutator/apply_presets_test.go

In https://github.com/databricks/cli/pull/1490 we regressed and started using the development mode prefix for UC schemas regardless of the mode of the bundle target.
This PR fixes the regression and adds a regression test
Failing integration tests pass now.

Fix prefix preset used for UC schemas

---

cmd/workspace/clusters/overrides.go

Fixes #1701 
```
Usage:
databricks clusters list [flags]
Flags:
--cluster-sources []string   Filter clusters by source
--cluster-states []string    Filter clusters by states
-h, --help                       help for list
--is-pinned                  Filter clusters by pinned status
--page-size int              Use this field to specify the maximum number of results to be returned by the server.
--page-token string          Use next_page_token or prev_page_token returned from the previous request to list the next or previous page of clusters respectively.
--policy-id string           Filter clusters by policy id
```

Added filtering flags for cluster list commands

---

CHANGELOG.md

CLI:
* Added filtering flags for cluster list commands ([#1703](https://github.com/databricks/cli/pull/1703)).
Bundles:
* Remove reference to "dbt" in the default-sql template ([#1696](https://github.com/databricks/cli/pull/1696)).
* Pause continuous pipelines when 'mode: development' is used ([#1590](https://github.com/databricks/cli/pull/1590)).
* Add configurable presets for name prefixes, tags, etc. ([#1490](https://github.com/databricks/cli/pull/1490)).
* Report all empty resources present in error diagnostic ([#1685](https://github.com/databricks/cli/pull/1685)).
* Improves detection of PyPI package names in environment dependencies ([#1699](https://github.com/databricks/cli/pull/1699)).
* [DAB] Add support for requirements libraries in Job Tasks …

[Release] Release v0.227.0

---

bundle/deploy/terraform/init.go
go.mod
go.sum
internal/bundle/deploy_test.go
internal/bundle/helpers.go

With hc-install version `0.8.0` there was a regression where debug logs would be leaked into stderr. Reported upstream in https://github.com/hashicorp/hc-install/issues/239.
Meanwhile we need to revert and pin to version`0.7.0`. This PR also includes a regression test.
Regression test.

Revert hc-install version to 0.7.0

---

bundle/config/mutator/verify_cli_version.go
bundle/config/mutator/verify_cli_version_test.go

This changes makes sure we ignore CLI version check on development builds of the CLI.
Before:
```
$ cat databricks.yml | grep cli_version
databricks_cli_version: ">= 0.223.1"
$ cli bundle deploy
Error: Databricks CLI version constraint not satisfied. Required: >= 0.223.1, current: 0.0.0-dev+06b169284737
```
after
```
...
$ cli bundle deploy
...
Warning: Ignoring Databricks CLI version constraint for development build. Required: >= 0.223.1, current: 0.0.0-dev+d52d6f08fcd5
```

Ignore CLI version check on development builds of the CLI

---

bundle/libraries/helpers.go
bundle/libraries/helpers_test.go
bundle/libraries/libraries.go
bundle/libraries/local_path.go
bundle/libraries/local_path_test.go
bundle/libraries/workspace_path.go
bundle/python/warning_test.go

Fixes issue introduced here https://github.com/databricks/cli/pull/1699 where PyPi packages were treated as local library.
The reason is that `libraryPath` returns an empty string as a path for PyPi packages and then `IsLibraryLocal` treated empty string as local path.
Both of these functions are fixed in this PR.

Do not treat empty path as a local path

---

.codegen/service.go.tmpl
cmd/workspace/storage-credentials/storage-credentials.go

Disable prompt for storage-credentials get command

---

bundle/libraries/local_path.go
bundle/libraries/local_path_test.go

Correctly mark pypi package name specs with multiple specifiers as remote libraries
Fixes this https://github.com/databricks/cli/issues/1728

Correctly mark PyPI package name specs with multiple specifiers as remote libraries

---

bundle/config/mutator/process_target_mode.go
bundle/config/mutator/process_target_mode_test.go

* Provide a more helpful error when using an artifact_path based on /Volumes
* Allow the use of short_names in /Volumes paths
Example of a valid /Volumes artifact_path:
* `artifact_path: /Volumes/catalog/schema/${workspace.current_user.short_name}/libs`
Example of an invalid /Volumes path (when using `mode: development`):
* `artifact_path: /Volumes/catalog/schema/libs`
* Resulting error: `artifact_path should contain the current username or ${workspace.current_user.short_name} to ensure uniqueness when using 'mode: development'`

Improve error handling for /Volumes paths in mode: development

---

bundle/python/warning.go
bundle/python/warning_test.go

Consider serverless clusters as compatible for Python wheel tasks.
Fixes a `Python wheel tasks require compute with DBR 13.3+ to include local libraries` warning shown for serverless clusters

Consider serverless clusters as compatible for Python wheel tasks

---

bundle/deploy/terraform/init.go
bundle/deploy/terraform/init_test.go

This ensures that the CLI and Terraform can both use an Azure CLI session configured under a non-standard path. This is the default behavior on Azure DevOps when using the AzureCLI@2 task.
Fixes #1722.
Unit test.

Pass along $AZURE_CONFIG_FILE to Terraform process

---

libs/template/templates/default-sql/template/{{.project_name}}/src/orders_daily.sql.tmpl

Materialized views now support `CREATE OR REPLACE` ([docs](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-materialized-view.html))! This makes it possible to use them with Workflows in DABs.This PR updates the template to use a materialized view rather than a regular view.
Manually validated in production.

Use materialized views in the default-sql template

---

libs/template/templates/dbt-sql/library/versions.tmpl
libs/template/templates/default-python/library/versions.tmpl
libs/template/templates/default-sql/library/versions.tmpl

This updates the templates to use the latest DBR 15 LTS version.

Update templates to latest LTS DBR

---

bundle/config/mutator/resolve_variable_references.go

Tested on the following bundle configuration
```
bundle:
name: clusters
mode: development
variables:
webhook_notifications:
description: Webhook URL for notifications
type: complex
default:
on_failure:
id: 6a6c04c1-389c-4534-95af-b68b62a9dbe6
resources:
jobs:
test_job:
name: "Andrew Nester Test Job"
tasks:
- task_key: test_task
notebook_task:
notebook_path: "./src/test.py"
new_cluster:
num_workers: 2
node_type_id: "i3.xlarge"
autoscale:
min_workers: 2
max_workers: 7
spark_version: "12.2.x-scala2.12"
spark_conf:
"spark.executor.memory": "2g"
webhook_notifications: ${var.webhook_notifications}
```
bundle validate output is below
```
andrew.nester@HFW9Y94129 wheel % databricks bundle validate
Warning: expected sequence, found map
at resources.jobs.test_job.webhook_notifications.on_failure
in …
```

Do not suppress normalisation diagnostics for resolving variables

---

bundle/config/mutator/python/python_mutator.go
bundle/config/mutator/python/python_mutator_test.go

Explain the error when the `databricks-pydabs` package is not installed or the Python environment isn't correctly activated.
Example output:
```
Error: python mutator process failed: ".venv/bin/python3 -m databricks.bundles.build --phase load --input .../input.json --output .../output.json --diagnostics .../diagnostics.json: exit status 1", use --debug to enable logging
.../.venv/bin/python3: Error while finding module specification for 'databricks.bundles.build' (ModuleNotFoundError: No module named 'databricks')
Explanation: 'databricks-pydabs' library is not installed in the Python environment.
If using Python wheels, ensure that 'databricks-pydabs' is included in the dependencies, 
and that the wheel is installed in the Python environment:
$ .venv/bin/pip install -e .
If using a …
```

PythonMutator: explain missing package error

---

libs/template/templates/dbt-sql/template/{{.project_name}}/databricks.yml.tmpl
libs/template/templates/default-python/template/{{.project_name}}/databricks.yml.tmpl
libs/template/templates/default-sql/template/{{.project_name}}/databricks.yml.tmpl

This updates the templates to include a `permissions` section. Having a permissions section is a best practice, is helpful to understand the notion of permissions, and helps diagnose permission errors (https://github.com/databricks/cli/pull/1386).
This is a cherry-pick from https://github.com/databricks/cli/pull/1387.
This change was verified to work both in dev and prod. Existing unit tests validate the validity of the templates in these modes.

Include a permissions section in all templates

---

cmd/auth/login.go

With https://github.com/databricks/cli/pull/1370 we started to error if a profile name was not provided in a non-tty setting. The Databricks VSCode extension, however, uses the `auth login` command to simply refresh the tokens. Thus, this PR is a regression fix for that use case.
Manually, `databricks auth login --host https://e2-dogfood.staging.cloud.databricks.com` no longer errors. Instead it successfully refreshes the credentials.

Do not error if we cannot prompt for a profile in `auth login`

---

bundle/config/root.go
bundle/tests/complex_variables_test.go
bundle/tests/variables/complex_multiple_files/databricks.yml
bundle/tests/variables/complex_multiple_files/variables/clusters.yml

Fixes an `Error: no value assigned to required variable <variable>.` when the main complex variable definition is defined in one file but target override is defined in separate file which is included in the main one.

Fixed complex variables are not being correctly merged from include files

---

bundle/config/root.go
bundle/tests/complex_variables_test.go
bundle/tests/variables/complex_multiple_files/databricks.yml
bundle/tests/variables/complex_multiple_files/variables/clusters.yml

This PR makes sure that both of this override syntax for variables work correctly
```
targets:
dev:
variables:
cluster1:
spark_version: "14.2.x-scala2.11"
node_type_id: "Standard_DS3_v2"
num_workers: 4
spark_conf:
spark.speculation: false
spark.databricks.delta.retentionDurationCheck.enabled: false
cluster2:
default:
spark_version: "14.2.x-scala2.11"
node_type_id: "Standard_DS3_v2"
num_workers: 4
spark_conf:
spark.speculation: false
spark.databricks.delta.retentionDurationCheck.enabled: false
```

Fixed variable override in target with full variable syntax

---

CHANGELOG.md

CLI:
* Do not error if we cannot prompt for a profile in `auth login` ([#1745](https://github.com/databricks/cli/pull/1745)).
Bundles:
As of this release CLI will show a prompt is if there are configuration changes which will lead to a DLT recreation.
Users can skip the prompt by specifying the `--auto-approve` flag
* Pass along $AZURE_CONFIG_FILE to Terraform process ([#1734](https://github.com/databricks/cli/pull/1734)).
* Add prompt when a pipeline recreation happens ([#1672](https://github.com/databricks/cli/pull/1672)).
* Use materialized views in the default-sql template ([#1709](https://github.com/databricks/cli/pull/1709)).
* Update templates to latest LTS DBR ([#1715](https://github.com/databricks/cli/pull/1715)).
* Make lock optional in the JSON schema …

[Release] Release v0.228.0

---

bundle/artifacts/expand_globs.go
bundle/config/validate/unique_resource_keys.go
bundle/libraries/expand_glob_references.go
bundle/libraries/upload.go
libs/dyn/visit.go
libs/dyn/visit_map.go
libs/dyn/visit_test.go

Some call sites hold on to the `dyn.Path` provided to them by the callback. It must therefore never be mutated after the callback returns, or these mutations leak out into unknown scope.
This change means it is no longer possible for this failure mode to happen.
Unit test.

Pass copy of `dyn.Path` to callback function

---

.codegen/lookup.go.tmpl
bundle/config/mutator/resolve_resource_references_test.go
bundle/config/variable/lookup.go
bundle/config/variable/lookup_overrides.go
bundle/tests/variables_test.go

We added a custom resolver for the cluster to add filtering for the cluster source when we list all clusters.
Without the filtering listing could take a very long time (5-10 mins) which leads to lookup timeouts.
Existing unit tests passing

Added listing cluster filtering for cluster lookups

---

bundle/libraries/expand_glob_references.go
bundle/libraries/expand_glob_references_test.go
bundle/libraries/match_test.go
bundle/libraries/upload.go
bundle/libraries/upload_test.go
bundle/tests/python_wheel/python_wheel_no_artifact_no_setup/bundle.yml
bundle/tests/python_wheel_test.go

Library glob expansion happens during deployment. Before that, all entries that refer to local paths in resource definitions are made relative to the _sync root_. Before #1694, they were made relative to the _bundle root_. This PR didn't update the library glob expansion code to use the sync root path.
If you were using the sync paths setting with library globs, the CLI would fail to expand the globs because the code was using the wrong path to anchor those globs.
This change fixes the issue.
Manually confirmed that this fixes the issue reported in #1755.

Expand library globs relative to the sync root

---

bundle/config/generate/job.go
cmd/bundle/generate/generate_test.go
libs/dyn/yamlsaver/saver.go

Fixed generated YAML missing 'default' for empty values

Fixed generated YAML missing 'default' for empty values

---

libs/template/templates/dbt-sql/template/{{.project_name}}/resources/{{.project_name}}_job.yml.tmpl
libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}_job.yml.tmpl
libs/template/templates/default-sql/template/{{.project_name}}/resources/{{.project_name}}_sql_job.yml.tmpl

Simplifies template by using the periodic trigger syntax instead of the cron schedule syntax. Periodic triggers are simpler to configure, simpler to read, and make sure that workloads are spread out through the day. We only recommend cron syntax for advanced cases or when more control is needed.
* Templates validation via unit tests
* Manual validation that the new triggers work as expected in dev/prod

Use periodic triggers in all templates

---

bundle/config/mutator/populate_current_user.go
internal/init_test.go
libs/auth/user.go
libs/auth/user_test.go
libs/template/helpers.go

Use the friendly name of service principals when shortening their name.
This change is helpful for the prefix in development mode. Instead of adding a prefix like `[dev 1706906c-c0a2-4c25-9f57-3a7aa3cb8123]`, we'll prefix like `[dev my_principal]`.

Use the friendly name of service principals when shortening their name

---

bundle/config/root.go
bundle/tests/complex_variables_test.go
bundle/tests/variables/complex/databricks.yml

Fixes #1773 
Confirmed manually

Fixed detecting full syntax variable override which includes type field

---

CHANGELOG.md

Bundles:
* Added listing cluster filtering for cluster lookups ([#1754](https://github.com/databricks/cli/pull/1754)).
* Expand library globs relative to the sync root ([#1756](https://github.com/databricks/cli/pull/1756)).
* Fixed generated YAML missing 'default' for empty values ([#1765](https://github.com/databricks/cli/pull/1765)).
* Use periodic triggers in all templates ([#1739](https://github.com/databricks/cli/pull/1739)).
* Use the friendly name of service principals when shortening their name ([#1770](https://github.com/databricks/cli/pull/1770)).
* Fixed detecting full syntax variable override which includes type field ([#1775](https://github.com/databricks/cli/pull/1775)).
Internal:
* Pass copy of `dyn.Path` to callback function …

[Release] Release v0.228.1

---

libs/template/templates/default-python/template/{{.project_name}}/resources/{{.project_name}}_pipeline.yml.tmpl

Enables Unity Catalog for pipelines in the default template. Pipelines will default to non-Unity Catalog pipelines if a catalog is not specified.
*Small caveat*: there are cases where admins lock down the default catalog of a workspace and don't allow the creation of a new schema there. If that happens, the pipeline would fail at runtime with a clear error indicating what happened. ("PERMISSION_DENIED: User does not have CREATE SCHEMA on Catalog 'main'."). I've seen this with an internal Databricks workspace, where creating new non-UC schemas wasn't locked down, but creation in the `main` was.
- Validated on a non-UC + UC workspace. The catalog selection logic here is the same as applied for the SQL templates.

Use Unity Catalog for pipelines in the default-python template

---

bundle/deploy/files/upload.go
bundle/phases/deploy.go
cmd/bundle/deploy.go
cmd/sync/sync.go
libs/sync/output.go
libs/sync/sync.go

- Extract sync output logic from `cmd/sync` into `lib/sync`
- Add hidden `verbose` flag to the `bundle deploy` command, it's false by default and hidden from the `--help` output
- Pass output handler to the `deploy/files/upload` mutator if the verbose option is true
The was an idea to use in-place output overriding each past file sync event in the output, bit that wont work for the extension, since it doesn't display deploy logs in the terminal.
Example output:
```
~/tmp/defpy: ~/cli/cli bundle deploy --sync-progress
Building defpy...
Uploading defpy-0.0.1+20240917.112755-py3-none-any.whl...
Uploading bundle files to /Users/ilia.babanov@databricks.com/.bundle/defpy/dev/files...
Action: PUT: requirements-dev.txt, resources/defpy_pipeline.yml, pytest.ini, src/defpy/main.py, …
```

Add verbose flag to the "bundle deploy" command

---

libs/git/repository_test.go

Assert tokens are redacted in origin URL when username is not specified

---

bundle/config/mutator/paths/job_paths_visitor.go
bundle/config/mutator/paths/job_paths_visitor_test.go
bundle/config/mutator/paths/visitor.go
bundle/config/mutator/translate_paths_jobs.go

Extract package for other modules to transform different kinds of paths in job resources.
Unit tests

Refactor jobs path translation

---

bundle/config/validate/job_task_cluster_spec.go
bundle/config/validate/job_task_cluster_spec_test.go
bundle/config/validate/validate.go

Add JobTaskClusterSpec validate mutator. It catches the case when tasks don't which cluster to use.
For example, we can get this error with minor modifications to `default-python` template:
```yaml
tasks:
- task_key: python_file_task
spark_python_task:
python_file: ../src/my_project_10/main.py
```
```
% databricks bundle validate
Error: Missing required cluster or environment settings
at resources.jobs.my_project_10_job.tasks[0]
in resources/my_project_10_job.yml:17:11
Task "print_github_stars" requires a cluster or an environment to run.
Specify one of the following fields: job_cluster_key, environment_key, existing_cluster_id, new_cluster.
```
We implicitly rely on "one of" validation, which does not exist. Many bundle fields can't co-exist, for instance, specifying: …

Add JobTaskClusterSpec validate mutator

---

bundle/config/root.go
bundle/config/root_test.go

Fixes #1786 
All valid override combinations are added as test cases

Fixed full variable override detection

---

.github/workflows/push.yml
.github/workflows/release-snapshot.yml
.github/workflows/release.yml
go.mod

Relates to https://github.com/databricks/cli/pull/1758.
More information about toolchains:
* https://go.dev/blog/toolchain
* https://go.dev/doc/toolchain
We need to specify the toolchain as we need to bump Go to 1.22.0 for the `mod` upgrade and want to use the latest toolchain on the 1.22 series.
The previous release was made with Go 1.22.7 so we should continue to use it.

Pin Go toolchain to 1.22.7

---

bundle/config/root.go

Simplified isFullVariableOverrideDef implementation
Follow up on https://github.com/databricks/cli/pull/1787

Simplified isFullVariableOverrideDef implementation

---

bundle/phases/deploy.go
bundle/phases/initialize.go
bundle/trampoline/conditional_transform_test.go
bundle/trampoline/python_dbr_warning.go
bundle/trampoline/python_dbr_warning_test.go
bundle/trampoline/python_wheel.go
bundle/trampoline/python_wheel_test.go
bundle/trampoline/trampoline.go
bundle/trampoline/trampoline_test.go

Doing this to make room for PyDABs under `bundle/python`.
n/a

Move trampoline code into trampoline package

---

bundle/config/mutator/apply_presets.go
bundle/config/mutator/apply_presets_test.go

This fixes the user-reported panic in `apply_presets.go`. I'm still unsure how to reproduce this, since the CLI just reports `ob broken_job is not defined` when I try to use `bundle deploy` with an empty job. That said — we may as well be defensive here and I see we have lots of checks for empty job/cluster/etc. settings scattered throughout our code base so at least we're somewhat consistent.

Fix panic in `apply_presets.go`

---

CHANGELOG.md

Bundles:
* Added support for creating all-purpose clusters ([#1698](https://github.com/databricks/cli/pull/1698)).
* Reduce time until the prompt is shown for bundle run ([#1727](https://github.com/databricks/cli/pull/1727)).
* Use Unity Catalog for pipelines in the default-python template ([#1766](https://github.com/databricks/cli/pull/1766)).
* Add verbose flag to the "bundle deploy" command ([#1774](https://github.com/databricks/cli/pull/1774)).
* Fixed full variable override detection ([#1787](https://github.com/databricks/cli/pull/1787)).
* Add sub-extension to resource files in built-in templates ([#1777](https://github.com/databricks/cli/pull/1777)).
* Fix panic in `apply_presets.go` ([#1796](https://github.com/databricks/cli/pull/1796)).
Internal:
* Assert tokens are redacted in …

[Release] Release v0.229.0

---

bundle/deploy/state_push.go
bundle/deploy/terraform/state_push.go
bundle/deploy/terraform/state_push_test.go

Currently API limits on exporting files from workspaces are set at 10 MBs while uploading to is 500 MBs. We want to prevent users running into deadlock when they won't be able to pull state file anymore so we prevent from uploading large state files (over 10 MBs) to Databricks workspace.

Add an error if state files grow bigger than the export limit

---

bundle/config/mutator/default_workspace_paths.go
bundle/config/mutator/default_workspace_paths_test.go
bundle/config/mutator/process_target_mode.go
bundle/config/workspace.go

Default workspace path for resources with a presence in the workspace tree.
Note: this path is **not** created automatically (yet). We need this only for dashboards (so far), so can take care of creation if one or more dashboards are part of a deployment. This saves an API call for deployments where this is not necessary.
Expanded existing tests.

Add resource path field to bundle workspace configuration

---

libs/template/helpers.go

This extends the `{{default_catalog}}` helper in templates to ignore any `PERMISSION_DENIED` error. We're still reviewing when exactly this error occurs, but if it does, it should not break templates. We should fall back to assuming there's no default catalog (and no UC) instead.
I have not been able to reproduce this issue, but there is a customer report about "access denied to clusters that don't have unity catalog enabled" being returned on a non-UC workspace. The error code in this PR corresponds to that message.
We'll work together with the UC team to review if this error even makes sense for this API. If that discussion leads to a behavior change in the API we can update the CLI code again.

Ignore metastore permission error during template generation
