databricks/cli

- bundle/internal/tf/schema/data_source_cluster_policy.go
- bundle/internal/tf/schema/data_source_job.go
- bundle/internal/tf/schema/resource_catalog.go
- bundle/internal/tf/schema/resource_external_location.go
- bundle/internal/tf/schema/resource_job.go
- bundle/internal/tf/schema/resource_model_serving.go
- bundle/internal/tf/schema/resource_permissions.go
- bundle/internal/tf/schema/resource_storage_credential.go
- bundle/internal/tf/schema/resource_volume.go
- bundle/internal/tf/schema/resources.go
Generated latest set of code gen for the newest objects from the terraform provider.
`bundles/internal/tf/schema`
Ran the existing unit tests and they seemed to have checked out.
> Update Terraform provider schema structs

- libs/databrickscfg/loader.go
- libs/databrickscfg/ops.go
This reverts changes from #513 which ended up not being necessary.
> Follow up to #513

- cmd/workspace/repos/overrides.go
- cmd/workspace/repos/provider.go
- cmd/workspace/repos/provider_test.go
- internal/repos_test.go
Closes #527.
Integration tests pass.
> Add provider detection to the repos create command

- cmd/fs/ls.go
- internal/fs_ls_test.go
> Add --absolute flag for ls command

- bundle/schema/docs/bundle_descriptions.json
- bundle/schema/openapi.go
> Add documentation for ML resources in JSON schema

- bundle/config/workspace.go
- bundle/schema/docs/bundle_descriptions.json
Add support for more SDK config options
> Add support for more SDK config options

- bundle/config/artifact.go
- bundle/libraries/libraries.go
Added support for build command chaining and error on missing wheel
> Added support for build command chaining and error on missing wheel

- .github/workflows/push.yml
- .github/workflows/release-snapshot.yml
- .github/workflows/release.yml
This should fix intermittent failures with v3 (see https://github.com/actions/checkout/issues/1448)
> Upgrade to actions/checkout@v4

- cmd/version/version.go
Added description for version command
```
databricks help
...
Additional Commands:
account              Databricks Account Commands
api                  Perform Databricks API call
auth                 Authentication related commands
bundle               Databricks Asset Bundles
completion           Generate the autocompletion script for the specified shell
fs                   Filesystem related commands
help                 Help about any command
sync                 Synchronize a local directory to a workspace directory
version              Retrieve information about the current version of CLI
```
> Added description for version command

- CHANGELOG.md
This release includes permission related commands for a subset of workspace
services where they apply. These complement the `permissions` command and
do not require specification of the object type to work with, as that is
implied by the command they are nested under.
CLI:
* Group permission related commands ([#730](https://github.com/databricks/cli/pull/730)).
Bundles:
* Fixed artifact file uploading on Windows and wheel execution on DBR 13.3 ([#722](https://github.com/databricks/cli/pull/722)).
* Make resource and artifact paths in bundle config relative to config folder ([#708](https://github.com/databricks/cli/pull/708)).
* Add support for ordering of input prompts ([#662](https://github.com/databricks/cli/pull/662)).
* Fix IsServicePrincipal() only working for workspace admins …
> Release v0.204.0

- internal/bundle/bundles/python_wheel_task/databricks_template_schema.json
- internal/bundle/bundles/python_wheel_task/template/databricks.yml.tmpl
- internal/bundle/python_wheel_test.go
Generate unique name for a job in Python wheel test
> Generate unique name for a job in Python wheel test

- bundle/config/mutator/select_target.go
- bundle/tests/suggest_target_test.go
List available targets when incorrect target passed
```
andrew.nester@HFW9Y94129 wheel % databricks bundle validate -t incorrect
Error: incorrect: no such target. Available targets: prod, development
```
> List available targets when incorrect target passed

- libs/template/templates/default-python/template/{{.project_name}}/setup.py.tmpl
Fix author in setup.py showing <no value>
> Fix author in setup.py

- CHANGELOG.md
CLI:
* Prompt for profile only in interactive mode ([#788](https://github.com/databricks/cli/pull/788)).
Internal:
* Added setup Python action ([#789](https://github.com/databricks/cli/pull/789)).
> Release v0.205.2

- bundle/config/artifact.go
Mark artifacts properties as optional
Fixes #816
> Mark artifacts properties as optional

- .github/workflows/release.yml
Create a release PR in setup-cli repo on tag push
> Create a release PR in setup-cli repo on tag push

- .github/workflows/release.yml
> Define goreleaser job output

- bundle/internal/tf/codegen/templates/root.go.tmpl
- bundle/internal/tf/schema/root.go
The preparations for this change were in place (see #713) but it wasn't actually used.
n/a
> Propagate Terraform provider version into generated config

- internal/build/info.go
> Make default dev semver a const

- bundle/python/warning.go
- bundle/python/warning_test.go
Do not emit wheel wrapper error when python_wheel_wrapper setting is true
Fixes #892 
Added an regression test
> Do not emit wheel wrapper error when python_wheel_wrapper setting is true

- libs/jsonschema/instance.go
- libs/jsonschema/instance_test.go
- libs/jsonschema/testdata/instance-validate/multiple-patterns-schema.json
Fixes bug where input validation would only be done on the first input parameter in the template schema.
Unit test.
> Fix pattern validation for input properties

- cmd/bundle/bundle.go
- cmd/configure/configure.go
> Make configure command visible + fix bundle command description

- libs/config/value.go
- libs/config/value_test.go
Small function broken out from other work in progress.
> Add function to check if `config.Value` is valid

- .codegen.json
Introduced in #1007 but doesn't work well yet. This will be automated again as part of #1012.
> Revert automation for bundle schema documentation generation

- cmd/labs/clear_cache.go
- cmd/labs/labs.go
- cmd/labs/list.go
- cmd/labs/project/entrypoint.go
- cmd/labs/project/fetcher.go
- cmd/labs/project/helpers.go
- cmd/labs/project/installed.go
- cmd/labs/project/installer.go
- cmd/labs/project/installer_test.go
- cmd/labs/project/project.go
- cmd/labs/project/proxy.go
- cmd/labs/show.go
- libs/databrickscfg/profiles.go
- libs/env/context.go
- libs/env/context_test.go
This PR adds error to `env.UserHomeDir(ctx)`
Fixes https://github.com/databricks/setup-cli/issues/73
> Fix `panic: $HOME is not set`

- cmd/workspace/secrets/overrides.go
Fixes #1067
```
andrew.nester@HFW9Y94129 cli % databricks secrets list-secrets "my-test-scope"  --output text         
Key             Last Updated Timestamp
my-secret       1692805686489
my-test-secret  1692767910771
```
> Added output template for list-secrets command

- libs/template/config.go
> Do not prompt for template values in Git Bash

- cmd/workspace/storage-credentials/overrides.go
- internal/storage_credentials_test.go
> Fixed storage-credentials list command in text output

- .github/workflows/push.yml
Added codecov integration on code push
> Added codecov integration on code push

- .codegen/lookup.go.tmpl
- bundle/config/variable/lookup.go
- bundle/tests/variables/env_overrides/databricks.yml
- bundle/tests/variables_test.go
Fixed instance pool resolving by name
> Fixed instance pool resolving by name

- internal/bundle/generate_job_test.go
Fixed path matching for Windows in generate job test
> Fixed path matching for Windows in generate job test

- cmd/workspace/dashboards/dashboards.go
- cmd/workspace/token-management/token-management.go
- go.mod
- go.sum
Update Go SDK to 0.30.1
```
make fmt && make test
```
> Update Go SDK to v0.30.1

- bundle/scripts/scripts_test.go
Follow up to https://github.com/databricks/cli/pull/1232
> Added test to verify scripts.Execute mutator works correctly

- libs/exec/shell_bash.go
Fixed building Python artifacts on Windows with WSL
Fixes #1243
> Fixed building Python artifacts on Windows with WSL

- CHANGELOG.md
Fixed --fail-on-active-runs in Changelog
> Fixed --fail-on-active-runs in Changelog

- bundle/config/mutator/mutator.go
Execute preinit after entry point to make sure scripts are loaded
> Execute preinit after entry point to make sure scripts are loaded

- internal/bundle/basic_test.go
- internal/bundle/helpers.go
- internal/bundle/job_metadata_test.go
- internal/bundle/local_state_staleness_test.go
- internal/bundle/python_wheel_test.go
> Update Spark version in integration tests to 13.3

- cmd/bundle/bundle.go
> Fix bundle documentation URL

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_job.go
- bundle/internal/tf/schema/resource_cluster.go
- bundle/internal/tf/schema/resource_cluster_policy.go
- bundle/internal/tf/schema/resource_job.go
- bundle/internal/tf/schema/resource_library.go
- bundle/internal/tf/schema/resource_mws_ncc_binding.go
- bundle/internal/tf/schema/resource_mws_ncc_private_endpoint_rule.go
- bundle/internal/tf/schema/resource_mws_network_connectivity_config.go
- bundle/internal/tf/schema/resources.go
- bundle/internal/tf/schema/root.go
Upgrade TF provider to 1.42.0
Also fixes #1258
> Upgrade TF provider to 1.42.0

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/root.go
Upgrade to 1.43 terraform provider
> Upgrade to 1.43 terraform provider

- internal/bundle/destroy_test.go
I've updated the `deploy_then_remove_resources` test template in the previous PR, but didn't notice that it was used in the destroy test too. Now destroy test also checks deletion of jobs
> Fix bundle destroy integration test

- libs/dyn/merge/override_test.go
Add test coverage to ensure we respect return value and error
Unit tests
> Add more tests for `merge.Override`

- bundle/artifacts/artifacts.go
- bundle/libraries/libraries.go
- bundle/libraries/match.go
- bundle/tests/enviroment_key_test.go
- bundle/tests/environment_key_only/databricks.yml
Fixed seg fault when specifying environment key for tasks
> Fixed seg fault when specifying environment key for tasks

- libs/template/templates/default-sql/template/{{.project_name}}/src/orders_daily.sql.tmpl
This corrects a mistake in the sample SQL identified by @pietern
> Fix conditional in query in `default-sql` template

- libs/template/templates/dbt-sql/template/{{.project_name}}/README.md.tmpl
Found in https://github.com/databricks/bundle-examples/pull/26.
n/a
> Fix typo in DBT template

- bundle/tests/variables/empty/databricks.yml
- bundle/tests/variables_test.go
- libs/dyn/convert/to_typed.go
- libs/dyn/convert/to_typed_test.go
> Fixed bundle not loading when empty variable is defined

- cmd/bundle/init.go
Add a new hidden experimental template 
Tested manually
> Add new template

- libs/auth/user_test.go
- libs/textutil/textutil.go
- libs/textutil/textutil_test.go
> Fixed job name normalisation for bundle generate

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_cluster.go
- bundle/internal/tf/schema/data_source_schema.go
- bundle/internal/tf/schema/data_source_volume.go
- bundle/internal/tf/schema/data_sources.go
- bundle/internal/tf/schema/resource_dashboard.go
- bundle/internal/tf/schema/resource_permissions.go
- bundle/internal/tf/schema/resource_workspace_binding.go
- bundle/internal/tf/schema/resources.go
- bundle/internal/tf/schema/root.go
This includes a fix for model serving endpoints.
See https://github.com/databricks/terraform-provider-databricks/pull/3690.
n/a
> Upgrade TF provider to 1.49.0

- internal/helpers.go
Increased chan size for clusters test to pass
> Increased chan size for clusters test to pass

- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/python/python_mutator_test.go
Preserve diagnostics if there are any errors or warnings when PythonMutator normalizes output. If anything goes wrong during conversion, diagnostics contain the relevant location and path.
Unit tests
> PythonMutator: preserve normalize diagnostics

- bundle/config/deployment.go
Fixes https://github.com/databricks/cli/issues/1561
> Make lock optional in the JSON schema

- internal/bundle/artifacts_test.go
I didn't run integration tests on #1756.
Manually confirmed integration tests pass.
> Fix artifact upload integration tests

- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/python/python_mutator_test.go
Trailing whitespace is trimmed per the VS Code settings for this repository.
n/a
> Trim trailing whitespace

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_current_metastore.go
- bundle/internal/tf/schema/data_source_metastore.go
- bundle/internal/tf/schema/data_source_mlflow_models.go
- bundle/internal/tf/schema/data_sources.go
- bundle/internal/tf/schema/resource_budget.go
- bundle/internal/tf/schema/resource_model_serving.go
- bundle/internal/tf/schema/resource_permissions.go
- bundle/internal/tf/schema/resource_pipeline.go
- bundle/internal/tf/schema/resource_sql_table.go
- bundle/internal/tf/schema/resources.go
- bundle/internal/tf/schema/root.go
See https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.53.0
Integration tests pass.
> Upgrade TF provider to 1.53.0

- bundle/permissions/mutator.go
Leftover from #1386.
All tests pass (indicating it really wasn't used).
> Remove unused `IS_OWNER` constant

- bundle/deploy/terraform/tfdyn/convert_cluster.go
- bundle/deploy/terraform/tfdyn/convert_cluster_test.go
Fixed typo in converting cluster permissions
> Fixed typo in converting cluster permissions

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_notification_destinations.go
- bundle/internal/tf/schema/data_source_registered_model.go
- bundle/internal/tf/schema/data_sources.go
- bundle/internal/tf/schema/resource_job.go
- bundle/internal/tf/schema/resource_online_table.go
- bundle/internal/tf/schema/resource_pipeline.go
- bundle/internal/tf/schema/root.go
> Upgrade TF provider to 1.54.0

- bundle/config/mutator/load_git_details.go
Suggested here https://github.com/databricks/cli/pull/1945#discussion_r1866088579
> Simplify load_git_details.go; remove unnecessary Abs() call

- Makefile
Make it possible to change what/how we run our integration tests from within this repository.
Integration tests all pass when run with this command.
> Add build rule for running integration tests

- .github/workflows/push.yml
Make this robust against inadvertent upgrades.
> Pin gotestsum version to v1.12.0

- .golangci.yaml
- bundle/artifacts/whl/autodetect.go
- bundle/deferred_test.go
- bundle/deploy/terraform/plan.go
- bundle/libraries/filer_volume_test.go
- bundle/run/job.go
- bundle/run/pipeline.go
- cmd/labs/project/entrypoint.go
- cmd/root/auth_test.go
- libs/diag/diagnostic.go
- libs/log/logger.go
- libs/template/renderer.go
Fix all the govet-found issues and enable govet linter.
This prompts adding non-formatting variants of logging functions (Errorf -> Error).
> Enable 'govet' linter; expand log/diag with non-f functions

- .github/workflows/push.yml
- .github/workflows/release-snapshot.yml
- .github/workflows/release.yml
- bundle/internal/tf/codegen/go.mod
- go.mod
`git grep -l 1.23.2 | xargs -n 1 sed -i '' 's/1.23.2/1.23.4/'`
Existing tests
> Upgrade go to 1.23.4

- .golangci.yaml
- bundle/config/mutator/process_target_mode_test.go
- bundle/config/resources_test.go
- bundle/config/variable/lookup_test.go
- bundle/deploy/terraform/convert_test.go
- bundle/deploy/terraform/state_push_test.go
- bundle/internal/schema/parser.go
- bundle/run/pipeline.go
- integration/libs/locker/locker_test.go
- integration/python/python_tasks_test.go
- libs/cmdio/render.go
- libs/cmdio/render_test.go
- libs/dyn/convert/from_typed.go
- libs/dyn/convert/struct_info.go
- libs/dyn/mapping_test.go
- libs/dyn/merge/override.go
- libs/dyn/path.go
- libs/dyn/visit_map_test.go
- libs/exec/exec_test.go
- libs/filer/fs_test.go
- libs/jsonschema/from_type.go
New construct in Go1.22+ for integer iteration: https://github.com/ckaznocha/intrange?tab=readme-ov-file#intrange
> Enable intrange linter and apply autofix

- go.mod
- go.sum
Fixes https://github.com/databricks/cli/security/dependabot/20
> Upgrade golang.org/x/net from v0.26.0 to v0.33.0

- .github/workflows/external-message.yml
- .github/workflows/integration-approve.yml
- .github/workflows/integration-main.yml
- .github/workflows/integration-pr.yml
See https://github.com/databricks/cli/issues/2084.
> Disable integration workflows

- bundle/deploy/terraform/init.go
- bundle/deploy/terraform/init_test.go
Update instrumentation for PythonMutator to handle `experimental/python` config.
Unit tests
> PythonMutator: update instrumentation

- acceptance/bundle/variables/complex-transitive-deeper/databricks.yml
- acceptance/bundle/variables/complex-transitive-deeper/output.txt
- acceptance/bundle/variables/complex-transitive-deeper/script
Extension of complex-transitive test that shows an error instead of simply failing to interpolate.
> Add complex-transitive-deeper acceptance test

- bundle/run/app.go
- bundle/run/app_test.go
If before running an app, the app was stopped with an active deployment, then Apps backend start it and does the auto-deploy of the last active deployment. In such cases StartApp API won't return any active or pending deployments in its response but doing the deploy immediately after the start might result in the error `Cannot deploy app *** as there is an active deployment in progress`.
From DABs side, we have to do a new deployment on every `bundle run` (command which start the app and does deployment) because local files in bundle might have been changed and users expect to have the app running with new code.
Thus this PR works around the error by catching “deployment in progress” error, getting any active / pending deployments,  waits for them to finish and start the new deployment …
> Retry app deployment if there is an active deployment in progress

- bundle/apps/slow_deploy_message.go
Changed warning message for apps
Original warning message added here: https://github.com/databricks/cli/pull/2161
> Changed warning message for apps

- acceptance/bundle/variables/arg-repeat/databricks.yml
- acceptance/bundle/variables/arg-repeat/output.txt
- acceptance/bundle/variables/arg-repeat/script
This shows that passing two --var for the same arg is rejected currently.
> Add test for passing --var twice for the same arg

- bundle/deploy/terraform/init.go
No functional changes, just making it easier to add variables.
> Refactor env forwarding function in terraform

- bundle/deploy/terraform/init.go
https://github.com/databricks/cli/pull/747#discussion_r1925248116
> Fix context propagation in bundle/deploy/terraform

- acceptance/acceptance_test.go
- acceptance/bundle/templates/experimental-jobs-as-code/script
Revert changes to acceptance_test.go added in #2177 and add test-specific fix.
> Remove test-specific logic from generic test runner

- acceptance/bundle/templates/wrong-path/output.txt
- acceptance/bundle/templates/wrong-path/script
- acceptance/bundle/templates/wrong-path/test.toml
- acceptance/bundle/templates/wrong-url/output.txt
- acceptance/bundle/templates/wrong-url/script
- acceptance/bundle/templates/wrong-url/test.toml
This captures how we log errors related to subprocess run and what does the output look like.
> acc: Add a couple of error tests for 'bundle init'

- bundle/internal/tf/codegen/schema/version.go
- bundle/internal/tf/schema/data_source_serving_endpoints.go
- bundle/internal/tf/schema/resource_app.go
- bundle/internal/tf/schema/resource_job.go
- bundle/internal/tf/schema/resource_model_serving.go
- bundle/internal/tf/schema/resource_recipient.go
- bundle/internal/tf/schema/root.go
- Added support for `no_compute` in Apps
- Added support for `run_as_repl` for job tasks
> Upgrade TF provider to 1.64.1

- integration/bundle/apps_test.go
- integration/bundle/bundles/apps/template/databricks.yml.tmpl
Adds additional step to integration test which changes the app config and confirms it's updated after redeploy
```
helpers_test.go:156: stderr: Deleting files...
helpers_test.go:156: stderr: Destroy complete!
--- PASS: TestDeployBundleWithApp (470.25s)
PASS
coverage: [no statements]
ok      github.com/databricks/cli/integration/bundle    470.981s        coverage: [no statements]
```
> Update app deploy test to confirm app config changes on redeploy

- acceptance/bundle/variables/env_overrides/test.toml
- acceptance/bundle/variables/resolve-builtin/test.toml
- acceptance/bundle/variables/resolve-vars-in-root-path/test.toml
- acceptance/bundle/variables/test.toml
> acc: Make variable tests local-only

- acceptance/bin/diff.py
Fix diff.py to apply replacements that have newlines in them.
> acc: Support multiline patterns in diff.py

- acceptance/bundle/includes/include_outside_root/output.txt
- bundle/config/loader/process_include.go
Addresses feedback from this thread: https://github.com/databricks/cli/pull/2389#discussion_r1975760462.
> Update warning for includes outside root to only mention databricks.yml

- bundle/config/validate/interpolation_in_auth_config.go
Addresses post merge feedback from https://github.com/databricks/cli/pull/2399#discussion_r1975091730
N/A
> Do not use `.MustString()` in auth interpolation warning

- libs/command/config_used_test.go
I forgot to add a unit test in the original PR, so adding it here: https://github.com/databricks/cli/pull/2440
N/A
NO_CHANGELOG=true
> Add unit test for `command.ConfigUsed`

- acceptance/acceptance_test.go
> acc: add replacement for $TEST_INSTANCE_POOL_ID

- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/pyproject.toml
- acceptance/bundle/templates/experimental-jobs-as-code/script
- libs/template/templates/experimental-jobs-as-code/template/{{.project_name}}/pyproject.toml.tmpl
Fix a problem where the output wheel didn't contain any code, because it was assuming flat-layout.
Updated acceptance tests
> Fix uv in experimental-jobs-as-code template

- acceptance/acceptance_test.go
Add test summary showing run/selected/total tests & skipped.
Also
- Refactor skip logic into separate function
- Remove SingleTest variable, debugging can be done via TestInprocessMode().
Manually. Also ran benchmark to see that there are no regressions.
> acc: Add test summary, refactor skip & debug logic

- NEXT_CHANGELOG.md
Added tarballs changes to the changes log + updated next version to be a minor bump
Worth calling out the change in the Changelog
> Added tarballs changes to the changes log

- .github/workflows/release-snapshot.yml
Add tar.gz to the release-snapshot.yml
> Add tar.gz to the release-snapshot.yml

- .github/CODEOWNERS
See #2055 for PR that introduced this.
> Add @anton-107 to CODEOWNERS

- acceptance/bin/diff.py
- acceptance/selftest/diff/output.txt
- acceptance/selftest/diff/script
> acc: support diffing files in diff.py

- acceptance/bundle/artifacts/glob_exact_whl/test.toml
Seems a copy-paste error. Thanks to https://github.com/databricks/cli/pull/2540/files#r2011812339
> Clean up wrong Badness

- bundle/config/mutator/python/python_mutator.go
- bundle/config/mutator/python/python_mutator_test.go
Allow PythonMutator to change non-job resources.
Previously, we disallowed adding/changing pipelines, for example. Now, we don't have such restrictions. With that, we can add support for other kinds of resources to Python code.
Unit tests
> [Python] Allow PythonMutator to change non-job resources

- acceptance/bundle/telemetry/deploy-config-file-count/output.txt
- acceptance/bundle/telemetry/deploy-mode/databricks.yml
- acceptance/bundle/telemetry/deploy-mode/output.txt
- acceptance/bundle/telemetry/deploy-mode/script
- acceptance/bundle/telemetry/deploy-no-uuid/output.txt
- acceptance/bundle/telemetry/deploy/output.txt
- bundle/phases/deploy.go
It's interesting to know how often these modes are used vs un-specified.
Acceptance test.
> Track deployment mode in deploy telemetry

- NEXT_CHANGELOG.md
Follow up to https://github.com/databricks/cli/pull/2565
> Update NEXT_CHANGELOG re email_notifications

- acceptance/bundle/includes/yml_outside_root/include.yml
- acceptance/bundle/includes/yml_outside_root/output.txt
- acceptance/bundle/includes/yml_outside_root/root/databricks.yml
- acceptance/bundle/includes/yml_outside_root/script
- acceptance/bundle/includes/yml_outside_root/test.toml
Added test for including YAML configuration outside bundle root
To confirm the feature works as expected
> acc: Added test for including YAML configuration outside bundle root

- NEXT_CHANGELOG.md
Add TF provider upgrade to Changelog
> Add TF provider upgrade to Changelog

- acceptance/bundle/deployment/bind/registered-model/test.toml
- acceptance/bundle/deployment/bind/schema/test.toml
- acceptance/bundle/deployment/bind/volume/test.toml
- acceptance/internal/server.go
- libs/testserver/apps.go
- libs/testserver/fake_workspace.go
- libs/testserver/quality_monitors.go
- libs/testserver/schemas.go
- Add CRUD for schemas to testserver.
- Add generic MapGet & MapDelete to use in different resources.
- Fix testserver apps DELETE method.
Existing tests with hard-coded responses switched to CRUD without any changes.
> testserver: Support schemas; generic get/delete

- .github/workflows/start-integration-tests.yml
Follow up to https://github.com/databricks/cli/pull/2688
> Fix typo in start-integration-tests.yml

- bundle/artifacts/build.go
- bundle/artifacts/prepare.go
- bundle/libraries/upload.go
- bundle/tests/include_test.go
- libs/dyn/dynvar/resolve.go
- libs/utils/utils.go
- Move helper sortedKeys from artifacts package to libs/utils
- Use it where it's useful.
> Add utils module with SortedKeys helper

- acceptance/bundle/presets/preset_vs_dev_mode/databricks.yml
- acceptance/bundle/presets/preset_vs_dev_mode/output.txt
- acceptance/bundle/presets/preset_vs_dev_mode/script
- acceptance/bundle/presets/preset_vs_dev_mode/test.toml
Based on slack thread in help-dabs.
Related: https://github.com/databricks/cli/pull/1490/files#diff-9eedd6c63465cd766c89497eda7f212c5b6868054393cfe464d8d1bc69692576R79
> acc: Add a test with development mode + preset

- acceptance/bundle/help/bundle-init/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/databricks.yml
- libs/template/template.go
- libs/template/template_test.go
- libs/template/templates/experimental-jobs-as-code/template/{{.project_name}}/databricks.yml.tmpl
Show `experimental-jobs-as-code` template in `bundle init` list
Existing acceptance tests
> [Python] Show experimental-jobs-as-code template

- libs/dyn/dynvar/resolve_test.go
Increase test coverage for variable interpolation.
Prompted by a discussion about the code in `resolve.go`.
> Add tests for map and sequence variable interpolation

- bundle/phases/deploy.go
- bundle/phases/telemetry.go
Based on feedback in https://github.com/databricks/cli/pull/2593#discussion_r2055792162
> Move deploy telemetry function to a separate file

- bundle/config/mutator/resourcemutator/configure_dashboards_serialized_dashboard.go
Uses more comprehensible code to achieve the same result
Existing acceptance tests
> refactor: use DropKeys instead of Walk+ErrDrop to drop the file_path key from dashboard definition

- NEXT_CHANGELOG.md
Follow up to https://github.com/databricks/cli/pull/2828
> Fix NEXT_CHANGELOG syntax

- acceptance/bundle/override/clusters/output.txt
- acceptance/bundle/override/merge-string-map/output.txt
- acceptance/bundle/validate/empty_resources/empty_dict/output.txt
- acceptance/bundle/validate/empty_resources/with_grants/output.txt
- acceptance/bundle/validate/empty_resources/with_permissions/output.txt
- bundle/config/mutator/resourcemutator/apply_presets.go
Follow up to https://github.com/databricks/cli/pull/2756
> presets: Do not add "custom_tags: {}" to clusters

- .wsignore
- acceptance/bundle/integration_whl/base/output.txt
- acceptance/bundle/integration_whl/custom_params/output.txt
- acceptance/bundle/integration_whl/interactive_cluster/output.txt
- acceptance/bundle/integration_whl/interactive_cluster_dynamic_version/output.txt
- acceptance/bundle/integration_whl/interactive_single_user/output.txt
- acceptance/bundle/integration_whl/serverless/output.txt
- acceptance/bundle/integration_whl/serverless_dynamic_version/output.txt
- acceptance/bundle/integration_whl/wrapper/output.txt
- acceptance/bundle/integration_whl/wrapper_custom_params/output.txt
- acceptance/bundle/run/basic/output.txt
- bundle/run/progress/job.go
Addressed feedback from: https://github.com/databricks/cli/pull/2695#discussion_r2084386583
> Remove trailing whitespace from bundle run output

- acceptance/cmd/workspace/apps/run-local/test.toml
I saw it failing a few times on CI today.
> acc: Increase TimeoutWindows for apps/run-local

- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/pyproject.toml
- acceptance/bundle/templates/experimental-jobs-as-code/test.toml
https://github.com/databricks/cli/pull/2868/files#r2087216913
> acc: Replace package version in jobs-as-code test

- acceptance/bundle/deploy/pipeline/auto-approve/bar.py
- acceptance/bundle/deploy/pipeline/auto-approve/databricks.yml.tmpl
- acceptance/bundle/deploy/pipeline/auto-approve/foo.py
- acceptance/bundle/deploy/pipeline/auto-approve/output.txt
- acceptance/bundle/deploy/pipeline/auto-approve/resources.yml.tmpl
- acceptance/bundle/deploy/pipeline/auto-approve/script
- acceptance/bundle/deploy/pipeline/auto-approve/test.toml
- integration/bundle/deploy_test.go
- libs/testserver/fake_workspace.go
One change in the series of changes for converting integration tests into acceptance tests.
This will allow for easier testing of various backing solutions for bundle deployment
> Convert integration test TestBundlePipelineDeleteWithoutAutoApprove to an acceptance test

- acceptance/bundle/deploy/secret-scope/permissions/databricks.yml.tmpl
- acceptance/bundle/deploy/secret-scope/permissions/output.txt
This test now exercises the top-level permissions mapping and setting secret scopes permissions on the resource level
Extended existing test
> Expand secret scope permissions test with more examples

- libs/testserver/apps.go
- libs/testserver/quality_monitors.go
- libs/testserver/schemas.go
- libs/testserver/volumes.go
Follow up to https://github.com/databricks/cli/pull/2816
> testserver: add missing synchronization

- bundle/apps/upload_config.go
- bundle/config/validate/validate_sync_patterns.go
- libs/diag/diagnostic.go
A new helper to update diags from multiple threads. Also includes shortcuts for frequently used Error and Errorf.
Simpler and less error-prone code in mutators.
Using this in https://github.com/databricks/cli/pull/2926
> Add diag.SafeDiagnostics class

- acceptance/bundle/templates/default-python/integration_classic/test.toml
Follow up to https://github.com/databricks/cli/pull/2943
> acc: enable replacement for UV_PYTHON

- NEXT_CHANGELOG.md
Add changelog entry for experimental Lakeflow template
> Add changelog entry for experimental Lakeflow template

- acceptance/acceptance_test.go
- acceptance/bundle/override/clusters/output.txt
- acceptance/bundle/override/job_cluster/output.txt
- acceptance/bundle/override/job_cluster_var/output.txt
- acceptance/bundle/override/job_tasks/output.txt
- acceptance/bundle/override/pipeline_cluster/output.txt
- acceptance/bundle/templates/dbt-sql/output/my_dbt_sql/resources/my_dbt_sql.job.yml
- acceptance/bundle/templates/default-python/classic/out.compare-vs-serverless.diff
- acceptance/bundle/templates/default-python/classic/output/my_default_python/resources/my_default_python.job.yml
- acceptance/bundle/templates/default-python/integration_classic/test.toml
- acceptance/bundle/templates/experimental-jobs-as-code/output.txt
- acceptance/bundle/templates/experimental-jobs-as-code/output/my_jobs_as_code/resources/my_jobs_as_code_job.py
Also modify NODE_TYPE_ID in local mode to match AWS.
> acc: enable default-python/integration_classic on local and GCP

- NEXT_CHANGELOG.md
- acceptance/bundle/artifacts/nil_artifacts/databricks.yml
- acceptance/bundle/artifacts/nil_artifacts/output.txt
- acceptance/bundle/artifacts/nil_artifacts/script
- acceptance/bundle/artifacts/nil_artifacts/test.toml
- bundle/artifacts/prepare.go
Fixed null pointer de-reference if artifacts missing fields
Fixes #3017 
> Fixed null pointer de-reference if artifacts missing fields

- acceptance/bundle/deploy/dashboard/nested-folders/dashboards/sample-dashboard.lvdash.json
- acceptance/bundle/deploy/dashboard/nested-folders/databricks.yml.tmpl
- acceptance/bundle/deploy/dashboard/nested-folders/output.txt
- acceptance/bundle/deploy/dashboard/nested-folders/resources/dashboards.yml.tmpl
- acceptance/bundle/deploy/dashboard/nested-folders/script
- acceptance/bundle/deploy/dashboard/nested-folders/test.toml
Added a new test that has a nested folder structure which reflects how some users are arranging their files in the bundle
> Add an acceptance test for deploying a dashboard from a nested folder structure

- tools/lintdiff.py
Capture thread in comments: https://github.com/databricks/cli/pull/3021#discussion_r2149308023
> Clarify assumptions in tools/lintdiff.py in comment

- bundle/deploy/terraform/showplanfile.go
- bundle/deployplan/plan.go
- bundle/phases/deploy_test.go
> deployplan: Rename Action.Action to Action.ActionType

- acceptance/bundle/integration_whl/test.toml
- acceptance/bundle/run/app-with-job/test.toml
Follow up to https://github.com/databricks/cli/pull/2926
> Disable CloudSlow tests on direct deployment

- bundle/config/mutator/initialize_urls_test.go
- bundle/config/mutator/resourcemutator/apply_target_mode_test.go
- bundle/config/mutator/translate_paths_dashboards_test.go
- bundle/config/resources/dashboard.go
- bundle/config/resources_test.go
- bundle/deploy/terraform/check_dashboards_modified_remotely_test.go
- bundle/deploy/terraform/convert_test.go
- bundle/deploy/terraform/tfdyn/convert_dashboard_test.go
Extract DashboardConfig out of Dashboard resource.
It's going to be used in direct backend to store state.
> Extract DashboardConfig struct

- acceptance/bin/read_id.py
- acceptance/bin/read_state.py
- bundle/bundle.go
- bundle/config/resources_types.go
- bundle/terranova/apply.go
- bundle/terranova/plan.go
- bundle/terranova/tnresources/resource.go
- bundle/terranova/tnstate/state.go
https://github.com/databricks/cli/pull/2926/files#r2154501729
> Use "group" instead of "section" when talking about resources

- integration/libs/locker/locker_test.go
This integration test creates a repo when it does not need to. Repos have been a persistent source of flakiness because they do not behave well under load.
This PR reduces flakiness and improves CI health. 
Failure logs:
```
=== FAIL: integration/libs/git TestFetchRepositoryInfoAPI_FromRepo (re-run 2) (4.42s)
Error:      	Received unexpected error:
a Workspace object at path /Repos/***/integration-test-e7844b5d8018420996b3bb0f95aec84e already exists. Try a different path for your Repo or rename the existing Workspace object.
```
> Fix TestLock not to create a new repo

- acceptance/bundle/resources/clusters/run/spark_python_task/test.toml
Reverts https://github.com/databricks/cli/pull/3195
> Restore slash replacement in spark_python_task

- acceptance/bundle/deploy/lakebase/database-instance/single-instance/out.test.toml
- acceptance/bundle/deploy/lakebase/database-instance/single-instance/test.toml
- bundle/terranova/tnresources/database_instance.go
- bundle/terranova/tnresources/resource.go
> Implement database instance resource in direct deployment

- acceptance/bundle/deploy/empty-bundle/out.test.toml
- acceptance/bundle/deploy/empty-bundle/test.toml
- For completeness of this test - in cloud mode it runs against cloud APIs
- It is a useful "no-op" test to have when debugging API calls that the CLI is making to the Workspace
Ran this test in cloud mode
> Enable "deploy empty bundle" acceptance test in the cloud

- acceptance/bundle/resources/jobs/create-error/databricks.yml
- acceptance/bundle/resources/jobs/create-error/out.test.toml
- acceptance/bundle/resources/jobs/create-error/output.txt
- acceptance/bundle/resources/jobs/create-error/script
- acceptance/bundle/resources/jobs/create-error/test.toml
> acc: Add a test for error during jobs creation

- acceptance/internal/prepare_server.go
Use the same code for calculating token to use in tests.
There is no need to have different logic for startProxyServer and startLocalServer and there is no reason to make those functions responsible for the token.
I'd like to use token to encode other info, such as user name or service principal name, this helps with that: https://github.com/databricks/cli/pull/3315
> acc: Extract token calculation into common block

- acceptance/bundle/integration_whl/base/out.test.toml
Follow up to https://github.com/databricks/cli/commit/a5d0248af87295ec53d9f85a1564941e3c6216f6
> Update out.test.toml for integration_whl/base

- bundle/terranova/apply.go
- bundle/terranova/tnresources/resource.go
The number of settings have grown and will continue to grow, this give better overview.
> direct: refactor: Group resources settings in a single struct

- bundle/config/mutator/resolve_variable_references.go
- bundle/config/mutator/resourcemutator/process_static_resources.go
- bundle/config/mutator/resourcemutator/resource_mutator.go
- bundle/phases/initialize.go
Plan to update this with "resources", this reduces number of places to change. Also adds a central place to explain why this list has this contents.
> Refactor repeated default prefixes in variable resolution

- bundle/config/mutator/resolve_variable_references.go
Usage removed in https://github.com/databricks/cli/pull/2157
Added in https://github.com/databricks/cli/pull/1467
> Remove unused skipFn in variable resolution mutator

- libs/dyn/convert/from_typed_test.go
- libs/dyn/value.go
https://github.com/databricks/cli/pull/3230/files#r2256951451
> dyn/convert: Properly detect zero float64 values

- bundle/terranova/plan.go
Resource group/key is useful context. This is similar to what we do in apply.go.
Untested. Planning currently does not use remote API calls so we cannot inject API errors. Once plan loads remote state, we'll have a test there.
> direct: plan: add prefix to errors with group/key

- libs/dyn/dynvar/ref.go
- libs/dyn/dynvar/ref_test.go
- libs/dyn/dynvar/resolve.go
This is a useful utility to extract references from the tree to build a DAG. Planning to use this in direct deployment.
> Export dynvar.ref as Ref with all its fields and methods

- .github/workflows/push.yml
Update uv to latest 0.8.9 version
Keeping the uv up-to-date
Exisiting tests should pass
> Update uv to latest 0.8.9 version

- bundle/bundle.go
- bundle/terranova/apply.go
- bundle/terranova/graph.go
- bundle/terranova/plan.go
- libs/dagrun/dagrun.go
Follow up to https://github.com/databricks/cli/pull/3455
> direct: refactor: query graph for IsReferenced info

- acceptance/bundle/deploy/lakebase/database-catalog/databricks.yml.tmpl
- acceptance/bundle/deploy/lakebase/database-catalog/out.test.toml
- acceptance/bundle/deploy/lakebase/database-catalog/output.txt
- acceptance/bundle/deploy/lakebase/database-catalog/script
- acceptance/bundle/deploy/lakebase/database-catalog/test.toml
- acceptance/bundle/deploy/lakebase/database-instance/single-instance/databricks.yml.tmpl
- acceptance/bundle/deploy/lakebase/database-instance/single-instance/output.txt
- acceptance/bundle/deploy/lakebase/database-instance/single-instance/script
- acceptance/bundle/deploy/lakebase/synced-database-table/databricks.yml.tmpl
- acceptance/bundle/deploy/lakebase/synced-database-table/output.txt
- rename database instances to have distinct names in each test
- move catalog test to `CloudSlow=true`
> Acc: tweak cloud tests for Lakebase

- NEXT_CHANGELOG.md
Add notable changes of TF provider 1.88.0 to NEXT_CHANGELOG
> Add notable changes of TF provider 1.88.0 to NEXT_CHANGELOG

- acceptance/acceptance_test.go
Fixes issue flagged in https://github.com/databricks/cli/pull/3527/files#r2321881715
> Move SkipOnDbr check below ForceRun

- acceptance/bundle/deploy/lakebase/database-instance/single-instance/output.txt
- libs/testserver/database_instances.go
This field is now included in the response payload.
> Update database acceptance test fixture

- NEXT_CHANGELOG.md
- acceptance/bundle/environments/dependencies/databricks.yml
- acceptance/bundle/environments/dependencies/output.txt
- bundle/config/mutator/paths/pipeline_paths_visitor.go
Fix PIP flag processing in pipeline environment dependencies
Follow up for https://github.com/databricks/cli/pull/3708
Added an acceptance test
> Fix PIP flag processing in pipeline environment dependencies

- acceptance/bundle/validate/presets_name_prefix/databricks.yml.tmpl
- acceptance/bundle/validate/presets_name_prefix/output.txt
- acceptance/bundle/validate/presets_name_prefix_dev/databricks.yml.tmpl
- acceptance/bundle/validate/presets_name_prefix_dev/out.test.toml
- acceptance/bundle/validate/presets_name_prefix_dev/out.with_empty_prefix.json
- acceptance/bundle/validate/presets_name_prefix_dev/out.with_nil_prefix.json
- acceptance/bundle/validate/presets_name_prefix_dev/out.with_static_prefix.json
- acceptance/bundle/validate/presets_name_prefix_dev/out.without_presets.json
- acceptance/bundle/validate/presets_name_prefix_dev/output.txt
- acceptance/bundle/validate/presets_name_prefix_dev/script
- acceptance/bundle/validate/presets_name_prefix_dev/test.toml
Clarifying feature interaction, not obvious what should happen and why current behaviour is best.
> Add a test for name_prefix and 'mode: development'
